// Generated Partner asset registry. Keep require() paths static for Metro bundling.
// Reserve assets may exist under assets/partner but are intentionally not exposed here.
export const PartnerAssets = {
  navigation: {
    business: require('../assets/partner/navigation/business.png'),
    claims: require('../assets/partner/navigation/claims.png'),
    customers: require('../assets/partner/navigation/customers.png'),
    home: require('../assets/partner/navigation/home.png'),
    notifications: require('../assets/partner/navigation/notifications.png'),
    policies: require('../assets/partner/navigation/policies.png'),
    policyIntake: require('../assets/partner/navigation/policy-intake.png'),
    profile: require('../assets/partner/navigation/profile.png'),
    renewals: require('../assets/partner/navigation/renewals.png'),
    search: require('../assets/partner/navigation/search.png'),
  },
  actions: {
    policies: require('../assets/partner/actions/policies.png'),
    support: require('../assets/partner/actions/support.png'),
    businessInsights: require('../assets/partner/actions/business-insights.png'),
    payoutGrowth: require('../assets/partner/actions/payout-growth.png'),
    addCustomer: require('../assets/partner/actions/add-customer.png'),
    addVehicle: require('../assets/partner/actions/add-vehicle.png'),
    healthCover: require('../assets/partner/actions/health-cover.png'),
    familyCover: require('../assets/partner/actions/family-cover.png'),
    call: require('../assets/partner/actions/call.png'),
    businessPerformance: require('../assets/partner/actions/business-performance.png'),
    whatsapp: require('../assets/partner/actions/whatsapp.png'),
    addDocument: require('../assets/partner/actions/add-document.png'),
    customerRegister: require('../assets/partner/actions/customer-register.png'),
    policyRegister: require('../assets/partner/actions/policy-register.png'),
    renewals: require('../assets/partner/actions/renewals.png'),
    documentSearch: require('../assets/partner/actions/document-search.png'),
  },
  products: {
    commercialInsurance: require('../assets/partner/products/commercial-insurance.png'),
    familyInsurance: require('../assets/partner/products/family-insurance.png'),
    healthInsurance: require('../assets/partner/products/health-insurance.png'),
    motorInsurance: require('../assets/partner/products/motor-insurance.png'),
    propertyTravelInsurance: require('../assets/partner/products/property-travel-insurance.png'),
  },
  status: {
    policyOpen: require('../assets/partner/status/policy-open.png'),
    documentUpload: require('../assets/partner/status/document-upload.png'),
    journey: require('../assets/partner/status/journey.png'),
    pendingReview: require('../assets/partner/status/pending-review.png'),
    verified: require('../assets/partner/status/verified.png'),
    warning: require('../assets/partner/status/warning.png'),
    rejected: require('../assets/partner/status/rejected.png'),
    renewalDue: require('../assets/partner/status/renewal-due.png'),
    policyAttention: require('../assets/partner/status/policy-attention.png'),
    businessGrowth: require('../assets/partner/status/business-growth.png'),
    policyActive: require('../assets/partner/status/policy-active.png'),
    policyPending: require('../assets/partner/status/policy-pending.png'),
    policyRenewed: require('../assets/partner/status/policy-renewed.png'),
    opportunityAlert: require('../assets/partner/status/opportunity-alert.png'),
    achievement: require('../assets/partner/status/achievement.png'),
    supportReply: require('../assets/partner/status/support-reply.png'),
    claimAttention: require('../assets/partner/status/claim-attention.png'),
    motorRenewal: require('../assets/partner/status/motor-renewal.png'),
    announcement: require('../assets/partner/status/announcement.png'),
    renewalRefresh: require('../assets/partner/status/renewal-refresh.png'),
  },
  emptyStates: {
    noPolicies: require('../assets/partner/empty-states/no-policies.png'),
    noRenewals: require('../assets/partner/empty-states/no-renewals.png'),
    noDocuments: require('../assets/partner/empty-states/no-documents.png'),
    offline: require('../assets/partner/empty-states/offline.png'),
    notificationsMuted: require('../assets/partner/empty-states/notifications-muted.png'),
    noSearchResults: require('../assets/partner/empty-states/no-search-results.png'),
    uploadFailed: require('../assets/partner/empty-states/upload-failed.png'),
    verificationFailed: require('../assets/partner/empty-states/verification-failed.png'),
    supportResolved: require('../assets/partner/empty-states/support-resolved.png'),
    noCustomers: require('../assets/partner/empty-states/no-customers.png'),
    policyUpload: require('../assets/partner/empty-states/policy-upload.png'),
    validationError: require('../assets/partner/empty-states/validation-error.png'),
    incompleteDetails: require('../assets/partner/empty-states/incomplete-details.png'),
    policySearchVerified: require('../assets/partner/empty-states/policy-search-verified.png'),
  },
  banners: {
    businessGrowth01: require('../assets/partner/banners/business-growth-01.png'),
    businessGrowth05: require('../assets/partner/banners/business-growth-05.png'),
    businessGrowth08: require('../assets/partner/banners/business-growth-08.png'),
    businessGrowth11: require('../assets/partner/banners/business-growth-11.png'),
  },
  profile: {
    avatar01: require('../assets/partner/profile/avatar-01.png'),
    avatar06: require('../assets/partner/profile/avatar-06.png'),
  },
} as const;

export type PartnerAssetCategory = keyof typeof PartnerAssets;
