export const partnerTheme = {
  colors: {
    canvas: '#F5F7FB',
    surface: '#FFFFFF',
    surfaceMuted: '#F0F3F8',
    ink: '#17203A',
    inkMuted: '#69758A',
    line: '#E0E6EF',
    brand: '#4F46C8',
    brandStrong: '#2D2A73',
    brandSoft: '#ECEBFF',
    accent: '#0F8B8D',
    accentSoft: '#E6F5F4',
    success: '#18794E',
    successSoft: '#E9F7EF',
    warning: '#B66A14',
    warningSoft: '#FFF2DD',
    danger: '#B42318',
    dangerSoft: '#FCEDEC',
    info: '#315E9C',
    infoSoft: '#EAF1FB',
    nav: '#111827',
    white: '#FFFFFF',
  },
  radius: {
    sm: 10,
    md: 14,
    lg: 20,
    xl: 26,
    pill: 999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
  },
  typography: {
    display: { fontSize: 28, lineHeight: 34, fontWeight: '800' as const },
    pageTitle: { fontSize: 22, lineHeight: 28, fontWeight: '800' as const },
    sectionTitle: { fontSize: 16, lineHeight: 22, fontWeight: '800' as const },
    cardTitle: { fontSize: 13, lineHeight: 18, fontWeight: '800' as const },
    body: { fontSize: 12, lineHeight: 18, fontWeight: '500' as const },
    bodyStrong: { fontSize: 12, lineHeight: 18, fontWeight: '700' as const },
    label: { fontSize: 11, lineHeight: 15, fontWeight: '700' as const },
    caption: { fontSize: 10, lineHeight: 14, fontWeight: '600' as const },
    meta: { fontSize: 9.5, lineHeight: 13, fontWeight: '600' as const },
    eyebrow: { fontSize: 9.5, lineHeight: 13, fontWeight: '800' as const },
  },
  control: {
    minTouchTarget: 48,
    fieldHeight: 50,
    buttonHeight: 50,
  },
  shadow: {
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.06,
    shadowRadius: 18,
    elevation: 2,
  },
} as const;
