import type { AppRole } from "@/lib/roles";
import type { AccessLevel, DataScope, PermissionKeyV2 } from "@/lib/access-control-catalogue-v2";

export type EmployeeRoleCodeV2 = Exclude<AppRole, "customer" | "intermediary">;
export type RoleCategoryV2 = "business" | "administrative" | "technical" | "compatibility";
export type RoleStatusV2 = "active" | "protected" | "compatibility";

export type RoleGrantV2 = {
  permission: PermissionKeyV2;
  access: Exclude<AccessLevel, "none">;
  scope?: DataScope;
};

export type RoleDefinitionV2 = {
  code: EmployeeRoleCodeV2;
  label: string;
  purpose: string;
  category: RoleCategoryV2;
  status: RoleStatusV2;
  assignable: boolean;
  defaultScope: DataScope;
  grants: readonly RoleGrantV2[];
};

const grant = (
  permission: PermissionKeyV2,
  access: Exclude<AccessLevel, "none">,
  scope?: DataScope,
): RoleGrantV2 => ({ permission, access, scope });

const commonUser: readonly RoleGrantV2[] = [
  grant("dashboard.view", "view"),
  grant("notifications.view", "view", "self"),
];

const allTechnicalGrants: readonly RoleGrantV2[] = [
  grant("dashboard.view", "view"),
  grant("claims.view", "view", "organization"),
  grant("claims.edit", "edit", "organization"),
  grant("claims.verify_documents", "approve", "organization"),
  grant("claims.assign_surveyor", "approve", "organization"),
  grant("claims.change_stage", "approve", "organization"),
  grant("intermediaries.view", "view", "organization"),
  grant("intermediaries.application.create", "edit", "organization"),
  grant("intermediaries.application.review", "edit", "organization"),
  grant("intermediaries.application.approve", "approve", "organization"),
  grant("intermediaries.activate", "approve", "organization"),
  grant("intermediaries.portal_users.manage", "approve", "organization"),
  grant("intermediaries.training.manage", "edit", "organization"),
  grant("intermediaries.agreement.manage", "approve", "organization"),
  grant("intermediaries.iib.manage", "approve", "organization"),
  grant("intermediaries.delete", "approve", "organization"),
  grant("customers.view", "view", "organization"),
  grant("customers.create", "edit", "organization"),
  grant("customers.edit", "edit", "organization"),
  grant("kyc.view", "view", "organization"),
  grant("kyc.review", "edit", "organization"),
  grant("kyc.approve", "approve", "organization"),
  grant("employees.view", "view", "organization"),
  grant("employees.create", "edit", "organization"),
  grant("employees.edit", "edit", "organization"),
  grant("employees.deactivate", "approve", "organization"),
  grant("organisation.view", "view", "organization"),
  grant("vehicles.view", "view", "organization"),
  grant("vehicles.create", "edit", "organization"),
  grant("vehicles.edit", "edit", "organization"),
  grant("policies.view", "view", "organization"),
  grant("policies.create", "edit", "organization"),
  grant("policies.edit", "edit", "organization"),
  grant("tasks.view", "view", "organization"),
  grant("tasks.create", "edit", "organization"),
  grant("tasks.assign", "approve", "organization"),
  grant("tasks.edit", "edit", "organization"),
  grant("reports.view", "view", "organization"),
  grant("notifications.view", "view", "self"),
  grant("admin.portal_users.manage", "approve"),
  grant("admin.roles.manage", "approve"),
  grant("admin.permissions.manage", "approve"),
  grant("admin.audit.view", "view"),
  grant("master_data.manage", "approve"),
  grant("system.manage", "approve"),
  grant("system.integrations.configure", "approve"),
];

const allBusinessAdminGrants = allTechnicalGrants.filter(
  (entry) => entry.permission !== "system.integrations.configure",
);

export const roleMatrixV2: readonly RoleDefinitionV2[] = [
  {
    code: "super_admin",
    label: "Super Admin",
    purpose: "Highest business authority for organisation-wide operations, employees, portal users and business access administration.",
    category: "administrative",
    status: "active",
    assignable: true,
    defaultScope: "organization",
    grants: allBusinessAdminGrants,
  },
  {
    code: "admin",
    label: "Admin",
    purpose: "Operational administrator for business records, employee administration, portal users, audit and master data without protected technical configuration authority.",
    category: "administrative",
    status: "active",
    assignable: true,
    defaultScope: "organization",
    grants: [
      ...commonUser,
      grant("claims.view", "view", "organization"),
      grant("claims.edit", "edit", "organization"),
      grant("claims.verify_documents", "approve", "organization"),
      grant("claims.assign_surveyor", "approve", "organization"),
      grant("claims.change_stage", "approve", "organization"),
      grant("intermediaries.view", "view", "organization"),
      grant("intermediaries.application.create", "edit", "organization"),
      grant("intermediaries.application.review", "edit", "organization"),
      grant("intermediaries.application.approve", "approve", "organization"),
      grant("intermediaries.activate", "approve", "organization"),
      grant("intermediaries.portal_users.manage", "approve", "organization"),
      grant("intermediaries.training.manage", "edit", "organization"),
      grant("intermediaries.agreement.manage", "approve", "organization"),
      grant("intermediaries.iib.manage", "approve", "organization"),
      grant("customers.view", "view", "organization"),
      grant("customers.create", "edit", "organization"),
      grant("customers.edit", "edit", "organization"),
      grant("kyc.view", "view", "organization"),
      grant("kyc.review", "edit", "organization"),
      grant("kyc.approve", "approve", "organization"),
      grant("employees.view", "view", "organization"),
      grant("employees.create", "edit", "organization"),
      grant("employees.edit", "edit", "organization"),
      grant("employees.deactivate", "approve", "organization"),
      grant("organisation.view", "view", "organization"),
      grant("vehicles.view", "view", "organization"),
      grant("vehicles.create", "edit", "organization"),
      grant("vehicles.edit", "edit", "organization"),
      grant("policies.view", "view", "organization"),
      grant("policies.create", "edit", "organization"),
      grant("policies.edit", "edit", "organization"),
      grant("tasks.view", "view", "organization"),
      grant("tasks.create", "edit", "organization"),
      grant("tasks.assign", "edit", "organization"),
      grant("tasks.edit", "edit", "organization"),
      grant("reports.view", "view", "organization"),
      grant("admin.portal_users.manage", "approve"),
      grant("admin.audit.view", "view"),
      grant("master_data.manage", "edit"),
    ],
  },
  {
    code: "director",
    label: "Director",
    purpose: "Organisation-wide executive visibility with selected business review and approval authority, without routine security or technical administration.",
    category: "business",
    status: "active",
    assignable: true,
    defaultScope: "organization",
    grants: [
      ...commonUser,
      grant("claims.view", "view", "organization"),
      grant("intermediaries.view", "view", "organization"),
      grant("intermediaries.application.review", "edit", "organization"),
      grant("intermediaries.application.approve", "approve", "organization"),
      grant("customers.view", "view", "organization"),
      grant("kyc.view", "view", "organization"),
      grant("kyc.review", "edit", "organization"),
      grant("employees.view", "view", "organization"),
      grant("organisation.view", "view", "organization"),
      grant("vehicles.view", "view", "organization"),
      grant("policies.view", "view", "organization"),
      grant("tasks.view", "view", "organization"),
      grant("tasks.create", "edit", "organization"),
      grant("tasks.assign", "edit", "organization"),
      grant("tasks.edit", "edit", "organization"),
      grant("reports.view", "view", "organization"),
    ],
  },
  {
    code: "sales_operations_head",
    label: "Operations Head",
    purpose: "Organisation-wide owner of operational onboarding, customer/KYC processing, claims workflow and follow-up execution.",
    category: "business",
    status: "active",
    assignable: true,
    defaultScope: "organization",
    grants: [
      ...commonUser,
      grant("claims.view", "view", "organization"),
      grant("claims.edit", "edit", "organization"),
      grant("claims.verify_documents", "approve", "organization"),
      grant("claims.assign_surveyor", "approve", "organization"),
      grant("claims.change_stage", "approve", "organization"),
      grant("intermediaries.view", "view", "organization"),
      grant("intermediaries.application.create", "edit", "organization"),
      grant("intermediaries.application.review", "edit", "organization"),
      grant("intermediaries.application.approve", "approve", "organization"),
      grant("intermediaries.activate", "approve", "organization"),
      grant("intermediaries.training.manage", "edit", "organization"),
      grant("intermediaries.agreement.manage", "approve", "organization"),
      grant("intermediaries.iib.manage", "approve", "organization"),
      grant("customers.view", "view", "organization"),
      grant("customers.create", "edit", "organization"),
      grant("customers.edit", "edit", "organization"),
      grant("kyc.view", "view", "organization"),
      grant("kyc.review", "edit", "organization"),
      grant("kyc.approve", "approve", "organization"),
      grant("tasks.view", "view", "organization"),
      grant("tasks.create", "edit", "organization"),
      grant("tasks.assign", "edit", "organization"),
      grant("tasks.edit", "edit", "organization"),
      grant("reports.view", "view", "organization"),
    ],
  },
  {
    code: "backoffice_executive",
    label: "Backoffice Executive",
    purpose: "Organisation-wide operational processing for intermediary onboarding, customer/KYC records and follow-up work without final activation or security administration.",
    category: "business",
    status: "active",
    assignable: true,
    defaultScope: "organization",
    grants: [
      ...commonUser,
      grant("intermediaries.view", "view", "organization"),
      grant("intermediaries.application.create", "edit", "organization"),
      grant("intermediaries.application.review", "edit", "organization"),
      grant("intermediaries.training.manage", "edit", "organization"),
      grant("intermediaries.agreement.manage", "edit", "organization"),
      grant("intermediaries.iib.manage", "edit", "organization"),
      grant("customers.view", "view", "organization"),
      grant("customers.create", "edit", "organization"),
      grant("customers.edit", "edit", "organization"),
      grant("kyc.view", "view", "organization"),
      grant("kyc.review", "edit", "organization"),
      grant("tasks.view", "view", "organization"),
      grant("tasks.create", "edit", "organization"),
      grant("tasks.assign", "edit", "organization"),
      grant("tasks.edit", "edit", "organization"),
    ],
  },
  {
    code: "sales_head",
    label: "Sales Head",
    purpose: "Senior sales leader with customer, intermediary and operational visibility inside their reporting hierarchy.",
    category: "business",
    status: "active",
    assignable: true,
    defaultScope: "hierarchy",
    grants: [
      ...commonUser,
      grant("claims.view", "view", "hierarchy"),
      grant("intermediaries.view", "view", "hierarchy"),
      grant("intermediaries.application.create", "edit", "hierarchy"),
      grant("intermediaries.application.review", "edit", "hierarchy"),
      grant("customers.view", "view", "hierarchy"),
      grant("customers.create", "edit", "hierarchy"),
      grant("customers.edit", "edit", "hierarchy"),
      grant("kyc.view", "view", "hierarchy"),
      grant("kyc.review", "edit", "hierarchy"),
      grant("employees.view", "view", "hierarchy"),
      grant("organisation.view", "view", "hierarchy"),
      grant("vehicles.view", "view", "hierarchy"),
      grant("policies.view", "view", "hierarchy"),
      grant("tasks.view", "view", "hierarchy"),
      grant("tasks.create", "edit", "hierarchy"),
      grant("tasks.assign", "edit", "hierarchy"),
      grant("tasks.edit", "edit", "hierarchy"),
      grant("reports.view", "view", "hierarchy"),
    ],
  },
  {
    code: "zonal_head",
    label: "Zonal Head",
    purpose: "Sales hierarchy leader for customer, intermediary, KYC and task activity inside their reporting hierarchy.",
    category: "business",
    status: "active",
    assignable: true,
    defaultScope: "hierarchy",
    grants: [
      ...commonUser,
      grant("intermediaries.view", "view", "hierarchy"),
      grant("intermediaries.application.create", "edit", "hierarchy"),
      grant("intermediaries.application.review", "edit", "hierarchy"),
      grant("customers.view", "view", "hierarchy"),
      grant("customers.create", "edit", "hierarchy"),
      grant("customers.edit", "edit", "hierarchy"),
      grant("kyc.view", "view", "hierarchy"),
      grant("kyc.review", "edit", "hierarchy"),
      grant("organisation.view", "view", "hierarchy"),
      grant("tasks.view", "view", "hierarchy"),
      grant("tasks.create", "edit", "hierarchy"),
      grant("tasks.assign", "edit", "hierarchy"),
      grant("tasks.edit", "edit", "hierarchy"),
      grant("reports.view", "view", "hierarchy"),
    ],
  },
  {
    code: "asm",
    label: "Area Sales Head",
    purpose: "Area sales leader for customer, intermediary, KYC and task activity inside their reporting hierarchy.",
    category: "business",
    status: "active",
    assignable: true,
    defaultScope: "hierarchy",
    grants: [
      ...commonUser,
      grant("intermediaries.view", "view", "hierarchy"),
      grant("intermediaries.application.create", "edit", "hierarchy"),
      grant("intermediaries.application.review", "edit", "hierarchy"),
      grant("customers.view", "view", "hierarchy"),
      grant("customers.create", "edit", "hierarchy"),
      grant("customers.edit", "edit", "hierarchy"),
      grant("kyc.view", "view", "hierarchy"),
      grant("kyc.review", "edit", "hierarchy"),
      grant("organisation.view", "view", "hierarchy"),
      grant("tasks.view", "view", "hierarchy"),
      grant("tasks.create", "edit", "hierarchy"),
      grant("tasks.assign", "edit", "hierarchy"),
      grant("tasks.edit", "edit", "hierarchy"),
      grant("reports.view", "view", "hierarchy"),
    ],
  },
  {
    code: "sales_manager",
    label: "Sales Manager",
    purpose: "Team-level sales manager for customer, intermediary, KYC and task activity inside their reporting hierarchy.",
    category: "business",
    status: "active",
    assignable: true,
    defaultScope: "hierarchy",
    grants: [
      ...commonUser,
      grant("intermediaries.view", "view", "hierarchy"),
      grant("intermediaries.application.create", "edit", "hierarchy"),
      grant("intermediaries.application.review", "edit", "hierarchy"),
      grant("customers.view", "view", "hierarchy"),
      grant("customers.create", "edit", "hierarchy"),
      grant("customers.edit", "edit", "hierarchy"),
      grant("kyc.view", "view", "hierarchy"),
      grant("kyc.review", "edit", "hierarchy"),
      grant("organisation.view", "view", "hierarchy"),
      grant("tasks.view", "view", "hierarchy"),
      grant("tasks.create", "edit", "hierarchy"),
      grant("tasks.assign", "edit", "hierarchy"),
      grant("tasks.edit", "edit", "hierarchy"),
      grant("reports.view", "view", "hierarchy"),
    ],
  },
  {
    code: "relationship_manager",
    label: "Relationship Manager",
    purpose: "Front-line owner of their own customer portfolio and initiation of intermediary onboarding.",
    category: "business",
    status: "active",
    assignable: true,
    defaultScope: "self",
    grants: [
      ...commonUser,
      grant("intermediaries.view", "view", "self"),
      grant("intermediaries.application.create", "edit", "self"),
      grant("customers.view", "view", "self"),
      grant("customers.create", "edit", "self"),
      grant("customers.edit", "edit", "self"),
      grant("kyc.view", "view", "self"),
      grant("tasks.view", "view", "self"),
    ],
  },
  {
    code: "claims_head",
    label: "Claims Head",
    purpose: "Organisation-wide claims owner with final operational authority across claim verification, assignment and workflow progression.",
    category: "business",
    status: "active",
    assignable: true,
    defaultScope: "organization",
    grants: [
      ...commonUser,
      grant("claims.view", "view", "organization"),
      grant("claims.edit", "edit", "organization"),
      grant("claims.verify_documents", "approve", "organization"),
      grant("claims.assign_surveyor", "approve", "organization"),
      grant("claims.change_stage", "approve", "organization"),
      grant("tasks.view", "view", "organization"),
      grant("tasks.create", "edit", "organization"),
      grant("tasks.assign", "approve", "organization"),
      grant("tasks.edit", "edit", "organization"),
      grant("reports.view", "view", "organization"),
    ],
  },
  {
    code: "claim_processor",
    label: "Claim Processor",
    purpose: "Processes assigned claims and related tasks without organisation-wide or final approval authority by default.",
    category: "business",
    status: "active",
    assignable: true,
    defaultScope: "assigned",
    grants: [
      ...commonUser,
      grant("claims.view", "view", "assigned"),
      grant("claims.edit", "edit", "assigned"),
      grant("claims.verify_documents", "edit", "assigned"),
      grant("claims.assign_surveyor", "edit", "assigned"),
      grant("claims.change_stage", "edit", "assigned"),
      grant("tasks.view", "view", "assigned"),
      grant("tasks.create", "edit", "self"),
      grant("tasks.edit", "edit", "assigned"),
    ],
  },
  {
    code: "field_executive",
    label: "Field Executive",
    purpose: "Views assigned field claims and tasks without broad business-data access.",
    category: "business",
    status: "active",
    assignable: true,
    defaultScope: "assigned",
    grants: [...commonUser, grant("claims.view", "view", "assigned"), grant("tasks.view", "view", "assigned")],
  },
  {
    code: "it_super_user",
    label: "IT Super User",
    purpose: "Protected technical authority for platform recovery, security administration and integration configuration.",
    category: "technical",
    status: "protected",
    assignable: false,
    defaultScope: "organization",
    grants: allTechnicalGrants,
  },
  {
    code: "manager",
    label: "Manager (Legacy Compatibility)",
    purpose: "Legacy broad-access role retained temporarily because existing TypeScript and database rules reference it. Do not assign to new employees.",
    category: "compatibility",
    status: "compatibility",
    assignable: false,
    defaultScope: "organization",
    grants: [],
  },
  {
    code: "agent",
    label: "Agent (Legacy Compatibility)",
    purpose: "Legacy customer-assignment role retained until customer ownership and sales RLS no longer depend on the Agent role name.",
    category: "compatibility",
    status: "compatibility",
    assignable: false,
    defaultScope: "self",
    grants: [
      ...commonUser,
      grant("customers.view", "view", "self"),
      grant("customers.create", "edit", "self"),
      grant("customers.edit", "edit", "self"),
      grant("tasks.view", "view", "self"),
    ],
  },
];

export const roleMatrixV2ByCode = new Map<EmployeeRoleCodeV2, RoleDefinitionV2>(
  roleMatrixV2.map((role) => [role.code, role]),
);

export function assignableRolesV2() {
  return roleMatrixV2.filter((role) => role.assignable);
}
