import type { ParsedPolicyField, ParsedPolicyResult } from "@/lib/policy-ocr-parsers";
import type { StructuredPolicyTable } from "@/lib/policy-ocr-iffco-structured-refiner";
type Fields=Map<string,ParsedPolicyField>;
const TITLE=/COMMERCIAL\s+VEHICLE\s+PACKAGE\s+POLICY[\s\S]{0,24}?ENHANCED\s+COVERS/i,INSURER=/THE\s+NEW\s+INDIA\s+ASSURANCE|NEW\s+INDIA\s+ASSURANCE\s+COMPANY/i;
export function refineNewIndiaEnhancedCoversLiveResiduals(pages:string[],tables:StructuredPolicyTable[],parsed:ParsedPolicyResult):ParsedPolicyResult{if(parsed.parserId!=="new_india_motor_v1")return parsed;const text=pages.slice(0,2).join("\n");if(!INSURER.test(text)||!TITLE.test(text))return parsed;const f:Fields=new Map(parsed.fields.map(x=>[x.key,x]));if(!has(f,"vehicle_manufacturing_year")){const h=find(tables,/Year\s+of\s+manufacture/i,isYear);if(h)set(f,"vehicle_manufacturing_year","Manufacturing year",h.value,h.page,h.evidence);}if(!has(f,"vehicle_chassis_number")){const h=find(tables,/Chassis\s*(?:no\.?|number)/i,isId);if(h)set(f,"vehicle_chassis_number","Chassis number",id(h.value),h.page,h.evidence);}if(!has(f,"vehicle_engine_number")){const h=find(tables,/Engine\s*(?:no\.?|number)/i,isId);if(h)set(f,"vehicle_engine_number","Engine number",id(h.value),h.page,h.evidence);}if(!has(f,"vehicle_chassis_number")||!has(f,"vehicle_engine_number")){const p=findPair(tables);if(p){if(!has(f,"vehicle_chassis_number"))set(f,"vehicle_chassis_number","Chassis number",p.chassis,p.page,p.evidence);if(!has(f,"vehicle_engine_number"))set(f,"vehicle_engine_number","Engine number",p.engine,p.page,p.evidence);}}return{...parsed,parserVersion:`${parsed.parserVersion}+new-india-enhanced-covers-live-residual-v1`,fields:[...f.values()]};}
function find(tables:StructuredPolicyTable[],label:RegExp,accept:(v:string)=>boolean){for(const t of tables)for(let r=0;r<t.rows.length;r++){const row=t.rows[r].map(clean);for(let c=0;c<row.length;c++){const m=row[c].match(label);if(!m)continue;const after=clean(row[c].slice((m.index??0)+m[0].length).replace(/^\s*[:\-]\s*/,""));if(accept(after))return{value:after,page:t.page,evidence:safe(row.join(" | "))};for(let a=c+1;a<row.length;a++){if(accept(row[a]))return{value:row[a],page:t.page,evidence:safe(row.join(" | "))};if(isLabel(row[a]))break;}for(let n=r+1;n<=Math.min(r+3,t.rows.length-1);n++){const v=clean(t.rows[n]?.[c]??"");if(accept(v))return{value:v,page:t.page,evidence:safe(`${row[c]} | ${v}`)};if(isLabel(v))break;}}}return null;}
function findPair(tables:StructuredPolicyTable[]){for(const t of tables)for(let r=0;r<t.rows.length;r++){const row=t.rows[r].map(clean);for(let c=0;c<row.length;c++){if(!/Chassis.*\/.*Engine/i.test(row[c]))continue;const vals=[...row.slice(c+1),...t.rows.slice(r+1,r+3).map(x=>clean(x?.[c]??""))];for(const v of vals){const p=pair(v);if(p)return{...p,page:t.page,evidence:safe(`${row.join(" | ")} | ${v}`)};}}}return null;}
function pair(v:string){const i=v.indexOf("/");if(i<0)return null;const a=id(v.slice(0,i)),b=id(v.slice(i+1));return isId(a)&&isId(b)&&a!==b?{chassis:a,engine:b}:null;}
function has(f:Fields,k:string){return Boolean(f.get(k)?.value?.trim());}function isYear(v:string){return /^(?:19|20)\d{2}$/.test(clean(v));}function isId(v:string){const x=id(v);return x.length>=6&&x.length<=30&&/[A-Z]/.test(x)&&/\d/.test(x);}function isLabel(v:string){return /Year|Chassis|Engine|fuel|body|Gross Vehicle|Make\s*\/\s*Model|Registration|Seating|Variant/i.test(v);}function id(v:string){return v.toUpperCase().replace(/[^A-Z0-9]/g,"");}function clean(v:string){return v.replace(/\u00a0/g," ").replace(/\s+/g," ").trim();}function safe(v:string){return clean(v).slice(0,600);}function set(f:Fields,key:string,label:string,value:string,page:number,evidence:string){f.set(key,{key,label,value,confidence:.999,page,evidence:safe(evidence)});}
