import type { ParsedPolicyField, ParsedPolicyResult } from "@/lib/policy-ocr-parsers";
import type { StructuredPolicyTable } from "@/lib/policy-ocr-iffco-structured-refiner";

type Fields = Map<string, ParsedPolicyField>;
type Hit = { value: string; page: number; evidence: string };
type Money = { value: number; page: number; evidence: string };
type Layout =
  | "uiic_gcv_package" | "uiic_pcv_package" | "uiic_gcv_3w_tp"
  | "hdfc_pcp" | "hdfc_twp_saod" | "hdfc_twp_tp"
  | "national_gcv" | "national_pcp_tp" | "national_twp_bundled"
  | "new_india_saod" | "royal_pcp_tp"
  | "magma_pcp_saod" | "magma_pcp_package" | "magma_gcv_tp"
  | "digit_pcp_package" | "shriram_pcp_tp";

const labels: Record<string, string> = {
  vehicle_registration_status:"Registration status",vehicle_registration_number:"Registration number",
  vehicle_class:"Vehicle class",vehicle_make:"Vehicle make",vehicle_model:"Vehicle model",
  vehicle_fuel_type:"Fuel type",vehicle_manufacturing_year:"Manufacturing year",vehicle_capacity:"Vehicle capacity",
  vehicle_chassis_number:"Chassis number",vehicle_engine_number:"Engine number",vehicle_rto_name:"RTO name",
  vehicle_rto_state:"RTO state",policy_product:"Policy product",policy_number:"Policy number",
  insurer_name:"Insurance company",policy_start_date:"Valid from",policy_end_date:"Valid upto",
  idv:"IDV / Sum insured",od_premium:"OD premium",tp_premium:"Third party premium",cpa_opted:"CPA opted",
  cpa_premium:"CPA amount",total_premium:"Printed net premium",tax_amount:"Printed GST",
  gross_premium:"Printed gross premium",
};
const policyKeys = ["policy_product","policy_number","insurer_name","policy_start_date","policy_end_date","idv","od_premium","tp_premium","cpa_opted","cpa_premium","total_premium","tax_amount","gross_premium"];

export function refineApprovedMotorPolicyLayout(pages:string[], tables:StructuredPolicyTable[], parsed:ParsedPolicyResult):ParsedPolicyResult {
  const allText = norm([...pages, ...tables.flatMap((table)=>table.rows.flat())].join(" | "));
  const header = currentPolicyHeader(pages);
  const layout = detect(header, allText, parsed.parserId);
  if (!layout) return parsed;
  const parserId = parserFor(layout);
  const fields:Fields = new Map(parsed.fields.map((field)=>[field.key, field]));
  for (const key of policyKeys) fields.delete(key);
  cleanVehicle(fields);
  commonVehicle(pages,tables,fields,layout);

  if(layout.startsWith("uiic_")) refineUiic(pages,tables,fields,allText,layout as Extract<Layout,`uiic_${string}`>);
  else if(layout.startsWith("hdfc_")) refineHdfc(pages,tables,fields,layout as Extract<Layout,`hdfc_${string}`>);
  else if(layout.startsWith("national_")) refineNational(pages,tables,fields,allText,layout as Extract<Layout,`national_${string}`>);
  else if(layout==="new_india_saod") refineNewIndia(pages,tables,fields);
  else if(layout==="royal_pcp_tp") refineRoyal(pages,tables,fields);
  else if(layout.startsWith("magma_")) refineMagma(pages,tables,fields,allText,layout as Extract<Layout,`magma_${string}`>);
  else if(layout==="digit_pcp_package") refineDigit(pages,tables,fields);
  else refineShriram(pages,tables,fields,allText);

  cleanVehicle(fields); repairIds(fields); applyFinancialSanity(fields);
  const warnings = parsed.warnings.filter((warning)=>!/not fully supported|missing or uncertain|financial fields require manual review|premium fields were withheld|IFFCO Owner-Driver|IFFCO printed net/i.test(warning));
  const required=["policy_product","idv","od_premium","tp_premium","policy_number","insurer_name","policy_start_date","policy_end_date"];
  const missing=required.filter((key)=>!fields.get(key)?.value?.trim());
  if(missing.length) warnings.push(`Review required. Missing or uncertain fields: ${missing.join(", ")}.`);
  const base=parserId===parsed.parserId?parsed.parserVersion:`${parserId}.1.0`;
  return {...parsed,parserId,parserVersion:`${base}+layout-${layout}-v6`,fields:[...fields.values()],warnings};
}

function currentPolicyHeader(pages:string[]):string {
  const first=(pages[0]??"").split(/\r?\n/).slice(0,45).join(" ");
  return norm(first).slice(0,6000);
}
function detect(header:string,text:string,parserId:string):Layout|null {
  if(/SHRIRAM\s+GENERAL\s+INSURANCE/i.test(header)){
    if(/LIABILITY\s+ONLY|THIRD\s+PARTY|ACT\s+ONLY|PRIVATE\s+CAR|MOTOR\s+INSURANCE/i.test(header)) return "shriram_pcp_tp";
  }
  if(/UNITED\s+INDIA\s+INSURANCE/i.test(header)){
    if(/MOTORIZED\s+3\s+WHEELERS?.*LIABILITY\s+ONLY|GCV\s+PUBLIC\s+CARRIERS?.*3\s+WHEELERS?.*LIABILITY/i.test(text)) return "uiic_gcv_3w_tp";
    if(/PCV\s+4\s+WHEELER.*PACKAGE|PASSENGER\s+CARRYING\s+VEHICLE\s+PACKAGE/i.test(text)) return "uiic_pcv_package";
    if(/(?:GCV|GOODS\s+CARRYING|PUBLIC\s+CARRIER).*PACKAGE/i.test(text)) return "uiic_gcv_package";
  }
  if(/HDFC\s+ERGO\s+GENERAL\s+INSURANCE/i.test(header)){
    if(/STANDALONE\s+MOTOR\s+OWN\s+DAMAGE\s+COVER\s*-?\s*TWO\s+WHEELER/i.test(text)) return "hdfc_twp_saod";
    if(/TWO\s+WHEELER\s+LIABILITY\s+ONLY|MOTOR\s+INSURANCE\s*-?\s*TWO\s+WHEELER\s+LIABILITY/i.test(text)) return "hdfc_twp_tp";
    if(/PRIVATE\s+CAR\s+(?:COMPREHENSIVE|PACKAGE)/i.test(text)) return "hdfc_pcp";
  }
  if(/NATIONAL\s+INSURANCE/i.test(header)){
    if(/TWO\s+WHEELERS?\s*-?\s*OD\s+WITH\s+LONGTERM\s+ACT|LONG\s+TERM\s+TWO\s+WHEELERS?\s+BUNDLED/i.test(text)) return "national_twp_bundled";
    if(/PRIVATE\s+CAR\s*-?\s*LIABILITY\s+ONLY|MOTOR\s*-?\s*PRIVATE\s+CAR\s*-?\s*LIABILITY\s+ONLY/i.test(text)) return "national_pcp_tp";
    if(/GOODS\s+CARRYING\s+VEHICLE|\bGCV\b/i.test(text)) return "national_gcv";
  }
  if(/MAGMA\s+GENERAL\s+INSURANCE|MAGMAINSURANCE\.COM/i.test(header)){
    if(/COMMERCIAL\s+VEHICLE\s+LIABILITY\s+ONLY/i.test(text)) return "magma_gcv_tp";
    if(/PRIVATE\s+CAR\s+PACKAGE\s+POLICY/i.test(text)) return "magma_pcp_package";
    if(/STAND[-\s]*ALONE\s+OWN\s+DAMAGE.*PRIVATE\s+CAR|PRIVATE\s+CAR.*STAND[-\s]*ALONE\s+OWN\s+DAMAGE/i.test(text)) return "magma_pcp_saod";
  }
  if(/GO\s+DIGIT\s+GENERAL\s+INSURANCE|DIGIT\s+PRIVATE\s+CAR\s+POLICY/i.test(header) && /DIGIT\s+PRIVATE\s+CAR\s+POLICY/i.test(text)) return "digit_pcp_package";
  if(/NEW\s+INDIA\s+ASSURANCE/i.test(header) && /STANDALONE\s+MOTOR\s+OWN\s+DAMAGE|STAND[-\s]*ALONE\s+OWN\s+DAMAGE|\bSAOD\b/i.test(text)) return "new_india_saod";
  if(/ROYAL\s+SUNDARAM/i.test(header) && /LIABILITY\s+ONLY/i.test(text)) return "royal_pcp_tp";
  if(parserId==="royal_sundaram_motor_v1"&&/ROYAL\s+SUNDARAM/i.test(header)&&/LIABILITY\s+ONLY/i.test(text)) return "royal_pcp_tp";
  return null;
}
function parserFor(layout:Layout):string{
  if(layout.startsWith("uiic_"))return"united_india_motor_v1";
  if(layout.startsWith("hdfc_"))return"hdfc_ergo_motor_v1";
  if(layout.startsWith("national_"))return"national_motor_v1";
  if(layout==="new_india_saod")return"new_india_motor_v1";
  if(layout==="royal_pcp_tp")return"royal_sundaram_motor_v1";
  if(layout.startsWith("magma_"))return"magma_motor_v1";
  if(layout==="digit_pcp_package")return"digit_commercial_motor_v1";
  return"shriram_motor_v1";
}

function refineUiic(pages:string[],tables:StructuredPolicyTable[],f:Fields,text:string,layout:Extract<Layout,`uiic_${string}`>){
  set(f,"insurer_name","United India Insurance Company Limited",1,1,"current UIIC header");identity(f,pages,"uiic");
  const tpOnly=layout==="uiic_gcv_3w_tp";set(f,"policy_product",tpOnly?"Third Party":"Package",1,1,tpOnly?"liability-only title":"package title");
  if(tpOnly){set(f,"idv","0",1,1,"liability only");set(f,"od_premium","0",1,1,"liability only");}
  else {putMoney(f,"idv",moneyHit(tables,pages,/Insured'?s\s+Declared\s+Value|Total\s+IDV|Total\s+Value/i,1000,1e9,"largest"));putMoney(f,"od_premium",moneyHit(tables,pages,/Gross\s+OD\s*\(?A\)?|Total\s+OD\s+Premium/i,20,1e7,"last"));}
  const basic=moneyHit(tables,pages,/(?:^|\b)B\.\s*Basic\s*-\s*TP\b|^Basic\s*-\s*TP\b|Basic\s+TP\s+Premium/i,100,1e7,"last");
  const grossTp=moneyHit(tables,pages,/Gross\s+TP\s*\(?B\)?|Total\s+Liability\s+Premium/i,100,1e7,"last");
  const net=moneyHit(tables,pages,/Premium\s*\(?A\s*\+\s*B\)?|Gross\s+OD\s*&\s*TP|Total\s+Liability\s+Premium/i,100,1e7,"last");
  const owner=ownerDriverPremium(pages,tables);putMoney(f,"tp_premium",basic);
  const additions=grossTp&&basic?round(grossTp.value-basic.value):net&&basic?round(net.value-(tpOnly?0:(numField(f,"od_premium")??0))-basic.value):null;
  if(additions!==null&&additions>=0&&(!grossTp||additions<=grossTp.value))set(f,"cpa_premium",money(additions),.99,grossTp?.page??net?.page??1,"liability additions outside basic TP");
  if(owner)set(f,"cpa_opted",owner.value>0?"Yes":"No",.99,owner.page,owner.evidence);else if(/CPA\s+COVER\s+IS\s+REMOVED|COMPULSORY\s+PERSONAL\s+ACCIDENT.*COVER\s+IS\s+REMOVED/i.test(text))set(f,"cpa_opted","No",.99,1,"explicit CPA removal");else if(additions===0)set(f,"cpa_opted","No",.95,1,"no owner-driver CPA evidence");
  putMoney(f,"total_premium",net);const tax=uiicTax(pages,tables);putMoney(f,"tax_amount",tax);putMoney(f,"gross_premium",preferReconciledGross(net,tax,moneyHit(tables,pages,/Total\s*\(?Rounded\s+Off\)?|Total\s+Payable\s+Premium/i,100,1e8,"last")));
}
function uiicTax(pages:string[],tables:StructuredPolicyTable[]):Money|null{const other=moneyHit(tables,pages,/IGST[-\s]*Others\s*\(?\s*18\s*%?\s*\)?/i,1,1e7,"last"),basic=moneyHit(tables,pages,/IGST[-\s]*Basic\s*TP\s*\(?\s*5\s*%?\s*\)?/i,1,1e7,"last");if(other&&basic)return combine(other,basic,"split UIIC IGST");const total=moneyHit(tables,pages,/Total\s+GST|Total\s+IGST/i,1,1e7,"last");if(total)return total;const cg=moneyHit(tables,pages,/CGST/i,1,1e7,"last"),sg=moneyHit(tables,pages,/SGST/i,1,1e7,"last");return cg&&sg?combine(cg,sg,"CGST + SGST"):null;}

function refineHdfc(pages:string[],tables:StructuredPolicyTable[],f:Fields,layout:Extract<Layout,`hdfc_${string}`>){
  set(f,"insurer_name","HDFC ERGO General Insurance Company Limited",1,1,"current HDFC header");identity(f,pages,"hdfc");
  if(layout==="hdfc_twp_tp"){set(f,"policy_product","Third Party",1,1,"TWP liability only");set(f,"idv","0",1,1,"liability only");set(f,"od_premium","0",1,1,"liability only");const liability=moneyHit(tables,pages,/Net\s+Liability\s+Premium|Total\s+Liability\s+Premium|Basic\s+Third\s+Party\s+Liability/i,100,1e7,"last"),cpa=ownerDriverPremium(pages,tables);if(liability)set(f,"tp_premium",money(Math.max(0,round(liability.value-(cpa?.value??0)))),.99,liability.page,"liability less owner-driver PA");set(f,"cpa_opted",cpa&&cpa.value>0?"Yes":"No",1,cpa?.page??1,cpa?.evidence??"no owner-driver PA");set(f,"cpa_premium",money(cpa?.value??0),1,cpa?.page??1,cpa?.evidence??"no owner-driver PA");putMoney(f,"total_premium",liability);finishHdfc(pages,tables,f,liability);return;}
  putMoney(f,"idv",moneyHit(tables,pages,/Total\s+IDV|Insured'?s\s+Declared\s+Value/i,1000,1e9,"largest"));const od=moneyHit(tables,pages,/Net\s+Own\s+Damage\s+Premium|Own\s+Damage\s+Premium/i,20,1e7,"last");
  if(layout==="hdfc_twp_saod"){set(f,"policy_product","SAOD",1,1,"standalone own damage");putMoney(f,"od_premium",od);set(f,"tp_premium","0",1,1,"active TP is separate policy");set(f,"cpa_opted","No",1,1,"SAOD");set(f,"cpa_premium","0",1,1,"SAOD");const net=moneyHit(tables,pages,/Net\s+Own\s+Damage\s+Premium|Net\s+Premium/i,20,1e7,"last")??od;putMoney(f,"total_premium",net);finishHdfc(pages,tables,f,net);return;}
  set(f,"policy_product","Package",1,1,"private-car package");putMoney(f,"od_premium",od);const liability=moneyHit(tables,pages,/Net\s+Liability\s+Premium/i,100,1e7,"last"),cpa=ownerDriverPremium(pages,tables),net=moneyHit(tables,pages,/Total\s+Package\s+Premium/i,100,1e7,"last");if(liability)set(f,"tp_premium",money(Math.max(0,round(liability.value-(cpa?.value??0)))),.99,liability.page,"liability less owner-driver PA");set(f,"cpa_opted",cpa&&cpa.value>0?"Yes":"No",1,cpa?.page??1,cpa?.evidence??"no owner-driver PA");set(f,"cpa_premium",money(cpa?.value??0),1,cpa?.page??1,cpa?.evidence??"no owner-driver PA");putMoney(f,"total_premium",net);finishHdfc(pages,tables,f,net);
}
function finishHdfc(pages:string[],tables:StructuredPolicyTable[],f:Fields,net:Money|null){const tax=hdfcTax(pages,tables);putMoney(f,"tax_amount",tax);putMoney(f,"gross_premium",preferReconciledGross(net,tax,moneyHit(tables,pages,/Total\s+Amount\s+Payable|Total\s+Premium(?!\s*\(a\s*\+\s*b\))/i,100,1e8,"last")));}
function hdfcTax(pages:string[],tables:StructuredPolicyTable[]):Money|null{const cg=moneyHit(tables,pages,/CGST|Central\s+Tax/i,1,1e7,"last"),sg=moneyHit(tables,pages,/SGST|State\s+Tax/i,1,1e7,"last");if(cg&&sg)return combine(cg,sg,"CGST + SGST");const igst=moneyHit(tables,pages,/Integrated\s+Tax|\bIGST\b/i,20,1e7,"last");if(igst)return igst;return moneyHit(tables,pages,/GST\s+18%|Total\s+GST/i,20,1e7,"last");}

function refineNational(pages:string[],tables:StructuredPolicyTable[],f:Fields,text:string,layout:Extract<Layout,`national_${string}`>){
  set(f,"insurer_name","National Insurance Company Limited",1,1,"current National header");identity(f,pages,"national");
  if(layout==="national_pcp_tp"){set(f,"policy_product","Third Party",1,1,"private-car liability only");set(f,"idv","0",1,1,"liability only");set(f,"od_premium","0",1,1,"liability only");const tp=moneyHit(tables,pages,/Legal\s+Liability\s+Cover|Basic\s+Liability/i,100,1e7,"last"),cpa=ownerDriverPremium(pages,tables)??moneyHit(tables,pages,/^Personal\s+Accident$/i,20,1e5,"last");const printedNet=moneyHit([],pages,/^Premium\s*[₹:]?/i,100,1e7,"first"),net=printedNet??(tp?{value:round(tp.value+(cpa?.value??0)),page:tp.page,evidence:"liability + PA"}:null);putMoney(f,"tp_premium",tp);set(f,"cpa_opted",cpa&&cpa.value>0?"Yes":"No",1,cpa?.page??1,cpa?.evidence??"no PA premium");set(f,"cpa_premium",money(cpa?.value??0),1,cpa?.page??1,cpa?.evidence??"no PA premium");putMoney(f,"total_premium",net);const tax=moneyHit([],pages,/\bIGST\b/i,20,1e7,"last");putMoney(f,"tax_amount",tax);putMoney(f,"gross_premium",preferReconciledGross(net,tax,moneyHit([],pages,/Total\s+Amount/i,100,1e8,"last")));return;}
  if(layout==="national_twp_bundled"){set(f,"policy_product","Bundled",1,1,"long-term two-wheeler bundled");putMoney(f,"idv",moneyHit(tables,pages,/Vehicle\s+IDV|Total\s+IDV/i,1000,1e9,"largest"));const tp=moneyHit(tables,pages,/Legal\s+Liability\s+Cover/i,100,1e7,"last"),cpa=ownerDriverPremium(pages,tables),printedNet=moneyHit([],pages,/^Premium\s*[₹:]?/i,100,1e7,"first");let od=moneyHit(tables,pages,/Own\s+Damage\s+Cover\s+Premium/i,20,1e7,"last");if(printedNet&&tp){const d=round(printedNet.value-tp.value-(cpa?.value??0));if(d>=0)od={value:d,page:printedNet.page,evidence:"printed premium less liability/CPA"};}putMoney(f,"od_premium",od);putMoney(f,"tp_premium",tp);set(f,"cpa_opted",cpa&&cpa.value>0?"Yes":"No",1,cpa?.page??1,cpa?.evidence??"no owner-driver PA");set(f,"cpa_premium",money(cpa?.value??0),1,cpa?.page??1,cpa?.evidence??"no owner-driver PA");putMoney(f,"total_premium",printedNet);const tax=moneyHit([],pages,/\bIGST\b/i,20,1e7,"last");putMoney(f,"tax_amount",tax);putMoney(f,"gross_premium",preferReconciledGross(printedNet,tax,moneyHit([],pages,/Total\s+Amount/i,100,1e8,"last")));return;}
  set(f,"policy_product","Package",1,1,"GCV package");putMoney(f,"idv",moneyHit(tables,pages,/Vehicle\s+IDV|Total\s+Value|Total\s+IDV/i,1000,1e9,"largest"));let od=moneyHit(tables,pages,/Own\s+Damage\s+Cover|Total\s+Own\s+Damage\s+Premium/i,20,1e7,"last");if(od)od={...od,value:round(od.value)};const tp=moneyHit(tables,pages,/Legal\s+Liability\s+Cover|Basic\s+Liability\s+Premium/i,100,1e7,"last"),totalLiability=moneyHit(tables,pages,/Total\s+Liability\s+Premium/i,100,1e7,"last"),driver=moneyHit(tables,pages,/Legal\s+Liability\s+to\s+Driver|Driver\s*,?\s*Cleaner\s*,?\s*Coolies/i,20,1e5,"last"),owner=ownerDriverPremium(pages,tables);const extra=totalLiability&&tp?Math.max(0,round(totalLiability.value-tp.value)):(driver?.value??0)+(owner?.value??0);const printedNet=moneyHit([],pages,/^Premium\s*[₹:]?/i,1000,1e7,"first"),net=printedNet??(od&&tp?{value:round(od.value+tp.value+extra),page:od.page,evidence:"reconciled net"}:null);putMoney(f,"od_premium",od);putMoney(f,"tp_premium",tp);if(owner)set(f,"cpa_opted",owner.value>0?"Yes":"No",.99,owner.page,owner.evidence);else if(/OWNER\s+DRIVER|PERSONAL\s+ACCIDENT\s+COVER/i.test(text))f.delete("cpa_opted");set(f,"cpa_premium",money(extra),.98,totalLiability?.page??driver?.page??owner?.page??1,"liability additions outside base TP");putMoney(f,"total_premium",net);const tax=moneyHit([],pages,/\bIGST\b/i,20,1e7,"last");putMoney(f,"tax_amount",tax);putMoney(f,"gross_premium",preferReconciledGross(net,tax,moneyHit(tables,pages,/Gross\s+Premium|Total\s+Amount/i,100,1e8,"last")));
}

function refineNewIndia(pages:string[],tables:StructuredPolicyTable[],f:Fields){set(f,"insurer_name","The New India Assurance Company Limited",1,1,"current New India header");set(f,"policy_product","SAOD",1,1,"standalone own damage");identity(f,pages,"new_india");putMoney(f,"idv",moneyHit(tables,pages,/Total\s+Value|Total\s+IDV/i,1000,1e9,"largest"));const od=moneyHit(tables,pages,/Total\s+OD\s+Premium|Calculated\s+OD\s+Premium/i,20,1e7,"last"),net=moneyHit(tables,pages,/Net\s+Premium/i,20,1e7,"last")??od;putMoney(f,"od_premium",od);set(f,"tp_premium","0",1,1,"SAOD");set(f,"cpa_opted","No",1,1,"SAOD");set(f,"cpa_premium","0",1,1,"SAOD");putMoney(f,"total_premium",net);const tax=moneyHit(tables,pages,/GST(?:\s+in\s+Rs)?|IGST/i,20,1e7,"last");putMoney(f,"tax_amount",tax);putMoney(f,"gross_premium",preferReconciledGross(net,tax,moneyHit(tables,pages,/Total\s+Payable/i,100,1e8,"last")));}
function refineRoyal(pages:string[],tables:StructuredPolicyTable[],f:Fields){set(f,"insurer_name","Royal Sundaram General Insurance Co. Limited",1,1,"current Royal header");set(f,"policy_product","Third Party",1,1,"liability only");identity(f,pages,"royal");set(f,"idv","0",1,1,"liability only");set(f,"od_premium","0",1,1,"liability only");const tp=moneyHit(tables,pages,/Basic\s+(?:premium.*TPPD|Liability\s+Premium)/i,100,1e7,"last"),total=moneyHit(tables,pages,/Total\s+Liability\s+Premium/i,100,1e7,"last"),paid=moneyHit(tables,pages,/Paid\s+Driver/i,20,1e5,"last");const extra=total&&tp?Math.max(0,round(total.value-tp.value)):(paid?.value??0);putMoney(f,"tp_premium",tp);set(f,"cpa_opted","No",1,1,"owner-driver PA zero/not opted");set(f,"cpa_premium",money(extra),1,total?.page??paid?.page??1,"non-owner liability addition");const net=total??(tp?{value:tp.value+extra,page:tp.page,evidence:"liability total"}:null);putMoney(f,"total_premium",net);const tax=moneyHit(tables,pages,/IGST/i,20,1e7,"last");putMoney(f,"tax_amount",tax);putMoney(f,"gross_premium",preferReconciledGross(net,tax,moneyHit(tables,pages,/Total\s+Premium\s+Payable|Total\s+Amount\s+Payable/i,100,1e8,"last")));}

function refineMagma(pages:string[],tables:StructuredPolicyTable[],f:Fields,text:string,layout:Extract<Layout,`magma_${string}`>){
  set(f,"insurer_name","Magma General Insurance Limited",1,1,"current Magma header");identity(f,pages,"magma");
  if(layout==="magma_gcv_tp"){set(f,"policy_product","Third Party",1,1,"commercial vehicle liability only");set(f,"idv","0",1,1,"liability only");set(f,"od_premium","0",1,1,"liability only");const basic=moneyHit(tables,pages,/Basic\s*-\s*TP/i,100,1e7,"last"),total=moneyHit(tables,pages,/Total\s+Liability\s+Premium|Sub\s+Total/i,100,1e7,"last");if(basic&&total&&basic.value<=total.value){putMoney(f,"tp_premium",basic);set(f,"cpa_premium",money(round(total.value-basic.value)),.99,total.page,"non-owner liability additions");}else{if(basic)putMoney(f,"tp_premium",basic);f.delete("cpa_premium");}set(f,"cpa_opted","No",1,1,/REASON\s+FOR\s+NOT\s+OPTING\s+PA\s+COVER|DO\s+NOT\s+HOLD\s+A\s+VALID\s+DRIVING\s+LICENSE/i.test(text)?"explicit owner-driver PA opt-out":"no owner-driver PA");putMoney(f,"total_premium",total);const tax=magmaTax(pages,tables);putMoney(f,"tax_amount",tax);putMoney(f,"gross_premium",preferReconciledGross(total,tax,moneyHit(tables,pages,/^TOTAL$/i,100,1e8,"last")));return;}
  putMoney(f,"idv",moneyHit(tables,pages,/Total\s+Value|IDV\s+of\s+Vehicle/i,1000,1e9,"largest"));const od=moneyHit(tables,pages,/Total\s+Own\s+Damage\s+Premium(?:\(A\))?/i,20,1e7,"last");putMoney(f,"od_premium",od);
  if(layout==="magma_pcp_saod"){set(f,"policy_product","SAOD",1,1,"private-car SAOD");set(f,"tp_premium","0",1,1,"external TP separate");set(f,"cpa_opted","No",1,1,"SAOD");set(f,"cpa_premium","0",1,1,"SAOD");putMoney(f,"total_premium",od);const tax=magmaTax(pages,tables);putMoney(f,"tax_amount",tax);putMoney(f,"gross_premium",preferReconciledGross(od,tax,null));return;}
  set(f,"policy_product","Package",1,1,"private-car package");const basic=moneyHit(tables,pages,/Basic\s*-\s*TP|Basic\s+TP/i,100,1e7,"last"),liability=moneyHit(tables,pages,/Total\s+Liability\s+Premium\s*\(?B\)?/i,100,1e7,"last"),owner=ownerDriverPremium(pages,tables),net=moneyHit(tables,pages,/Total\s+Package\s+Premium\s*\(?A\s*\+\s*B\)?/i,100,1e7,"last");if(basic&&liability){const nonOwner=Math.max(0,round(liability.value-basic.value-(owner?.value??0)));set(f,"tp_premium",money(round(basic.value+nonOwner)),.99,liability.page,"basic TP + non-owner liability additions");}else if(liability&&owner)set(f,"tp_premium",money(Math.max(0,round(liability.value-owner.value))),.99,liability.page,"liability less owner-driver PA");set(f,"cpa_opted",owner&&owner.value>0?"Yes":"No",1,owner?.page??1,owner?.evidence??"no owner-driver PA");set(f,"cpa_premium",money(owner?.value??0),1,owner?.page??1,owner?.evidence??"no owner-driver PA");putMoney(f,"total_premium",net);const tax=magmaTax(pages,tables);putMoney(f,"tax_amount",tax);putMoney(f,"gross_premium",preferReconciledGross(net,tax,moneyHit(tables,pages,/^TOTAL$/i,100,1e8,"last")));
}
function magmaTax(pages:string[],tables:StructuredPolicyTable[]):Money|null{const cg=moneyHit(tables,pages,/CGST\s*@?\s*9%?/i,1,1e7,"last"),sg=moneyHit(tables,pages,/SGST\s*@?\s*9%?/i,1,1e7,"last");if(cg&&sg)return combine(cg,sg,"CGST + SGST");const total=moneyHit(tables,pages,/TOTAL\s+IGST/i,20,1e7,"last");if(total)return total;const five=moneyHit(tables,pages,/IGST\s*@?\s*5%/i,1,1e7,"last"),eighteen=moneyHit(tables,pages,/IGST\s*@?\s*18%/i,1,1e7,"last");return five&&eighteen?combine(five,eighteen,"split IGST"):null;}

function refineDigit(pages:string[],tables:StructuredPolicyTable[],f:Fields){set(f,"insurer_name","Go Digit General Insurance Limited",1,1,"current Digit header");set(f,"policy_product","Package",1,1,"Digit private-car policy");identity(f,pages,"digit");putMoney(f,"idv",moneyHit(tables,pages,/Total\s+IDV|Vehicle\s+IDV/i,1000,1e9,"largest"));const od=moneyHit(tables,pages,/Total\s+OD\s+Premium|Own\s+Damage\s+Premium/i,20,1e7,"last"),act=moneyHit(tables,pages,/Total\s+Act\s+Premium/i,100,1e7,"last"),owner=ownerDriverPremium(pages,tables),net=moneyHit(tables,pages,/Net\s+Premium/i,100,1e7,"last");putMoney(f,"od_premium",od);if(act)set(f,"tp_premium",money(Math.max(0,round(act.value-(owner?.value??0)))),.99,act.page,"total act less owner-driver PA");set(f,"cpa_opted",owner&&owner.value>0?"Yes":"No",1,owner?.page??1,owner?.evidence??"no owner-driver PA");set(f,"cpa_premium",money(owner?.value??0),1,owner?.page??1,owner?.evidence??"no owner-driver PA");putMoney(f,"total_premium",net);const cg=moneyHit(tables,pages,/CGST\s*@?\s*9%/i,1,1e7,"last"),sg=moneyHit(tables,pages,/SGST|UTGST/i,1,1e7,"last"),tax=cg&&sg?combine(cg,sg,"CGST + SGST/UTGST"):null;putMoney(f,"tax_amount",tax);putMoney(f,"gross_premium",preferReconciledGross(net,tax,moneyHit(tables,pages,/Final\s+Premium|Gross\s+Premium/i,100,1e8,"last")));}
function refineShriram(pages:string[],tables:StructuredPolicyTable[],f:Fields,text:string){set(f,"insurer_name","Shriram General Insurance Company Limited",1,1,"current Shriram header");set(f,"policy_product","Third Party",1,1,"Shriram liability/third-party current policy");identity(f,pages,"shriram");set(f,"idv","0",1,1,"liability policy");set(f,"od_premium","0",1,1,"liability policy");const basic=moneyHit(tables,pages,/Basic\s+TP|Basic\s+Third\s+Party|Third\s+Party\s+Liability/i,100,1e7,"last"),liability=moneyHit(tables,pages,/Total\s+Liability\s+Premium|Net\s+Liability\s+Premium/i,100,1e7,"last"),owner=ownerDriverPremium(pages,tables),tp=basic??(liability?{...liability,value:Math.max(0,round(liability.value-(owner?.value??0)))}:null);putMoney(f,"tp_premium",tp);if(owner){set(f,"cpa_opted",owner.value>0?"Yes":"No",1,owner.page,owner.evidence);set(f,"cpa_premium",money(owner.value),1,owner.page,owner.evidence);}else if(/NOT\s+OPT(?:ED|ING).*PA|CPA.*REMOVED/i.test(text)){set(f,"cpa_opted","No",1,1,"explicit PA/CPA opt-out");set(f,"cpa_premium","0",1,1,"explicit PA/CPA opt-out");}const net=moneyHit(tables,pages,/Net\s+Premium|Total\s+Premium|Total\s+Liability\s+Premium/i,100,1e7,"last")??liability;putMoney(f,"total_premium",net);const tax=shriramTax(pages,tables);putMoney(f,"tax_amount",tax);putMoney(f,"gross_premium",preferReconciledGross(net,tax,moneyHit(tables,pages,/Gross\s+Premium|Total\s+Amount\s+Payable|Total\s+Payable/i,100,1e8,"last")));}
function shriramTax(pages:string[],tables:StructuredPolicyTable[]):Money|null{const total=moneyHit(tables,pages,/Total\s+GST|\bIGST\b/i,20,1e7,"last");if(total)return total;const cg=moneyHit(tables,pages,/CGST/i,1,1e7,"last"),sg=moneyHit(tables,pages,/SGST/i,1,1e7,"last");return cg&&sg?combine(cg,sg,"CGST + SGST"):null;}

function commonVehicle(pages:string[],tables:StructuredPolicyTable[],f:Fields,layout:Layout){const reg=fieldHit(tables,pages,/(?:Vehicle\s+)?(?:Registration|Regn\.?)\s*(?:No\.?|Number)(?!\s+Authority)/i,vehicleId);if(reg){if(/^NEW(?:[-/\s]|$)|^NEW-?0+1$/i.test(reg.value)){set(f,"vehicle_registration_status","registration_pending",1,reg.page,reg.evidence);f.delete("vehicle_registration_number");}else{set(f,"vehicle_registration_status","registered",.99,reg.page,reg.evidence);set(f,"vehicle_registration_number",compactRegistration(reg.value),.99,reg.page,reg.evidence);}}const chassis=fieldHit(tables,pages,/Chassis\s*(?:No\.?|Number)?/i,chassisId),engine=fieldHit(tables,pages,/Engine(?:\s+or\s+M\/C)?\s*(?:No\.?|Number)?/i,engineId);if(chassis)set(f,"vehicle_chassis_number",compact(chassis.value),.98,chassis.page,chassis.evidence);if(engine)set(f,"vehicle_engine_number",compact(engine.value),.98,engine.page,engine.evidence);const make=fieldHit(tables,pages,/^(?:Vehicle\s+)?Make\s*[:/-]?$/i,makeText),model=fieldHit(tables,pages,/^(?:Vehicle\s+)?Model(?:\s*-\s*Variant)?\s*[:/-]?$/i,modelText),combined=fieldHit(tables,pages,/(?:Vehicle\s+)?Make\s*\/\s*Model|Vehicle\s+Make\s*&\s*Model|Make\s*\/\s*Model\s*\/\s*Type\s+of\s+Body/i,vehicleText);if(make)set(f,"vehicle_make",cleanMake(make.value),.98,make.page,make.evidence);if(model)set(f,"vehicle_model",cleanModel(model.value),.98,model.page,model.evidence);if(combined&&(!make||!model))applyCombinedMakeModel(f,combined);const fuel=fieldHit(tables,pages,/^(?:Type\s+of\s+)?Fuel(?:\s+Type)?\s*:?$/i,fuelText),yr=fieldHit(tables,pages,/Year\s+of\s+(?:Manufacture|Mfg)|Mfg\.?\s*Year|^Year$/i,/^(?:19|20)\d{2}$/);if(fuel)set(f,"vehicle_fuel_type",normalizeFuel(fuel.value),.97,fuel.page,fuel.evidence);if(yr)set(f,"vehicle_manufacturing_year",yr.value,.97,yr.page,yr.evidence);const cls=classFor(layout);set(f,"vehicle_class",cls,1,1,"insurer/product layout family");const capLabel=cls==="GCV"?/GVW|Gross\s+Vehicle\s+Weight/i:cls==="PCV"?/Carrying\s+Capacity|Seating\s+Capacity|Licensed\s+Seating/i:/Cubic\s+Capacity|Cubic\s+Capacity\/Watts|\bCC\s*\/\s*KW\b|^\s*CC\s*$/i;const cap=fieldHit(tables,pages,capLabel,/^\d{1,6}(?:\.\d+)?$/);if(cap&&!isPercentLike(cap.value))set(f,"vehicle_capacity",cap.value.replace(/,/g,""),.97,cap.page,cap.evidence);const auth=fieldHit(tables,pages,/Registration\s+Authority|RTA\s+Name|RTO(?:\s+Name|\s+Location)?/i,rtoText),rr=rto(auth?.value??reg?.value??"");if(rr.name)set(f,"vehicle_rto_name",rr.name,.94,auth?.page??reg?.page??1,auth?.evidence??reg?.evidence??"RTO");if(rr.state)set(f,"vehicle_rto_state",rr.state,.94,auth?.page??reg?.page??1,auth?.evidence??reg?.evidence??"RTO");}
function classFor(layout:Layout):"GCV"|"PCV"|"PCP"|"TWP"{if(layout.includes("gcv"))return"GCV";if(layout.includes("pcv"))return"PCV";if(layout.includes("twp"))return"TWP";return"PCP";}
function identity(f:Fields,pages:string[],family:string){const no=policyNo(pages,family);if(no)set(f,"policy_number",no.value,.99,no.page,no.evidence);const per=period(pages,family);if(per){set(f,"policy_start_date",per.from,.99,per.page,per.evidence);set(f,"policy_end_date",per.to,.99,per.page,per.evidence);}}
function policyNo(pages:string[],family:string):Hit|null{for(let pi=0;pi<Math.min(pages.length,3);pi++)for(const raw of pages[pi].split(/\r?\n/)){const line=norm(raw);if(!/Policy\s*(?:No\.?|Number|#)/i.test(line)||/Previous\s+Policy|Active\s+TP\s+Policy|Liability\s+Policy\s+No|Existing\s+TP/i.test(line))continue;let v:string|undefined;if(family==="hdfc")v=line.match(/Policy\s*No\.?\s*[:#-]?\s*((?:\d[\s-]?){15,25})/i)?.[1]?.replace(/\D/g,"");else if(family==="royal")v=line.match(/Policy\s*No\.?\s*[:#-]?\s*(VPT[A-Z0-9/-]{8,30})/i)?.[1];else if(family==="digit")v=line.match(/Policy\s*(?:No\.?|Number)\s*[:#-]?\s*(D\d{6,15})\b/i)?.[1];else v=line.match(/Policy\s*(?:No\.?|Number)\s*[:#-]?\s*([A-Z0-9][A-Z0-9/-]{5,40})/i)?.[1];if(v&&/\d/.test(v))return{value:v.replace(/\s+/g,""),page:pi+1,evidence:line};}return null;}
function period(pages:string[],family:string):{from:string;to:string;page:number;evidence:string}|null{const anchor=family==="new_india"?/Period\s+of\s+cover|Own\s+Damage\s+Period/i:family==="digit"?/Period\s+of\s+Policy\s+for\s+Own\s+Damage\s+Cover/i:/Period\s+of\s+Insurance|Policy\s+Effective\s+from|Effective\s+date\s+of\s+commencement|From\s+\d/i;for(let pi=0;pi<Math.min(pages.length,4);pi++){const lines=pages[pi].split(/\r?\n/);for(let i=0;i<lines.length;i++){if(!test(anchor,lines[i]))continue;const block=lines.slice(i,i+10).join(" ");const ds=dates(block).map(parseDate).filter((x):x is string=>!!x);if(ds.length>=2)return{from:ds[0],to:ds[1],page:pi+1,evidence:norm(block)};}}return null;}

function fieldHit(tables:StructuredPolicyTable[],pages:string[],label:RegExp,accept:RegExp|((v:string)=>boolean)):Hit|null{const fromTables=tableValue(tables,label,accept);if(fromTables)return fromTables;return pageValue(pages,label,accept);}
function tableValue(tables:StructuredPolicyTable[],label:RegExp,accept:RegExp|((v:string)=>boolean)):Hit|null{for(const tb of tables)for(let ri=0;ri<tb.rows.length;ri++){const row=tb.rows[ri].map(norm);for(let ci=0;ci<row.length;ci++){const cell=row[ci];if(!test(label,cell))continue;const inline=trim(cell.replace(label,""));label.lastIndex=0;if(inline&&ok(accept,inline)&&!garbage(inline))return hit(inline,tb.page,row);for(const x of row.slice(ci+1)){const c=trim(x);if(c&&ok(accept,c)&&!garbage(c))return hit(c,tb.page,row);}for(let n=ri+1;n<=Math.min(ri+4,tb.rows.length-1);n++){const c=trim(tb.rows[n][ci]??"");if(c&&ok(accept,c)&&!garbage(c))return hit(c,tb.page,[cell,c]);}}}return null;}
function pageValue(pages:string[],label:RegExp,accept:RegExp|((v:string)=>boolean)):Hit|null{for(let pi=0;pi<pages.length;pi++){const lines=pages[pi].split(/\r?\n/).map(norm).filter(Boolean);for(let i=0;i<lines.length;i++){const line=lines[i];if(!test(label,line))continue;const m=line.match(label);label.lastIndex=0;const after=m?.index===undefined?"":trim(line.slice((m.index??0)+(m[0]?.length??0)));for(const c of [after,...lines.slice(i+1,i+4).map(trim)])if(c&&ok(accept,c)&&!garbage(c))return hit(c,pi+1,lines.slice(i,i+3));}}return null;}
function moneyHit(tables:StructuredPolicyTable[],pages:string[],label:RegExp,min:number,max:number,mode:"first"|"last"|"largest"="first"):Money|null{const a=amountFromTables(tables,label,min,max,mode),b=amountFromPages(pages,label,min,max,mode);return a??b;}
function amountFromTables(tables:StructuredPolicyTable[],label:RegExp,min:number,max:number,mode:"first"|"last"|"largest"):Money|null{const hits:Money[]=[];for(const tb of tables)for(let ri=0;ri<tb.rows.length;ri++){const row=tb.rows[ri].map(norm);for(let ci=0;ci<row.length;ci++){const cell=row[ci];if(!test(label,cell))continue;const m=cell.match(label);label.lastIndex=0;const sources=[row.slice(ci+1).join(" "),m?.index===undefined?"":cell.slice((m.index??0)+(m[0]?.length??0)),[1,2].map((o)=>tb.rows[ri+o]?.[ci]??"").join(" ")];for(const src of sources){const xs=nums(src).filter((v)=>v>=min&&v<=max&&!year(v)&&!percentToken(v,src));if(xs.length){hits.push({value:pick(xs,mode),page:tb.page,evidence:norm(row.join(" | "))});break;}}}}return choose(hits,mode);}
function amountFromPages(pages:string[],label:RegExp,min:number,max:number,mode:"first"|"last"|"largest"):Money|null{const hits:Money[]=[];for(let pi=0;pi<pages.length;pi++){const lines=pages[pi].split(/\r?\n/);for(let i=0;i<lines.length;i++){if(!test(label,lines[i]))continue;const m=lines[i].match(label);label.lastIndex=0;const after=m?.index===undefined?lines[i]:lines[i].slice((m.index??0)+(m[0]?.length??0));let xs=nums(after).filter((v)=>v>=min&&v<=max&&!year(v)&&!percentToken(v,after));if(!xs.length){const next=lines.slice(i+1,i+2).join(" ");xs=nums(next).filter((v)=>v>=min&&v<=max&&!year(v)&&!percentToken(v,next));}if(xs.length)hits.push({value:pick(xs,mode),page:pi+1,evidence:norm(lines.slice(i,i+2).join(" "))});}}return choose(hits,mode);}
function ownerDriverPremium(pages:string[],tables:StructuredPolicyTable[]):Money|null{return moneyHit(tables,pages,/(?:PA|P\.A\.|Personal\s+Accident)\s+(?:Cover\s+)?(?:for\s+)?Owner\s*[- ]?Driver|Owner\s*[- ]?Driver\s+(?:PA|CPA)/i,20,1e5,"last");}
function combine(a:Money,b:Money,evidence:string):Money{return{value:round(a.value+b.value),page:a.page,evidence:`${evidence}: ${a.evidence} | ${b.evidence}`};}
function preferReconciledGross(net:Money|null,tax:Money|null,printed:Money|null):Money|null{if(net&&tax){const derived=round(net.value+tax.value);if(!printed||printed.value<net.value||Math.abs(printed.value-derived)>Math.max(2,derived*.03))return{value:derived,page:net.page,evidence:"net + tax reconciliation"};return printed;}return printed;}
function applyFinancialSanity(f:Fields){const net=numField(f,"total_premium"),tax=numField(f,"tax_amount"),gross=numField(f,"gross_premium"),tp=numField(f,"tp_premium"),cpa=numField(f,"cpa_premium");if(cpa!==null&&cpa<0)f.delete("cpa_premium");if(tp!==null&&net!==null&&tp>net*1.1)f.delete("tp_premium");if(net!==null&&tax!==null&&gross!==null&&Math.abs((net+tax)-gross)>Math.max(2,(net+tax)*.03))set(f,"gross_premium",money(net+tax),.95,f.get("total_premium")?.page??1,"financial reconciliation: net + GST");}
function numField(f:Fields,key:string):number|null{const v=f.get(key)?.value,n=v==null?NaN:Number(v);return Number.isFinite(n)?n:null;}
function putMoney(f:Fields,key:string,x:Money|null){if(x)set(f,key,money(x.value),.99,x.page,x.evidence);}
function set(f:Fields,key:string,value:string,confidence:number,page:number|null,evidence:string){const v=norm(value);if(v)f.set(key,{key,label:labels[key]??key,value:v,confidence,page,evidence:norm(evidence).slice(0,400)});}
function cleanVehicle(f:Fields){for(const key of ["vehicle_make","vehicle_model","vehicle_registration_number","vehicle_engine_number","vehicle_chassis_number","vehicle_rto_name"]){const x=f.get(key);if(x&&garbage(x.value))f.delete(key);}}
function repairIds(f:Fields){const e=f.get("vehicle_engine_number"),c=f.get("vehicle_chassis_number");if(!e||!c)return;const ev=compact(e.value),cv=compact(c.value);if(ev===cv&&ev.length>20){f.delete("vehicle_engine_number");return;}if(ev.length>cv.length+5&&ev.endsWith(cv)){const v=ev.slice(0,-cv.length);if(v.length>=6)f.set(e.key,{...e,value:v});}}
function applyCombinedMakeModel(f:Fields,h:Hit){const raw=norm(h.value),pieces=raw.split(/\s*(?:\/|&|\|)\s*/).filter(Boolean);if(pieces.length>=2){if(!f.get("vehicle_make"))set(f,"vehicle_make",cleanMake(pieces[0]),.97,h.page,h.evidence);if(!f.get("vehicle_model"))set(f,"vehicle_model",cleanModel(pieces.slice(1).join(" ")),.97,h.page,h.evidence);return;}const m=raw.match(/^(MARUTI(?:\s+SUZUKI)?|TATA(?:\s+MOTORS?)?|BMW|KIA|HERO|SKODA(?:\s+AUTO)?|SCOOTERS\s+INDIA|DAIMLER\s+INDIA\s+COMMERCIAL\s+VEHICLES)\s+(.*)$/i);if(m){if(!f.get("vehicle_make"))set(f,"vehicle_make",cleanMake(m[1]),.96,h.page,h.evidence);if(m[2]&&!f.get("vehicle_model"))set(f,"vehicle_model",cleanModel(m[2]),.96,h.page,h.evidence);}}
function garbage(value:string):boolean{const x=norm(value);return /^(?:VEHICLE|DESCRIPTION|MODEL|MAKE|MAKE\s*\/\s*MODEL|FUEL\s+TYPE|TYPE\s+OF\s+BODY|MAKEMODEL|ENGINE(?:\s+(?:NO\.?|NUMBER))?|CHASSIS(?:\s+(?:NO\.?|NUMBER))?|REGISTRATION(?:\s+(?:NO\.?|NUMBER))?|VEHICLE\s+REGISTRATION\s+NO\.?|YEAR\s+OF\s+MFG|INSURED\s*&\s*VEHICLE\s+DETAILS|GVW|TOTAL\s+IDV|RTO|\(IF\s+ANY\)|&\s*VARIANT)$/i.test(x)||/^(?:MODEL\s+)?TYPE\s+OF\b|^OF\s+OF\b|SECTION\s+(?:I|II|III|IV)\b|GEOGRAPHICAL\s+AREA|TOWING\s+DISABLED|ABOUT\s+THE\s+THEFT\s+OF\s+VEHICLE/i.test(x);}
function vehicleId(v:string):boolean{const x=norm(v);return /^(?:NEW(?:[-/\s].*)?|[A-Z0-9][A-Z0-9\s/-]{4,35})$/i.test(x)&&(/^NEW(?:[-/\s]|$)/i.test(x)||(/[A-Z]/i.test(x)&&/\d/.test(x)))&&!garbage(x);}
function chassisId(v:string):boolean{const x=compact(v);return x.length>=6&&x.length<=24&&/[A-Z0-9]/.test(x)&&!garbage(v);}
function engineId(v:string):boolean{const x=compact(v);return x.length>=6&&x.length<=22&&/[A-Z]/.test(x)&&/\d/.test(x)&&!garbage(v);}
function vehicleText(v:string):boolean{const x=norm(v);return x.length>=2&&x.length<=100&&/[A-Z]/i.test(x)&&!/^(?:NA|N\/A|NONE|NULL)$/i.test(x)&&!garbage(x);}
function makeText(v:string):boolean{return vehicleText(v)&&!/MODEL|VARIANT|REGISTRATION|YEAR|BODY|ENGINE|CHASSIS/i.test(v);}
function modelText(v:string):boolean{return vehicleText(v)&&!/MAKE|REGISTRATION|YEAR\s+OF|BODY|ENGINE|CHASSIS/i.test(v);}
function fuelText(v:string):boolean{return /PETROL|DIESEL|CNG|LPG|ELECTRIC|BATTERY|HYBRID/i.test(norm(v));}
function rtoText(v:string):boolean{return vehicleText(v)&&!/THEFT|VEHICLE\s+DETAILS|MODEL|MAKE/i.test(v);}
function compactRegistration(v:string):string{return compact(v).replace(/^VEHICLE/,"");}
function compact(v:string):string{return v.toUpperCase().replace(/[^A-Z0-9]/g,"");}
function cleanMake(v:string):string{const x=norm(v);if(/DAIMLER\s+INDIA\s+COMMERCIAL\s+VEHICLES/i.test(x))return"BharatBenz";if(/MARUTI\s+SUZUKI/i.test(x))return"Maruti Suzuki";if(/SKODA\s+AUTO/i.test(x))return"Skoda";if(/SCOOTERS\s+INDIA/i.test(x))return"Scooters India";if(/TATA(?:\s+MOTORS?)?/i.test(x))return"Tata";if(/\bBMW\b/i.test(x))return"BMW";if(/\bKIA\b/i.test(x))return"Kia";if(/\bHERO\b/i.test(x))return"Hero";return x.replace(/\b(?:INDIA|PVT\.?|PRIVATE|LIMITED|LTD\.?)\b/gi," ").replace(/\s+/g," ").trim();}
function cleanModel(v:string):string{return norm(v).replace(/^(?:TATA|MARUTI\s+SUZUKI|KIA|BMW)\s*[/:-]\s*/i,"").replace(/\bBS\s*VI\b/gi,"").replace(/\bNULL\b/gi,"").replace(/\s+/g," ").trim();}
function normalizeFuel(v:string):string{const x=norm(v).toUpperCase();if(/ELECTRIC|BATTERY/.test(x))return"Electric";if(/CNG/.test(x))return"CNG";if(/LPG/.test(x))return"LPG";if(/DIESEL/.test(x))return"Diesel";if(/PETROL/.test(x))return"Petrol";if(/HYBRID/.test(x))return"Hybrid";return title(v);}
function rto(v:string):{name:string|null;state:string|null}{const u=norm(v).toUpperCase(),m=u.match(/\b(MP|DL|HR|UP|RJ)[-\s]?0?(\d{1,2})\b/);let name=m?`${m[1]}${String(Number(m[2])).padStart(m[1]==="DL"?2:1,"0")}`:null;if(!name){if(/JABALPUR/.test(u))name="MP20";else if(/MANDLA/.test(u))name="MP51";else if(/SEONI/.test(u))name="MP22";else if(/NARSINGHPUR/.test(u))name="MP49";else if(/ANUPPUR/.test(u))name="MP65";else if(/BALLABGARH|FARIDABAD/.test(u))name="HR29";else if(/PALWAL|HODAL/.test(u))name="HR30";else if(/JAIPUR/.test(u))name="RJ14";else if(/FATEHPUR/.test(u))name="UP71";else if(/DELHI/.test(u))name="DL08";}const state=name?.startsWith("MP")?"Madhya Pradesh":name?.startsWith("DL")?"Delhi":name?.startsWith("HR")?"Haryana":name?.startsWith("RJ")?"Rajasthan":name?.startsWith("UP")?"Uttar Pradesh":null;return{name,state};}
function dates(v:string):string[]{const a=v.match(/\b\d{1,2}\s*[\/-]\s*\d{1,2}\s*[\/-]\s*\d{2,4}\b/g)??[],b=v.match(/\b\d{1,2}[\s-]+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*,?[\s-]+\d{4}\b/gi)??[];return[...a,...b].sort((x,y)=>v.indexOf(x)-v.indexOf(y));}
function parseDate(v:string):string|null{const x=norm(v).replace(/\s*([/-])\s*/g,"$1"),n=x.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{2,4})$/);if(n){let y=+n[3];if(y<100)y+=y>=70?1900:2000;return iso(+n[1],+n[2],y);}const w=x.match(/^(\d{1,2})[\s-]+([A-Za-z]{3,9}),?[\s-]+(\d{4})$/);if(!w)return null;const ms:Record<string,number>={jan:1,feb:2,mar:3,apr:4,may:5,jun:6,jul:7,aug:8,sep:9,oct:10,nov:11,dec:12};return iso(+w[1],ms[w[2].slice(0,3).toLowerCase()]??0,+w[3]);}
function iso(d:number,m:number,y:number):string|null{return d<1||d>31||m<1||m>12?null:`${String(y).padStart(4,"0")}-${String(m).padStart(2,"0")}-${String(d).padStart(2,"0")}`;}
function nums(v:string):number[]{return[...v.matchAll(/\d[\d,]*(?:\.\d{1,2})?/g)].map((m)=>Number(m[0].replaceAll(",",""))).filter(Number.isFinite);}
function percentToken(n:number,src:string):boolean{return (n===5||n===9||n===18||n===28||n===75||n===100)&&new RegExp(`\\b${n}\\s*%|IMT\\s*${n}\\b`,"i").test(src);}
function isPercentLike(v:string):boolean{return /^(?:5|9|18|28|75|100)(?:\.0+)?$/.test(v);}
function pick(xs:number[],mode:"first"|"last"|"largest"):number{return mode==="largest"?Math.max(...xs):mode==="last"?xs[xs.length-1]:xs[0];}
function choose(xs:Money[],mode:"first"|"last"|"largest"):Money|null{if(!xs.length)return null;return mode==="last"?xs[xs.length-1]:mode==="largest"?xs.reduce((a,b)=>b.value>a.value?b:a):xs[0];}
function hit(value:string,page:number,evidence:string[]):Hit{return{value,page,evidence:norm(evidence.join(" | "))};}
function test(r:RegExp,v:string):boolean{r.lastIndex=0;const matched=r.test(v);r.lastIndex=0;return matched;}
function ok(a:RegExp|((v:string)=>boolean),v:string):boolean{return a instanceof RegExp?test(a,v):a(v);}
function trim(v:string):string{return norm(v).replace(/^[:|\-\s]+|[:|\-\s]+$/g,"");}
function norm(v:string):string{return v.replace(/\s+/g," ").trim();}
function title(v:string):string{const x=norm(v).toLowerCase();return x?x[0].toUpperCase()+x.slice(1):x;}
function year(v:number):boolean{return v>=1900&&v<=2100&&Number.isInteger(v);}
function round(v:number):number{return Math.round((v+Number.EPSILON)*100)/100;}
function money(v:number):string{const x=round(v);return Number.isInteger(x)?String(x):x.toFixed(2).replace(/0+$/,"").replace(/\.$/,"");}
