import Link from "next/link";
import { FormSubmitButton } from "@/components/form-submit-button";

type Customer = { company_name:string|null; pan_number:string|null; gst_number:string|null; address_street:string|null; address_locality:string|null; india_location_id:string|null; city:string|null; state:string|null; postal_code:string|null; fleet_size_band:string|null };
type Contact = { contact_role:string; full_name:string; phone:string; email:string|null; access_status:string; profile_id:string|null };
type GroupOption = { id:string; customer_code:string; company_name:string|null; contact_name:string };
type Props = { customer:Customer; contacts:Contact[]; groups:GroupOption[]; currentGroupId:string|null; action:(formData:FormData)=>Promise<void>; errorMessage:string|null; successMessage:string|null };
const input = "h-10 w-full rounded-md border border-[#CBD5E1] bg-white px-3 text-[12px] text-[#17203A]";
const label = "mb-1 block text-[10.5px] font-semibold text-[#344054]";
const roles = [["ceo_head","CEO / Head"],["admin_head","Admin Head"],["dedicated_spoc","Dedicated SPOC"]] as const;

export function CorporateProfileEditor({ customer, contacts, groups, currentGroupId, action, errorMessage, successMessage }: Props) {
  const byRole = Object.fromEntries(contacts.map((contact)=>[contact.contact_role,contact]));
  return <div className="mx-auto max-w-[1240px] space-y-3 pb-16">
    {errorMessage?<div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-[11px] text-red-700">{errorText(errorMessage)}</div>:null}
    {successMessage?<div className="rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-[11px] text-emerald-700">Corporate profile updated.</div>:null}
    <form action={action} className="overflow-hidden rounded-xl border border-[#E2E8F0] bg-white">
      <Section title="Company details"><Field labelText="Company name" name="company_name" required defaultValue={customer.company_name??""}/><Field labelText="Company PAN" name="company_pan" required maxLength={10} defaultValue={customer.pan_number??""}/><Field labelText="GSTIN" name="gst_number" maxLength={15} defaultValue={customer.gst_number??""}/><Select labelText="Fleet size" name="fleet_size_band" required defaultValue={customer.fleet_size_band??""}/></Section>
      <Section title="Group affiliation"><div className="md:col-span-2"><label className={label} htmlFor="parent_group_id">Parent Group</label><select id="parent_group_id" name="parent_group_id" defaultValue={currentGroupId??""} className={input}><option value="">No parent Group</option>{groups.map((group)=><option key={group.id} value={group.id}>{group.company_name?.trim()||group.contact_name} · {group.customer_code}</option>)}</select><p className="mt-1 text-[10px] text-[#64748B]">Select an active Group to link this Corporate customer. Choosing “No parent Group” removes the existing link without deleting customer data.</p></div><div className="rounded-lg border border-[#E2E8F0] bg-[#F8FAFC] px-3 py-2 text-[10.5px] text-[#475569]"><span className="font-semibold">Current status:</span> {currentGroupId?"Linked to Group":"Independent Corporate"}</div></Section>
      <Section title="Company address"><Field labelText="Street" name="address_street" required defaultValue={customer.address_street??""}/><Field labelText="Locality" name="address_locality" defaultValue={customer.address_locality??""}/><Field labelText="City" name="city" required defaultValue={customer.city??""}/><Field labelText="State" name="state" required defaultValue={customer.state??""}/><Field labelText="PIN code" name="postal_code" required maxLength={6} defaultValue={customer.postal_code??""}/><Field labelText="Location ID" name="india_location_id" required defaultValue={customer.india_location_id??""}/></Section>
      <section className="border-t border-[#E2E8F0] px-5 py-4"><h3 className="text-[13px] font-semibold">Corporate login contacts</h3><p className="mt-1 text-[10.5px] text-[#64748B]">Pending users receive access after signing up with the same mobile number.</p><div className="mt-3 grid gap-3 lg:grid-cols-3">{roles.map(([role,title])=>{const contact=byRole[role];return <div key={role} className="rounded-lg border border-[#E2E8F0] p-3"><div className="mb-3 flex items-center justify-between"><h4 className="text-[11px] font-semibold">{title}</h4><span className={`rounded-full px-2 py-0.5 text-[9px] font-semibold ${contact?.access_status==="active"?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}>{contact?.access_status??"pending"}</span></div><Field labelText="Full name" name={`${role}_name`} required defaultValue={contact?.full_name??""}/><div className="mt-2"><Field labelText="Mobile" name={`${role}_mobile`} required maxLength={10} defaultValue={(contact?.phone??"").replace(/^\+91/,"")}/></div><div className="mt-2"><Field labelText="Email" name={`${role}_email`} type="email" defaultValue={contact?.email??""}/></div></div>})}</div></section>
      <div className="flex justify-end gap-2 border-t border-[#E2E8F0] px-5 py-3"><Link href="/customers" className="rounded-md border px-4 py-2 text-[11px] font-semibold">Cancel</Link><FormSubmitButton label="Save Corporate Profile"/></div>
    </form>
  </div>;
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="border-b border-[#E2E8F0] px-5 py-4"><h3 className="mb-3 text-[13px] font-semibold">{title}</h3><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{children}</div></section>}
function Field({labelText,...props}:React.InputHTMLAttributes<HTMLInputElement>&{labelText:string}){return <div><label className={label} htmlFor={props.name}>{labelText}{props.required?" *":""}</label><input id={String(props.name)} className={input} {...props}/></div>}
function Select({labelText,...props}:React.SelectHTMLAttributes<HTMLSelectElement>&{labelText:string}){return <div><label className={label} htmlFor={props.name}>{labelText} *</label><select id={String(props.name)} className={input} {...props}><option value="">Select</option><option value="less_than_5">Less than 5</option><option value="5_to_20">5 to 20</option><option value="20_to_50">20 to 50</option><option value="more_than_50">More than 50</option></select></div>}
function errorText(value:string){const map:Record<string,string>={unauthorized:"You are not authorized.",invalid_corporate_details:"Complete all required Corporate details.",invalid_contacts:"Enter three different valid login contacts.",invalid_group:"Select a valid active Group.",group_update_failed:"Group affiliation could not be updated.",customer_update_failed:"Corporate profile could not be updated."};return map[value]??"The Corporate profile could not be updated."}
