"use client";

import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import { FormSubmitButton } from "@/components/form-submit-button";
import { IndianDateField } from "@/components/indian-date-field";
import { updateIntermediaryApplication } from "./intermediary-edit-actions";
import { retryPospMispPanVerification } from "./posp-misp-workflow-actions";

export type PospMispEditProfile={partner_type:"posp"|"misp";partner_id:string|null;associate_employee_id:string|null;associate_profile_id:string|null;external_onboarding_id:string|null;document_received_at:string|null;pos_name:string|null;pos_first_name:string|null;pos_middle_name:string|null;pos_last_name:string|null;misp_name:string|null;applicant_phone:string|null;applicant_email:string|null;date_of_birth:string|null;aadhaar_last_four:string|null;aadhaar_number:string|null;pan_number:string|null;gst_number:string|null;address:string|null;city:string|null;state:string|null;postal_code:string|null;bank_id:string|null;bank_account_number:string|null;bank_ifsc_code:string|null;oem_name:string|null;dp_name:string|null;dp_first_name:string|null;dp_middle_name:string|null;dp_last_name:string|null;dp_phone:string|null;dp_email:string|null;dp_pan_number:string|null};
type WorkflowStage="pre_iib"|"iib_processing"|"training"|"completed";type ViewStage="primary"|"documents"|"review";
type Props={applicationId:string;profile:PospMispEditProfile;workflowStage?:WorkflowStage;viewStage?:ViewStage;editable:boolean;salesManagers:Array<{value:string;label:string}>;banks:Array<{value:string;label:string}>;oems:Array<{value:string;label:string}>;documents:Array<{document_type:string;file_name:string}>};
const inputClass="h-10 w-full rounded-xl border border-[#CBD5E1] bg-white px-3 text-[11px] font-medium text-[#17203A] outline-none transition focus:border-[#635BFF] focus:ring-2 focus:ring-[#E7E5FF] disabled:bg-[#F8FAFC] disabled:text-[#475569]";const labelClass="mb-1.5 block text-[9.5px] font-semibold uppercase tracking-[0.04em] text-[#526178]";const namePattern="[A-Za-z ]+";
const marksheetOptions=[["education_10th_marksheet","10th Marksheet"],["education_12th_marksheet","12th Marksheet"],["education_graduation_marksheet","Graduation Marksheet"],["education_post_graduation_marksheet","Post Graduation Marksheet"]] as const;
const baseDocumentFields=[["aadhaar_front","Aadhaar front"],["aadhaar_back","Aadhaar back"],["pan_copy","PAN copy"],["cancelled_cheque","Cancelled cheque"],["photograph","Photograph"],["agreement_copy","Agreement copy"]] as const;

export function PospMispApplicationEditor({applicationId,profile,workflowStage="pre_iib",viewStage,editable,salesManagers,banks,oems,documents}:Props){
 const isMisp=profile.partner_type==="misp";const requiresGstDocument=isMisp||Boolean(profile.gst_number);const documentFields=useMemo(()=>requiresGstDocument?[...baseDocumentFields,["gst_copy","GST certificate"] as const]:baseDocumentFields,[requiresGstDocument]);const requiredUploadNames=useMemo(()=>["education_marksheet",...documentFields.map(([value])=>value)],[documentFields]);
 const currentMarksheet=documents.find(document=>marksheetOptions.some(([value])=>value===document.document_type));const fallbackPos=useMemo(()=>splitName(profile.pos_name),[profile.pos_name]);const fallbackDp=useMemo(()=>splitName(profile.dp_name),[profile.dp_name]);
 const[posFirstName,setPosFirstName]=useState(profile.pos_first_name??fallbackPos.first);const[posMiddleName,setPosMiddleName]=useState(profile.pos_middle_name??fallbackPos.middle);const[posLastName,setPosLastName]=useState(profile.pos_last_name??fallbackPos.last);const[dpFirstName,setDpFirstName]=useState(profile.dp_first_name??fallbackDp.first);const[dpMiddleName,setDpMiddleName]=useState(profile.dp_middle_name??fallbackDp.middle);const[dpLastName,setDpLastName]=useState(profile.dp_last_name??fallbackDp.last);const[dpPhone,setDpPhone]=useState(profile.dp_phone??profile.applicant_phone??"");const[dpEmail,setDpEmail]=useState(profile.dp_email??profile.applicant_email??"");
 const[selectedFiles,setSelectedFiles]=useState<Record<string,boolean>>({});const[selectedMarksheetType,setSelectedMarksheetType]=useState(currentMarksheet?.document_type??"");const[missingDocument,setMissingDocument]=useState<string|null>(null);const formRef=useRef<HTMLFormElement>(null);
 const activeView=viewStage??(workflowStage==="pre_iib"?"primary":workflowStage==="iib_processing"?"documents":"review");const showPrimary=activeView==="primary";const showDocuments=activeView==="documents";const showReview=activeView==="review";const hasExisting=(name:string)=>name==="education_marksheet"?Boolean(currentMarksheet):documents.some(document=>document.document_type===name);const documentsReady=requiredUploadNames.every(name=>hasExisting(name)||selectedFiles[name])&&Boolean(currentMarksheet||selectedMarksheetType);
 function handleFileChange(name:string,selected:boolean){setSelectedFiles(current=>({...current,[name]:selected}));if(selected&&missingDocument===name)setMissingDocument(null)}function focusDocument(name:string){setMissingDocument(name);requestAnimationFrame(()=>{document.getElementById(`document-${name}`)?.scrollIntoView({behavior:"smooth",block:"center"});const field=formRef.current?.elements.namedItem(name);if(field instanceof HTMLElement)field.focus({preventScroll:true})})}function handleSubmit(event:React.FormEvent<HTMLFormElement>){if(!showDocuments)return;const missing=requiredUploadNames.find(name=>!hasExisting(name)&&!selectedFiles[name]);if(missing){event.preventDefault();focusDocument(missing);return}if(!currentMarksheet&&!selectedMarksheetType){event.preventDefault();focusDocument("education_document_type")}}
 return <form ref={formRef} action={editable?updateIntermediaryApplication:undefined} onSubmit={handleSubmit} className="bg-[#F4F7FB]"><input type="hidden" name="application_id" value={applicationId}/><input type="hidden" name="edit_section" value={showDocuments?"documents":"primary"}/><input type="hidden" name="external_onboarding_id" value={profile.external_onboarding_id??`PENDING-${profile.partner_type.toUpperCase()}-${applicationId}`}/>{isMisp?<><input type="hidden" name="dp_name" value={[dpFirstName,dpMiddleName,dpLastName].filter(Boolean).join(" ")}/><input type="hidden" name="applicant_phone" value={dpPhone}/><input type="hidden" name="applicant_email" value={dpEmail}/></>:<input type="hidden" name="pos_name" value={[posFirstName,posMiddleName,posLastName].filter(Boolean).join(" ")}/>}<div className="space-y-4 p-4 sm:p-5">
 {profile.partner_id?<div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3"><p className="text-[9px] font-semibold uppercase tracking-[.08em] text-emerald-700">Partner ID issued</p><p className="mt-1 text-[16px] font-bold text-emerald-900">{profile.partner_id}</p></div>:null}
 {showPrimary?<section className="overflow-hidden rounded-2xl border border-[#DCE5EF] bg-white shadow-sm"><Header number="1" title="Primary information & PAN check" subtitle="POSP/MISP IDs are issued only after successful onboarding."/><div className="space-y-0">
  <EditorSection title={isMisp?"MISP details":"POSP details"}><div className={`grid gap-4 md:grid-cols-2 xl:col-span-4 ${isMisp?"xl:grid-cols-4":"xl:grid-cols-3"}`}><Select label="RM Name" name="associate_employee_id" defaultValue={profile.associate_employee_id??profile.associate_profile_id??""} options={salesManagers} required disabled={!editable}/>{isMisp?<Field label="MISP Name" name="misp_name" defaultValue={profile.misp_name??""} required disabled={!editable}/>:null}<PanField label={isMisp?"MISP PAN":"PAN Number"} name="pan_number" value={profile.pan_number??""} editable={editable} recheck={!isMisp}/><IndianDateField label="Document Received Date" name="document_received_at" defaultValue={profile.document_received_at} disabled={!editable}/></div>{!isMisp?<div className="grid gap-4 md:grid-cols-3 xl:col-span-4"><Field label="POS First Name" name="pos_first_name" value={posFirstName} onChange={e=>setPosFirstName(e.target.value)} required pattern={namePattern} disabled={!editable}/><Field label="POS Middle Name" name="pos_middle_name" value={posMiddleName} onChange={e=>setPosMiddleName(e.target.value)} pattern={namePattern} disabled={!editable}/><Field label="POS Last Name" name="pos_last_name" value={posLastName} onChange={e=>setPosLastName(e.target.value)} required pattern={namePattern} disabled={!editable}/></div>:null}{isMisp?<Select label="OEM Name" name="oem_name" defaultValue={profile.oem_name??""} options={oems} required disabled={!editable}/>:null}<Field label="Address" name="address" defaultValue={profile.address??""} required disabled={!editable}/><Field label="City" name="city" defaultValue={profile.city??""} required disabled={!editable}/><Field label="State" name="state" defaultValue={profile.state??""} required disabled={!editable}/><Field label="PIN Code" name="postal_code" defaultValue={profile.postal_code??""} required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} disabled={!editable}/></EditorSection>
  {!isMisp?<EditorSection title="POSP contact"><Field label="Mobile Number" name="applicant_phone" defaultValue={profile.applicant_phone??""} required disabled={!editable}/><Field label="Email" name="applicant_email" defaultValue={profile.applicant_email??""} type="email" required disabled={!editable}/><IndianDateField label="Date of Birth" name="date_of_birth" defaultValue={profile.date_of_birth} required disabled={!editable}/><Field label="Aadhaar Number" name="aadhaar_number" defaultValue={profile.aadhaar_number??""} required maxLength={12} pattern="[0-9]{12}" disabled={!editable}/></EditorSection>:null}
  {isMisp?<EditorSection title="Designated Person (DP)"><Field label="DP First Name" name="dp_first_name" value={dpFirstName} onChange={e=>setDpFirstName(e.target.value)} required disabled={!editable}/><Field label="DP Middle Name" name="dp_middle_name" value={dpMiddleName} onChange={e=>setDpMiddleName(e.target.value)} disabled={!editable}/><Field label="DP Last Name" name="dp_last_name" value={dpLastName} onChange={e=>setDpLastName(e.target.value)} required disabled={!editable}/><Field label="DP Contact" name="dp_phone" value={dpPhone} onChange={e=>setDpPhone(e.target.value)} required disabled={!editable}/><Field label="DP Email" name="dp_email" value={dpEmail} onChange={e=>setDpEmail(e.target.value)} required type="email" disabled={!editable}/><PanField label="DP PAN No" name="dp_pan_number" value={profile.dp_pan_number??""} editable={editable} recheck/><IndianDateField label="DP Date of Birth" name="date_of_birth" defaultValue={profile.date_of_birth} required disabled={!editable}/><Field label="DP Aadhaar Number" name="aadhaar_number" defaultValue={profile.aadhaar_number??""} required maxLength={12} pattern="[0-9]{12}" disabled={!editable}/></EditorSection>:null}
  <EditorSection title={isMisp?"Bank & GST detail":"Bank details"}><Select label="Bank Name" name="bank_id" defaultValue={profile.bank_id??""} options={banks} required disabled={!editable}/><Field label="Account Number" name="bank_account_number" defaultValue={profile.bank_account_number??""} required disabled={!editable}/><Field label="IFSC Code" name="bank_ifsc_code" defaultValue={profile.bank_ifsc_code??""} required disabled={!editable}/>{isMisp?<Field label="GST Number" name="gst_number" defaultValue={profile.gst_number??""} required maxLength={15} minLength={15} pattern="[0-9]{2}[A-Za-z]{5}[0-9]{4}[A-Za-z][1-9A-Za-z]Z[0-9A-Za-z]" disabled={!editable}/>:null}</EditorSection>
 </div></section>:null}
 {showDocuments?<section className="overflow-hidden rounded-2xl border border-[#DCE5EF] bg-white shadow-sm"><Header number="2" title="Documents" subtitle="GST certificate is included only when GST details are present or for MISP onboarding."/><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3"><DocumentCard id="document-education_marksheet" label="Marksheet" current={currentMarksheet?.file_name} missing={missingDocument==="education_marksheet"||missingDocument==="education_document_type"}><Select label="Marksheet Type" name="education_document_type" value={selectedMarksheetType} onChange={e=>{setSelectedMarksheetType(e.target.value);setMissingDocument(null)}} options={marksheetOptions.map(([value,label])=>({value,label}))} required disabled={!editable}/><FileReplacement name="education_marksheet" current={currentMarksheet?.file_name} required={!currentMarksheet} disabled={!editable} onChange={selected=>handleFileChange("education_marksheet",selected)}/></DocumentCard>{documentFields.map(([documentType,label])=>{const current=documents.find(document=>document.document_type===documentType);return <DocumentCard id={`document-${documentType}`} key={documentType} label={label} current={current?.file_name} missing={missingDocument===documentType}><FileReplacement name={documentType} current={current?.file_name} required={!current} disabled={!editable} onChange={selected=>handleFileChange(documentType,selected)}/></DocumentCard>})}</div></section>:null}
 {showReview?<section className="overflow-hidden rounded-2xl border border-[#DCE5EF] bg-white shadow-sm"><Header number="3" title="Final review" subtitle="Review the saved details and attached documents."/><div className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-3"><Summary label="Application type" value={profile.partner_type.toUpperCase()}/><Summary label="Partner ID" value={profile.partner_id??"Pending until Stage 2"}/><Summary label="Applicant" value={(isMisp?profile.misp_name:profile.pos_name)??"-"}/><Summary label="Email" value={(isMisp?profile.dp_email:profile.applicant_email)??"-"}/><Summary label="Documents" value={`${documents.length} attached`}/><Summary label="PAN used for IIB" value={(isMisp?profile.dp_pan_number:profile.pan_number)??"-"}/></div></section>:null}</div>{editable&&(showPrimary||showDocuments)?<div className="sticky bottom-0 z-10 flex items-center justify-between gap-3 border-t border-[#DCE5EF] bg-white/95 px-5 py-3 backdrop-blur">{showDocuments?<Link href={`/intermediaries/applications/${applicationId}/workflow?stage=primary`} className="rounded-xl border px-4 py-2.5 text-[10.5px] font-semibold">Back to Primary</Link>:<span/>}<div className="text-right">{showDocuments&&!documentsReady?<p className="mb-1 text-[8.5px] font-semibold text-amber-700">Attach every mandatory document before saving.</p>:null}<FormSubmitButton label={showPrimary?(workflowStage==="pre_iib"?"Save primary details":"Save & return to Documents"):"Save documents"} pendingLabel="Saving"/></div></div>:null}</form>
}
function PanField({label,name,value,editable,recheck}:{label:string;name:string;value:string;editable:boolean;recheck:boolean}){return <div className="min-w-0"><label className={labelClass}>{label} *</label><div className="flex gap-2"><input name={name} defaultValue={value} required maxLength={10} pattern="[A-Za-z]{5}[0-9]{4}[A-Za-z]" disabled={!editable} className={`${inputClass} flex-1 font-mono`}/>{recheck?<button type="submit" formAction={retryPospMispPanVerification} className="h-10 w-10 rounded-xl border bg-[#EEF2FF]">↻</button>:null}</div></div>}
function splitName(value:string|null){const parts=(value??"").trim().split(/\s+/).filter(Boolean);if(!parts.length)return{first:"",middle:"",last:""};if(parts.length===1)return{first:parts[0],middle:"",last:""};return{first:parts[0],middle:parts.slice(1,-1).join(" "),last:parts.at(-1)??""}}
function Header({number,title,subtitle}:{number:string;title:string;subtitle:string}){return <div className="flex items-start gap-3 border-b bg-[#F8FAFC] px-4 py-3"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[#071D49] text-[9px] font-bold text-white">{number}</span><div><h3 className="text-[12.5px] font-semibold">{title}</h3><p className="mt-0.5 text-[9.8px] text-[#64748B]">{subtitle}</p></div></div>}
function EditorSection({title,children}:{title:string;children:React.ReactNode}){return <section className="border-b border-[#E2E8F0] px-4 py-4"><h4 className="mb-3 text-[11px] font-semibold text-[#0F172A]">{title}</h4><div className="grid min-w-0 grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">{children}</div></section>}
function DocumentCard({id,label,current,missing,children}:{id:string;label:string;current?:string;missing:boolean;children:React.ReactNode}){return <div id={id} className={`rounded-xl border p-3 ${missing?"border-red-400 bg-red-50":current?"border-emerald-200 bg-emerald-50/35":"border-amber-200 bg-amber-50/30"}`}><div className="mb-3 flex justify-between"><span className="text-[10.5px] font-semibold">{label} *</span><span className="text-[8.5px]">{current?"Received":"Required"}</span></div>{children}</div>}
function Summary({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-[#F8FAFC] p-3"><p className="text-[8.5px] uppercase text-[#64748B]">{label}</p><p className="mt-1 text-[10.5px] font-semibold">{value}</p></div>}
function Field({label,name,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string;name:string}){return <div className="min-w-0"><label className={labelClass}>{label}{props.required?" *":""}</label><input name={name} className={inputClass} {...props}/></div>}
function Select({label,name,options,required,...props}:React.SelectHTMLAttributes<HTMLSelectElement>&{label:string;name:string;options:ReadonlyArray<{value:string;label:string}>;required?:boolean}){return <div className="min-w-0"><label className={labelClass}>{label}{required?" *":""}</label><select name={name} required={required} className={inputClass} {...props}><option value="">Select {label.toLowerCase()}</option>{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></div>}
function FileReplacement({name,current,required,disabled,onChange}:{name:string;current?:string;required:boolean;disabled:boolean;onChange:(selected:boolean)=>void}){return <div><p className="truncate text-[9.5px]">{current??"Not received"}</p>{!disabled?<input name={name} type="file" required={required} accept=".pdf,.jpg,.jpeg,.png" onChange={e=>onChange(Boolean(e.currentTarget.files?.length))} className="mt-2 block w-full text-[9.5px]"/>:null}</div>}
