"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { FormSubmitButton } from "@/components/form-submit-button";
import { IndianDateField } from "@/components/indian-date-field";
import { updateIntermediaryApplication } from "./intermediary-edit-actions";
import { retryPospMispPanVerification } from "./posp-misp-workflow-actions";

export type PospMispEditProfile={partner_type:"posp"|"misp";associate_employee_id:string|null;associate_profile_id:string|null;external_onboarding_id:string|null;document_received_at:string|null;pos_name:string|null;pos_first_name:string|null;pos_middle_name:string|null;pos_last_name:string|null;misp_name:string|null;applicant_phone:string|null;applicant_email:string|null;date_of_birth:string|null;aadhaar_last_four:string|null;aadhaar_number:string|null;pan_number:string|null;gst_number:string|null;address:string|null;city:string|null;state:string|null;postal_code:string|null;bank_id:string|null;bank_account_number:string|null;bank_ifsc_code:string|null;oem_name:string|null;dp_name:string|null;dp_first_name:string|null;dp_middle_name:string|null;dp_last_name:string|null;dp_phone:string|null;dp_email:string|null;dp_pan_number:string|null};
type WorkflowStage="pre_iib"|"iib_processing"|"training"|"completed";
type ViewStage="primary"|"documents"|"review";
type Props={applicationId:string;profile:PospMispEditProfile;workflowStage?:WorkflowStage;viewStage?:ViewStage;editable:boolean;salesManagers:Array<{value:string;label:string}>;banks:Array<{value:string;label:string}>;oems:Array<{value:string;label:string}>;documents:Array<{document_type:string;file_name:string}>};
const inputClass="h-10 w-full rounded-xl border border-[#CBD5E1] bg-white px-3 text-[11px] font-medium text-[#17203A] outline-none transition focus:border-[#635BFF] focus:ring-2 focus:ring-[#E7E5FF] disabled:bg-[#F8FAFC] disabled:text-[#475569]";
const labelClass="mb-1.5 block text-[9.5px] font-semibold uppercase tracking-[0.04em] text-[#526178]";
const namePattern="[A-Za-z ]+";
const marksheetOptions=[["education_10th_marksheet","10th Marksheet"],["education_12th_marksheet","12th Marksheet"],["education_graduation_marksheet","Graduation Marksheet"],["education_post_graduation_marksheet","Post Graduation Marksheet"]] as const;
const documentFields=[["aadhaar_front","Aadhaar front"],["aadhaar_back","Aadhaar back"],["pan_copy","PAN copy"],["cancelled_cheque","Cancelled cheque"],["photograph","Photograph"],["gst_copy","GST certificate"],["agreement_copy","Agreement copy"]] as const;

export function PospMispApplicationEditor({applicationId,profile,workflowStage="pre_iib",viewStage,editable,salesManagers,banks,oems,documents}:Props){
 const isMisp=profile.partner_type==="misp";const currentMarksheet=documents.find(document=>marksheetOptions.some(([value])=>value===document.document_type));const fallbackPos=useMemo(()=>splitName(profile.pos_name),[profile.pos_name]);const fallbackDp=useMemo(()=>splitName(profile.dp_name),[profile.dp_name]);
 const[posFirstName,setPosFirstName]=useState(profile.pos_first_name??fallbackPos.first);const[posMiddleName,setPosMiddleName]=useState(profile.pos_middle_name??fallbackPos.middle);const[posLastName,setPosLastName]=useState(profile.pos_last_name??fallbackPos.last);
 const[dpFirstName,setDpFirstName]=useState(profile.dp_first_name??fallbackDp.first);const[dpMiddleName,setDpMiddleName]=useState(profile.dp_middle_name??fallbackDp.middle);const[dpLastName,setDpLastName]=useState(profile.dp_last_name??fallbackDp.last);const[dpPhone,setDpPhone]=useState(profile.dp_phone??profile.applicant_phone??"");const[dpEmail,setDpEmail]=useState(profile.dp_email??profile.applicant_email??"");
 const activeView=viewStage??(workflowStage==="pre_iib"?"primary":workflowStage==="iib_processing"?"documents":"review");const showPrimary=activeView==="primary";const showDocuments=activeView==="documents";const showReview=activeView==="review";
 return <form action={editable?updateIntermediaryApplication:undefined} className="bg-[#F4F7FB]"><input type="hidden" name="application_id" value={applicationId}/><input type="hidden" name="edit_section" value={showDocuments?"documents":"primary"}/>{isMisp?<><input type="hidden" name="dp_name" value={[dpFirstName,dpMiddleName,dpLastName].filter(Boolean).join(" ")}/><input type="hidden" name="applicant_phone" value={dpPhone}/><input type="hidden" name="applicant_email" value={dpEmail}/></>:<input type="hidden" name="pos_name" value={[posFirstName,posMiddleName,posLastName].filter(Boolean).join(" ")}/>} 
  <div className="space-y-4 p-4 sm:p-5"><StageBar applicationId={applicationId} workflowStage={workflowStage} viewStage={activeView}/>
   {showPrimary?<section className="overflow-hidden rounded-2xl border border-[#DCE5EF] bg-white shadow-sm"><Header number="1" title="Primary information & PAN check" subtitle="Update the intermediary details or recheck the PAN."/><div className="grid gap-4 p-4 md:grid-cols-2 xl:grid-cols-4">
    <Select label="RM Name" name="associate_employee_id" defaultValue={profile.associate_employee_id??profile.associate_profile_id??""} options={salesManagers} required disabled={!editable}/><Field label={isMisp?"MISP ID":"POSP ID"} name="external_onboarding_id" defaultValue={profile.external_onboarding_id??""} required disabled={!editable}/>{isMisp?<Field label="MISP Name" name="misp_name" defaultValue={profile.misp_name??""} required disabled={!editable}/>:null}<PanField label={isMisp?"MISP PAN":"PAN Number"} name="pan_number" value={profile.pan_number??""} editable={editable} recheck={!isMisp}/><IndianDateField label="Document Received Date" name="document_received_at" defaultValue={profile.document_received_at} disabled={!editable}/>{isMisp?<Select label="OEM Name" name="oem_name" defaultValue={profile.oem_name??""} options={oems} required disabled={!editable}/>:null}<Field label="GST Number" name="gst_number" defaultValue={profile.gst_number??""} maxLength={15} disabled={!editable}/><div className="md:col-span-2"><Field label="Address" name="address" defaultValue={profile.address??""} required disabled={!editable}/></div><Field label="City" name="city" defaultValue={profile.city??""} required disabled={!editable}/><Field label="State" name="state" defaultValue={profile.state??""} required disabled={!editable}/><Field label="PIN Code" name="postal_code" defaultValue={profile.postal_code??""} required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} disabled={!editable}/>
    {!isMisp?<><Field label="POSP First Name" name="pos_first_name" value={posFirstName} onChange={event=>setPosFirstName(event.target.value)} required pattern={namePattern} disabled={!editable}/><Field label="POSP Middle Name" name="pos_middle_name" value={posMiddleName} onChange={event=>setPosMiddleName(event.target.value)} pattern={namePattern} disabled={!editable}/><Field label="POSP Last Name" name="pos_last_name" value={posLastName} onChange={event=>setPosLastName(event.target.value)} required pattern={namePattern} disabled={!editable}/><Field label="Mobile Number" name="applicant_phone" defaultValue={profile.applicant_phone??""} required inputMode="tel" disabled={!editable}/><Field label="Email" name="applicant_email" defaultValue={profile.applicant_email??""} type="email" required disabled={!editable}/><IndianDateField label="Date of Birth" name="date_of_birth" defaultValue={profile.date_of_birth} required disabled={!editable}/><Field label="Aadhaar Number" name="aadhaar_number" defaultValue={profile.aadhaar_number??""} placeholder={profile.aadhaar_last_four?`Stored ending ${profile.aadhaar_last_four}`:"12-digit Aadhaar"} required maxLength={12} pattern="[0-9]{12}" disabled={!editable}/></>:null}
    {isMisp?<><Field label="DP First Name" name="dp_first_name" value={dpFirstName} onChange={event=>setDpFirstName(event.target.value)} required pattern={namePattern} disabled={!editable}/><Field label="DP Middle Name" name="dp_middle_name" value={dpMiddleName} onChange={event=>setDpMiddleName(event.target.value)} pattern={namePattern} disabled={!editable}/><Field label="DP Last Name" name="dp_last_name" value={dpLastName} onChange={event=>setDpLastName(event.target.value)} required pattern={namePattern} disabled={!editable}/><Field label="DP Contact" name="dp_phone" value={dpPhone} onChange={event=>setDpPhone(event.target.value)} required inputMode="tel" disabled={!editable}/><Field label="DP Email" name="dp_email" value={dpEmail} onChange={event=>setDpEmail(event.target.value)} required type="email" disabled={!editable}/><PanField label="DP PAN No" name="dp_pan_number" value={profile.dp_pan_number??""} editable={editable} recheck/><IndianDateField label="DP Date of Birth" name="date_of_birth" defaultValue={profile.date_of_birth} required disabled={!editable}/><Field label="DP Aadhaar Number" name="aadhaar_number" defaultValue={profile.aadhaar_number??""} placeholder={profile.aadhaar_last_four?`Stored ending ${profile.aadhaar_last_four}`:"12-digit Aadhaar"} required maxLength={12} minLength={12} pattern="[0-9]{12}" disabled={!editable}/></>:null}
    <Select label="Bank Name" name="bank_id" defaultValue={profile.bank_id??""} options={banks} required disabled={!editable}/><Field label="Account Number" name="bank_account_number" defaultValue={profile.bank_account_number??""} required inputMode="numeric" pattern="[0-9]{6,20}" disabled={!editable}/><Field label="IFSC Code" name="bank_ifsc_code" defaultValue={profile.bank_ifsc_code??""} required maxLength={11} minLength={11} pattern="[A-Za-z]{4}0[A-Za-z0-9]{6}" disabled={!editable}/>
   </div></section>:null}
   {showDocuments?<section className="overflow-hidden rounded-2xl border border-[#DCE5EF] bg-white shadow-sm"><Header number="2" title="Documents" subtitle="Upload or replace the intermediary documents."/><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3"><DocumentCard label="Marksheet" current={currentMarksheet?.file_name}><Select label="Marksheet Type" name="education_document_type" defaultValue={currentMarksheet?.document_type??""} options={marksheetOptions.map(([value,label])=>({value,label}))} disabled={!editable}/><FileReplacement name="education_marksheet" current={currentMarksheet?.file_name} disabled={!editable}/></DocumentCard>{documentFields.map(([documentType,label])=>{const current=documents.find(document=>document.document_type===documentType);return <DocumentCard key={documentType} label={label} current={current?.file_name}><FileReplacement name={documentType} current={current?.file_name} disabled={!editable}/></DocumentCard>})}</div></section>:null}
   {showReview?<section className="overflow-hidden rounded-2xl border border-[#DCE5EF] bg-white shadow-sm"><Header number="3" title="Final review" subtitle="Review the saved intermediary details and attached documents before activation."/><div className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-3"><Summary label="Application type" value={profile.partner_type.toUpperCase()}/><Summary label={isMisp?"MISP ID":"POSP ID"} value={profile.external_onboarding_id??"-"}/><Summary label="Applicant" value={(isMisp?profile.misp_name:profile.pos_name)??"-"}/><Summary label="Email" value={(isMisp?profile.dp_email:profile.applicant_email)??"-"}/><Summary label="Documents" value={`${documents.length} attached`}/><Summary label="PAN used for IIB" value={(isMisp?profile.dp_pan_number:profile.pan_number)??"-"}/></div></section>:null}
  </div>{editable&&(showPrimary||showDocuments)?<div className="sticky bottom-0 z-10 flex items-center justify-between gap-3 border-t border-[#DCE5EF] bg-white/95 px-5 py-3 backdrop-blur">{showDocuments?<Link href={`/intermediaries/applications/${applicationId}?stage=primary`} className="rounded-xl border border-[#CBD5E1] bg-white px-4 py-2.5 text-[10.5px] font-semibold text-[#334155]">Back to Primary</Link>:<span/>}<FormSubmitButton label={showPrimary?(workflowStage==="pre_iib"?"Save primary details":"Save & return to Documents"):"Save documents"} pendingLabel="Saving"/></div>:null}</form>;
}
function StageBar({applicationId,workflowStage,viewStage}:{applicationId:string;workflowStage:WorkflowStage;viewStage:ViewStage}){const unlocked=workflowStage==="pre_iib"?1:workflowStage==="iib_processing"?2:3;const stages:Array<{number:number,label:string,value:ViewStage}>=[{number:1,label:"Primary & IIB",value:"primary"},{number:2,label:"Documents",value:"documents"},{number:3,label:"Review",value:"review"}];return <div className="grid grid-cols-3 gap-2 rounded-2xl border border-[#DCE5EF] bg-white p-2 shadow-sm">{stages.map(stage=>{const available=stage.number<=unlocked;const active=stage.value===viewStage;const className=`rounded-xl border px-3 py-2.5 text-center text-[9.5px] font-semibold ${active?"border-[#C7D2FE] bg-[#EEF2FF] text-[#4338CA]":stage.number<unlocked?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-[#E2E8F0] bg-[#F8FAFC] text-[#94A3B8]"}`;return available?<Link key={stage.value} href={`/intermediaries/applications/${applicationId}?stage=${stage.value}`} className={className}>{stage.number<unlocked?"✓ ":""}{stage.number} {stage.label}</Link>:<div key={stage.value} className={className}>{stage.number} {stage.label}</div>})}</div>}
function PanField({label,name,value,editable,recheck}:{label:string;name:string;value:string;editable:boolean;recheck:boolean}){return <div><label className={labelClass}>{label} *</label><div className="flex items-center gap-2"><input name={name} defaultValue={value} required maxLength={10} minLength={10} pattern="[A-Za-z]{5}[0-9]{4}[A-Za-z]" disabled={!editable} className={inputClass}/>{recheck?<button type="submit" formAction={retryPospMispPanVerification} title="Recheck PAN in IIB" aria-label="Recheck PAN in IIB" className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-[#C7D2FE] bg-[#EEF2FF] text-[#4338CA]"><svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.9"><path d="M20 11a8 8 0 1 0-2.34 5.66"/><path d="M20 4v7h-7"/><path d="m9.5 12 1.7 1.7 3.6-4"/></svg></button>:null}</div>{recheck?<p className="mt-1 text-[8.5px] text-[#64748B]">Rechecks this PAN and resets the current IIB result.</p>:null}</div>}
function splitName(value:string|null){const parts=(value??"").trim().split(/\s+/).filter(Boolean);if(!parts.length)return{first:"",middle:"",last:""};if(parts.length===1)return{first:parts[0],middle:"",last:""};return{first:parts[0],middle:parts.slice(1,-1).join(" "),last:parts.at(-1)??""}}
function Header({number,title,subtitle}:{number:string;title:string;subtitle:string}){return <div className="flex items-start gap-3 border-b border-[#E2E8F0] bg-[#F8FAFC] px-4 py-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-[#071D49] text-[9px] font-bold text-white">{number}</span><div><h3 className="text-[12.5px] font-semibold text-[#0F172A]">{title}</h3><p className="mt-0.5 text-[9.8px] text-[#64748B]">{subtitle}</p></div></div>}
function DocumentCard({label,current,children}:{label:string;current?:string;children:React.ReactNode}){return <div className={`rounded-xl border p-3 ${current?"border-emerald-200 bg-emerald-50/35":"border-amber-200 bg-amber-50/30"}`}><div className="mb-3 flex items-center justify-between"><span className="text-[10.5px] font-semibold">{label}</span><span className={`rounded-full px-2 py-0.5 text-[8.5px] font-semibold ${current?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}>{current?"Received":"Pending"}</span></div>{children}</div>}
function Summary({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-[#E2E8F0] bg-[#F8FAFC] p-3"><p className="text-[8.5px] font-semibold uppercase tracking-[.05em] text-[#64748B]">{label}</p><p className="mt-1 text-[10.5px] font-semibold text-[#0F172A]">{value}</p></div>}
function Field({label,name,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string;name:string}){return <div><label className={labelClass}>{label}{props.required?" *":""}</label><input name={name} className={inputClass} {...props}/></div>}
function Select({label,name,options,required,...props}:React.SelectHTMLAttributes<HTMLSelectElement>&{label:string;name:string;options:ReadonlyArray<{value:string;label:string}>;required?:boolean}){return <div><label className={labelClass}>{label}{required?" *":""}</label><select name={name} required={required} className={inputClass} {...props}><option value="">Select {label.toLowerCase()}</option>{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></div>}
function FileReplacement({name,current,disabled}:{name:string;current?:string;disabled:boolean}){return <div><p className={`truncate text-[9.5px] ${current?"text-emerald-700":"text-[#64748B]"}`}>{current??"Not received"}</p>{!disabled?<input name={name} type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" className="mt-2 block w-full text-[9.5px]"/>:null}</div>}
