import { FormSubmitButton } from "@/components/form-submit-button";
import { updateMobileCorporateApplicationDraft } from "./corporate-actions";
import { updateMobileDealershipApplicationDraft } from "./dealership-actions";

export type ReviewContact = { contact_role:string; full_name:string; phone:string; email:string|null };
type CommonProps = { applicationId:string; draft:Record<string,unknown>; canReview:boolean; status:string };

const corporateContactRoles=[["corporate_creator","Corporate Creator"],["ceo_head","CEO / Head"],["admin_head","Admin Head"],["dedicated_spoc","Dedicated SPOC"]] as const;
const dealershipContactRoles=[["sales_head","Sales Head"],["bodyshop_head","Bodyshop Head"],["insurance_head","Insurance Head"],["insurance_spoc","Insurance SPOC"]] as const;
const fleetOptions=[["less_than_5","Less than 5"],["5_to_20","5 to 20"],["20_to_50","20 to 50"],["more_than_50","More than 50"]] as const;
const dealershipTypeOptions=[["posp","POSP"],["misp","MISP"]] as const;
const salesOptions=[["less_than_500","Less than 500"],["500_to_1000","500 to 1000"],["more_than_1000","More than 1000"]] as const;

export function CorporateReviewWorkspace({applicationId,draft,canReview,status,contacts,applicantPhone,applicantEmail}:CommonProps&{contacts:ReviewContact[];applicantPhone:string|null;applicantEmail:string|null}){
  const byRole=new Map(contacts.map(contact=>[contact.contact_role,contact]));
  return <form action={canReview?updateMobileCorporateApplicationDraft:undefined} className="space-y-4 bg-[#F4F7FB] p-4 sm:p-5"><input type="hidden" name="application_id" value={applicationId}/>
    <FileSection number="01" title="Company particulars" subtitle="Legal identity, tax registration and fleet profile."><Field name="company_name" label="Company name" defaultValue={text(draft.company_name)} required disabled={!canReview}/><Field name="company_pan" label="Company PAN" defaultValue={text(draft.company_pan)} required disabled={!canReview}/><Field name="gst_number" label="GSTIN" defaultValue={text(draft.gst_number)} disabled={!canReview}/><SelectField name="fleet_size_band" label="Fleet size" defaultValue={text(draft.fleet_size_band)} options={fleetOptions} required disabled={!canReview}/></FileSection>
    <FileSection number="02" title="Registered address" subtitle="Verified location recorded against the Corporate account."><Field name="address_street" label="Street" defaultValue={text(draft.address_street)} required disabled={!canReview}/><Field name="address_locality" label="Locality" defaultValue={text(draft.address_locality)} disabled={!canReview}/><Field name="city" label="City" defaultValue={text(draft.city)} required disabled={!canReview}/><Field name="state" label="State" defaultValue={text(draft.state)} required disabled={!canReview}/><Field name="postal_code" label="PIN code" defaultValue={text(draft.postal_code)} required disabled={!canReview}/><Field name="india_location_id" label="Location ID" defaultValue={text(draft.india_location_id)} required disabled={!canReview}/></FileSection>
    <section className="overflow-hidden rounded-2xl border border-[#DCE5EF] bg-white shadow-sm"><FileHeader number="03" title="Corporate login contacts" subtitle="Separate role-based access for the Corporate account."/><div className="grid gap-3 p-4 md:grid-cols-2">{corporateContactRoles.map(([role,label])=>{const contact=byRole.get(role);return <div key={role} className="rounded-xl border border-[#E2E8F0] bg-[#FBFDFF] p-4"><p className="text-[11px] font-semibold text-[#071D49]">{label}</p><div className="mt-3 space-y-3"><Field name={`${role}_name`} label="Full name" defaultValue={contact?.full_name??""} required disabled={!canReview}/><Field name={`${role}_phone`} label="Mobile number" defaultValue={contact?.phone??(role==="corporate_creator"?applicantPhone??"":"")} required disabled={!canReview}/><Field name={`${role}_email`} label="Email" defaultValue={contact?.email??(role==="corporate_creator"?applicantEmail??"":"")} disabled={!canReview}/></div></div>})}</div></section>
    <SaveBar canReview={canReview} status={status}/>
  </form>;
}

export function DealershipReviewWorkspace({applicationId,draft,canReview,status}:CommonProps){
  return <form action={canReview?updateMobileDealershipApplicationDraft:undefined} className="space-y-4 bg-[#F4F7FB] p-4 sm:p-5"><input type="hidden" name="application_id" value={applicationId}/>
    <FileSection number="01" title="Dealership particulars" subtitle="Dealership identity, ownership and business profile."><SelectField name="dealership_type" label="Dealership type" defaultValue={text(draft.dealership_type)} options={dealershipTypeOptions} required disabled={!canReview}/><Field name="dealership_name" label="Dealership name" defaultValue={text(draft.dealership_name)} required disabled={!canReview}/><Field name="owner_name" label="Owner name" defaultValue={text(draft.owner_name)} required disabled={!canReview}/><Field name="phone" label="Owner mobile number" defaultValue={text(draft.phone)} required disabled={!canReview}/><Field name="email" label="Owner email" defaultValue={text(draft.email)} disabled={!canReview}/><Field name="oem_name" label="Dealership OEM" defaultValue={text(draft.oem_name)} required disabled={!canReview}/><SelectField name="yearly_sales_band" label="Yearly sales" defaultValue={text(draft.yearly_sales_band)} options={salesOptions} required disabled={!canReview}/></FileSection>
    <FileSection number="02" title="Registered address" subtitle="Verified business address and location mapping."><Field name="address_street" label="Street" defaultValue={text(draft.address_street)} required disabled={!canReview}/><Field name="address_locality" label="Locality" defaultValue={text(draft.address_locality)} disabled={!canReview}/><Field name="city" label="City" defaultValue={text(draft.city)} required disabled={!canReview}/><Field name="state" label="State" defaultValue={text(draft.state)} required disabled={!canReview}/><Field name="postal_code" label="PIN code" defaultValue={text(draft.postal_code)} required disabled={!canReview}/><Field name="india_location_id" label="Location ID" defaultValue={text(draft.india_location_id)} required disabled={!canReview}/></FileSection>
    <FileSection number="03" title="GST and representative" subtitle="Tax status and authorized POSP / DP representative."><label className="flex h-10 items-center gap-2 self-end text-[10.5px] font-semibold text-[#17203A]"><input type="checkbox" name="is_gst_registered" value="true" defaultChecked={draft.is_gst_registered===true} disabled={!canReview} className="h-4 w-4"/>GST registered</label><Field name="gst_number" label="GSTIN" defaultValue={text(draft.gst_number)} disabled={!canReview}/><Field name="representative_name" label="Representative name" defaultValue={text(draft.representative_name)} required disabled={!canReview}/><Field name="representative_mobile" label="Representative mobile" defaultValue={text(draft.representative_mobile)} required disabled={!canReview}/><Field name="representative_email" label="Representative email" defaultValue={text(draft.representative_email)} disabled={!canReview}/><Field name="representative_pan" label="Representative PAN" defaultValue={text(draft.representative_pan)} required disabled={!canReview}/><Field name="representative_aadhaar" label="Replace Aadhaar number" defaultValue="" disabled={!canReview}/></FileSection>
    <section className="overflow-hidden rounded-2xl border border-[#DCE5EF] bg-white shadow-sm"><FileHeader number="04" title="Additional Dealership contacts" subtitle="Optional operational contacts retained with the Dealership file."/><div className="grid gap-3 p-4 md:grid-cols-2">{dealershipContactRoles.map(([role,label])=><div key={role} className="rounded-xl border border-[#E2E8F0] bg-[#FBFDFF] p-4"><p className="text-[11px] font-semibold text-[#071D49]">{label}</p><div className="mt-3 space-y-3"><Field name={`${role}_name`} label="Full name" defaultValue={text(draft[`${role}_name`])} disabled={!canReview}/><Field name={`${role}_mobile`} label="Mobile number" defaultValue={text(draft[`${role}_mobile`])} disabled={!canReview}/><Field name={`${role}_email`} label="Email" defaultValue={text(draft[`${role}_email`])} disabled={!canReview}/></div></div>)}</div></section>
    <SaveBar canReview={canReview} status={status}/>
  </form>;
}

export function SummaryReviewWorkspace({fields}:{fields:Array<[string,unknown]>}){return <div className="grid gap-px bg-[#E8EEF5] sm:grid-cols-2">{fields.map(([label,value])=><div key={label} className="bg-white px-4 py-3"><p className="text-[9px] font-semibold uppercase tracking-[.06em] text-[#64748B]">{label}</p><p className="mt-1 text-[11.5px] font-medium text-[#0F172A]">{display(value)}</p></div>)}</div>}

function FileSection({number,title,subtitle,children}:{number:string;title:string;subtitle:string;children:React.ReactNode}){return <section className="overflow-hidden rounded-2xl border border-[#DCE5EF] bg-white shadow-sm"><FileHeader number={number} title={title} subtitle={subtitle}/><div className="grid gap-4 p-4 md:grid-cols-2 xl:grid-cols-4">{children}</div></section>}
function FileHeader({number,title,subtitle}:{number:string;title:string;subtitle:string}){return <div className="flex items-start gap-3 border-b border-[#E2E8F0] bg-[#F8FAFC] px-4 py-3"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[#071D49] text-[9px] font-bold text-white">{number}</span><div><h3 className="text-[12.5px] font-semibold text-[#0F172A]">{title}</h3><p className="mt-0.5 text-[9.5px] text-[#64748B]">{subtitle}</p></div></div>}
function SaveBar({canReview,status}:{canReview:boolean;status:string}){return canReview?<div className="sticky bottom-0 z-10 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#DCE5EF] bg-white/95 px-4 py-3 backdrop-blur"><p className="text-[10px] text-[#64748B]">Save verified corrections before approval.</p><FormSubmitButton label="Save verified corrections" pendingLabel="Saving verified corrections"/></div>:<div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-[10.5px] font-medium text-emerald-800">This official file is {status.replaceAll("_"," ")} and locked for review edits.</div>}
function Field({name,label,defaultValue,required,disabled}:{name:string;label:string;defaultValue:string;required?:boolean;disabled?:boolean}){return <label className="block text-[9.5px] font-semibold uppercase tracking-[0.04em] text-[#526178]">{label}{required?" *":""}<input name={name} defaultValue={defaultValue} required={required} disabled={disabled} className="mt-1.5 h-10 w-full rounded-lg border border-[#CBD5E1] bg-white px-3 text-[11px] font-medium normal-case tracking-normal text-[#0F172A] outline-none focus:border-[#1D4ED8] focus:ring-2 focus:ring-blue-100 disabled:bg-[#F8FAFC]"/></label>}
function SelectField({name,label,defaultValue,options,required,disabled}:{name:string;label:string;defaultValue:string;options:readonly(readonly[string,string])[];required?:boolean;disabled?:boolean}){return <label className="block text-[9.5px] font-semibold uppercase tracking-[0.04em] text-[#526178]">{label}{required?" *":""}<select name={name} defaultValue={defaultValue} required={required} disabled={disabled} className="mt-1.5 h-10 w-full rounded-lg border border-[#CBD5E1] bg-white px-3 text-[11px] font-medium normal-case tracking-normal text-[#0F172A] outline-none focus:border-[#1D4ED8] focus:ring-2 focus:ring-blue-100 disabled:bg-[#F8FAFC]"><option value="">Select {label.toLowerCase()}</option>{options.map(([value,optionLabel])=><option key={value} value={value}>{optionLabel}</option>)}</select></label>}
function text(value:unknown){return typeof value==="string"?value:""}
function display(value:unknown){return typeof value==="string"&&value.trim()?value:typeof value==="number"?String(value):"-"}
