from pathlib import Path

p = Path('apps/web-portal/app/intermediaries/intermediary-register.tsx')
s = p.read_text()
section = '        <section className="overflow-hidden rounded-2xl border border-[#DCE5EF] bg-white shadow-sm">\n'
start = s.index(section)
load = s.index('          {loadError ?', start)
header = '''        <section className="overflow-hidden rounded-2xl border border-[#DCE5EF] bg-white shadow-sm">\n          <div className="grid items-center gap-5 border-b border-[#E7ECF3] bg-[#FAFBFD] px-5 py-3.5 lg:grid-cols-[auto_minmax(280px,460px)_1fr]">\n            <h2 className="whitespace-nowrap text-[12.5px] font-semibold text-[#17203A]">{selectedType === "partner" ? "Partner Register" : "Intermediary Register"}</h2>\n            <form method="get" action={searchAction} className="relative min-w-0 max-w-[460px]">\n              {accountStatus ? <input type="hidden" name="account_status" value={accountStatus} /> : null}\n              <Search className="pointer-events-none absolute left-3.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-[#94A3B8]" />\n              <input name="q" defaultValue={search} placeholder="Search name, mobile, email or ID" className="h-9 w-full rounded-lg border border-[#D8E1EC] bg-white pl-9 pr-3 text-[10.5px] text-[#17203A] outline-none placeholder:text-[#94A3B8] focus:border-[#315FEA] focus:ring-2 focus:ring-[#E6ECFF]" />\n            </form>\n            <div className="flex items-center justify-end gap-1.5 whitespace-nowrap text-[9.5px] font-semibold">\n              <Link href={registerFilterHref(searchAction, search, "")} className={`rounded-lg px-2.5 py-1.5 transition ${!accountStatus ? "bg-[#0F2A55] text-white" : "text-[#526178] hover:bg-white hover:text-[#0F2A55]"}`}>All <span className="ml-1">{partnerCountRows.length}</span></Link>\n              <Link href={registerFilterHref(searchAction, search, "active")} className={`rounded-lg px-2.5 py-1.5 transition ${accountStatus === "active" ? "bg-emerald-100 text-emerald-800" : "text-[#526178] hover:bg-emerald-50 hover:text-emerald-700"}`}>Active <span className="ml-1">{partnerCounts.active}</span></Link>\n              <Link href={registerFilterHref(searchAction, search, "onboarding")} className={`rounded-lg px-2.5 py-1.5 transition ${accountStatus === "onboarding" ? "bg-amber-100 text-amber-800" : "text-[#526178] hover:bg-amber-50 hover:text-amber-700"}`}>Onboarding <span className="ml-1">{partnerCounts.onboarding}</span></Link>\n            </div>\n          </div>\n'''
s = s[:start] + header + s[load:]
p.write_text(s)
