from pathlib import Path

# POSP / MISP register
path = Path('apps/web-portal/app/intermediaries/structured-account-register.tsx')
text = path.read_text()

old_top = '''        <div className="flex flex-col gap-2 rounded-2xl border border-[#DCE5EF] bg-white p-3 shadow-sm sm:flex-row sm:items-center">\n          <form method="get" className="relative min-w-0 flex-1">\n            <Search className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-[#94A3B8]" />\n            <input name="q" defaultValue={search} placeholder={`Search ${title} name, ID, Partner ID, mobile or email`} className="h-10 w-full rounded-xl border border-[#D8E1EC] bg-white pl-10 pr-4 text-[11px] text-[#17203A] outline-none placeholder:text-[#94A3B8] focus:border-[#315FEA] focus:ring-2 focus:ring-[#E6ECFF]" />\n          </form>\n          <Link href={onboardHref} className="inline-flex h-10 shrink-0 items-center justify-center rounded-xl bg-[#0F2A55] px-4 text-[10.5px] font-semibold text-white transition hover:bg-[#173A70]">Onboard {title}</Link>\n        </div>\n\n'''
if old_top not in text:
    raise SystemExit('POSP/MISP top toolbar not found')
text = text.replace(old_top, '', 1)

old_header = '''          <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#E7ECF3] bg-[#FAFBFD] px-4 py-3">\n            <h2 className="text-[12px] font-semibold text-[#17203A]">{title} Register</h2>\n            <div className="flex items-center gap-3 text-[9.5px] font-medium text-[#64748B]">\n              <span>All <strong className="ml-1 text-[#0F2A55]">{rows.length}</strong></span>\n              <span>Active <strong className="ml-1 text-emerald-700">{counts.active}</strong></span>\n              <span>Onboarding <strong className="ml-1 text-amber-700">{counts.onboarding}</strong></span>\n            </div>\n          </div>'''
new_header = '''          <div className="grid items-center gap-3 border-b border-[#E7ECF3] bg-[#FAFBFD] px-4 py-2.5 lg:grid-cols-[auto_minmax(260px,1fr)_auto_auto]">\n            <h2 className="whitespace-nowrap text-[12px] font-semibold text-[#17203A]">{title} Register</h2>\n            <form method="get" className="relative min-w-0">\n              <Search className="pointer-events-none absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-[#94A3B8]" />\n              <input name="q" defaultValue={search} placeholder={`Search ${title} name, ID, Partner ID, mobile or email`} className="h-8 w-full rounded-lg border border-[#D8E1EC] bg-white pl-9 pr-3 text-[10px] text-[#17203A] outline-none placeholder:text-[#94A3B8] focus:border-[#315FEA] focus:ring-2 focus:ring-[#E6ECFF]" />\n            </form>\n            <Link href={onboardHref} className="inline-flex h-8 shrink-0 items-center justify-center rounded-lg bg-[#0F2A55] px-3.5 text-[9.5px] font-semibold text-white transition hover:bg-[#173A70]">Onboard {title}</Link>\n            <div className="flex items-center justify-end gap-3 whitespace-nowrap text-[9.5px] font-medium text-[#64748B]">\n              <span>All <strong className="ml-1 text-[#0F2A55]">{rows.length}</strong></span>\n              <span>Active <strong className="ml-1 text-emerald-700">{counts.active}</strong></span>\n              <span>Onboarding <strong className="ml-1 text-amber-700">{counts.onboarding}</strong></span>\n            </div>\n          </div>'''
if old_header not in text:
    raise SystemExit('POSP/MISP table header not found')
text = text.replace(old_header, new_header, 1)

text = text.replace('''              <table className="w-full min-w-[840px] table-fixed text-left text-[10.5px]">''', '''              <table className="w-full min-w-[940px] table-fixed text-left text-[10.5px]">''', 1)
text = text.replace('''                  <th className="px-5 py-3.5">{title} account</th>''', '''                  <th className="px-5 py-3.5">{title} Name</th>\n                  <th className="px-3 py-3.5">Mobile Number</th>''', 1)
text = text.replace('''                    <td className="truncate px-5 py-3.5 font-semibold text-[#0F2A55]" title={row.display_name}>{row.display_name}</td>''', '''                    <td className="truncate px-5 py-3.5 font-semibold text-[#0F2A55]" title={row.display_name}>{row.display_name}</td>\n                    <td className="truncate px-3 py-3.5 font-medium text-[#17203A]" title={mobile10(row.mobile)}>{mobile10(row.mobile)}</td>''', 1)
text = text.replace('''function textValue(value: unknown) { return typeof value === "string" && value.trim() ? value.trim() : null; }''', '''function textValue(value: unknown) { return typeof value === "string" && value.trim() ? value.trim() : null; }\nfunction mobile10(value: string | null | undefined) { const digits = value?.replace(/\\D/g, "") ?? ""; return digits.length >= 10 ? digits.slice(-10) : digits || "—"; }''', 1)
path.write_text(text)

# Partner register
path = Path('apps/web-portal/app/intermediaries/intermediary-register.tsx')
text = path.read_text()

old_toolbar = '''        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">\n          <form method="get" action={searchAction} className="relative min-w-0 flex-1">\n            <Search className="pointer-events-none absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-[#94A3B8]" />\n            <input name="q" defaultValue={search} placeholder="Search name, mobile, email or ID" className="h-10 w-full rounded-xl border border-[#D8E1EC] bg-white pl-10 pr-4 text-[11px] text-[#17203A] outline-none placeholder:text-[#94A3B8] focus:border-[#315FEA] focus:ring-2 focus:ring-[#E6ECFF]" />\n          </form>\n          {canCreate && onboardingAction ? <Link href={onboardingAction.href} className={`${secondaryActionClassName} shrink-0 bg-white/75 backdrop-blur`}>{onboardingAction.label}</Link> : null}\n        </div>\n\n'''
if old_toolbar not in text:
    raise SystemExit('Partner top toolbar not found')
text = text.replace(old_toolbar, '', 1)

insert_after = '''  const activeMetric = typeFilter;\n'''
partner_counts = '''  const partnerCounts = selectedType === "partner"\n    ? rows.reduce((acc, row) => {\n        const app = applicationMap.get(row.application_id as string);\n        if (app?.partner_status === "active_partner") acc.active += 1;\n        else acc.onboarding += 1;\n        return acc;\n      }, { active: 0, onboarding: 0 })\n    : { active: 0, onboarding: 0 };\n'''
if insert_after not in text:
    raise SystemExit('Partner count insertion point missing')
text = text.replace(insert_after, insert_after + partner_counts, 1)

old_section_header = '''          <div className="flex items-center justify-between border-b border-[#E7ECF3] bg-[#FAFBFD] px-4 py-3"><h2 className="text-[12px] font-semibold text-[#17203A]">{selectedType === "partner" ? "Partner Register" : "Intermediary Register"}</h2><span className="text-[9.5px] font-medium text-[#64748B]">{rows.length} records</span></div>'''
new_section_header = '''          <div className="grid items-center gap-3 border-b border-[#E7ECF3] bg-[#FAFBFD] px-4 py-2.5 lg:grid-cols-[auto_minmax(260px,1fr)_auto_auto]">\n            <h2 className="whitespace-nowrap text-[12px] font-semibold text-[#17203A]">{selectedType === "partner" ? "Partner Register" : "Intermediary Register"}</h2>\n            <form method="get" action={searchAction} className="relative min-w-0">\n              <Search className="pointer-events-none absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-[#94A3B8]" />\n              <input name="q" defaultValue={search} placeholder="Search name, mobile, email or ID" className="h-8 w-full rounded-lg border border-[#D8E1EC] bg-white pl-9 pr-3 text-[10px] text-[#17203A] outline-none placeholder:text-[#94A3B8] focus:border-[#315FEA] focus:ring-2 focus:ring-[#E6ECFF]" />\n            </form>\n            {canCreate && onboardingAction ? <Link href={onboardingAction.href} className="inline-flex h-8 shrink-0 items-center justify-center rounded-lg bg-[#0F2A55] px-3.5 text-[9.5px] font-semibold text-white transition hover:bg-[#173A70]">{onboardingAction.label}</Link> : <span />}\n            <div className="flex items-center justify-end gap-3 whitespace-nowrap text-[9.5px] font-medium text-[#64748B]">\n              <span>All <strong className="ml-1 text-[#0F2A55]">{rows.length}</strong></span>\n              {selectedType === "partner" ? <>\n                <span>Active <strong className="ml-1 text-emerald-700">{partnerCounts.active}</strong></span>\n                <span>Onboarding <strong className="ml-1 text-amber-700">{partnerCounts.onboarding}</strong></span>\n              </> : null}\n            </div>\n          </div>'''
if old_section_header not in text:
    raise SystemExit('Partner section header not found')
text = text.replace(old_section_header, new_section_header, 1)

text = text.replace('''<table className="w-full min-w-[1040px] table-fixed text-left text-[10.5px]"><thead className="border-b text-[8.5px] uppercase text-[#64748B]"><tr><th className="px-4 py-3">Partner</th><th className="px-3 py-3">Partner ID</th>''', '''<table className="w-full min-w-[1120px] table-fixed text-left text-[10.5px]"><thead className="border-b text-[8.5px] uppercase text-[#64748B]"><tr><th className="px-4 py-3">Partner Name</th><th className="px-3 py-3">Mobile Number</th><th className="px-3 py-3">Partner ID</th>''', 1)
text = text.replace('''<th className="px-3 py-3">Status</th><th className="px-3 py-3">Action</th>''', '''<th className="px-3 py-3">Status</th><th className="px-3 py-3 text-right">Action</th>''', 1)
text = text.replace('''</FreshAccountReviewLink></td><td className="truncate px-3 py-3 font-semibold text-[#0F2A55]" title={displayIdentity(row, app, "partner")}>''', '''</FreshAccountReviewLink></td><td className="truncate px-3 py-3 font-medium text-[#17203A]" title={mobile10(row.mobile)}>{mobile10(row.mobile)}</td><td className="truncate px-3 py-3 font-semibold text-[#0F2A55]" title={displayIdentity(row, app, "partner")}>''', 1)
text = text.replace(', secondaryActionClassName', '')
text = text.replace('''function textValue(value: unknown)''', '''function mobile10(value: string | null | undefined) { const digits = value?.replace(/\\D/g, "") ?? ""; return digits.length >= 10 ? digits.slice(-10) : digits || "—"; }\nfunction textValue(value: unknown)''', 1)
path.write_text(text)
