"use client";

import Link from "next/link";
import { useState, useTransition } from "react";
import { closeReconciliationCycle, markReconciliationCycleReconciled, reopenReconciliationCycle, reviewReconciliationLine } from "./actions";

type Cycle = { id:string; status:string; period_start:string; period_end:string; statement_reference:string|null; row_count:number; matched_row_count:number; variance_row_count:number; projected_total:number|string; actual_total:number|string; adjustment_total:number|string; tds_total:number|string; variance_total:number|string; submitted_at:string; insurance_companies?: {name?:string|null}|Array<{name?:string|null}>|null; creator?: {full_name?:string|null}|Array<{full_name?:string|null}>|null };
type Line = { id:string; source_row_no:number; input_policy_no:string; match_status:string; projected_payin_snapshot:number|string|null; actual_recognized_payin:number|string; tds_amount:number|string; adjustment_amount:number|string; variance_amount:number|string|null; transaction_type:string; variance_reason:string|null; insurer_reference:string|null; remarks:string|null; review_status:string; policies?: { policy_no?:string|null; customers?:{contact_name?:string|null}|null; vehicles?:{vehicle_no?:string|null}|null }|null };
type Event = { id:string; event_type:string; from_status:string|null; to_status:string|null; reason:string|null; created_at:string; profiles?:{full_name?:string|null}|null };

function relationName(value: Cycle["insurance_companies"]) { const row=Array.isArray(value)?value[0]:value; return row?.name??"—"; }
function creatorName(value: Cycle["creator"]) { const row=Array.isArray(value)?value[0]:value; return row?.full_name??"—"; }
function money(value: unknown) { const number=Number(value??0); return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(Number.isFinite(number)?number:0); }

export function CycleDetailClient({ initialCycle, initialLines, initialEvents }:{initialCycle:Cycle;initialLines:Line[];initialEvents:Event[]}) {
  const [cycle,setCycle]=useState(initialCycle); const [lines,setLines]=useState(initialLines); const [events]=useState(initialEvents); const [message,setMessage]=useState<string|null>(null); const [pending,startTransition]=useTransition();
  const unresolved=lines.filter((line)=>line.match_status!=="Matched"||!["Accepted","Resolved"].includes(line.review_status)).length;
  function review(line:Line,status:"Accepted"|"Follow-up"|"Resolved") { startTransition(async()=>{try{await reviewReconciliationLine({cycleId:cycle.id,lineId:line.id,reviewStatus:status,reason:line.variance_reason??undefined});setLines((current)=>current.map((item)=>item.id===line.id?{...item,review_status:status}:item));if(cycle.status==="Submitted")setCycle({...cycle,status:"Under Review"});setMessage(`Row ${line.source_row_no} marked ${status}.`);}catch(error){setMessage(error instanceof Error?error.message:"Review failed.");}}); }
  function reconcile(){startTransition(async()=>{try{await markReconciliationCycleReconciled(cycle.id);setCycle({...cycle,status:"Reconciled"});setMessage("Cycle marked reconciled.");}catch(error){setMessage(error instanceof Error?error.message:"Could not reconcile cycle.");}});}
  function close(){startTransition(async()=>{try{await closeReconciliationCycle(cycle.id);setCycle({...cycle,status:"Closed"});setMessage("Cycle closed and locked.");}catch(error){setMessage(error instanceof Error?error.message:"Could not close cycle.");}});}
  function reopen(){const reason=window.prompt("Reason for reopening this closed cycle?")?.trim();if(!reason)return;startTransition(async()=>{try{await reopenReconciliationCycle({cycleId:cycle.id,reason});setCycle({...cycle,status:"Reopened"});setMessage("Cycle reopened for review.");}catch(error){setMessage(error instanceof Error?error.message:"Could not reopen cycle.");}});}

  return <div className="mx-auto max-w-[1680px] space-y-4 pb-10">
    <section className="rounded-2xl border border-[#dbe3ee] bg-white shadow-sm overflow-hidden"><div className="bg-[linear-gradient(135deg,#071D49,#17365D_62%,#315B9A)] px-5 py-5 text-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[9px] font-bold uppercase tracking-[.16em] text-white/60">Reconciliation cycle</p><h1 className="mt-1 text-[20px] font-semibold">{relationName(cycle.insurance_companies)}</h1><p className="mt-1 text-[10px] text-white/70">{cycle.period_start} → {cycle.period_end} · {cycle.statement_reference||"No statement reference"}</p></div><div className="flex gap-2"><Link href="/reconciliation/history" className="rounded-xl border border-white/20 bg-white/10 px-3 py-2 text-[9px] font-bold">History</Link><span className="rounded-xl bg-white px-3 py-2 text-[9px] font-bold text-[#17365D]">{cycle.status}</span></div></div></div>
      <div className="grid gap-px bg-[#e6ebf2] sm:grid-cols-3 lg:grid-cols-6"><Metric label="Rows" value={String(cycle.row_count)}/><Metric label="Projected" value={money(cycle.projected_total)}/><Metric label="Actual" value={money(cycle.actual_total)}/><Metric label="TDS" value={money(cycle.tds_total)}/><Metric label="Variance" value={money(cycle.variance_total)}/><Metric label="Unresolved" value={String(unresolved)}/></div>
      <div className="flex flex-wrap items-center justify-between gap-3 border-t border-[#e6ebf2] px-4 py-3"><div className="text-[9px] text-[#667085]">Submitted {new Date(cycle.submitted_at).toLocaleString("en-IN")} by {creatorName(cycle.creator)}{message?` · ${message}`:""}</div><div className="flex gap-2">{["Submitted","Under Review","Reopened"].includes(cycle.status)?<button disabled={pending||unresolved>0} onClick={reconcile} className="rounded-lg bg-[#17365D] px-3 py-2 text-[8.5px] font-bold text-white disabled:bg-[#a9b4c4]">Mark reconciled</button>:null}{cycle.status==="Reconciled"?<button disabled={pending} onClick={close} className="rounded-lg bg-[#18794e] px-3 py-2 text-[8.5px] font-bold text-white">Close cycle</button>:null}{cycle.status==="Closed"?<button disabled={pending} onClick={reopen} className="rounded-lg border border-[#b8c7da] px-3 py-2 text-[8.5px] font-bold text-[#17365D]">Reopen</button>:null}</div></div>
    </section>

    <section className="overflow-hidden rounded-2xl border border-[#dbe3ee] bg-white shadow-sm"><div className="border-b border-[#e6ebf2] bg-[#fbfcfe] px-4 py-3"><h2 className="text-[13px] font-semibold text-[#17365D]">Submitted transaction lines</h2><p className="mt-1 text-[8.5px] text-[#667085]">Exact matches are accepted automatically. Variances and unmatched rows require review before the cycle can be reconciled.</p></div><div className="overflow-x-auto"><table className="min-w-[1380px] w-full text-[9px]"><thead className="bg-[#f5f7fa] text-[#526277]"><tr>{["#","Policy","Customer / Vehicle","Match","Projected","Actual","Adjustment","Variance","Transaction","Reason","Reference","Review","Actions"].map((label)=><th key={label} className="border-b px-2 py-2 text-left font-bold uppercase tracking-[.04em]">{label}</th>)}</tr></thead><tbody>{lines.map((line)=><tr key={line.id} className="border-b border-[#edf0f4]"><td className="px-2 py-2">{line.source_row_no}</td><td className="px-2 py-2 font-semibold">{line.input_policy_no}</td><td className="px-2 py-2"><div>{line.policies?.customers?.contact_name??"—"}</div><div className="text-[8px] text-[#7a8798]">{line.policies?.vehicles?.vehicle_no??"—"}</div></td><td className="px-2 py-2"><Badge value={line.match_status}/></td><td className="px-2 py-2 text-right tabular-nums">{line.projected_payin_snapshot===null?"—":money(line.projected_payin_snapshot)}</td><td className="px-2 py-2 text-right font-semibold tabular-nums">{money(line.actual_recognized_payin)}</td><td className="px-2 py-2 text-right tabular-nums">{money(line.adjustment_amount)}</td><td className="px-2 py-2 text-right font-bold tabular-nums">{line.variance_amount===null?"—":money(line.variance_amount)}</td><td className="px-2 py-2">{line.transaction_type}</td><td className="px-2 py-2">{line.variance_reason||"—"}</td><td className="px-2 py-2">{line.insurer_reference||"—"}</td><td className="px-2 py-2"><Badge value={line.review_status}/></td><td className="px-2 py-2"><div className="flex gap-1">{line.match_status==="Matched"&&!["Accepted","Resolved"].includes(line.review_status)?<><button disabled={pending||cycle.status==="Closed"} onClick={()=>review(line,"Accepted")} className="rounded border px-2 py-1 font-bold text-[#18794e]">Accept</button><button disabled={pending||cycle.status==="Closed"} onClick={()=>review(line,"Follow-up")} className="rounded border px-2 py-1 font-bold text-[#9a6700]">Follow-up</button><button disabled={pending||cycle.status==="Closed"} onClick={()=>review(line,"Resolved")} className="rounded border px-2 py-1 font-bold text-[#17365D]">Resolve</button></>:line.match_status!=="Matched"?<span className="text-[8px] font-semibold text-[#b42318]">Unmatched — correct in a replacement/reopened cycle</span>:<span className="text-[8px] text-[#667085]">Complete</span>}</div></td></tr>)}</tbody></table></div></section>

    <section className="rounded-2xl border border-[#dbe3ee] bg-white p-4 shadow-sm"><h2 className="text-[13px] font-semibold text-[#17365D]">Audit history</h2><div className="mt-3 space-y-2">{events.length?events.map((event)=><div key={event.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-[#edf0f4] px-3 py-2 text-[9px]"><div><strong>{event.event_type}</strong>{event.reason?` · ${event.reason}`:""}<div className="mt-1 text-[8px] text-[#7a8798]">{event.profiles?.full_name??"User"}</div></div><div className="text-[8px] text-[#667085]">{new Date(event.created_at).toLocaleString("en-IN")}{event.to_status?` · ${event.to_status}`:""}</div></div>):<div className="text-[9px] text-[#667085]">No audit events yet.</div>}</div></section>
  </div>;
}

function Metric({label,value}:{label:string;value:string}){return <div className="bg-white px-4 py-3"><div className="text-[8px] font-bold uppercase tracking-[.08em] text-[#7a8798]">{label}</div><div className="mt-1 text-[15px] font-bold tabular-nums text-[#17365D]">{value}</div></div>}
function Badge({value}:{value:string}){const tone=value==="Matched"||value==="Accepted"||value==="Resolved"||value==="Closed"?"bg-[#ecf8f3] text-[#18794e]":value==="Unmatched"?"bg-[#fff1f1] text-[#b42318]":"bg-[#fff8e6] text-[#9a6700]";return <span className={`rounded-full px-2 py-1 text-[7.5px] font-bold ${tone}`}>{value}</span>}
