"use client";

import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {closeAccountingPeriod,createAccountingPeriod,previewPeriodBlockers,reopenAccountingPeriod} from "./actions";
type Data=Awaited<ReturnType<typeof import("./actions").listPeriodCloseWorkbench>>;
type Snapshot=Awaited<ReturnType<typeof previewPeriodBlockers>>;
const labels:Record<keyof Snapshot,string>={unmatched_reconciliation:"Unmatched reconciliation",pending_reconciliation_review:"Pending reconciliation review",reconciled_uninvoiced:"Reconciled not invoiced",outstanding_invoices:"Outstanding invoices",tds_pending_or_mismatch:"TDS pending / mismatch",partner_payables_open:"Open partner payables",insurer_commercials_incomplete:"Insurer commercials incomplete",partner_commercials_incomplete:"Partner commercials incomplete",unallocated_receipts:"Unallocated receipts"};
export function PeriodCloseWorkbench({data}:{data:Data}){const router=useRouter();const[pending,startTransition]=useTransition();const[msg,setMsg]=useState("");const[start,setStart]=useState("");const[end,setEnd]=useState("");const[snapshot,setSnapshot]=useState<Snapshot|null>(null);const run=(fn:()=>Promise<unknown>,ok:string)=>startTransition(async()=>{try{setMsg("");await fn();setMsg(ok);router.refresh()}catch(e){setMsg(e instanceof Error?e.message:"Action failed")}});
return <div className="mx-auto max-w-[1500px] space-y-4 pb-10">
<section className="rounded-2xl border border-[#dbe3ee] bg-white p-5 shadow-sm"><p className="text-[9px] font-black uppercase tracking-[.14em] text-[#0f766e]">Phase G · Accounting control</p><h1 className="mt-2 text-[21px] font-semibold text-[#17365D]">Period Close</h1><p className="mt-1 max-w-5xl text-[10px] leading-5 text-[#667085]">Review month-end exceptions, snapshot the close position, and lock back-dated accounting activity. Closing never erases exceptions: the snapshot and close reason remain part of the audit trail.</p>{msg?<div className="mt-3 rounded-xl bg-[#f8fafc] px-3 py-2 text-[10px]">{msg}</div>:null}</section>
<section className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-2xl border border-[#dbe3ee] bg-white p-5 shadow-sm"><h2 className="text-[13px] font-semibold text-[#17365D]">Create / preview period</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input type="date" value={start} onChange={e=>setStart(e.target.value)} className="rounded border px-3 py-2 text-[10px]"/><input type="date" value={end} onChange={e=>setEnd(e.target.value)} className="rounded border px-3 py-2 text-[10px]"/></div><div className="mt-3 flex gap-2"><button disabled={pending||!start||!end} onClick={()=>startTransition(async()=>{try{setSnapshot(await previewPeriodBlockers(start,end));setMsg("")}catch(e){setMsg(e instanceof Error?e.message:"Preview failed")}})} className="rounded-lg border px-3 py-2 text-[9px] font-bold">Preview blockers</button><button disabled={pending||!start||!end} onClick={()=>run(()=>createAccountingPeriod({start,end}),"Accounting period created.")} className="rounded-lg bg-[#17365D] px-3 py-2 text-[9px] font-bold text-white">Create period</button></div></div><div className="rounded-2xl border border-[#dbe3ee] bg-white p-5 shadow-sm"><h2 className="text-[13px] font-semibold text-[#17365D]">Live blocker preview</h2>{snapshot?<div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{Object.entries(snapshot).map(([k,v])=><div key={k} className={`rounded-xl border p-3 ${Number(v)>0?"bg-[#fff8f0]":"bg-[#f8fafc]"}`}><p className="text-[8px] font-bold uppercase text-[#667085]">{labels[k as keyof Snapshot]}</p><p className="mt-1 text-[18px] font-semibold text-[#17365D]">{v}</p></div>)}</div>:<p className="mt-3 text-[9.5px] text-[#667085]">Choose dates and preview the operational close checklist.</p>}</div></section>
<section className="rounded-2xl border border-[#dbe3ee] bg-white p-5 shadow-sm"><h2 className="text-[13px] font-semibold text-[#17365D]">Accounting period register</h2><div className="mt-3 overflow-auto rounded-xl border"><table className="min-w-[1080px] w-full text-[9.5px]"><thead className="bg-[#f8fafc]"><tr><th className="p-2 text-left">Period</th><th className="p-2 text-left">Status</th><th className="p-2 text-left">Close / reopen reason</th><th className="p-2 text-left">Snapshot</th><th className="p-2">Control</th></tr></thead><tbody>{data.periods.map(p=>{const snap=(p.readiness_snapshot??{}) as Record<string,number>;return <tr key={p.id} className="border-t align-top"><td className="p-2 font-semibold">{p.period_start} → {p.period_end}</td><td className="p-2">{p.status}</td><td className="p-2 max-w-[260px]">{p.close_reason??p.reopen_reason??"—"}</td><td className="p-2"><div className="flex max-w-[420px] flex-wrap gap-1">{Object.entries(snap).filter(([,v])=>Number(v)>0).map(([k,v])=><span key={k} className="rounded bg-[#fff1e8] px-2 py-1 text-[8px]">{labels[k as keyof Snapshot]??k}: {v}</span>)}{Object.values(snap).every(v=>Number(v)===0)?<span className="text-[#0f766e]">No recorded blockers</span>:null}</div></td><td className="p-2 text-center">{p.status!=="Closed"?<button disabled={pending} onClick={()=>{const reason=window.prompt("Close reason / exception acknowledgement");if(reason)run(()=>closeAccountingPeriod({periodId:p.id,reason}),"Period closed and posting lock activated.")}} className="rounded border px-2 py-1 font-bold">Close</button>:<button disabled={pending} onClick={()=>{const reason=window.prompt("Reopen reason");if(reason)run(()=>reopenAccountingPeriod({periodId:p.id,reason}),"Period reopened.")}} className="rounded border px-2 py-1 font-bold">Reopen</button>}</td></tr>})}</tbody></table></div></section>
</div>}
