import { redirect } from "next/navigation";
import { BrandLockup } from "@/components/brand-lockup";
import { getAuthenticatedProfile, getServerAccessToken } from "@/lib/auth-server";
import { createSupabaseAdminClient } from "@/lib/supabase-admin";
import { IntermediaryLogoutButton } from "./logout-button";

export const dynamic="force-dynamic";export const revalidate=0;
type PortalAccount={intermediary_id:string;application_id:string|null;status:string};
type Intermediary={id:string;display_name:string;intermediary_type:"posp"|"misp"|"partner";mobile:string|null;email:string|null;account_status:string;portal_access_status:string};
type Application={registration_status:string;status:string};
type Assignment={training_title:string|null;training_url:string|null;training_instructions:string|null;training_deadline:string|null;training_status:string;exam_status:string;agreement_status:string};

export default async function IntermediaryPortalPage(){
 const accessToken=await getServerAccessToken();const{profile}=await getAuthenticatedProfile(accessToken);if(!profile?.id||profile.role!=="intermediary"||!profile.is_active)redirect("/access-denied");const admin=createSupabaseAdminClient();
 const{data:account}=await admin.from("intermediary_portal_accounts").select("intermediary_id,application_id,status").eq("auth_user_id",profile.id).maybeSingle<PortalAccount>();if(!account||account.status==="disabled")redirect("/access-denied");
 const[{data:intermediary},{data:application},{data:assignment},{count:documentCount}]=await Promise.all([
  admin.from("intermediaries").select("id,display_name,intermediary_type,mobile,email,account_status,portal_access_status").eq("id",account.intermediary_id).maybeSingle<Intermediary>(),
  account.application_id?admin.from("intermediary_onboarding_applications").select("registration_status,status").eq("id",account.application_id).maybeSingle<Application>():Promise.resolve({data:null}),
  account.application_id?admin.from("intermediary_training_exam_assignments").select("training_title,training_url,training_instructions,training_deadline,training_status,exam_status,agreement_status").eq("application_id",account.application_id).maybeSingle<Assignment>():Promise.resolve({data:null}),
  account.application_id?admin.from("intermediary_onboarding_documents").select("id",{count:"exact",head:true}).eq("application_id",account.application_id):Promise.resolve({count:0})
 ]);
 if(!intermediary)redirect("/access-denied");
 if(account.status==="invited"){const now=new Date().toISOString();await Promise.all([admin.from("intermediary_portal_accounts").update({status:"active",activated_at:now,updated_at:now}).eq("auth_user_id",profile.id),admin.from("intermediaries").update({portal_access_status:"active",updated_at:now}).eq("id",intermediary.id)]);}
 const registrationStatus=application?.registration_status??"primary_pending";const trainingStatus=assignment?.training_status??"not_assigned";const examStatus=assignment?.exam_status??"not_allotted";const agreementStatus=assignment?.agreement_status??"not_generated";
 return <main className="min-h-screen bg-[#F3F7FC]"><header className="border-b border-[#DCE5EF] bg-white"><div className="mx-auto flex max-w-[1180px] items-center justify-between gap-4 px-4 py-4"><BrandLockup size="compact"/><IntermediaryLogoutButton/></div></header><div className="mx-auto max-w-[1180px] space-y-4 px-4 py-6">
  <section className="overflow-hidden rounded-3xl border border-[#D8E3EF] bg-white shadow-sm"><div className="bg-gradient-to-r from-[#071D49] via-[#12386D] to-[#2666A8] px-5 py-5 text-white sm:px-7"><div className="flex flex-wrap items-end justify-between gap-4"><div className="min-w-0"><h1 className="text-2xl font-semibold">{intermediary.display_name}</h1><p className="mt-2 flex flex-wrap items-center gap-x-2 gap-y-1 text-[11px] text-white/75"><span><span className="font-semibold text-white/90">Mobile:</span> {intermediary.mobile??"-"}</span><span aria-hidden="true" className="hidden text-white/40 sm:inline">|</span><span className="min-w-0 break-all"><span className="font-semibold text-white/90">Email:</span> {intermediary.email??"-"}</span></p></div><Status value={registrationStatus}/></div></div><div className="grid gap-px bg-[#E2E8F0] sm:grid-cols-5"><Metric label="Account" value={intermediary.account_status}/><Metric label="Portal access" value="active"/><Metric label="Training" value={trainingStatus}/><Metric label="Examination" value={examStatus}/><Metric label="Agreement" value={agreementStatus}/></div></section>
  <section className="rounded-2xl border border-[#DCE5EF] bg-white p-5 shadow-sm"><h2 className="text-[14px] font-semibold text-[#0F172A]">Your onboarding</h2><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><Progress label="Primary information" done/><Progress label={`${documentCount??0} documents attached`} done={Boolean(documentCount)}/><Progress label="Training" done={trainingStatus==="completed"}/><Progress label="Examination" done={examStatus==="passed"}/><Progress label="Agreement" done={agreementStatus==="signed"}/><Progress label="IIB registration" done={registrationStatus==="iib_registered"}/></div></section>
  <section className="rounded-2xl border border-[#DCE5EF] bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[9px] font-semibold uppercase tracking-[.09em] text-[#64748B]">Training material</p><h2 className="mt-1 text-[15px] font-semibold">{assignment?.training_title??"Training has not been assigned"}</h2></div><Status value={trainingStatus}/></div>{assignment?.training_instructions?<p className="mt-3 max-w-3xl whitespace-pre-wrap text-[11px] leading-5 text-[#475569]">{assignment.training_instructions}</p>:null}{assignment?.training_deadline?<p className="mt-3 text-[10px] text-[#64748B]">Complete by {formatDate(assignment.training_deadline)}</p>:null}{assignment?.training_url?<a href={assignment.training_url} target="_blank" rel="noreferrer" className="mt-4 inline-flex rounded-xl bg-[#071D49] px-4 py-2.5 text-[11px] font-semibold text-white">Open training</a>:null}</section>
 </div></main>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="bg-white px-4 py-3"><p className="text-[9px] font-semibold uppercase tracking-[.06em] text-[#64748B]">{label}</p><p className="mt-1 text-[11px] font-semibold capitalize text-[#0F172A]">{value.replaceAll("_"," ")}</p></div>}
function Progress({label,done}:{label:string;done:boolean}){return <div className={`flex items-center gap-2 rounded-xl border px-3 py-3 text-[10.5px] font-semibold ${done?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-[#E2E8F0] bg-[#F8FAFC] text-[#64748B]"}`}><span className={`grid h-5 w-5 place-items-center rounded-full text-[9px] ${done?"bg-emerald-600 text-white":"bg-slate-200"}`}>{done?"✓":"•"}</span>{label}</div>}
function Status({value}:{value:string}){return <span className="inline-flex rounded-full bg-white/15 px-3 py-1.5 text-[9px] font-semibold capitalize text-inherit">{value.replaceAll("_"," ")}</span>}
function formatDate(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat("en-IN",{dateStyle:"medium"}).format(date)}