import Link from "next/link";
import { redirect } from "next/navigation";
import { BrandLockup } from "@/components/brand-lockup";
import { getAuthenticatedProfile, getServerAccessToken } from "@/lib/auth-server";
import { createSupabaseAdminClient } from "@/lib/supabase-admin";
import { IntermediaryLogoutButton } from "./logout-button";

export const dynamic = "force-dynamic";
export const revalidate = 0;

type PortalAccount={id:string;intermediary_id:string;application_id:string|null;status:string;email:string};
type Intermediary={id:string;display_name:string;intermediary_type:"posp"|"misp"|"partner";onboarding_id:string|null;mobile:string|null;email:string|null;city:string|null;state:string|null;account_status:string;portal_access_status:string};
type Application={registration_status:string;status:string};
type Assignment={training_title:string|null;training_url:string|null;training_instructions:string|null;training_deadline:string|null;training_status:string;exam_title:string|null;exam_url:string|null;passing_percentage:number|null;maximum_attempts:number|null;exam_duration_minutes:number|null;exam_status:string;exam_score:number|null;agreement_status:string;iib_registration_status:string};

export default async function IntermediaryPortalPage(){
 const accessToken=await getServerAccessToken();const{user,profile}=await getAuthenticatedProfile(accessToken);if(!user||!profile||profile.role!=="intermediary"||!profile.is_active)redirect("/access-denied");
 const admin=createSupabaseAdminClient();const{data:portal}=await admin.from("intermediary_portal_accounts").select("id,intermediary_id,application_id,status,email").eq("auth_user_id",user.id).maybeSingle<PortalAccount>();if(!portal)redirect("/access-denied");
 const[{data:intermediary},{data:application},{data:assignment},{count:documentCount}]=await Promise.all([
  admin.from("intermediaries").select("id,display_name,intermediary_type,onboarding_id,mobile,email,city,state,account_status,portal_access_status").eq("id",portal.intermediary_id).maybeSingle<Intermediary>(),
  portal.application_id?admin.from("intermediary_onboarding_applications").select("registration_status,status").eq("id",portal.application_id).maybeSingle<Application>():Promise.resolve({data:null}),
  portal.application_id?admin.from("intermediary_training_exam_assignments").select("training_title,training_url,training_instructions,training_deadline,training_status,exam_title,exam_url,passing_percentage,maximum_attempts,exam_duration_minutes,exam_status,exam_score,agreement_status,iib_registration_status").eq("application_id",portal.application_id).maybeSingle<Assignment>():Promise.resolve({data:null}),
  portal.application_id?admin.from("intermediary_onboarding_documents").select("id",{count:"exact",head:true}).eq("application_id",portal.application_id):Promise.resolve({count:0})
 ]);
 if(!intermediary)redirect("/access-denied");
 if(portal.status==="invited"){const now=new Date().toISOString();await Promise.all([admin.from("intermediary_portal_accounts").update({status:"active",activated_at:now,updated_at:now}).eq("id",portal.id),admin.from("intermediaries").update({portal_access_status:"active",updated_at:now}).eq("id",intermediary.id)]);}
 const registrationStatus=application?.registration_status??"primary_pending";const trainingComplete=assignment?.training_status==="completed";const examAvailable=trainingComplete&&Boolean(assignment?.exam_url)&&["available","allotted","locked","in_progress","failed"].includes(assignment?.exam_status??"");
 return <main className="min-h-screen bg-[#F4F7FB] text-[#0F172A]"><header className="border-b border-[#DCE5EF] bg-white"><div className="mx-auto flex max-w-[1180px] items-center justify-between gap-4 px-4 py-4 sm:px-6"><BrandLockup compact/><IntermediaryLogoutButton/></div></header><div className="mx-auto max-w-[1180px] space-y-4 px-4 py-5 sm:px-6 sm:py-7">
  <section className="overflow-hidden rounded-3xl border border-[#DCE5EF] bg-white"><div className="bg-gradient-to-r from-[#071D49] via-[#0F2A55] to-[#163B70] px-5 py-6 text-white"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-white/60">Onboarding portal</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold">{intermediary.display_name}</h1><p className="mt-1 text-[11px] text-white/70">{intermediary.intermediary_type.toUpperCase()} · {intermediary.onboarding_id??"ID pending"}</p></div><span className="rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-[10px] font-semibold capitalize">{registrationStatus.replaceAll("_"," ")}</span></div></div>
  <div className="grid gap-px bg-[#E2E8F0] sm:grid-cols-4"><StatusCell label="Primary information" value="Complete" done/><StatusCell label="Documents" value={`${documentCount??0} attached`} done={(documentCount??0)>0}/><StatusCell label="Training" value={label(assignment?.training_status??"not_assigned")} done={trainingComplete}/><StatusCell label="Examination" value={label(assignment?.exam_status??"not_allotted")} done={assignment?.exam_status==="passed"}/></div></section>
  <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-[#DCE5EF] bg-white p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#64748B]">Training</p><h2 className="mt-1 text-lg font-semibold">{assignment?.training_title??"Training not assigned"}</h2></div><Badge value={assignment?.training_status??"not_assigned"}/></div>{assignment?.training_instructions?<p className="mt-3 text-[11px] leading-5 text-[#475569]">{assignment.training_instructions}</p>:null}{assignment?.training_deadline?<p className="mt-3 text-[10px] text-[#64748B]">Complete by {formatDate(assignment.training_deadline)}</p>:null}{assignment?.training_url?<a href={assignment.training_url} target="_blank" rel="noreferrer" className="mt-4 inline-flex rounded-xl bg-[#0F2A55] px-4 py-2.5 text-[11px] font-semibold text-white">Open training</a>:<p className="mt-4 rounded-xl bg-[#F8FAFC] px-3 py-4 text-[10.5px] text-[#64748B]">The training material has not been assigned yet.</p>}</div>
  <div className="rounded-2xl border border-[#DCE5EF] bg-white p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#64748B]">Examination</p><h2 className="mt-1 text-lg font-semibold">{assignment?.exam_title??"Examination not allotted"}</h2></div><Badge value={assignment?.exam_status??"not_allotted"}/></div>{assignment?.exam_title?<div className="mt-3 grid grid-cols-3 gap-2"><Mini label="Passing" value={assignment.passing_percentage?`${assignment.passing_percentage}%`:"-"}/><Mini label="Attempts" value={assignment.maximum_attempts?String(assignment.maximum_attempts):"-"}/><Mini label="Duration" value={assignment.exam_duration_minutes?`${assignment.exam_duration_minutes} min`:"-"}/></div>:null}{examAvailable&&assignment?.exam_url?<a href={assignment.exam_url} target="_blank" rel="noreferrer" className="mt-4 inline-flex rounded-xl bg-[#4F46E5] px-4 py-2.5 text-[11px] font-semibold text-white">Start examination</a>:<p className="mt-4 rounded-xl bg-[#F8FAFC] px-3 py-4 text-[10.5px] text-[#64748B]">{assignment?.exam_title&&!trainingComplete?"Complete the assigned training to begin the examination.":"The examination has not been allotted yet."}</p>}</div></section>
  <section className="rounded-2xl border border-[#DCE5EF] bg-white p-5"><h2 className="text-[13px] font-semibold">Your information</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info label="Mobile" value={intermediary.mobile??"-"}/><Info label="Email" value={intermediary.email??portal.email}/><Info label="Location" value={[intermediary.city,intermediary.state].filter(Boolean).join(", ")||"-"}/><Info label="Account status" value={label(intermediary.account_status)}/></div></section>
 </div></main>;
}
function label(value:string){return value.replaceAll("_"," ").replace(/\b\w/g,char=>char.toUpperCase())}
function formatDate(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat("en-IN",{dateStyle:"medium"}).format(date)}
function StatusCell({label:caption,value,done}:{label:string;value:string;done:boolean}){return <div className="bg-white px-4 py-3"><p className="text-[9px] font-semibold uppercase tracking-[.05em] text-[#64748B]">{caption}</p><p className={`mt-1 text-[11px] font-semibold ${done?"text-emerald-700":"text-[#334155]"}`}>{done?"✓ ":""}{value}</p></div>}
function Badge({value}:{value:string}){return <span className="rounded-full bg-[#F1F5F9] px-2.5 py-1 text-[9px] font-semibold capitalize text-[#475569]">{value.replaceAll("_"," ")}</span>}
function Mini({label:caption,value}:{label:string;value:string}){return <div className="rounded-xl bg-[#F8FAFC] p-3"><p className="text-[8px] uppercase tracking-[.04em] text-[#64748B]">{caption}</p><p className="mt-1 text-[11px] font-semibold">{value}</p></div>}
function Info({label:caption,value}:{label:string;value:string}){return <div className="rounded-xl border border-[#E2E8F0] bg-[#F8FAFC] p-3"><p className="text-[8.5px] font-semibold uppercase tracking-[.05em] text-[#64748B]">{caption}</p><p className="mt-1 text-[11px] font-semibold">{value}</p></div>}
