"use client";

import Link from "next/link";
import { usePathname, useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { BarChart3, CheckSquare2, ChevronRight, ClipboardList, FileChartColumn, FileCheck2, Gauge, LayoutGrid, Settings, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { BrandLockup } from "@/components/brand-lockup";
import { hasCapability, type Capability } from "@/lib/roles";

type SectionKey="claims"|"distribution"|"master-data"|"tasks"|"reports";
type ActiveNav="dashboard"|SectionKey|"none";
type Item={href:string;label:string;icon:LucideIcon;capability:Capability};
type Section={key:SectionKey;label:string;icon:LucideIcon;tint:string;capability:Capability;items:Item[]};
type Props={activeNav:ActiveNav;role:string|null|undefined};

export const navigationSections:Section[]=[
 {key:"claims",label:"Claims",icon:ShieldCheck,tint:"from-[#ff6f61] to-[#ff9f68]",capability:"view_claims",items:[{href:"/claims",label:"All Claims",icon:ClipboardList,capability:"view_claims"},{href:"/claims?queue=documents",label:"Documents",icon:FileCheck2,capability:"view_claims"},{href:"/claims?journey=spot-intimation",label:"Verification",icon:CheckSquare2,capability:"manage_claims"},{href:"/claims?journey=spot-surveyor-assigned",label:"Survey",icon:Gauge,capability:"manage_claims"},{href:"/claims?journey=under-repair",label:"Repair",icon:Settings,capability:"manage_claims"},{href:"/claims?journey=payment-advice-received",label:"Settlement",icon:BarChart3,capability:"manage_claims"}]},
 {key:"distribution",label:"Intermediatory",icon:Sparkles,tint:"from-[#17c7c9] to-[#6759ff]",capability:"view_intermediaries",items:[{href:"/intermediaries",label:"Overview",icon:UsersRound,capability:"view_intermediaries"},{href:"/intermediaries/posp",label:"POSP",icon:UsersRound,capability:"view_intermediaries"},{href:"/intermediaries/misp",label:"MISP",icon:UsersRound,capability:"view_intermediaries"},{href:"/intermediaries/partner",label:"Partners",icon:UsersRound,capability:"view_intermediaries"},{href:"/customers/posp-misp",label:"Onboarding Applications",icon:FileCheck2,capability:"view_intermediaries"}]},
 {key:"master-data",label:"Master Data",icon:LayoutGrid,tint:"from-[#6759ff] to-[#8f7cff]",capability:"view_customers",items:[{href:"/employees",label:"Employees",icon:UsersRound,capability:"view_employees"},{href:"/customers",label:"Customers",icon:UsersRound,capability:"view_customers"},{href:"/customer-kyc",label:"Customer KYC",icon:FileCheck2,capability:"view_kyc"},{href:"/vehicles",label:"Vehicles",icon:Gauge,capability:"view_vehicles"},{href:"/policies",label:"Policies",icon:ShieldCheck,capability:"view_policies"}]},
 {key:"tasks",label:"Tasks",icon:CheckSquare2,tint:"from-[#17c7c9] to-[#62ddd3]",capability:"view_tasks",items:[{href:"/tasks",label:"All Tasks",icon:CheckSquare2,capability:"view_tasks"},{href:"/tasks?status=open",label:"Open",icon:ClipboardList,capability:"view_tasks"},{href:"/tasks?status=in_progress",label:"In Progress",icon:Gauge,capability:"view_tasks"},{href:"/tasks?status=completed",label:"Completed",icon:FileCheck2,capability:"view_tasks"}]},
 {key:"reports",label:"Reports",icon:FileChartColumn,tint:"from-[#f1b94a] to-[#ffcf6b]",capability:"view_reports",items:[{href:"/reports",label:"Reports Workspace",icon:FileChartColumn,capability:"view_reports"}]}
];

export function visibleNavigationSections(role:string|null|undefined){return navigationSections.filter(section=>hasCapability(role,section.capability)).map(section=>({...section,items:section.items.filter(item=>hasCapability(role,item.capability))}));}

export function AppNavigation({activeNav,role}:Props){
 const pathname=usePathname();const searchParams=useSearchParams();const sections=useMemo(()=>visibleNavigationSections(role),[role]);const routeSection=sectionForPath(pathname);const resolved=routeSection??(activeNav!=="dashboard"&&activeNav!=="none"?activeNav:null);const[openSection,setOpenSection]=useState<SectionKey|null>(resolved);useEffect(()=>{if(resolved&&sections.some(section=>section.key===resolved))setOpenSection(resolved)},[pathname,resolved,sections]);const currentQuery=searchParams.toString();
 return <aside className="fixed inset-y-0 left-0 z-50 hidden w-[268px] overflow-hidden border-r border-white/10 bg-[#111a35] text-white shadow-[20px_0_60px_rgba(17,26,53,0.22)] lg:flex lg:flex-col">
  <div className="pointer-events-none absolute inset-0 overflow-hidden"><div className="absolute -left-20 top-14 h-52 w-52 rounded-full bg-[#6759ff]/25 blur-3xl"/><div className="absolute -right-20 bottom-20 h-56 w-56 rounded-full bg-[#17c7c9]/15 blur-3xl"/><div className="portal-noise absolute inset-0 opacity-20"/></div>
  <Link href="/dashboard" className="relative flex h-[78px] items-center border-b border-white/10 px-5" aria-label="InsureIt home"><BrandLockup compact inverse/></Link>
  <nav className="relative flex-1 overflow-y-auto px-3.5 py-4">
   {hasCapability(role,"view_dashboard")?<Link href="/dashboard" className={`group mb-2 flex h-12 items-center gap-3 rounded-2xl px-3.5 text-[12px] font-bold ${activeNav==="dashboard"&&!routeSection?"bg-white text-[#141d3b] shadow-[0_14px_35px_rgba(0,0,0,.18)]":"text-white/90 hover:bg-white/10 hover:text-white"}`}><span className="grid h-8 w-8 place-items-center rounded-xl bg-gradient-to-br from-[#66B5FF] via-[#2F6BFF] to-[#1746C8] text-white shadow-[0_8px_18px_rgba(47,107,255,.28)]"><Gauge className="h-4 w-4 stroke-[2.2]"/></span><span className="flex-1">Dashboard</span></Link>:null}
   {sections.length?<p className="mb-2 mt-6 px-3 text-[9px] font-black uppercase tracking-[0.18em] text-white/65">Workspaces</p>:null}
   <div className="space-y-1.5">{sections.map(section=>{const open=openSection===section.key;const active=resolved===section.key;const SectionIcon=section.icon;return <div key={section.key} className={`overflow-hidden rounded-2xl border ${active?"border-white/15 bg-white/10":"border-transparent"}`}><button type="button" onClick={()=>setOpenSection(current=>current===section.key&&!active?null:section.key)} className={`group flex h-11 w-full items-center gap-3 px-3.5 text-left text-[12px] font-bold ${active?"text-white":"text-white/88 hover:bg-white/8 hover:text-white"}`} aria-expanded={open}><span className={`grid h-8 w-8 place-items-center rounded-xl bg-gradient-to-br ${section.tint} text-white`}><SectionIcon className="h-4 w-4"/></span><span className="flex-1">{section.label}</span><ChevronRight className={`h-4 w-4 text-white/65 ${open?"rotate-90":""}`}/></button>{open?<div className="space-y-1 px-2.5 pb-2.5 pl-[50px]">{section.items.map(item=>{const itemActive=isCurrent(item.href,pathname,currentQuery);const ItemIcon=item.icon;return <Link key={item.href} href={item.href} title={item.label} className={`group flex min-h-9 items-center gap-2 rounded-xl px-2.5 py-2 text-[10.5px] font-semibold ${itemActive?"bg-white text-[#17213e]":"text-white/82 hover:bg-white/10 hover:text-white"}`}><ItemIcon className={`h-3.5 w-3.5 ${itemActive?"text-[#6759ff]":"text-white/60 group-hover:text-white/90"}`}/><span className="truncate">{item.label}</span></Link>})}</div>:null}</div>})}</div>
  </nav>
  <div className="relative border-t border-white/10 p-3.5"><Link href="/settings" className="group flex h-11 items-center gap-3 rounded-2xl px-3.5 text-[12px] font-bold text-white/88 hover:bg-white/10 hover:text-white"><span className="grid h-8 w-8 place-items-center rounded-xl bg-white/10 text-white/90"><Settings className="h-4 w-4"/></span><span>Settings</span></Link></div>
 </aside>;
}

export function sectionForPath(pathname:string):SectionKey|null{if(pathname==="/claims"||pathname.startsWith("/claims/"))return"claims";if(pathname==="/intermediaries"||pathname.startsWith("/intermediaries/")||pathname==="/customers/posp-misp"||pathname.startsWith("/customers/posp-misp/"))return"distribution";if(pathname==="/tasks"||pathname.startsWith("/tasks/"))return"tasks";if(pathname==="/reports"||pathname.startsWith("/reports/"))return"reports";if(pathname==="/employees"||pathname.startsWith("/employees/")||pathname==="/customers"||pathname==="/customer-kyc"||pathname.startsWith("/customer-kyc/")||pathname==="/vehicles"||pathname.startsWith("/vehicles/")||pathname==="/policies"||pathname.startsWith("/policies/"))return"master-data";return null}
export function isCurrent(href:string,pathname:string,currentQuery:string){const[targetPath,targetQuery=""]=href.split("?");if(pathname!==targetPath)return false;if(!targetQuery)return currentQuery.length===0;const expected=new URLSearchParams(targetQuery);const current=new URLSearchParams(currentQuery);return Array.from(expected.entries()).every(([key,value])=>current.get(key)===value)}
