import type { ReactNode } from "react";
import Link from "next/link";
import { createServerSupabaseClient, getAuthenticatedProfile, getServerAccessToken } from "@/lib/auth-server";
import { UserMenu } from "@/components/user-menu";
import { HistoryBackButton } from "@/components/history-back-button";
import { AppNavigation } from "@/components/claim-manager/app-navigation";

type Props = { title: string; backHref?: string; children: ReactNode; activeNav?: "dashboard" | "claims" | "master-data" | "tasks" | "reports" | "none" };
type NotificationRow = { id: string; event_type: string; title: string; priority: "low" | "medium" | "high" | "critical"; status: "new" | "seen" | "in_progress" | "handled" | "dismissed"; created_at: string };
type NotificationGroup = { key: string; label: string; count: number; urgentCount: number; oldestAt: string; href: string };
const logoUrl = "https://raw.githubusercontent.com/antnish1/insureit_new/main/apps/mobile-app/assets/brand/insureit-stitch-logo.png";

export async function ClaimManagerShell({ title, backHref = "/dashboard", children, activeNav = "claims" }: Props) {
  const accessToken = await getServerAccessToken();
  const { user, profile } = await getAuthenticatedProfile(accessToken);
  const supabase = await createServerSupabaseClient();
  const [{ count: customerCount }, notificationRows] = await Promise.all([supabase.from("customers").select("id", { count: "exact", head: true }), getNotificationRows(supabase)]);
  const notificationGroups = buildNotificationGroups(notificationRows);

  return <div className="min-h-screen bg-[#F4F6FA] text-[#101828]">
    <AppNavigation activeNav={activeNav} customerCount={customerCount ?? 0} />
    <div className="lg:pl-[244px]"><header className="sticky top-0 z-30 border-b border-[#DDE3EC] bg-white/95 backdrop-blur"><div className="flex h-14 items-center justify-between gap-4 px-4 lg:px-5"><div className="flex min-w-0 items-center gap-3"><HistoryBackButton fallbackHref={backHref} /><img src={logoUrl} alt="InsureIT" className="h-8 w-[118px] shrink-0 object-contain object-left" /><div className="hidden h-6 w-px bg-[#E3E7EE] sm:block" /><h1 className="truncate text-[16px] font-semibold tracking-tight text-[#17203A]">{title}</h1></div><div className="flex items-center gap-2"><label className="relative hidden md:block"><span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[13px] text-[#98A2B3]">⌕</span><input aria-label="Global search" placeholder="Search" className="h-8 w-56 rounded-md border border-[#D8DEE8] bg-[#FAFBFC] py-1 pl-8 pr-3 text-[12px]" /></label><NotificationMenu groups={notificationGroups} count={notificationRows.length} /><div className="ml-1 border-l border-[#E4E7EC] pl-2"><UserMenu profile={profile} user={user ? { id: user.id, email: user.email } : null} /></div></div></div></header><main className="min-h-[calc(100vh-56px)] px-3 py-3 sm:px-4 lg:px-5">{children}</main></div>
  </div>;
}

function NotificationMenu({ groups, count }: { groups: NotificationGroup[]; count: number }) { return <details className="relative"><summary className="relative grid h-8 w-8 cursor-pointer list-none place-items-center rounded-md border border-[#E1E6EE] bg-white text-[14px] [&::-webkit-details-marker]:hidden">♧{count ? <span className="absolute -right-1.5 -top-1.5 grid min-h-4 min-w-4 place-items-center rounded-full bg-[#E5484D] px-1 text-[8px] font-bold text-white ring-2 ring-white">{count > 99 ? "99+" : count}</span> : null}</summary><div className="absolute right-0 top-10 z-50 w-[350px] overflow-hidden rounded-xl border border-[#DCE3EC] bg-white shadow-[0_18px_45px_rgba(16,24,40,0.16)]"><div className="flex items-center justify-between border-b border-[#E7ECF2] px-4 py-3"><div><p className="text-[12px] font-semibold">Action Inbox</p><p className="mt-0.5 text-[10px] text-[#667085]">Items requiring attention</p></div><span className="rounded-full bg-[#FFF3E8] px-2 py-0.5 text-[10px] font-semibold text-[#A45A08]">{count} pending</span></div>{groups.length ? <div className="divide-y divide-[#EDF0F4]">{groups.slice(0, 6).map((group) => <Link key={group.key} href={group.href} className="flex items-center justify-between gap-3 px-4 py-2.5 hover:bg-[#F8FAFC]"><div><p className="text-[11px] font-semibold">{group.label}</p><p className="text-[9.5px] text-[#7A8699]">Oldest {relativeTime(group.oldestAt)}</p></div><span className="rounded-full bg-[#EEF1F5] px-2 py-1 text-[10px] font-semibold">{group.count}</span></Link>)}</div> : <div className="px-4 py-7 text-center text-[11px] text-[#7A8699]">No pending actions</div>}</div></details>; }
async function getNotificationRows(supabase: Awaited<ReturnType<typeof createServerSupabaseClient>>) { const { data } = await supabase.from("customer_activity_events").select("id, event_type, title, priority, status, created_at").in("status", ["new", "seen", "in_progress"]).order("created_at", { ascending: false }).limit(80).returns<NotificationRow[]>(); return data ?? []; }
function buildNotificationGroups(rows: NotificationRow[]) { const groups = new Map<string, NotificationGroup>(); for (const row of rows) { const definition = notificationGroupDefinition(row.event_type); const existing = groups.get(definition.key); if (!existing) groups.set(definition.key, { ...definition, count: 1, urgentCount: isUrgent(row), oldestAt: row.created_at }); else { existing.count += 1; existing.urgentCount += isUrgent(row); if (Date.parse(row.created_at) < Date.parse(existing.oldestAt)) existing.oldestAt = row.created_at; } } return Array.from(groups.values()).sort((a, b) => b.urgentCount - a.urgentCount || b.count - a.count); }
function notificationGroupDefinition(eventType: string): Pick<NotificationGroup, "key" | "label" | "href"> { if (eventType === "claim_document_reuploaded") return { key: "reupload", label: "Rejected Docs Reuploaded", href: "/dashboard?activity=replacements#manager-action" }; if (eventType === "claim_document_uploaded" || eventType === "claim_documents_completed") return { key: "documents", label: "Documents Uploaded", href: "/dashboard?activity=documents#manager-action" }; if (eventType.startsWith("support_ticket")) return { key: "support", label: "Support Replies / Tickets", href: "/dashboard?activity=support#manager-action" }; if (eventType.startsWith("customer_kyc")) return { key: "kyc", label: "KYC / Profile Updates", href: "/dashboard?activity=kyc#customer-activity" }; if (eventType === "roadside_call_started") return { key: "roadside", label: "Roadside Assistance", href: "/dashboard?activity=roadside#manager-action" }; return { key: "customer-updates", label: "Customer Updates", href: "/dashboard#manager-action" }; }
function isUrgent(row: NotificationRow) { return row.priority === "critical" || row.priority === "high" ? 1 : 0; }
function relativeTime(value: string) { const diffMs = Date.now() - Date.parse(value); if (!Number.isFinite(diffMs)) return "-"; const minutes = Math.max(0, Math.floor(diffMs / 60000)); if (minutes < 1) return "just now"; if (minutes < 60) return `${minutes}m ago`; const hours = Math.floor(minutes / 60); if (hours < 24) return `${hours}h ago`; const days = Math.floor(hours / 24); return days === 1 ? "1d ago" : `${days}d ago`; }
