"use client";

import Link from "next/link";
import { usePathname, useSearchParams } from "next/navigation";
import { useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { ChevronRight, Gauge, Menu, Settings, X } from "lucide-react";
import { BrandLockup } from "@/components/brand-lockup";
import { isCurrent, permits, sectionForPath, visibleNavigationSections, type NavigationGroup, type NavigationItem } from "@/components/claim-manager/app-navigation";
import { isIntermediaryOnlyLaunch } from "@/lib/launch-scope";
import type { Capability } from "@/lib/roles";
import type { PermissionAccess } from "@/lib/permission-management";

export function MobileNavigation({role,permissionAccess}:{role:string|null|undefined;permissionAccess:Partial<Record<Capability,PermissionAccess>>}) {
 const pathname=usePathname();const searchParams=useSearchParams();const currentQuery=searchParams.toString();const resolvedSection=sectionForPath(pathname);const sections=useMemo(()=>visibleNavigationSections(role,permissionAccess),[role,permissionAccess]);const[open,setOpen]=useState(false);const[openSection,setOpenSection]=useState<string|null>(resolvedSection);const[openGroups,setOpenGroups]=useState<Record<string,boolean>>({});const[mounted,setMounted]=useState(false);const triggerRef=useRef<HTMLButtonElement>(null);const closeRef=useRef<HTMLButtonElement>(null);const panelRef=useRef<HTMLElement>(null);
 useEffect(()=>setMounted(true),[]);useEffect(()=>{setOpen(false);if(resolvedSection)setOpenSection(resolvedSection);for(const section of sections){for(const node of section.items){if(node.kind==="group"&&node.items.some(item=>isCurrent(item.href,pathname,currentQuery)))setOpenGroups(current=>({...current,[`${section.key}:${node.key}`]:true}))}}},[pathname,currentQuery,resolvedSection,sections]);useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;const trigger=triggerRef.current;document.body.style.overflow="hidden";window.requestAnimationFrame(()=>closeRef.current?.focus());function onKeyDown(event:KeyboardEvent){if(event.key==="Escape"){setOpen(false);return}if(event.key!=="Tab"||!panelRef.current)return;const focusable=Array.from(panelRef.current.querySelectorAll<HTMLElement>("a[href], button:not([disabled])"));if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}window.addEventListener("keydown",onKeyDown);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",onKeyDown);trigger?.focus()}},[open]);
 const drawer=open&&mounted?createPortal(<div className="fixed inset-0 isolate lg:hidden" style={{zIndex:2147483647}} role="dialog" aria-modal="true" aria-label="Workspace navigation"><button className="absolute inset-0 h-full w-full bg-[#081127]/78 backdrop-blur-sm" onClick={()=>setOpen(false)} aria-label="Close navigation"/><aside ref={panelRef} id="mobile-workspace-navigation" className="fixed inset-y-0 left-0 flex h-[100dvh] w-[min(88vw,360px)] flex-col overflow-hidden border-r border-white/10 bg-[#111a35] text-white shadow-[24px_0_70px_rgba(0,0,0,.5)] animate-portal-enter"><div className="relative flex h-[78px] shrink-0 items-center justify-between border-b border-white/10 px-4"><BrandLockup compact inverse/><button ref={closeRef} type="button" onClick={()=>setOpen(false)} className="grid h-11 w-11 place-items-center rounded-2xl bg-white/10 text-white" aria-label="Close navigation"><X className="h-5 w-5"/></button></div><nav className="relative min-h-0 flex-1 overflow-y-auto px-3.5 py-4">
  {!isIntermediaryOnlyLaunch&&permits(permissionAccess,"view_dashboard")?<Link href="/dashboard" className={`group mb-2 flex h-12 items-center gap-3 rounded-2xl px-3.5 text-[12px] font-bold ${pathname==="/dashboard"?"bg-white text-[#141d3b]":"text-white/90 hover:bg-white/10"}`}><span className="grid h-8 w-8 place-items-center rounded-xl bg-gradient-to-br from-[#66B5FF] via-[#2F6BFF] to-[#1746C8] text-white"><Gauge className="h-4 w-4"/></span><span>Dashboard</span></Link>:null}
  {sections.length?<p className="mb-2 mt-4 px-3 text-[9px] font-black uppercase tracking-[0.18em] text-white/65">{isIntermediaryOnlyLaunch?"Production workspace":"Workspaces"}</p>:null}<div className="space-y-1.5">{sections.map(section=>{const sectionOpen=openSection===section.key;const active=resolvedSection===section.key;const SectionIcon=section.icon;return <div key={section.key} className={`overflow-hidden rounded-2xl border ${active?"border-white/15 bg-white/10":"border-transparent"}`}><button type="button" onClick={()=>setOpenSection(current=>current===section.key&&!active?null:section.key)} className="flex h-11 w-full items-center gap-3 px-3.5 text-left text-[12px] font-bold text-white"><span className={`grid h-8 w-8 place-items-center rounded-xl bg-gradient-to-br ${section.tint}`}><SectionIcon className="h-4 w-4"/></span><span className="flex-1">{section.label}</span><ChevronRight className={`h-4 w-4 ${sectionOpen?"rotate-90":""}`}/></button>{sectionOpen?<div className="space-y-1 px-2.5 pb-2.5 pl-[42px]">{section.items.map(node=>node.kind==="group"?<MobileGroup key={node.key} group={node} pathname={pathname} currentQuery={currentQuery} open={Boolean(openGroups[`${section.key}:${node.key}`])} onToggle={()=>setOpenGroups(current=>({...current,[`${section.key}:${node.key}`]:!current[`${section.key}:${node.key}`]}))}/>:<MobileLink key={node.href} item={node} pathname={pathname} currentQuery={currentQuery}/>)}</div>:null}</div>})}</div>{!isIntermediaryOnlyLaunch&&permits(permissionAccess,"manage_system","approve")?<div className="mt-4 border-t border-white/10 pt-3"><Link href="/settings" className="flex h-11 items-center gap-3 rounded-2xl px-3.5 text-[12px] font-bold text-white/88 hover:bg-white/10"><Settings className="h-4 w-4"/><span>Settings</span></Link></div>:null}</nav></aside></div>,document.body):null;
 return <><button ref={triggerRef} type="button" onClick={()=>setOpen(true)} className="grid h-11 w-11 place-items-center rounded-2xl border border-[#dbe2ec] bg-white text-[#1b2b49] lg:hidden" aria-label="Open workspace navigation"><Menu className="h-5 w-5"/></button>{drawer}</>;
}

function MobileGroup({group,pathname,currentQuery,open,onToggle}:{group:NavigationGroup;pathname:string;currentQuery:string;open:boolean;onToggle:()=>void}){const Icon=group.icon;const active=group.items.some(item=>isCurrent(item.href,pathname,currentQuery));return <div><button type="button" onClick={onToggle} className={`flex min-h-10 w-full items-center gap-2 rounded-xl px-2.5 py-2 text-left text-[11px] font-semibold ${active?"bg-white/12 text-white":"text-white/82 hover:bg-white/10"}`}><Icon className="h-3.5 w-3.5"/><span className="flex-1">{group.label}</span><ChevronRight className={`h-3.5 w-3.5 ${open?"rotate-90":""}`}/></button>{open?<div className="ml-3 mt-1 space-y-1 border-l border-white/12 pl-2">{group.items.map(item=><MobileLink key={item.href} item={item} pathname={pathname} currentQuery={currentQuery}/>)}</div>:null}</div>}
function MobileLink({item,pathname,currentQuery}:{item:NavigationItem;pathname:string;currentQuery:string}){const active=isCurrent(item.href,pathname,currentQuery);const Icon=item.icon;return <Link href={item.href} className={`flex min-h-10 items-center gap-2 rounded-xl px-2.5 py-2 text-[11px] font-semibold ${active?"bg-white text-[#17213e]":"text-white/82 hover:bg-white/10"}`}><Icon className="h-3.5 w-3.5"/><span>{item.label}</span></Link>}
