import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { GroupPageShell } from '@/components/group/group-page-shell';
import { EmptyState, LoadingState } from '@/components/ui';
import { customerAccountTitle, getAccessibleCustomerContexts, getSelectedCustomerContext, type CustomerAccountContext } from '@/lib/customer-context';
import { supabase } from '@/lib/supabase';
import { palette } from '@/lib/theme';
import type { InsuranceCompany, Policy, Vehicle } from '@/lib/types';

type ExternalPolicy={id:string;customer_id:string;vehicle_id:string;insurance_company_id:string;policy_no:string;policy_type:string;end_date:string};
type Row={id:string;source:'sankalp'|'external';customer_id:string;vehicle_id:string;insurance_company_id:string;policy_no:string;policy_type:string;end_date:string};

export function GroupPolicyPortfolioScreen(){const router=useRouter();const[contexts,setContexts]=useState<CustomerAccountContext[]>([]);const[rows,setRows]=useState<Row[]>([]);const[vehicles,setVehicles]=useState<Vehicle[]>([]);const[companies,setCompanies]=useState<InsuranceCompany[]>([]);const[accountId,setAccountId]=useState('all');const[loading,setLoading]=useState(true);
useEffect(()=>{let active=true;void(async()=>{const selected=await getSelectedCustomerContext();if(!selected)return;const associated=(await getAccessibleCustomerContexts()).filter(x=>x.customer_id!==selected.customer_id&&x.group_customer_id===selected.customer_id);const next=[selected,...associated];const ids=next.map(x=>x.customer_id);const[a,b,c,d]=await Promise.all([supabase.from('policies').select('*').in('customer_id',ids).order('end_date'),supabase.from('external_policies').select('*').in('customer_id',ids).order('end_date'),supabase.from('vehicles').select('*').in('customer_id',ids),supabase.from('insurance_companies').select('*')]);if(!active)return;setContexts(next);setRows([...(a.data??[]).map((p:any)=>({...p,source:'sankalp' as const})),...(b.data??[]).map((p:ExternalPolicy)=>({...p,source:'external' as const}))]);setVehicles((c.data??[]) as Vehicle[]);setCompanies((d.data??[]) as InsuranceCompany[]);setLoading(false)})();return()=>{active=false}},[]);
const filtered=useMemo(()=>rows.filter(r=>accountId==='all'||r.customer_id===accountId),[rows,accountId]);const names=new Map(contexts.map(c=>[c.customer_id,customerAccountTitle(c)]));const sankalp=filtered.filter(r=>r.source==='sankalp').length;const external=filtered.filter(r=>r.source==='external').length;
return <GroupPageShell title="Policy Portfolio" subtitle={`${filtered.length} policies • ${sankalp} Sankalp • ${external} external`} icon="file-document-outline" loading={loading} rightAction={<Pressable onPress={()=>router.push('/customer/add-policy')} style={styles.add}><MaterialCommunityIcons name="plus" size={16} color={palette.navy}/><Text style={styles.addText}>External</Text></Pressable>}>
{loading?<LoadingState/>:<><View style={styles.filters}><Pressable onPress={()=>setAccountId('all')} style={[styles.chip,accountId==='all'&&styles.chipActive]}><Text style={[styles.chipText,accountId==='all'&&styles.chipTextActive]}>All Accounts</Text></Pressable>{contexts.map(c=><Pressable key={c.customer_id} onPress={()=>setAccountId(c.customer_id)} style={[styles.chip,accountId===c.customer_id&&styles.chipActive]}><Text numberOfLines={1} style={[styles.chipText,accountId===c.customer_id&&styles.chipTextActive]}>{customerAccountTitle(c)}</Text></Pressable>)}</View>{!filtered.length?<EmptyState title="No policies" body="No policies are available for this account."/>:filtered.sort((a,b)=>a.source===b.source?0:a.source==='sankalp'?-1:1).map(r=>{const v=vehicles.find(x=>x.id===r.vehicle_id);const co=companies.find(x=>x.id===r.insurance_company_id);return <Pressable key={`${r.source}-${r.id}`} disabled={r.source==='external'} onPress={()=>router.push({pathname:'/customer/policy-detail',params:{id:r.id}} as any)} style={[styles.card,r.source==='external'&&styles.externalCard]}><View style={[styles.icon,r.source==='external'&&styles.externalIcon]}><MaterialCommunityIcons name={r.source==='sankalp'?'shield-check-outline':'file-document-outline'} size={21} color={r.source==='sankalp'?'#14845C':'#0A43A3'}/></View><View style={styles.copy}><Text style={[styles.badge,r.source==='external'&&styles.externalBadge]}>{r.source==='sankalp'?'SANKALP SERVICED':'EXTERNAL POLICY'}</Text><Text style={styles.account}>{names.get(r.customer_id)??'Account'}</Text><Text style={styles.vehicle}>{v?.vehicle_no??'Vehicle'}</Text><Text style={styles.meta}>{co?.name??'Insurer'} • {r.policy_no} • Ends {fmt(r.end_date)}</Text></View></Pressable>})}</>}</GroupPageShell>}
function fmt(v:string){return new Date(v).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}
const styles=StyleSheet.create({add:{minHeight:36,borderRadius:11,backgroundColor:'#FFF',paddingHorizontal:9,flexDirection:'row',gap:4,alignItems:'center'},addText:{color:palette.navy,fontSize:9.5,fontWeight:'900'},filters:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{maxWidth:170,minHeight:34,borderRadius:999,borderWidth:1,borderColor:'#D8E3EF',backgroundColor:'#FFF',paddingHorizontal:11,justifyContent:'center'},chipActive:{backgroundColor:palette.navy,borderColor:palette.navy},chipText:{color:'#65758B',fontSize:10,fontWeight:'800'},chipTextActive:{color:'#FFF'},card:{minHeight:92,borderRadius:16,backgroundColor:'#FFF',borderWidth:1,borderColor:'#DCE8F4',padding:12,flexDirection:'row',gap:10,alignItems:'center'},externalCard:{backgroundColor:'#FBFDFF',borderColor:'#C9DCF5'},icon:{width:42,height:42,borderRadius:13,backgroundColor:'#E8F8F0',alignItems:'center',justifyContent:'center'},externalIcon:{backgroundColor:'#EAF2FF'},copy:{flex:1},badge:{color:'#14845C',fontSize:8,fontWeight:'900',letterSpacing:.5},externalBadge:{color:'#0A43A3'},account:{color:'#667085',fontSize:9.5,fontWeight:'800',marginTop:2},vehicle:{color:palette.navy,fontSize:15,fontWeight:'900',marginTop:1},meta:{color:'#65758B',fontSize:10,fontWeight:'600',marginTop:2}});
