import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

import { GroupPageShell } from '@/components/group/group-page-shell';
import { Message } from '@/components/ui';
import { partnerTypeLabel } from '@/lib/customer-context';
import { palette } from '@/lib/theme';

type AccountType = 'corporate' | 'individual_proprietor' | 'dealership';

export function GroupAddAccountScreen() {
  const [step, setStep] = useState<1 | 2 | 3>(1);
  const [type, setType] = useState<AccountType | null>(null);
  const [values, setValues] = useState({ accountName: '', contactName: '', mobile: '', email: '', city: '', state: '' });
  const [message, setMessage] = useState('');
  const ready = Boolean(type && values.accountName.trim() && values.contactName.trim() && values.mobile.replace(/\D/g, '').length === 10 && values.city.trim() && values.state.trim());
  const label = type === 'corporate' ? 'Company Name' : type === 'dealership' ? 'Dealership Name' : 'Customer / Trade Name';

  function next() { setMessage(''); if (step === 1 && !type) return setMessage('Select an account type to continue.'); if (step === 2 && !ready) return setMessage('Complete all required details before continuing.'); setStep((current) => current === 1 ? 2 : 3); }

  return <GroupPageShell title="Add Associated Customer" subtitle="Create a business account inside your Group portfolio" icon="account-plus-outline">
    <View style={styles.stepTrack}>{[1,2,3].map((item) => <View key={item} style={[styles.stepDot, item <= step && styles.stepDotActive]} />)}</View>
    {message ? <Message type="error">{message}</Message> : null}
    {step === 1 ? <View style={styles.section}><Text style={styles.sectionTitle}>Select account type</Text><Text style={styles.sectionText}>Choose the customer category you want to associate with this Group.</Text>{([
      ['corporate','office-building-outline','Corporate','Companies and fleet-owning businesses'],
      ['individual_proprietor','account-outline','Individual / Proprietor','Individual owners and proprietorship firms'],
      ['dealership','storefront-outline','Dealership','Vehicle dealers and authorized outlets'],
    ] as const).map(([value,icon,title,body]) => <Pressable key={value} onPress={() => setType(value)} style={[styles.typeCard, type === value && styles.typeCardSelected]}><View style={[styles.typeIcon, type === value && styles.typeIconSelected]}><MaterialCommunityIcons name={icon} size={25} color={type === value ? '#FFFFFF' : '#0A43A3'} /></View><View style={styles.typeCopy}><Text style={styles.typeTitle}>{title}</Text><Text style={styles.typeBody}>{body}</Text></View>{type === value ? <MaterialCommunityIcons name="check-circle" size={23} color="#0A43A3" /> : <MaterialCommunityIcons name="chevron-right" size={23} color="#7A8799" />}</Pressable>)}</View> : null}
    {step === 2 ? <View style={styles.section}><Text style={styles.sectionTitle}>Basic information</Text><Text style={styles.sectionText}>Enter the primary account details.</Text><Field label={`${label} *`} value={values.accountName} onChangeText={(accountName) => setValues((current) => ({ ...current, accountName }))} /><Field label="Contact Person *" value={values.contactName} onChangeText={(contactName) => setValues((current) => ({ ...current, contactName }))} /><Field label="Mobile Number *" value={values.mobile} keyboardType="phone-pad" onChangeText={(mobile) => setValues((current) => ({ ...current, mobile: mobile.replace(/\D/g, '').slice(0, 10) }))} /><Field label="Email" value={values.email} keyboardType="email-address" onChangeText={(email) => setValues((current) => ({ ...current, email }))} /><View style={styles.twoColumn}><View style={styles.flex}><Field label="City *" value={values.city} onChangeText={(city) => setValues((current) => ({ ...current, city }))} /></View><View style={styles.flex}><Field label="State *" value={values.state} onChangeText={(state) => setValues((current) => ({ ...current, state }))} /></View></View></View> : null}
    {step === 3 ? <View style={styles.section}><Text style={styles.sectionTitle}>Review details</Text><View style={styles.reviewCard}><Review label="Account Type" value={type ? partnerTypeLabel(type) : '—'} /><Review label="Account Name" value={values.accountName} /><Review label="Contact Person" value={values.contactName} /><Review label="Mobile" value={values.mobile} /><Review label="Email" value={values.email || '—'} /><Review label="Location" value={`${values.city}, ${values.state}`} /></View><View style={styles.infoCard}><MaterialCommunityIcons name="information-outline" size={20} color="#0A43A3" /><Text style={styles.infoText}>The production submit action will use the approved onboarding service after UI testing.</Text></View></View> : null}
    <View style={styles.footerActions}>{step > 1 ? <Pressable onPress={() => setStep((current) => current === 3 ? 2 : 1)} style={styles.secondaryButton}><Text style={styles.secondaryButtonText}>Back</Text></Pressable> : <View style={styles.flex} />}<Pressable onPress={step === 3 ? () => setMessage('Layout preview complete. Database creation is not connected yet.') : next} style={styles.primaryButton}><Text style={styles.primaryButtonText}>{step === 3 ? 'Create Account' : 'Continue'}</Text><MaterialCommunityIcons name="arrow-right" size={17} color="#FFFFFF" /></Pressable></View>
  </GroupPageShell>;
}

function Field({ label, value, onChangeText, keyboardType }: { label: string; value: string; onChangeText: (value: string) => void; keyboardType?: 'default' | 'phone-pad' | 'email-address' }) { return <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><TextInput value={value} onChangeText={onChangeText} keyboardType={keyboardType} autoCapitalize={keyboardType === 'email-address' ? 'none' : 'words'} style={styles.input} /></View>; }
function Review({ label, value }: { label: string; value: string }) { return <View style={styles.reviewRow}><Text style={styles.reviewLabel}>{label}</Text><Text style={styles.reviewValue}>{value}</Text></View>; }

const styles = StyleSheet.create({
  stepTrack: { flexDirection: 'row', gap: 6 }, stepDot: { flex: 1, height: 4, borderRadius: 999, backgroundColor: '#DCE5EF' }, stepDotActive: { backgroundColor: '#0A43A3' }, section: { gap: 9 }, sectionTitle: { color: palette.navy, fontSize: 15, fontWeight: '900' }, sectionText: { color: '#65758B', fontSize: 10.5, lineHeight: 15, fontWeight: '600' }, typeCard: { minHeight: 77, borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DCE6F0', padding: 12, flexDirection: 'row', alignItems: 'center', gap: 11 }, typeCardSelected: { borderColor: '#0A43A3', backgroundColor: '#F5F9FF' }, typeIcon: { width: 45, height: 45, borderRadius: 14, backgroundColor: '#EEF5FF', alignItems: 'center', justifyContent: 'center' }, typeIconSelected: { backgroundColor: '#0A43A3' }, typeCopy: { flex: 1 }, typeTitle: { color: palette.navy, fontSize: 14, fontWeight: '900' }, typeBody: { color: '#65758B', fontSize: 10, lineHeight: 14, fontWeight: '600', marginTop: 2 }, field: { marginBottom: 1 }, fieldLabel: { color: '#334155', fontSize: 10.5, fontWeight: '800', marginBottom: 5 }, input: { minHeight: 47, borderRadius: 13, borderWidth: 1, borderColor: '#DCE6F0', backgroundColor: '#FFFFFF', paddingHorizontal: 12, color: palette.navy, fontSize: 13, fontWeight: '600' }, twoColumn: { flexDirection: 'row', gap: 8 }, flex: { flex: 1 }, reviewCard: { borderRadius: 17, borderWidth: 1, borderColor: '#DCE8F4', backgroundColor: '#FFFFFF', padding: 13 }, reviewRow: { minHeight: 40, borderBottomWidth: 1, borderBottomColor: '#EEF2F6', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, reviewLabel: { color: '#65758B', fontSize: 10.5, fontWeight: '700' }, reviewValue: { flex: 1, textAlign: 'right', color: palette.navy, fontSize: 11.5, fontWeight: '900' }, infoCard: { borderRadius: 14, backgroundColor: '#EEF5FF', borderWidth: 1, borderColor: '#CFE0F8', padding: 12, flexDirection: 'row', alignItems: 'flex-start', gap: 9 }, infoText: { flex: 1, color: '#315277', fontSize: 10.5, lineHeight: 15, fontWeight: '600' }, footerActions: { flexDirection: 'row', gap: 8 }, secondaryButton: { flex: 1, minHeight: 48, borderRadius: 13, borderWidth: 1, borderColor: '#C9D5E3', backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' }, secondaryButtonText: { color: palette.navy, fontSize: 12, fontWeight: '900' }, primaryButton: { flex: 1.5, minHeight: 48, borderRadius: 13, backgroundColor: '#0A43A3', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, primaryButtonText: { color: '#FFFFFF', fontSize: 12, fontWeight: '900' },
});