import { FormSubmitButton } from "@/components/form-submit-button";
import { CompactRegistrationForm } from "./compact-registration-form";
import { allotIntermediaryExam, assignIntermediaryTraining, updateIntermediaryExamResult, updateIntermediaryTrainingStatus } from "./training-exam-actions";
import { sendIntermediaryAgreement, updateIntermediaryAgreementStatus } from "./agreement-actions";

type Assignment = {
  training_title:string|null; training_url:string|null; training_instructions:string|null; training_assigned_at:string|null; training_deadline:string|null; training_status:string;
  exam_title:string|null; exam_url:string|null; passing_percentage:number|null; maximum_attempts:number|null; exam_duration_minutes:number|null; exam_available_from:string|null; exam_available_until:string|null; exam_status:string; exam_score:number|null; exam_attempts_used:number;
  agreement_status:string; agreement_signing_url:string|null; agreement_sent_at:string|null; agreement_signed_at:string|null;
};
type Profile={partner_type:"posp"|"misp";external_onboarding_id:string|null;document_received_at:string|null;pos_name:string|null;misp_name:string|null;applicant_phone:string|null;applicant_email:string|null;pan_number:string|null;gst_number:string|null;address:string|null;city:string|null;state:string|null;postal_code:string|null;bank_name:string|null;bank_account_number:string|null;bank_ifsc_code:string|null;dp_name:string|null;dp_phone:string|null;dp_email:string|null;dp_pan_number:string|null;aadhaar_number:string|null};
type Props={applicationId:string;profile:Profile;assignment:Assignment|null;documents:Array<{document_type:string;file_name:string}>;iibVerified:boolean;finalType:string|null};
const inputClass="h-10 w-full rounded-xl border border-[#CBD5E1] bg-white px-3 text-[10.5px] outline-none focus:border-[#635BFF] focus:ring-2 focus:ring-[#E7E5FF]";
const labelClass="mb-1.5 block text-[9px] font-semibold uppercase tracking-[.05em] text-[#526178]";

export function TrainingExamStage({applicationId,profile,assignment,documents,iibVerified,finalType}:Props){
 if(finalType==="partner")return <section className="rounded-2xl border border-violet-200 bg-violet-50 p-4"><h2 className="text-[12px] font-semibold text-violet-900">Business Associate onboarding</h2><p className="mt-1 text-[9.5px] text-violet-800">Training, examination and IIB registration are not applicable to this route.</p></section>;
 const registrationCompleted=documents.length>0;
 const trainingAssigned=Boolean(assignment?.training_title&&assignment.training_url);
 const trainingCompleted=assignment?.training_status==="completed";
 const examAllotted=Boolean(assignment?.exam_title&&assignment.exam_url);
 const examPassed=assignment?.exam_status==="passed";
 const agreementSent=Boolean(assignment?.agreement_signing_url&&["sent","opened","signed"].includes(assignment?.agreement_status??""));
 const agreementSigned=assignment?.agreement_status==="signed";
 const currentStep=!registrationCompleted?1:!trainingCompleted?2:!examPassed?3:!agreementSigned?4:5;
 return <div id="qualification-process" className="scroll-mt-24 space-y-5">
  <ProcessHeader currentStep={currentStep}/>

  <ProcessSection anchorId="registration-requirement" number="1" title="Registration form" description="Verified intermediary information and supporting documents." state={registrationCompleted?"completed":"current"}>
   <div className={`mb-3 rounded-xl border px-4 py-3 ${registrationCompleted?"border-emerald-200 bg-emerald-50":"border-amber-200 bg-amber-50"}`}><p className={`text-[10.5px] font-semibold ${registrationCompleted?"text-emerald-900":"text-amber-900"}`}>{registrationCompleted?"Registration information completed":"Registration information requires review"}</p><p className={`mt-1 text-[9.5px] ${registrationCompleted?"text-emerald-800":"text-amber-800"}`}>{registrationCompleted?"The registration form and submitted documents are available below for reference.":"Complete the registration information and document stage before continuing."}</p></div>
   <CompactRegistrationForm profile={profile} iibVerified={iibVerified} documents={documents}/>
  </ProcessSection>

  {registrationCompleted?<ProcessSection anchorId="training-requirement" number="2" title="Training" description="Assign the approved training material and record completion." state={trainingCompleted?"completed":"current"}>
   {trainingCompleted?<CompletedPanel title="Training completed" detail={`Completed${assignment?.training_deadline?` · Deadline ${formatDate(assignment.training_deadline)}`:""}. The examination stage is now available.`} facts={[{label:"Training",value:assignment?.training_title??"-"},{label:"Completion status",value:"Completed"}]}/>:trainingAssigned?<div className="space-y-4"><div className="grid gap-2 sm:grid-cols-3"><Info label="Training" value={assignment?.training_title??"-"}/><Info label="Deadline" value={formatDate(assignment?.training_deadline)}/><Info label="Current status" value={assignment?.training_status??"assigned"}/></div>{assignment?.training_instructions?<Info label="Instructions" value={assignment.training_instructions}/>:null}<div className="flex flex-wrap items-center gap-2"><a href={assignment?.training_url??"#"} target="_blank" rel="noreferrer" className="rounded-xl bg-[#071D49] px-4 py-2.5 text-[10px] font-semibold text-white">Open training material</a><form action={updateIntermediaryTrainingStatus} className="flex flex-wrap gap-2"><input type="hidden" name="application_id" value={applicationId}/><select name="training_status" defaultValue={assignment?.training_status??"assigned"} className="h-10 rounded-xl border border-[#CBD5E1] bg-white px-3 text-[10px]"><option value="assigned">Assigned</option><option value="opened">Opened</option><option value="in_progress">In progress</option><option value="completed">Completed</option><option value="expired">Expired</option></select><FormSubmitButton label="Save training status" pendingLabel="Saving" className="rounded-xl border border-[#CBD5E1] bg-white px-4 py-2.5 text-[10px] font-semibold text-[#334155]"/></form></div></div>:<form action={assignIntermediaryTraining} className="grid gap-3 lg:grid-cols-2"><input type="hidden" name="application_id" value={applicationId}/><Field label="Training title" name="training_title" defaultValue="POSP / MISP Training" required/><Field label="Training material URL" name="training_url" type="url" placeholder="https://" required/><Field label="Completion deadline" name="training_deadline" type="date"/><div className="lg:col-span-2"><label className={labelClass}>Instructions</label><textarea name="training_instructions" className="min-h-24 w-full rounded-xl border border-[#CBD5E1] bg-white px-3 py-2 text-[10.5px]"/></div><div className="lg:col-span-2"><FormSubmitButton label="Assign training" pendingLabel="Assigning" className="rounded-xl bg-[#071D49] px-5 py-2.5 text-[10px] font-semibold text-white"/></div></form>}
  </ProcessSection>:null}

  {trainingCompleted?<ProcessSection anchorId="examination-requirement" number="3" title="Examination" description="Allot the examination and record the official result." state={examPassed?"completed":"current"}>
   {examPassed?<CompletedPanel title="Examination passed" detail="The examination requirement has been completed. The agreement stage is now available." facts={[{label:"Examination",value:assignment?.exam_title??"-"},{label:"Score",value:assignment?.exam_score!=null?String(assignment.exam_score):"-"},{label:"Attempts used",value:String(assignment?.exam_attempts_used??0)}]}/>:examAllotted?<div className="space-y-4"><div className="grid gap-2 sm:grid-cols-4"><Info label="Examination" value={assignment?.exam_title??"-"}/><Info label="Passing score" value={assignment?.passing_percentage!=null?`${assignment.passing_percentage}%`:"-"}/><Info label="Maximum attempts" value={String(assignment?.maximum_attempts??"-")}/><Info label="Duration" value={assignment?.exam_duration_minutes?`${assignment.exam_duration_minutes} minutes`:"-"}/></div><div className="flex flex-wrap items-center gap-2"><a href={assignment?.exam_url??"#"} target="_blank" rel="noreferrer" className="rounded-xl bg-[#4F46E5] px-4 py-2.5 text-[10px] font-semibold text-white">Open examination</a><form action={updateIntermediaryExamResult} className="flex flex-wrap gap-2"><input type="hidden" name="application_id" value={applicationId}/><select name="exam_result" defaultValue="failed" className="h-10 rounded-xl border border-[#CBD5E1] bg-white px-3 text-[10px]"><option value="passed">Passed</option><option value="failed">Failed</option></select><input name="exam_score" type="number" min="0" max="100" step="0.01" placeholder="Score" className="h-10 w-24 rounded-xl border border-[#CBD5E1] px-3 text-[10px]"/><FormSubmitButton label="Record examination result" pendingLabel="Saving" className="rounded-xl border border-[#CBD5E1] bg-white px-4 py-2.5 text-[10px] font-semibold text-[#334155]"/></form></div></div>:<form action={allotIntermediaryExam} className="grid gap-3 lg:grid-cols-2"><input type="hidden" name="application_id" value={applicationId}/><Field label="Examination name" name="exam_title" defaultValue="POSP / MISP Examination" required/><Field label="Examination URL" name="exam_url" type="url" placeholder="https://" required/><Field label="Passing percentage" name="passing_percentage" type="number" min="1" max="100" defaultValue="60" required/><Field label="Maximum attempts" name="maximum_attempts" type="number" min="1" defaultValue="3" required/><Field label="Duration (minutes)" name="exam_duration_minutes" type="number" min="1" defaultValue="30"/><Field label="Available from" name="exam_available_from" type="datetime-local"/><Field label="Available until" name="exam_available_until" type="datetime-local"/><div className="self-end"><FormSubmitButton label="Allot examination" pendingLabel="Allotting" className="rounded-xl bg-[#4F46E5] px-5 py-2.5 text-[10px] font-semibold text-white"/></div></form>}
  </ProcessSection>:null}

  {examPassed?<ProcessSection anchorId="agreement-requirement" number="4" title="Agreement" description="Send the approved agreement and record its signing status." state={agreementSigned?"completed":"current"}>
   {agreementSigned?<CompletedPanel title="Agreement signed" detail="The agreement requirement has been completed. The application is ready for IIB registration." facts={[{label:"Sent at",value:formatDateTime(assignment?.agreement_sent_at)},{label:"Signed at",value:formatDateTime(assignment?.agreement_signed_at)}]}/>:agreementSent?<div className="space-y-4"><div className="grid gap-2 sm:grid-cols-3"><Info label="Agreement status" value={assignment?.agreement_status??"sent"}/><Info label="Sent at" value={formatDateTime(assignment?.agreement_sent_at)}/><Info label="Signed at" value={formatDateTime(assignment?.agreement_signed_at)}/></div><div className="flex flex-wrap items-center gap-2"><a href={assignment?.agreement_signing_url??"#"} target="_blank" rel="noreferrer" className="rounded-xl bg-[#0F766E] px-4 py-2.5 text-[10px] font-semibold text-white">Open agreement</a><form action={updateIntermediaryAgreementStatus} className="flex flex-wrap gap-2"><input type="hidden" name="application_id" value={applicationId}/><select name="agreement_status" defaultValue={assignment?.agreement_status??"sent"} className="h-10 rounded-xl border border-[#CBD5E1] bg-white px-3 text-[10px]"><option value="sent">Sent</option><option value="opened">Opened</option><option value="signed">Signed</option><option value="declined">Declined</option><option value="expired">Expired</option><option value="failed">Failed</option></select><FormSubmitButton label="Save agreement status" pendingLabel="Saving" className="rounded-xl border border-[#CBD5E1] bg-white px-4 py-2.5 text-[10px] font-semibold text-[#334155]"/></form></div></div>:<form action={sendIntermediaryAgreement} className="grid gap-3 sm:grid-cols-[1fr_auto]"><input type="hidden" name="application_id" value={applicationId}/><Field label="Agreement signing URL" name="agreement_signing_url" type="url" placeholder="https://" required/><FormSubmitButton label="Send agreement" pendingLabel="Sending" className="self-end rounded-xl bg-[#0F766E] px-5 py-2.5 text-[10px] font-semibold text-white"/></form>}
  </ProcessSection>:null}
 </div>;
}

function ProcessHeader({currentStep}:{currentStep:number}){const labels=["Registration","Training","Examination","Agreement"];return <section className="overflow-hidden rounded-2xl border border-[#DCE5EF] bg-white shadow-sm"><div className="bg-gradient-to-r from-[#071D49] to-[#163B70] px-5 py-4 text-white"><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-white/60">Stage 3</p><h2 className="mt-1 text-[15px] font-semibold">Qualification and agreement process</h2><p className="mt-1 text-[9.5px] text-white/70">Complete each requirement in sequence. The next requirement appears automatically after the current one is completed.</p></div><div className="grid gap-px bg-[#E2E8F0] sm:grid-cols-4">{labels.map((label,index)=>{const number=index+1;const completed=currentStep>number;const current=currentStep===number;return <div key={label} className={`px-4 py-3 ${current?"bg-[#EEF4FF]":"bg-white"}`}><div className="flex items-center gap-2"><span className={`grid h-6 w-6 place-items-center rounded-full text-[9px] font-bold ${completed?"bg-emerald-600 text-white":current?"bg-[#071D49] text-white":"bg-slate-100 text-slate-400"}`}>{completed?"✓":number}</span><div><p className={`text-[9.5px] font-semibold ${current?"text-[#071D49]":completed?"text-emerald-800":"text-slate-400"}`}>{label}</p><p className="text-[8px] text-[#64748B]">{completed?"Completed":current?"Action required":"Upcoming"}</p></div></div></div>})}</div></section>}
function ProcessSection({anchorId,number,title,description,state,children}:{anchorId:string;number:string;title:string;description:string;state:"current"|"completed";children:React.ReactNode}){return <section id={anchorId} className={`scroll-mt-24 overflow-hidden rounded-2xl border bg-white shadow-sm ${state==="completed"?"border-emerald-200":"border-[#BFD0E2]"}`}><div className={`flex items-center justify-between gap-4 border-b px-5 py-4 ${state==="completed"?"border-emerald-200 bg-emerald-50":"border-[#DCE5EF] bg-[#F8FAFC]"}`}><div className="flex items-center gap-3"><span className={`grid h-9 w-9 place-items-center rounded-xl text-[11px] font-bold ${state==="completed"?"bg-emerald-600 text-white":"bg-[#071D49] text-white"}`}>{state==="completed"?"✓":number}</span><div><h3 className="text-[12px] font-semibold text-[#0F172A]">{title}</h3><p className="mt-0.5 text-[9px] text-[#64748B]">{description}</p></div></div><span className={`rounded-full px-3 py-1.5 text-[8.5px] font-semibold ${state==="completed"?"bg-emerald-100 text-emerald-800":"bg-blue-100 text-blue-800"}`}>{state==="completed"?"Requirement completed":"Action required"}</span></div><div className="p-4 sm:p-5">{children}</div></section>}
function CompletedPanel({title,detail,facts}:{title:string;detail:string;facts:Array<{label:string;value:string}>}){return <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-emerald-600 text-sm font-bold text-white">✓</span><div><p className="text-[11px] font-semibold text-emerald-950">{title}</p><p className="mt-1 text-[9.5px] leading-5 text-emerald-800">{detail}</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-3">{facts.map(item=><Info key={item.label} label={item.label} value={item.value}/>)}</div><div className="mt-3 inline-flex rounded-xl border border-emerald-300 bg-white px-4 py-2.5 text-[9.5px] font-semibold text-emerald-800">No further action required</div></div>}
function Field({label,name,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string;name:string}){return <div><label className={labelClass}>{label}{props.required?" *":""}</label><input name={name} className={inputClass} {...props}/></div>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-[#E2E8F0] bg-white px-3 py-2.5"><p className="text-[8px] font-semibold uppercase tracking-[.05em] text-[#64748B]">{label}</p><p className="mt-1 break-words text-[9.5px] font-medium capitalize text-[#0F172A]">{value.replaceAll("_"," ")}</p></div>}
function formatDate(value:string|null|undefined){if(!value)return "-";const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat("en-IN").format(date)}
function formatDateTime(value:string|null|undefined){if(!value)return "-";const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(date)}