import type { ReactElement } from "react";
import { FileText, Phone, ShieldCheck, UserRound } from "lucide-react";
import { AppShell } from "@/components/shell";
import { PolicyIntakeDocumentButton } from "@/components/policy-intake-document-button";
import { PolicyIntakeHandoffButton } from "@/components/policy-intake-handoff-button";
import { PolicyIntakeResponseUpload } from "@/components/policy-intake-response-upload";
import { PolicyIntakeReviewActions } from "@/components/policy-intake-review-actions";
import { hasEffectiveCapability } from "@/lib/effective-permissions";
import { requirePolicyIntakeViewer } from "@/lib/policy-intake-server";
import { createSupabaseAdminClient } from "@/lib/supabase-admin";
import type { PolicyIntakeOcrField } from "@/app/policy-intakes/ocr-actions";

export const dynamic="force-dynamic";
type Intake={id:string;intake_number:string;status:string;lead_source_name:string;lead_source_type:string;lead_source_code:string|null;customer_mobile:string;matched_customer_id:string|null;file_name:string;ocr_status:string;ocr_fields:PolicyIntakeOcrField[];ocr_warnings:string[];attention_reason:string|null;created_at:string;submitted_by_profile_id:string;final_policy_id:string|null};
function statusLabel(row:Intake){if(row.status==="processing"&&row.ocr_status==="failed")return"Manual review required";return({processing:"Fetching policy & vehicle details",ready_for_review:"Ready for review",in_review:"In review",needs_attention:"Needs attention",completed:"Completed",rejected:"Rejected"}[row.status]??row.status);}

export default async function PolicyIntakeDetail({params}:{params:Promise<{id:string}>}){
  const{id}=await params;const profile=await requirePolicyIntakeViewer();const[reviewer,finalizer]=await Promise.all([hasEffectiveCapability(profile,"review_policy_intakes","edit"),hasEffectiveCapability(profile,"finalize_policy_intakes","approve")]);const admin=createSupabaseAdminClient();
  const{data}=await admin.from("policy_intake_requests").select("id,intake_number,status,lead_source_name,lead_source_type,lead_source_code,customer_mobile,matched_customer_id,file_name,ocr_status,ocr_fields,ocr_warnings,attention_reason,created_at,submitted_by_profile_id,final_policy_id").eq("id",id).maybeSingle<Intake>();
  if(!data)return <AppShell title="Policy Intake"><div className="rounded-2xl bg-white p-5 text-[11px]">Intake not found.</div></AppShell>;
  const owner=data.submitted_by_profile_id===profile.id;if(!reviewer&&!finalizer&&!owner)return <AppShell title="Policy Intake"><div className="rounded-2xl bg-white p-5 text-[11px]">You do not have access to this intake.</div></AppShell>;
  const manualReview=data.status==="processing"&&data.ocr_status==="failed";
  return <AppShell title={data.intake_number}><div className="mx-auto grid max-w-[1180px] gap-3 xl:grid-cols-[minmax(0,1fr)_320px]">
    <div className="space-y-3"><section className="rounded-2xl border border-[#DDE5EF] bg-white p-4 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[8px] font-bold uppercase tracking-[.1em] text-[#7A8798]">Policy intake</p><h1 className="mt-1 text-[15px] font-bold text-[#17365D]">{data.intake_number}</h1><p className="mt-1 text-[9px] text-[#667085]">Submitted {new Date(data.created_at).toLocaleString("en-IN")}</p></div><span className="max-w-[190px] rounded-full bg-[#EEF2FF] px-2.5 py-1 text-center text-[8px] font-bold text-[#4F46E5]">{statusLabel(data)}</span></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><Meta icon={<ShieldCheck/>} label="Lead source" value={`${data.lead_source_name}${data.lead_source_code?` · ${data.lead_source_code}`:""}`}/><Meta icon={<Phone/>} label="Customer" value={data.customer_mobile}/><Meta icon={<FileText/>} label="Policy copy" value={data.file_name}/></div>{data.attention_reason?<div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-[9px] text-amber-900">{data.attention_reason}</div>:null}</section>
      <section className="rounded-2xl border border-[#DDE5EF] bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[8px] font-bold uppercase tracking-[.1em] text-[#7A8798]">Fetched proposal</p><h2 className="mt-1 text-[12px] font-bold text-[#17365D]">Policy & vehicle details</h2></div><span className="text-[8px] font-semibold text-[#64748B]">{data.ocr_fields?.length??0} fields</span></div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(data.ocr_fields??[]).map(field=><div key={field.key} className="rounded-xl border border-[#E5EAF1] bg-[#FAFBFD] px-3 py-2.5"><p className="text-[7.5px] font-bold uppercase tracking-[.06em] text-[#8A96A8]">{field.label}</p><p className="mt-1 break-words text-[10px] font-semibold text-[#253B59]">{field.value||"—"}</p>{typeof field.confidence==="number"?<p className="mt-1 text-[7px] text-[#98A2B3]">{Math.round(field.confidence*100)}% confidence</p>:null}</div>)}</div>{data.status==="processing"&&data.ocr_status!=="failed"?<p className="mt-3 text-[9px] text-[#315B9A]">The request is safely saved. Policy and vehicle details are being fetched in the background.</p>:manualReview?<p className="mt-3 text-[9px] text-amber-800">Automatic detail fetching was unavailable. Operations can open the saved policy copy and complete the onboarding manually.</p>:!(data.ocr_fields??[]).length?<p className="mt-3 text-[9px] text-[#7A8798]">No structured details are available. Operations can use the saved policy copy for manual review.</p>:null}</section></div>
    <aside className="space-y-3"><PolicyIntakeDocumentButton id={data.id}/>{owner&&data.status==="needs_attention"?<PolicyIntakeResponseUpload id={data.id}/>:null}{reviewer&&!["completed","rejected"].includes(data.status)?<PolicyIntakeReviewActions id={data.id}/>:null}{finalizer&&(!["completed","rejected","needs_attention","processing"].includes(data.status)||manualReview)?<PolicyIntakeHandoffButton id={data.id}/>:null}<div className="rounded-2xl border border-[#E2E8F0] bg-white p-3 text-[9px] leading-4 text-[#667085]"><UserRound className="mb-2 h-4 w-4 text-[#315B9A]"/>The saved policy copy is the source document for this intake. Sales can view it immediately; Operations uses the same copy to review and finalize the policy.</div></aside>
  </div></AppShell>;
}
function Meta({icon,label,value}:{icon:ReactElement;label:string;value:string}){return <div className="flex items-center gap-2 rounded-xl bg-[#F7F9FC] px-3 py-2.5"><span className="text-[#315B9A] [&_svg]:h-4 [&_svg]:w-4">{icon}</span><span className="min-w-0"><span className="block text-[7px] font-bold uppercase tracking-[.07em] text-[#8A96A8]">{label}</span><span className="block truncate text-[9px] font-semibold text-[#344054]">{value}</span></span></div>}
