import Link from "next/link";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/shell";
import { FormSubmitButton } from "@/components/form-submit-button";
import { requirePospMispManager } from "@/lib/master-data-server";
import { loadPospMispAssociates } from "@/lib/posp-misp-associates";
import { decryptSensitiveValue } from "@/lib/sensitive-data";
import { createSupabaseAdminClient } from "@/lib/supabase-admin";
import { approvePospMispApplication } from "@/app/customers/applications/posp-misp-actions";
import { PospMispApplicationEditor, type PospMispEditProfile } from "@/app/customers/applications/posp-misp-application-editor";
import { PospMispWorkflowPanel, type PospMispWorkflowProfile } from "@/app/customers/applications/posp-misp-workflow-panel";

export const dynamic="force-dynamic";
export const revalidate=0;

type Application={id:string;requested_type:"posp"|"misp";final_type:"posp"|"misp"|"partner"|null;status:string;applicant_phone:string|null;applicant_email:string|null;updated_at:string};
type Document={id:string;document_type:string;file_name:string;storage_bucket:string;storage_path:string;verification_status:string};
type ProfileRow=PospMispWorkflowProfile&Omit<PospMispEditProfile,"aadhaar_number">&{aadhaar_number_encrypted:string|null;dp_aadhaar_number_encrypted:string|null;dp_aadhaar_last_four:string|null;dp_date_of_birth:string|null};

const errors:Record<string,string>={application_not_found:"The intermediary application could not be found.",posp_misp_profile_missing:"The intermediary profile could not be loaded.",posp_misp_edit_locked:"This application is read only.",posp_misp_edit_invalid:"Complete all required intermediary fields.",posp_misp_aadhaar_invalid:"Enter a valid 12-digit Aadhaar number.",posp_misp_edit_failed:"The intermediary details could not be saved.",posp_misp_document_invalid:"The selected document is invalid.",posp_misp_document_failed:"The document could not be saved.",posp_misp_marksheet_type_required:"Select the marksheet type.",intermediary_activation_failed:"The intermediary could not be activated.",application_not_ready:"Complete all onboarding stages before activation.",stage_locked:"This stage has already been completed.",documents_incomplete:"Upload at least one document before completing the document stage.",workflow_save_failed:"The workflow update could not be saved.",pan_verification_invalid:"Enter a valid PAN before starting the check.",pan_verification_queue_failed:"The PAN check could not be queued.",partner_decision_required:"Choose how to proceed with the existing IIB record.",partner_decision_failed:"The Partner decision could not be saved."};
const successes:Record<string,string>={posp_misp_submitted:"Intermediary application saved.",posp_misp_updated:"Intermediary details and documents were saved.",pan_verification_queued:"PAN verification queued.",pan_verification_requeued:"PAN verification queued again.",partner_route_selected:"Business Associate route selected.",application_closed:"Application closed.",documents_started:"Document stage opened.",documents_completed:"Documents completed.",ready_for_onboarding:"Application is ready for activation.",intermediary_activated:"Intermediary activated."};

export default async function IntermediaryApplicationPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;success?:string}>}){
 await requirePospMispManager();const {id}=await params;const query=await searchParams;const admin=createSupabaseAdminClient();
 const [{data:application},{data:profile},{data:documents}]=await Promise.all([
  admin.from("intermediary_onboarding_applications").select("id,requested_type,final_type,status,applicant_phone,applicant_email,updated_at").eq("id",id).maybeSingle<Application>(),
  admin.from("posp_misp_onboarding_profiles").select("partner_type,associate_employee_id,associate_profile_id,external_onboarding_id,document_received_at,pos_name,misp_name,applicant_phone,applicant_email,date_of_birth,aadhaar_last_four,aadhaar_number_encrypted,pan_number,gst_number,address,city,state,postal_code,bank_id,bank_account_number,bank_ifsc_code,oem_name,dp_name,dp_phone,dp_email,dp_pan_number,dp_date_of_birth,dp_aadhaar_last_four,dp_aadhaar_number_encrypted,workflow_stage,iib_remarks,iib_uploaded,iib_uploaded_at,training_login_id,training_credentials_shared_flag,training_start_date,training_end_date,training_status,training_certificate_number,exam_status,onboarding_date").eq("application_id",id).maybeSingle<ProfileRow>(),
  admin.from("intermediary_onboarding_documents").select("id,document_type,file_name,storage_bucket,storage_path,verification_status").eq("application_id",id).order("created_at").returns<Document[]>()
 ]);
 if(!application||!profile)notFound();
 const [associates,{data:banks},{data:oems}]=await Promise.all([
  loadPospMispAssociates(admin),
  admin.from("banks").select("id,name").eq("is_active",true).order("name").returns<Array<{id:string;name:string}>>(),
  admin.from("vehicle_manufacturers").select("name").eq("is_active",true).order("sort_order").order("name").returns<Array<{name:string}>>()
 ]);
 const aadhaarEncrypted=profile.partner_type==="misp"?profile.dp_aadhaar_number_encrypted:profile.aadhaar_number_encrypted;const aadhaarLastFour=profile.partner_type==="misp"?profile.dp_aadhaar_last_four:profile.aadhaar_last_four;const editProfile:PospMispEditProfile={...profile,date_of_birth:profile.partner_type==="misp"?profile.dp_date_of_birth:profile.date_of_birth,aadhaar_last_four:aadhaarLastFour,aadhaar_number:decryptSensitiveValue(aadhaarEncrypted)};
 const editable=["submitted","under_review","changes_requested"].includes(application.status);const ready=profile.workflow_stage==="completed"&&application.status!=="approved";const title=profile.partner_type==="misp"?(profile.misp_name??"MISP application"):(profile.pos_name??"POSP application");
 return <AppShell title="Review Intermediary Application"><div className="mx-auto max-w-[1280px] space-y-4 pb-8">
  <section className="overflow-hidden rounded-2xl border border-[#DCE5EF] bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4 bg-gradient-to-r from-[#071D49] via-[#0F2A55] to-[#163B70] px-5 py-5 text-white"><div><Link href="/customers/posp-misp" className="text-[9.5px] font-semibold text-white/70">← Back to applications</Link><h1 className="mt-2 text-xl font-semibold">{title}</h1><p className="mt-1 text-[10px] text-white/70">{profile.external_onboarding_id??`Ref ${id.slice(0,8).toUpperCase()}`}</p></div><div className="flex gap-2"><Pill>{profile.partner_type.toUpperCase()}</Pill><Pill>{application.status.replaceAll("_"," ")}</Pill><Pill>{documents?.length??0} Documents</Pill><Pill>{editable?"Editable":"Read only"}</Pill></div></div></section>
  {query.error?<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-[10.5px] font-medium text-red-700">{errors[query.error]??"The action could not be completed."}</div>:null}{query.success?<div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-[10.5px] font-medium text-emerald-700">{successes[query.success]??"Saved successfully."}</div>:null}
  <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_340px]"><main className="overflow-hidden rounded-2xl border border-[#DCE5EF] bg-white shadow-sm"><PospMispApplicationEditor applicationId={id} profile={editProfile} editable={editable} salesManagers={associates.map(item=>({value:item.id,label:`${item.full_name??"Unnamed"}${item.employee_code?` - ${item.employee_code}`:""}`}))} banks={(banks??[]).map(item=>({value:item.id,label:item.name}))} oems={(oems??[]).map(item=>({value:item.name,label:item.name}))} documents={(documents??[]).map(item=>({document_type:item.document_type,file_name:item.file_name}))}/></main><aside className="space-y-4"><PospMispWorkflowPanel applicationId={id} profile={profile}/><section className="rounded-2xl border border-[#DCE5EF] bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-[12px] font-semibold">Verification documents</h2><span className="text-[9px] text-[#64748B]">{documents?.length??0} files</span></div><div className="mt-3 space-y-2">{(documents??[]).map(document=><DocumentRow key={document.id} document={document}/>)}</div></section>{ready?<form action={approvePospMispApplication} className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 shadow-sm"><input type="hidden" name="application_id" value={id}/><p className="text-[11px] font-semibold text-emerald-900">Approve and activate</p><FormSubmitButton label="Activate intermediary" pendingLabel="Activating" className="mt-3 w-full rounded-lg bg-emerald-700 px-4 py-2.5 text-[10.5px] font-semibold text-white"/></form>:null}</aside></div>
 </div></AppShell>;
}
function Pill({children}:{children:React.ReactNode}){return <span className="rounded-full border border-white/25 bg-white/10 px-3 py-1 text-[9px] font-semibold capitalize text-white">{children}</span>}
async function DocumentRow({document}:{document:Document}){const admin=createSupabaseAdminClient();const {data}=await admin.storage.from(document.storage_bucket).createSignedUrl(document.storage_path,900);return <div className="flex items-center justify-between rounded-xl border border-[#E2E8F0] bg-[#FBFDFF] px-3 py-2.5"><div className="min-w-0"><p className="text-[10px] font-semibold capitalize">{document.document_type.replaceAll("_"," ")}</p><p className="truncate text-[8.5px] text-[#64748B]">{document.file_name}</p></div>{data?.signedUrl?<a href={data.signedUrl} target="_blank" rel="noreferrer" className="rounded-md border px-2 py-1 text-[9px] font-semibold">Open</a>:null}</div>}
