"use client";

import Link from "next/link";
import { createPortal } from "react-dom";
import { useEffect, useMemo, useState } from "react";
import { FormSubmitButton } from "@/components/form-submit-button";
import { IndianDateField } from "@/components/indian-date-field";
import { decidePospMispPartnerRoute } from "../../applications/posp-misp-workflow-actions";
import { DeleteImportRowButton } from "./delete-import-row-button";
import { deleteSelectedPospMispImportRows } from "./bulk-delete-actions";
import { updatePospMispImportRowV2 } from "./update-row-v2-actions";

type PartnerType="posp"|"misp";
type PanJob={status:string;result_message:string|null;last_error:string|null;checked_by_device:string|null};
type RouteProfile={requested_account_type:"posp"|"misp"|null;final_account_type:"posp"|"misp"|"partner"|null;partner_decision:string;iib_remarks:string|null};
type ImportRow={id:string;row_number:number;sheet_name:string;partner_type:PartnerType;source_data:Record<string,unknown>;normalized_data:Record<string,unknown>;validation_errors:string[]|null;status:string;application_id:string|null;error_message:string|null;documents:Array<{document_type:string;file_name:string}>;pan_job:PanJob|null;route_profile:RouteProfile|null};
type Props={batchId:string;batchStatus:string;rows:ImportRow[];salesManagers:Array<{id:string;fullName:string;employeeCode:string|null}>;oems:Array<{value:string;label:string}>;banks:Array<{value:string;label:string}>};
type Option={value:string;label:string};

const inputClass="h-11 w-full rounded-xl border border-[#CBD5E1] bg-white px-3 text-[12px] font-medium text-[#17203A] outline-none focus:border-[#635BFF] focus:ring-2 focus:ring-[#E7E5FF] disabled:bg-[#F8FAFC]";
const labelClass="mb-1.5 block text-[10px] font-semibold uppercase tracking-[0.04em] text-[#526178]";

export function ImportRowReviewTableV2({batchId,batchStatus,rows,salesManagers,oems,banks}:Props){
  const[editingRow,setEditingRow]=useState<ImportRow|null>(null);
  const[selected,setSelected]=useState<string[]>([]);
  const canEditBatch=["parsed","partially_submitted","failed"].includes(batchStatus);
  const selectableRows=useMemo(()=>rows.filter(row=>canEditBatch&&!["submitted","processing"].includes(row.status)),[rows,canEditBatch]);
  const allSelected=selectableRows.length>0&&selectableRows.every(row=>selected.includes(row.id));
  const toggleAll=()=>setSelected(allSelected?[]:selectableRows.map(row=>row.id));
  const toggleRow=(id:string)=>setSelected(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);

  return <>
    <div className="overflow-hidden rounded-2xl border border-white/80 bg-white/80 shadow-sm backdrop-blur">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#E2E8F0] bg-[#F8FAFC]/80 px-4 py-3">
        <div><h2 className="text-[12px] font-semibold text-[#0F172A]">Parsed workbook rows</h2><p className="mt-0.5 text-[9.5px] text-[#64748B]">IIB checking starts automatically after a valid row is submitted.</p></div>
        <div className="flex items-center gap-2">
          {selected.length?<form action={deleteSelectedPospMispImportRows} onSubmit={event=>{if(!window.confirm(`Delete ${selected.length} selected row${selected.length===1?"":"s"}?`))event.preventDefault()}}><input type="hidden" name="batch_id" value={batchId}/>{selected.map(id=><input key={id} type="hidden" name="row_ids" value={id}/>)}<FormSubmitButton label={`Delete Selected (${selected.length})`} pendingLabel="Deleting" className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-[9.5px] font-semibold text-red-700"/></form>:null}
          <span className="rounded-full border border-[#DCE5EF] bg-white px-2.5 py-1 text-[9px] font-semibold capitalize text-[#475569]">{batchStatus.replaceAll("_"," ")}</span>
        </div>
      </div>
      <div className="w-full overflow-x-auto">
        <table className="min-w-[1180px] w-full table-fixed text-left text-[10px]">
          <thead className="border-b border-[#E2E8F0] bg-white text-[8.5px] uppercase tracking-[0.04em] text-[#64748B]"><tr><th className="w-12 px-2 py-2.5 text-center"><input type="checkbox" checked={allSelected} onChange={toggleAll} disabled={!selectableRows.length}/></th><th className="w-16 px-2 py-2.5">Row</th><th className="w-[230px] px-2 py-2.5">Application</th><th className="w-[210px] px-2 py-2.5">Contact</th><th className="w-[150px] px-2 py-2.5">IIB Status</th><th className="w-[150px] px-2 py-2.5">Final Route</th><th className="px-2 py-2.5">Validation</th><th className="w-[150px] px-2 py-2.5">Import</th><th className="w-[130px] px-2 py-2.5 text-center">Actions</th></tr></thead>
          <tbody className="divide-y divide-[#EEF2F6]">{rows.map(row=>{const data=row.normalized_data??{};const name=stringValue(row.partner_type==="posp"?data.pos_name:data.misp_name);const onboardingId=stringValue(data.external_onboarding_id);const editable=canEditBatch&&!["submitted","processing"].includes(row.status);return <tr key={row.id} className={row.validation_errors?.length?"bg-red-50/30":"hover:bg-[#FAFCFF]"}><td className="px-2 py-3 text-center"><input type="checkbox" checked={selected.includes(row.id)} onChange={()=>toggleRow(row.id)} disabled={!editable}/></td><td className="px-2 py-3"><p className="font-semibold">{row.row_number}</p><p className="text-[8px] text-[#64748B]">{row.sheet_name}</p></td><td className="px-2 py-3"><div className="flex items-start gap-2"><span className={`rounded-full px-1.5 py-0.5 text-[7.5px] font-bold ${row.partner_type==="misp"?"bg-amber-50 text-amber-700":"bg-blue-50 text-blue-700"}`}>{row.partner_type.toUpperCase()}</span><div className="min-w-0"><p className="truncate font-semibold">{name??"Name missing"}</p><p className="truncate text-[8px]">ID: {onboardingId??"Not entered"}</p><p className="text-[8px] text-[#64748B]">{maskPan(stringValue(row.partner_type==="misp"?data.dp_pan_number:data.pan_number))}</p></div></div></td><td className="px-2 py-3"><p>{stringValue(data.applicant_phone)??"-"}</p><p className="truncate text-[8px] text-[#64748B]">{stringValue(data.applicant_email)??"Email not provided"}</p></td><td className="px-2 py-3"><IibStatus row={row}/></td><td className="px-2 py-3"><RouteStatus row={row}/></td><td className="px-2 py-3">{row.validation_errors?.length?<ul className="space-y-0.5">{row.validation_errors.slice(0,3).map((error,index)=><li key={index} className="text-[8.5px] font-medium leading-4 text-red-700">• {error}</li>)}</ul>:<span className="rounded-full bg-emerald-50 px-2 py-1 text-[8px] font-semibold text-emerald-700">Ready</span>}</td><td className="px-2 py-3"><RowStatus row={row}/></td><td className="px-2 py-3"><div className="flex justify-center gap-1.5">{row.application_id?<Link href={`/intermediaries/applications/${row.application_id}`} className="grid h-8 w-8 place-items-center rounded-lg border border-indigo-200 bg-indigo-50 text-indigo-700">↗</Link>:null}<button type="button" onClick={()=>setEditingRow(row)} className="grid h-8 w-8 place-items-center rounded-lg border border-[#CBD5E1] bg-white">✎</button>{editable?<DeleteImportRowButton batchId={batchId} rowId={row.id} rowNumber={row.row_number}/>:null}</div></td></tr>})}</tbody>
        </table>
      </div>
    </div>
    {editingRow?<FullScreenEditModal batchId={batchId} row={editingRow} editable={canEditBatch&&!["submitted","processing"].includes(editingRow.status)} salesManagers={salesManagers} oems={oems} banks={banks} onClose={()=>setEditingRow(null)}/>:null}
  </>;
}

function FullScreenEditModal({batchId,row,editable,salesManagers,oems,banks,onClose}:{batchId:string;row:ImportRow;editable:boolean;salesManagers:Props["salesManagers"];oems:Props["oems"];banks:Props["banks"];onClose:()=>void}){
  const[mounted,setMounted]=useState(false);
  const[saving,setSaving]=useState(false);
  const data=row.normalized_data??{};
  const isMisp=row.partner_type==="misp";
  useEffect(()=>{setMounted(true);const previous=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=previous}},[]);
  if(!mounted)return null;
  const selectedManagerId=stringValue(data.associate_employee_id)??stringValue(data.associate_profile_id)??"";
  const content=<div className="fixed inset-0 z-[99999] h-[100dvh] w-screen overflow-hidden bg-[#F4F7FB]" role="dialog" aria-modal="true">
    <form action={updatePospMispImportRowV2} onSubmit={()=>setSaving(true)} className="flex h-full min-h-0 flex-col">
      <input type="hidden" name="batch_id" value={batchId}/><input type="hidden" name="row_id" value={row.id}/>
      <header className="flex shrink-0 items-center justify-between border-b border-[#DCE5EF] bg-white px-5 py-4 shadow-sm"><div><p className="text-[9px] font-semibold uppercase tracking-[.1em] text-[#64748B]">Bulk onboarding · Primary information</p><h3 className="mt-1 text-xl font-semibold text-[#071D49]">{isMisp?"MISP":"POSP"} row {row.row_number}</h3></div><button type="button" onClick={onClose} disabled={saving} className="grid h-10 w-10 place-items-center rounded-xl border border-[#CBD5E1] bg-white text-xl disabled:opacity-50">×</button></header>
      <main className="min-h-0 flex-1 overflow-y-auto overscroll-contain p-4 md:p-6">
        <div className="mx-auto max-w-[1500px] space-y-5 pb-8">
          <Section title="Primary information"><SelectField label="Associate" name="associate_employee_id" defaultValue={selectedManagerId} required disabled={!editable||saving} options={salesManagers.map(item=>({value:item.id,label:`${item.fullName}${item.employeeCode?` - ${item.employeeCode}`:""}`}))}/><Field label={isMisp?"MISP ID":"POSP ID"} name="external_onboarding_id" defaultValue={stringValue(data.external_onboarding_id)??""} required disabled={!editable||saving}/>{isMisp?<Field label="MISP Name" name="misp_name" defaultValue={stringValue(data.misp_name)??""} required disabled={!editable||saving}/>:null}<Field label={isMisp?"MISP PAN":"PAN Number"} name="pan_number" defaultValue={stringValue(data.pan_number)??""} required disabled={!editable||saving}/><DateField label="Document Received Date" name="document_received_at" defaultValue={stringValue(data.document_received_at)??""} disabled={!editable||saving}/></Section>
          {!isMisp?<Section title="POSP identity"><Field label="POS First Name" name="pos_first_name" defaultValue={stringValue(data.pos_first_name)??firstFromLegacy(stringValue(data.pos_name))} required disabled={!editable||saving}/><Field label="POS Middle Name" name="pos_middle_name" defaultValue={stringValue(data.pos_middle_name)??middleFromLegacy(stringValue(data.pos_name))} disabled={!editable||saving}/><Field label="POS Last Name" name="pos_last_name" defaultValue={stringValue(data.pos_last_name)??lastFromLegacy(stringValue(data.pos_name))} required disabled={!editable||saving}/></Section>:<Section title="Designated Person"><Field label="DP First Name" name="dp_first_name" defaultValue={stringValue(data.dp_first_name)??firstFromLegacy(stringValue(data.dp_name))} required disabled={!editable||saving}/><Field label="DP Middle Name" name="dp_middle_name" defaultValue={stringValue(data.dp_middle_name)??middleFromLegacy(stringValue(data.dp_name))} disabled={!editable||saving}/><Field label="DP Last Name" name="dp_last_name" defaultValue={stringValue(data.dp_last_name)??lastFromLegacy(stringValue(data.dp_name))} required disabled={!editable||saving}/><Field label="DP PAN" name="dp_pan_number" defaultValue={stringValue(data.dp_pan_number)??""} required disabled={!editable||saving}/><Field label="DP Mobile" name="dp_phone" defaultValue={stringValue(data.dp_phone)??stringValue(data.applicant_phone)??""} required disabled={!editable||saving}/><Field label="DP Email" name="dp_email" type="email" defaultValue={stringValue(data.dp_email)??stringValue(data.applicant_email)??""} required disabled={!editable||saving}/><DateField label="DP Date of Birth" name="dp_date_of_birth" defaultValue={stringValue(data.dp_date_of_birth)??stringValue(data.date_of_birth)??""} required disabled={!editable||saving}/><Field label="DP Aadhaar Number" name="aadhaar_number" defaultValue={stringValue(data.aadhaar_number)??""} required disabled={!editable||saving}/></Section>}
          {!isMisp?<Section title="Contact and identity"><Field label="Mobile Number" name="applicant_phone" defaultValue={stringValue(data.applicant_phone)??""} required disabled={!editable||saving}/><Field label="Email" name="applicant_email" type="email" defaultValue={stringValue(data.applicant_email)??""} required disabled={!editable||saving}/><DateField label="Date of Birth" name="date_of_birth" defaultValue={stringValue(data.date_of_birth)??""} required disabled={!editable||saving}/><Field label="Aadhaar Number" name="aadhaar_number" defaultValue={stringValue(data.aadhaar_number)??""} required disabled={!editable||saving}/></Section>:null}
          <Section title={isMisp?"Company address":"Address"}><Field label="Address" name="address" defaultValue={stringValue(data.address)??""} required disabled={!editable||saving} span="md:col-span-2"/><Field label="City" name="city" defaultValue={stringValue(data.city)??""} required disabled={!editable||saving}/><Field label="State" name="state" defaultValue={stringValue(data.state)??""} required disabled={!editable||saving}/><Field label="PIN Code" name="postal_code" defaultValue={stringValue(data.postal_code)??""} required disabled={!editable||saving}/>{isMisp?<SelectField label="OEM Name" name="oem_name" defaultValue={stringValue(data.oem_name)??""} required disabled={!editable||saving} options={oems}/>:null}<Field label="GST Number" name="gst_number" defaultValue={stringValue(data.gst_number)??""} disabled={!editable||saving}/></Section>
          <Section title="Bank particulars"><SelectField label="Bank Name" name="bank_id" defaultValue={stringValue(data.bank_id)??""} required disabled={!editable||saving} options={banks}/><Field label="Account Number" name="bank_account_number" defaultValue={unmask(stringValue(data.bank_account_number))} required disabled={!editable||saving}/><Field label="IFSC Code" name="bank_ifsc_code" defaultValue={stringValue(data.bank_ifsc_code)??""} required disabled={!editable||saving}/></Section>
        </div>
      </main>
      <footer className="flex shrink-0 items-center justify-end gap-3 border-t border-[#DCE5EF] bg-white px-5 py-4 shadow-[0_-8px_24px_rgba(15,23,42,.06)]"><button type="button" onClick={onClose} disabled={saving} className="rounded-xl border border-[#CBD5E1] bg-white px-5 py-2.5 text-[11px] font-semibold text-[#334155] disabled:opacity-50">Cancel</button>{editable?<FormSubmitButton label="Save and revalidate" pendingLabel="Saving and revalidating" className="rounded-xl bg-gradient-to-r from-[#635BFF] to-[#4285F4] px-5 py-2.5 text-[11px] font-semibold text-white disabled:opacity-60"/>:null}</footer>
    </form>
  </div>;
  return createPortal(content,document.body);
}

function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="overflow-hidden rounded-2xl border border-[#DCE5EF] bg-white shadow-sm"><div className="border-b border-[#DCE5EF] bg-[#F8FAFC] px-4 py-3 text-[12px] font-semibold text-[#132746]">{title}</div><div className="grid gap-4 p-4 sm:grid-cols-2 xl:grid-cols-4">{children}</div></section>}
function Field({label,name,defaultValue="",required=false,disabled=false,type="text",span=""}:{label:string;name:string;defaultValue?:string;required?:boolean;disabled?:boolean;type?:string;span?:string}){return <label className={span}><span className={labelClass}>{label}{required?" *":""}</span><input className={inputClass} name={name} defaultValue={defaultValue} required={required} disabled={disabled} type={type}/></label>}
function SelectField({label,name,defaultValue,options,required=false,disabled=false}:{label:string;name:string;defaultValue:string;options:Option[];required?:boolean;disabled?:boolean}){return <label><span className={labelClass}>{label}{required?" *":""}</span><select className={inputClass} name={name} defaultValue={defaultValue} required={required} disabled={disabled}><option value="">Select</option>{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>}
function DateField({label,name,defaultValue,required=false,disabled=false}:{label:string;name:string;defaultValue:string;required?:boolean;disabled?:boolean}){return <div><span className={labelClass}>{label}{required?" *":""}</span><IndianDateField name={name} defaultValue={defaultValue} required={required} disabled={disabled} inputClassName={inputClass}/></div>}
function IibStatus({row}:{row:ImportRow}){if(!row.application_id)return <span className="rounded-full bg-slate-100 px-2 py-1 text-[8px] font-semibold text-slate-600">Starts after submission</span>;const status=row.pan_job?.status??"pending";const styles=status==="not_found"?"bg-emerald-50 text-emerald-700":status==="matched"?"bg-amber-50 text-amber-800":status==="failed"||status==="invalid"?"bg-red-50 text-red-700":"bg-blue-50 text-blue-700";return <div><span className={`rounded-full px-2 py-1 text-[8px] font-semibold ${styles}`}>{status.replaceAll("_"," ")}</span>{row.pan_job?.checked_by_device?<p className="mt-1 text-[7.5px] text-[#64748B]">{row.pan_job.checked_by_device}</p>:null}</div>}
function RouteStatus({row}:{row:ImportRow}){const profile=row.route_profile;if(!row.application_id)return <span className="text-[8px] text-[#94A3B8]">Pending</span>;if(row.pan_job?.status==="matched"&&profile?.partner_decision==="pending")return <div className="space-y-1"><form action={decidePospMispPartnerRoute}><input type="hidden" name="application_id" value={row.application_id}/><input type="hidden" name="partner_decision" value="convert_to_partner"/><FormSubmitButton label="Partner" pendingLabel="Converting" className="w-full rounded-md bg-[#635BFF] px-2 py-1 text-[8px] font-semibold text-white"/></form><form action={decidePospMispPartnerRoute}><input type="hidden" name="application_id" value={row.application_id}/><input type="hidden" name="partner_decision" value="do_not_proceed"/><FormSubmitButton label="Close" pendingLabel="Closing" className="w-full rounded-md border border-red-200 bg-red-50 px-2 py-1 text-[8px] font-semibold text-red-700"/></form></div>;if(profile?.final_account_type)return <span className="rounded-full bg-emerald-50 px-2 py-1 text-[8px] font-semibold text-emerald-700">{profile.final_account_type}</span>;return <span className="text-[8px] text-[#64748B]">Awaiting IIB</span>}
function RowStatus({row}:{row:ImportRow}){const style=row.status==="submitted"?"bg-emerald-50 text-emerald-700":row.status==="failed"?"bg-red-50 text-red-700":row.status==="invalid"?"bg-amber-50 text-amber-700":"bg-blue-50 text-blue-700";return <div><span className={`rounded-full px-2 py-1 text-[8px] font-semibold capitalize ${style}`}>{row.status.replaceAll("_"," ")}</span>{row.error_message?<p className="mt-1 text-[8px] leading-4 text-red-700">{row.error_message}</p>:null}</div>}
function stringValue(value:unknown){return typeof value==="string"&&value.trim()?value.trim():null}
function legacyParts(value:string|null){return(value??"").split(/\s+/).filter(Boolean)}
function firstFromLegacy(value:string|null){return legacyParts(value)[0]??""}
function middleFromLegacy(value:string|null){const parts=legacyParts(value);return parts.length>2?parts.slice(1,-1).join(" "):""}
function lastFromLegacy(value:string|null){const parts=legacyParts(value);return parts.length>1?parts.at(-1)??"":""}
function maskPan(value:string|null){return value&&value.length===10?`${value.slice(0,2)}***${value.slice(5,8)}${value.slice(-1)}`:"—"}
function unmask(value:string|null){return value?.includes("•")?"":value??""}
