"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { deletePospMispImportRow, updatePospMispImportRow } from "../actions";
import { FormSubmitButton } from "@/components/form-submit-button";
import { IndianDateField } from "@/components/indian-date-field";

type PartnerType = "posp" | "misp";
type ImportRow = { id:string; row_number:number; sheet_name:string; partner_type:PartnerType; source_data:Record<string,unknown>; normalized_data:Record<string,unknown>; validation_errors:string[]|null; status:string; application_id:string|null; error_message:string|null; documents:Array<{document_type:string;file_name:string}> };
type Props = { batchId:string; batchStatus:string; rows:ImportRow[]; salesManagers:Array<{id:string;fullName:string;employeeCode:string|null}>; oems:Array<{value:string;label:string}>; banks:Array<{value:string;label:string}> };

const inputClass="h-10 w-full rounded-lg border border-[#CBD5E1] bg-white px-3 text-[11px] font-medium text-[#17203A] outline-none focus:border-[#1D4ED8] focus:ring-2 focus:ring-[#DBEAFE] disabled:bg-[#F8FAFC]";
const labelClass="mb-1.5 block text-[9.5px] font-semibold uppercase tracking-[0.04em] text-[#526178]";
const trackedFields=["associate_name","associate_id","external_onboarding_id","pos_name","misp_name","applicant_phone","applicant_email","pan_number","gst_number","city","state","postal_code","bank_name","bank_account_number","bank_ifsc_code","oem_name","dp_name","dp_phone"];
const marksheetOptions=[{value:"education_10th_marksheet",label:"10th Marksheet"},{value:"education_12th_marksheet",label:"12th Marksheet"},{value:"education_graduation_marksheet",label:"Graduation Marksheet"},{value:"education_post_graduation_marksheet",label:"Post Graduation Marksheet"}];
const documentFields=[...["aadhaar_front","aadhaar_back","pan_copy","cancelled_cheque","photograph","gst_copy"].map(value=>({value,label:value.replaceAll("_"," ")})),{value:"agreement_copy",label:"Agreement copy"}];

export function ImportRowReviewTable({batchId,batchStatus,rows,salesManagers,oems,banks}:Props){
  const [editingRow,setEditingRow]=useState<ImportRow|null>(null);
  const canEditBatch=["parsed","partially_submitted","failed"].includes(batchStatus);
  const summary=useMemo(()=>rows.reduce((result,row)=>{const key=row.validation_errors?.length?"needs_attention":row.status==="submitted"?"submitted":row.status==="failed"?"failed":"ready";result[key]=(result[key]??0)+1;return result;},{} as Record<string,number>),[rows]);
  return <>
    <div className="mb-3 grid gap-2 sm:grid-cols-4"><SummaryCard label="Total rows" value={rows.length}/><SummaryCard label="Ready" value={summary.ready??0} tone="ready"/><SummaryCard label="Needs attention" value={summary.needs_attention??0} tone="warning"/><SummaryCard label="Submitted" value={summary.submitted??0} tone="complete"/></div>
    <div className="overflow-hidden rounded-2xl border border-[#E2E8F0] bg-white shadow-sm">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#E2E8F0] bg-[#F8FAFC] px-4 py-3"><div><h2 className="text-[12px] font-semibold text-[#0F172A]">Parsed workbook rows</h2><p className="mt-0.5 text-[9.5px] text-[#64748B]">Corrected values are marked so reviewers can distinguish them from the original workbook.</p></div><span className="rounded-full border border-[#DCE5EF] bg-white px-2.5 py-1 text-[9px] font-semibold text-[#475569]">Batch {batchStatus.replaceAll("_"," ")}</span></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[1240px] text-left text-[11px]"><thead className="border-b border-[#E2E8F0] bg-white text-[9px] uppercase tracking-[0.06em] text-[#64748B]"><tr><th className="px-4 py-3">Row</th><th className="px-3 py-3">Application</th><th className="px-3 py-3">Contact</th><th className="px-3 py-3">Documents</th><th className="px-3 py-3">Corrections</th><th className="px-3 py-3">Validation</th><th className="px-3 py-3">Row status</th><th className="px-4 py-3 text-right">Actions</th></tr></thead>
      <tbody className="divide-y divide-[#EEF2F6]">{rows.map(row=>{const data=row.normalized_data??{};const name=stringValue(row.partner_type==="posp"?data.pos_name:data.misp_name);const editable=canEditBatch&&!["submitted","processing"].includes(row.status);const corrections=correctedFields(row);return <tr key={row.id} className={row.validation_errors?.length?"bg-red-50/30 hover:bg-red-50/55":"hover:bg-[#FAFCFF]"}>
        <td className="px-4 py-3"><p className="font-semibold tabular-nums text-[#0F172A]">{row.row_number}</p><p className="mt-0.5 text-[9px] text-[#64748B]">{row.sheet_name}</p></td>
        <td className="px-3 py-3"><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-0.5 text-[8.5px] font-bold ${row.partner_type==="misp"?"bg-[#FFF7D6] text-[#8A6500]":"bg-[#E8F0FF] text-[#174EA6]"}`}>{row.partner_type.toUpperCase()}</span><div><p className="font-semibold text-[#0F172A]">{name??"Name missing"}</p><p className="text-[9px] text-[#64748B]">{stringValue(data.external_onboarding_id)??"ID pending"}</p></div></div></td>
        <td className="px-3 py-3"><p className="tabular-nums text-[#0F172A]">{stringValue(data.applicant_phone)??"-"}</p><p className="mt-0.5 max-w-[180px] truncate text-[9px] text-[#64748B]">{stringValue(data.applicant_email)??"Email not provided"}</p></td>
        <td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-[9px] font-semibold ${row.documents.length?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{row.documents.length} attached</span></td>
        <td className="px-3 py-3">{corrections.length?<div className="flex flex-wrap gap-1">{corrections.slice(0,3).map(field=><span key={field} title={field.replaceAll("_"," ")} className="rounded-full border border-blue-200 bg-blue-50 px-2 py-0.5 text-[8.5px] font-semibold text-blue-700">Corrected</span>)}{corrections.length>3?<span className="text-[9px] font-semibold text-blue-700">+{corrections.length-3}</span>:null}</div>:<span className="text-[9.5px] text-[#94A3B8]">Original import</span>}</td>
        <td className="max-w-[320px] px-3 py-3">{row.validation_errors?.length?<ul className="space-y-1">{row.validation_errors.slice(0,2).map((error,index)=><li key={index} className="text-[9.5px] font-medium text-red-700">• {error}</li>)}{row.validation_errors.length>2?<li className="text-[9px] font-semibold text-red-600">+{row.validation_errors.length-2} more</li>:null}</ul>:<span className="inline-flex rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-semibold text-emerald-700">Ready to submit</span>}</td>
        <td className="px-3 py-3"><RowStatus row={row}/></td>
        <td className="px-4 py-3"><div className="flex justify-end gap-2">{row.application_id?<Link href={`/customers/applications/${row.application_id}`} className="rounded-md border border-indigo-200 bg-indigo-50 px-2.5 py-1 text-[9.5px] font-semibold text-indigo-700">Open file</Link>:null}<button type="button" onClick={()=>setEditingRow(row)} className="rounded-md border border-[#CBD5E1] px-2.5 py-1 text-[9.5px] font-semibold text-[#334155]">{editable?"Review / correct":"View"}</button>{editable?<form action={deletePospMispImportRow} onSubmit={event=>{if(!window.confirm(`Remove row ${row.row_number} from this import batch?`))event.preventDefault();}}><input type="hidden" name="batch_id" value={batchId}/><input type="hidden" name="row_id" value={row.id}/><FormSubmitButton label="Remove" pendingLabel="Removing row" className="inline-flex items-center justify-center rounded-md border border-red-200 bg-red-50 px-2.5 py-1 text-[9.5px] font-semibold text-red-700 disabled:opacity-70"/></form>:null}</div></td>
      </tr>})}</tbody></table></div>
    </div>
    {editingRow?<EditRowModal batchId={batchId} row={editingRow} editable={canEditBatch&&!["submitted","processing"].includes(editingRow.status)} salesManagers={salesManagers} oems={oems} banks={banks} onClose={()=>setEditingRow(null)}/>:null}
  </>;
}

function EditRowModal({batchId,row,editable,salesManagers,oems,banks,onClose}:{batchId:string;row:ImportRow;editable:boolean;salesManagers:Props["salesManagers"];oems:Props["oems"];banks:Props["banks"];onClose:()=>void}){
  const data=row.normalized_data??{};const isMisp=row.partner_type==="misp";const selectedManagerId=stringValue(data.associate_employee_id)??stringValue(data.associate_profile_id)??"";const corrections=correctedFields(row);const currentMarksheet=row.documents.find(document=>document.document_type.startsWith("education_"));
  return <div className="fixed inset-0 z-[130] flex items-start justify-center overflow-y-auto bg-[#0F172A]/45 px-4 py-8 backdrop-blur-[2px]" role="dialog" aria-modal="true"><div className="w-full max-w-[1160px] overflow-hidden rounded-2xl border border-white/60 bg-[#F4F7FB] shadow-[0_28px_80px_rgba(15,23,42,0.28)]">
    <div className="flex items-start justify-between gap-4 border-b border-[#DCE5EF] bg-white px-5 py-4"><div><p className="text-[9.5px] font-semibold uppercase tracking-[0.1em] text-[#64748B]">{row.sheet_name} · row {row.row_number}</p><h3 className="mt-1 text-lg font-semibold text-[#071D49]">{editable?"Review and correct imported file":"Imported file details"}</h3><div className="mt-2 flex flex-wrap gap-2"><RowStatus row={row}/>{corrections.length?<span className="rounded-full bg-blue-50 px-2 py-1 text-[9px] font-semibold text-blue-700">{corrections.length} corrected fields</span>:null}</div></div><button type="button" onClick={onClose} className="grid h-8 w-8 place-items-center rounded-lg border border-[#CBD5E1] text-[#64748B]">×</button></div>
    <form action={updatePospMispImportRow}><input type="hidden" name="batch_id" value={batchId}/><input type="hidden" name="row_id" value={row.id}/><input type="hidden" name="partner_type" value={row.partner_type}/>
      <div className="space-y-4 p-4">
        <Section title={isMisp?"MISP business particulars":"POSP particulars"}><SelectField label="Associate Name" name="associate_employee_id" defaultValue={selectedManagerId} required disabled={!editable} options={salesManagers.map(manager=>({value:manager.id,label:`${manager.fullName}${manager.employeeCode?` - ${manager.employeeCode}`:""}`}))} placeholder="Select Sales employee"/><Field label={isMisp?"MISP ID":"Onboarding ID"} name="external_onboarding_id" defaultValue={stringValue(data.external_onboarding_id)??""} disabled={!editable}/><IndianDateField label="Document Received Date" name="document_received_at" defaultValue={stringValue(data.document_received_at)} disabled={!editable}/>{isMisp?<Field label="MISP Name" name="misp_name" required defaultValue={stringValue(data.misp_name)??""} disabled={!editable}/>:<Field label="POS Name" name="pos_name" required defaultValue={stringValue(data.pos_name)??""} disabled={!editable}/>}<Field label="PAN Number" name="pan_number" maxLength={10} defaultValue={stringValue(data.pan_number)??""} disabled={!editable}/>{isMisp?<SelectField label="OEM Name" name="oem_name" required defaultValue={stringValue(data.oem_name)??""} disabled={!editable} options={oems} placeholder="Select OEM"/>:null}<Field label="GST Number" name="gst_number" maxLength={15} defaultValue={stringValue(data.gst_number)??""} disabled={!editable}/></Section>
        <Section title="Identity and contact"><Field label="Mobile Number" name="applicant_phone" required inputMode="tel" defaultValue={stringValue(data.applicant_phone)??""} disabled={!editable}/><Field label="Email" name="applicant_email" type="email" defaultValue={stringValue(data.applicant_email)??""} disabled={!editable}/><IndianDateField label="Date of Birth" name="date_of_birth" defaultValue={stringValue(data.date_of_birth)} disabled={!editable}/><Field label="Aadhaar Number" name="aadhaar_number" inputMode="numeric" maxLength={12} defaultValue={stringValue(data.aadhaar_number)??""} disabled={!editable}/><Field label="Address" name="address" defaultValue={stringValue(data.address)??""} disabled={!editable}/><Field label="City" name="city" defaultValue={stringValue(data.city)??""} disabled={!editable}/><Field label="State" name="state" defaultValue={stringValue(data.state)??""} disabled={!editable}/><Field label="PIN Code" name="postal_code" inputMode="numeric" defaultValue={stringValue(data.postal_code)??""} disabled={!editable}/></Section>
        {isMisp?<Section title="Designated person"><Field label="DP Name" name="dp_name" required defaultValue={stringValue(data.dp_name)??""} disabled={!editable}/><Field label="DP Mobile" name="dp_phone" required inputMode="tel" defaultValue={stringValue(data.dp_phone)??""} disabled={!editable}/><Field label="DP Email" name="dp_email" type="email" defaultValue={stringValue(data.dp_email)??""} disabled={!editable}/><Field label="DP PAN" name="dp_pan_number" maxLength={10} defaultValue={stringValue(data.dp_pan_number)??""} disabled={!editable}/></Section>:null}
        <Section title="Bank particulars"><SelectField label="Bank Name" name="bank_id" required defaultValue={stringValue(data.bank_id)??""} disabled={!editable} options={banks} placeholder="Select bank"/><Field label="Account Number" name="bank_account_number" defaultValue={stringValue(data.bank_account_number)??""} disabled={!editable}/><Field label="IFSC Code" name="bank_ifsc_code" defaultValue={stringValue(data.bank_ifsc_code)??""} disabled={!editable}/></Section>
        <section className="overflow-hidden rounded-2xl border border-[#DCE5EF] bg-white"><div className="border-b border-[#E2E8F0] bg-[#F8FAFC] px-4 py-3"><h4 className="text-[12px] font-semibold text-[#0F172A]">Verification documents</h4><p className="mt-0.5 text-[9.5px] text-[#64748B]">Existing files remain attached. Select a file only to add or replace it.</p></div><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3"><DocumentBox label="Marksheet" current={currentMarksheet?.file_name}>{<><SelectField label="Marksheet type" name="education_document_type" defaultValue={currentMarksheet?.document_type??""} disabled={!editable} options={marksheetOptions} placeholder="Select marksheet type"/>{editable?<input name="education_marksheet" type="file" className="mt-2 block w-full text-[9px]"/>:null}</>}</DocumentBox>{documentFields.map(document=>{const current=row.documents.find(item=>item.document_type===document.value);return <DocumentBox key={document.value} label={document.label} current={current?.file_name}>{editable?<input name={document.value} type="file" className="mt-2 block w-full text-[9px]"/>:null}</DocumentBox>})}</div></section>
      </div>
      <div className="sticky bottom-0 flex items-center justify-end gap-2 border-t border-[#DCE5EF] bg-white/95 px-5 py-3 backdrop-blur"><button type="button" onClick={onClose} className="rounded-lg border border-[#CBD5E1] px-4 py-2 text-[10.5px] font-semibold text-[#334155]">Close</button>{editable?<FormSubmitButton label="Save row corrections" pendingLabel="Saving row corrections"/>:null}</div>
    </form>
  </div></div>;
}

function SummaryCard({label,value,tone}:{label:string;value:number;tone?:"ready"|"warning"|"complete"}){const color=tone==="warning"?"text-red-700":tone==="complete"||tone==="ready"?"text-emerald-700":"text-[#071D49]";return <div className="rounded-xl border border-[#E2E8F0] bg-white px-4 py-3"><p className="text-[9px] font-semibold uppercase tracking-[0.06em] text-[#64748B]">{label}</p><p className={`mt-1 text-xl font-semibold ${color}`}>{value}</p></div>}
function RowStatus({row}:{row:ImportRow}){const label=row.status==="failed"?(row.error_message?.match(/Reference ([A-Za-z0-9-]+)/)?.[1]?`Failed · ref ${row.error_message.match(/Reference ([A-Za-z0-9-]+)/)?.[1]}`:"Failed · review"):row.status.replaceAll("_"," ");const style=row.status==="submitted"?"bg-emerald-50 text-emerald-700":row.status==="failed"?"bg-red-50 text-red-700":row.status==="processing"?"bg-blue-50 text-blue-700":"bg-amber-50 text-amber-700";return <span className={`inline-flex rounded-full px-2 py-1 text-[9px] font-semibold capitalize ${style}`}>{label}</span>}
function correctedFields(row:ImportRow){return trackedFields.filter(field=>normalizeCompare(row.source_data[field])!==normalizeCompare(row.normalized_data[field])&&normalizeCompare(row.normalized_data[field])!=="")}
function normalizeCompare(value:unknown){return typeof value==="string"?value.trim().toLowerCase():value==null?"":String(value).trim().toLowerCase()}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="overflow-hidden rounded-2xl border border-[#DCE5EF] bg-white"><div className="border-b border-[#E2E8F0] bg-[#F8FAFC] px-4 py-3"><h4 className="text-[12px] font-semibold text-[#0F172A]">{title}</h4></div><div className="grid gap-4 p-4 md:grid-cols-2 xl:grid-cols-4">{children}</div></section>}
function DocumentBox({label,current,children}:{label:string;current?:string;children:React.ReactNode}){return <div className={`rounded-xl border p-3 ${current?"border-emerald-200 bg-emerald-50/35":"border-amber-200 bg-amber-50/30"}`}><div className="flex items-center justify-between gap-2"><span className="text-[10px] font-semibold capitalize text-[#0F172A]">{label}</span><span className={`rounded-full px-2 py-0.5 text-[8px] font-semibold ${current?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}>{current?"Received":"Pending"}</span></div><p className="mt-1 truncate text-[9px] text-[#64748B]">{current??"No file attached"}</p><div className="mt-2">{children}</div></div>}
function Field({label,name,required=false,disabled=false,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string;name:string}){return <div><label className={labelClass} htmlFor={`${name}-${label}`}>{label}{required?" *":""}</label><input id={`${name}-${label}`} name={name} required={required} disabled={disabled} className={inputClass} {...props}/></div>}
function SelectField({label,name,required=false,options,placeholder,disabled=false,...props}:React.SelectHTMLAttributes<HTMLSelectElement>&{label:string;name:string;options:Array<{value:string;label:string}>;placeholder:string}){return <div><label className={labelClass} htmlFor={`${name}-${label}`}>{label}{required?" *":""}</label><select id={`${name}-${label}`} name={name} required={required} disabled={disabled} className={inputClass} {...props}><option value="">{placeholder}</option>{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></div>}
function stringValue(value:unknown){return typeof value==="string"&&value.trim()?value.trim():null}
