import Link from "next/link";
import { Download, ExternalLink, Filter } from "lucide-react";
import { AppShell } from "@/components/shell";
import { requireCapability } from "@/lib/master-data-server";
import { loadRenewalReport, type RenewalBucket, type RenewalFilters, type RenewalQuery, type RenewalReport } from "@/lib/reports/renewals";

export const dynamic = "force-dynamic";
export const revalidate = 0;

const HORIZONS = [{days:30,label:"30 days"},{days:60,label:"60 days"},{days:90,label:"90 days"},{days:180,label:"180 days"},{days:365,label:"365 days"}] as const;
type Props={searchParams:Promise<RenewalQuery>};

export default async function RenewalReportsPage({searchParams}:Props){
  const profile=await requireCapability("view_reports");
  const query=await searchParams;
  let payload:Awaited<ReturnType<typeof loadRenewalReport>>|null=null; let loadError=false;
  try{payload=await loadRenewalReport(profile,query)}catch(error){console.error("[reports] renewal report failed",error instanceof Error?error.message:"unknown error");loadError=true}
  const report=payload?.report??emptyReport(); const filters=payload?.filters??fallbackFilters();
  const pages=Math.max(1,Math.ceil(report.register.total_count/Math.max(report.register.page_size,1)));
  const exportHref=href("/reports/export/renewals",filters,undefined);
  return <AppShell title="Reports"><div className="mx-auto max-w-[1560px] space-y-4 pb-8">
    <header className="portal-card overflow-hidden">
      <div className="border-b border-[#e8ecf2] px-5 py-5 sm:px-6"><h1 className="text-[26px] font-semibold tracking-[-0.025em] text-[#13203b] sm:text-[30px]">Renewal pipeline</h1><ReportTabs/></div>
      <div className="px-5 py-4 sm:px-6">
        <div className="flex flex-wrap gap-2">{HORIZONS.map(x=><Link key={x.days} href={`/reports/renewals?horizon=${x.days}`} className={`rounded-lg border px-3 py-2 text-[10px] font-bold transition ${filters.horizonDays===x.days?"border-[#223a78] bg-[#223a78] text-white":"border-[#dfe5ee] bg-white text-[#506077] hover:border-[#bfc9db]"}`}>{x.label}</Link>)}</div>
        <form action="/reports/renewals" method="get" className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-[120px_minmax(190px,1fr)_minmax(170px,1fr)_minmax(190px,1fr)_160px_auto_auto]">
          <input type="hidden" name="horizon" value={filters.horizonDays}/>
          <Field label="Insurance company"><select name="insurer" defaultValue={filters.insurerId??""} className={inputClass}><option value="">All insurers</option>{report.filters.insurers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>
          <Field label="Relationship manager"><select name="rm" defaultValue={filters.rmName??""} className={inputClass}><option value="">All RMs</option>{report.filters.rms.map(x=><option key={x} value={x}>{x}</option>)}</select></Field>
          <Field label="Partner / intermediary"><select name="intermediary" defaultValue={filters.intermediaryCode??""} className={inputClass}><option value="">All intermediaries</option>{report.filters.intermediaries.map(x=><option key={x.code} value={x.code}>{x.name}{x.name!==x.code?` · ${x.code}`:""}</option>)}</select></Field>
          <Field label="Expiry bucket"><select name="bucket" defaultValue={filters.bucket??""} className={inputClass}><option value="">All buckets</option>{bucketOptions().map(x=><option key={x.key} value={x.key}>{x.label}</option>)}</select></Field>
          <button className="mt-auto inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-[#172a5c] px-4 text-[10.5px] font-bold text-white"><Filter className="h-3.5 w-3.5"/>Apply</button>
          <Link href="/reports/renewals" className="mt-auto inline-flex h-10 items-center justify-center rounded-lg border border-[#dfe5ee] bg-white px-4 text-[10.5px] font-bold text-[#526174]">Reset</Link>
        </form>
      </div>
    </header>
    {loadError?<div className="rounded-xl border border-red-200 bg-red-50 px-5 py-4 text-[11px] font-bold text-red-700">Reporting service unavailable.</div>:null}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">
      <Metric label="Upcoming" value={integer(report.summary.upcoming_policy_count)}/><Metric label="Due in 30 days" value={integer(report.summary.due_30_count)}/><Metric label="Due in 90 days" value={integer(report.summary.due_90_count)}/><Metric label="Expired" value={integer(report.summary.expired_policy_count)}/><Metric label="Customers" value={integer(report.summary.customer_count)}/><Metric label="Premium at risk" value={currency(report.summary.premium_at_risk)}/>
    </section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{normalizedBuckets(report).map(x=><Link key={x.key} href={href("/reports/renewals",filters,x.key)} className="rounded-xl border border-[#e2e7ee] bg-white px-4 py-3 transition hover:border-[#bfc9db]"><p className="text-[8px] font-black uppercase tracking-[0.08em] text-[#8994a5]">{x.label}</p><div className="mt-1.5 flex items-end justify-between gap-3"><p className="text-[18px] font-semibold text-[#1e2d49]">{integer(x.policy_count)}</p><p className="text-[9px] font-bold text-[#59687c]">{currency(x.gross_premium)}</p></div></Link>)}</section>
    <section className="grid gap-4 xl:grid-cols-2"><article className="portal-card overflow-hidden"><Header title="Insurance company exposure"/><InsurerTable rows={report.insurers}/></article><article className="portal-card overflow-hidden"><Header title="RM renewal exposure"/><RmTable rows={report.rms}/></article></section>
    <section className="portal-card overflow-hidden">
      <div className="flex items-center justify-between border-b border-[#e9edf3] px-5 py-4"><h2 className="text-[14px] font-bold text-[#1b2943]">Renewal register</h2><a href={exportHref} className="inline-flex h-9 items-center gap-2 rounded-lg border border-[#cad4e4] bg-white px-3 text-[10px] font-bold text-[#263b69]"><Download className="h-3.5 w-3.5"/>Export CSV</a></div>
      <Register rows={report.register.rows}/><Pagination page={report.register.page} pages={pages} total={report.register.total_count} prev={href("/reports/renewals",filters,filters.bucket,Math.max(1,report.register.page-1))} next={href("/reports/renewals",filters,filters.bucket,report.register.page+1)}/>
    </section>
  </div></AppShell>
}

const inputClass="h-10 w-full rounded-lg border border-[#dfe5ee] bg-white px-3 text-[10.5px] font-semibold text-[#26364f] outline-none focus:border-[#7788bd] focus:ring-2 focus:ring-[#dfe5ff]";
function ReportTabs(){return <nav className="mt-4 flex flex-wrap gap-2"><Tab href="/reports" label="Business"/><Tab href="/reports/distribution" label="Distribution"/><Tab href="/reports/renewals" label="Renewals" active/></nav>}
function Tab({href,label,active=false}:{href:string;label:string;active?:boolean}){return <Link href={href} className={`rounded-lg border px-3 py-2 text-[10px] font-bold ${active?"border-[#223a78] bg-[#223a78] text-white":"border-[#dfe5ee] bg-white text-[#506077]"}`}>{label}</Link>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-1 block text-[8.5px] font-black uppercase tracking-[0.08em] text-[#7b8799]">{label}</span>{children}</label>}
function Metric({label,value}:{label:string;value:string}){return <article className="portal-card px-4 py-4 sm:px-5"><p className="text-[9px] font-black uppercase tracking-[0.1em] text-[#7c899b]">{label}</p><p className="mt-2 text-[22px] font-semibold tracking-[-0.03em] text-[#14213c]">{value}</p></article>}
function Header({title}:{title:string}){return <div className="border-b border-[#e9edf3] px-5 py-4"><h2 className="text-[14px] font-bold text-[#1b2943]">{title}</h2></div>}
function InsurerTable({rows}:{rows:RenewalReport["insurers"]}){if(!rows.length)return <Empty/>;return <div className="overflow-x-auto"><table className="w-full min-w-[700px]"><thead><tr className="bg-[#f8fafc] text-[8.3px] font-black uppercase tracking-[.07em] text-[#7c899b]"><th className="px-5 py-3 text-left">Insurance company</th><th className="px-3 py-3 text-right">Upcoming</th><th className="px-3 py-3 text-right">Due 30</th><th className="px-3 py-3 text-right">Expired</th><th className="px-3 py-3 text-right">Nearest</th><th className="px-5 py-3 text-right">Premium at risk</th></tr></thead><tbody className="divide-y divide-[#edf0f4]">{rows.map((x,i)=><tr key={`${x.id??"none"}-${i}`} className="text-[10px]"><td className="px-5 py-3.5 font-semibold text-[#283851]">{x.insurer_name}</td><td className="px-3 py-3.5 text-right">{integer(x.upcoming_policy_count)}</td><td className="px-3 py-3.5 text-right">{integer(x.due_30_count)}</td><td className="px-3 py-3.5 text-right">{integer(x.expired_count)}</td><td className="px-3 py-3.5 text-right">{date(x.nearest_expiry)}</td><td className="px-5 py-3.5 text-right font-bold">{currency(x.premium_at_risk)}</td></tr>)}</tbody></table></div>}
function RmTable({rows}:{rows:RenewalReport["rms"]}){if(!rows.length)return <Empty/>;return <div className="overflow-x-auto"><table className="w-full min-w-[700px]"><thead><tr className="bg-[#f8fafc] text-[8.3px] font-black uppercase tracking-[.07em] text-[#7c899b]"><th className="px-5 py-3 text-left">Relationship manager</th><th className="px-3 py-3 text-right">Upcoming</th><th className="px-3 py-3 text-right">Customers</th><th className="px-3 py-3 text-right">Due 30</th><th className="px-3 py-3 text-right">Expired</th><th className="px-5 py-3 text-right">Premium at risk</th></tr></thead><tbody className="divide-y divide-[#edf0f4]">{rows.map(x=><tr key={x.rm_name} className="text-[10px]"><td className="px-5 py-3.5 font-semibold text-[#283851]">{x.rm_name}</td><td className="px-3 py-3.5 text-right">{integer(x.upcoming_policy_count)}</td><td className="px-3 py-3.5 text-right">{integer(x.customer_count)}</td><td className="px-3 py-3.5 text-right">{integer(x.due_30_count)}</td><td className="px-3 py-3.5 text-right">{integer(x.expired_count)}</td><td className="px-5 py-3.5 text-right font-bold">{currency(x.premium_at_risk)}</td></tr>)}</tbody></table></div>}
function Register({rows}:{rows:RenewalReport["register"]["rows"]}){if(!rows.length)return <Empty/>;return <div className="overflow-x-auto"><table className="w-full min-w-[1220px]"><thead><tr className="bg-[#f8fafc] text-[8.1px] font-black uppercase tracking-[.07em] text-[#7c899b]"><th className="px-5 py-3 text-left">Expiry</th><th className="px-3 py-3 text-left">Policy</th><th className="px-3 py-3 text-left">Customer / vehicle</th><th className="px-3 py-3 text-left">Insurer</th><th className="px-3 py-3 text-left">RM / intermediary</th><th className="px-3 py-3 text-right">Days</th><th className="px-3 py-3 text-right">Gross premium</th><th className="px-3 py-3 text-left">Bucket</th><th className="px-5 py-3 text-center">Open</th></tr></thead><tbody className="divide-y divide-[#edf0f4]">{rows.map(x=><tr key={x.id} className="text-[10px] hover:bg-[#fbfcfe]"><td className="px-5 py-3.5 font-bold text-[#24344f]">{date(x.end_date)}</td><td className="px-3 py-3.5"><p className="font-semibold">{x.policy_no}</p><p className="text-[8.5px] text-[#8490a1]">{x.policy_type}</p></td><td className="px-3 py-3.5"><p className="font-semibold">{x.customer_name}</p><p className="text-[8.5px] text-[#8490a1]">{x.vehicle_no}</p></td><td className="px-3 py-3.5">{x.insurer_name}</td><td className="px-3 py-3.5"><p className="font-semibold">{x.rm_name}</p><p className="text-[8.5px] text-[#8490a1]">{x.intermediary_code??"—"}</p></td><td className={`px-3 py-3.5 text-right font-bold ${x.days_to_expiry<0?"text-red-700":"text-[#34445e]"}`}>{x.days_to_expiry}</td><td className="px-3 py-3.5 text-right font-bold">{currency(x.gross_premium)}</td><td className="px-3 py-3.5"><span className="rounded-md bg-[#eef2f7] px-2 py-1 text-[8.5px] font-bold text-[#4d5d73]">{bucketLabel(x.renewal_bucket)}</span></td><td className="px-5 py-3.5 text-center"><Link href={`/policies/${x.id}`} className="inline-grid h-8 w-8 place-items-center rounded-lg border border-[#d9e1ec] text-[#425b8f]"><ExternalLink className="h-3.5 w-3.5"/></Link></td></tr>)}</tbody></table></div>}
function Pagination({page,pages,total,prev,next}:{page:number;pages:number;total:number;prev:string;next:string}){return <div className="flex items-center justify-between border-t border-[#edf0f4] px-5 py-3 text-[9.5px] text-[#738095]"><span>{integer(total)} records</span><div className="flex items-center gap-2"><Link aria-disabled={page<=1} href={page<=1?"#":prev} className={`rounded-md border px-3 py-1.5 font-bold ${page<=1?"pointer-events-none opacity-40":""}`}>Previous</Link><span>{page} / {pages}</span><Link aria-disabled={page>=pages} href={page>=pages?"#":next} className={`rounded-md border px-3 py-1.5 font-bold ${page>=pages?"pointer-events-none opacity-40":""}`}>Next</Link></div></div>}
function Empty(){return <div className="px-5 py-10 text-center text-[10px] font-semibold text-[#8a96a7]">No records</div>}
function bucketOptions(){return [{key:"expired" as RenewalBucket,label:"Expired"},{key:"due_30" as RenewalBucket,label:"0–30 days"},{key:"due_31_60" as RenewalBucket,label:"31–60 days"},{key:"due_61_90" as RenewalBucket,label:"61–90 days"},{key:"due_91_180" as RenewalBucket,label:"91–180 days"},{key:"due_181_365" as RenewalBucket,label:"181–365 days"}]}
function normalizedBuckets(report:RenewalReport){const map=new Map(report.buckets.map(x=>[x.key,x]));return bucketOptions().map(x=>map.get(x.key)??{...x,policy_count:0,gross_premium:0})}
function bucketLabel(key:RenewalBucket){return bucketOptions().find(x=>x.key===key)?.label??key}
function href(base:string,f:RenewalFilters,bucket?:RenewalBucket|null,page?:number){const p=new URLSearchParams();p.set("horizon",String(f.horizonDays));if(f.insurerId)p.set("insurer",f.insurerId);if(f.rmName)p.set("rm",f.rmName);if(f.intermediaryCode)p.set("intermediary",f.intermediaryCode);if(bucket)p.set("bucket",bucket);if(page&&page>1)p.set("page",String(page));return `${base}?${p.toString()}`}
function currency(v:number){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v)}
function integer(v:number){return new Intl.NumberFormat("en-IN",{maximumFractionDigits:0}).format(v)}
function date(v:string|null){if(!v)return "—";const d=new Date(`${v}T00:00:00+05:30`);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric",timeZone:"Asia/Kolkata"}).format(d)}
function emptyReport():RenewalReport{return{summary:{upcoming_policy_count:0,expired_policy_count:0,due_30_count:0,due_90_count:0,customer_count:0,premium_at_risk:0,premium_due_30:0,nearest_expiry:null},buckets:[],insurers:[],rms:[],filters:{insurers:[],rms:[],intermediaries:[]},register:{rows:[],total_count:0,page:1,page_size:25}}}
function fallbackFilters():RenewalFilters{return{horizonDays:365,insurerId:null,rmName:null,intermediaryCode:null,bucket:null,page:1}}
