import Link from "next/link";
import { IndianDateField } from "@/components/indian-date-field";

type PartnerType="posp"|"misp";
type Props={partnerType:PartnerType;salesManagers:Array<{id:string;fullName:string;employeeCode:string|null}>;oems:Array<{value:string;label:string}>;banks:Array<{value:string;label:string}>;error?:string|null};
const inputClass="h-9 w-full min-w-0 rounded-lg border border-[#CBD5E1] bg-white px-3 text-[11px] text-[#17203A] outline-none transition placeholder:text-[#98A2B3] focus:border-[#4F46E5] focus:ring-2 focus:ring-[#E0E7FF]";
const dateInputClass="h-9 w-full rounded-lg border border-[#CBD5E1] bg-white px-3 pr-9 text-[11px] font-medium text-[#17203A] outline-none transition focus:border-[#4F46E5] focus:ring-2 focus:ring-[#E0E7FF] disabled:bg-[#F8FAFC] disabled:text-[#64748B]";
const labelClass="mb-1 block text-[9.5px] font-semibold text-[#344054]";

export function PospMispOnboardingForm({partnerType,salesManagers,oems,banks,error}:Props){
 const isMisp=partnerType==="misp";const backHref=isMisp?"/intermediaries/misp":"/intermediaries/posp";
 return <div className="w-full space-y-2 pb-12">
  {error?<div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-[10px] font-medium text-red-700">{error}</div>:null}
  <div className="flex flex-col gap-1.5 sm:flex-row sm:items-center sm:justify-between"><span className="w-fit rounded-full border border-[#D8DEE8] bg-white px-2.5 py-1 text-[10px] font-semibold text-[#475569]">New {partnerType.toUpperCase()} Application</span><div className="flex gap-3"><Link href="/customers/posp-misp/import" className="text-[10px] font-semibold text-[#4F46E5]">Import Excel</Link><Link href={backHref} className="text-[10px] font-semibold text-[#4F46E5]">Back</Link></div></div>
  <StageBar/>
  <form method="post" action="/customers/posp-misp/new/submit" className="w-full overflow-hidden rounded-xl border border-[#DCE5EF] bg-white shadow-sm"><input type="hidden" name="partner_type" value={partnerType}/>
   <header className="border-b border-[#E2E8F0] bg-[#F8FAFC] px-3 py-2.5 sm:px-4"><div className="flex items-start gap-2.5"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-[#071D49] text-[9px] font-bold text-white">1</span><div><h2 className="text-[13px] font-semibold text-[#0F172A]">Primary information & PAN check</h2><p className="mt-0.5 text-[9px] leading-3.5 text-[#64748B]">The POSP/MISP ID is issued only after successful onboarding. A Partner ID is issued after Stage 2 documents are submitted.</p></div></div></header>
   <Section title={isMisp?"MISP details":"POSP details"}>
    <div className={`grid min-w-0 gap-3 md:grid-cols-2 xl:col-span-4 ${isMisp?"xl:grid-cols-4":"xl:grid-cols-3"}`}><SelectField label="RM Name" name="associate_employee_id" required options={salesManagers.map(manager=>({value:manager.id,label:`${manager.fullName}${manager.employeeCode?` - ${manager.employeeCode}`:""}`}))} placeholder="Select RM"/>{isMisp?<Field label="MISP Name" name="misp_name" required/>:null}<PanInput label={isMisp?"MISP PAN":"PAN Number"} name="pan_number" compact/><IndianDateField label="Document Received Date" name="document_received_at" inputClassName={dateInputClass}/></div>
    {!isMisp?<div className="grid min-w-0 gap-3 md:grid-cols-3 xl:col-span-4"><Field label="POS First Name" name="pos_first_name" required/><Field label="POS Middle Name" name="pos_middle_name"/><Field label="POS Last Name" name="pos_last_name" required/></div>:null}
    {isMisp?<SelectField label="OEM Name" name="oem_name" required options={oems} placeholder="Select OEM"/>:null}
    <Field label="Address" name="address" required/><Field label="City" name="city" required/><Field label="State" name="state" required/><Field label="PIN Code" name="postal_code" required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} minLength={6}/>
   </Section>
   {!isMisp?<Section title="POSP contact"><Field label="Mobile Number" name="applicant_phone" required inputMode="tel" pattern="(?:\+91)?[6-9][0-9]{9}"/><Field label="Email" name="applicant_email" type="email" required/><IndianDateField label="Date of Birth" name="date_of_birth" required inputClassName={dateInputClass}/><Field label="Aadhaar Number" name="aadhaar_number" required inputMode="numeric" pattern="[0-9]{12}" maxLength={12} minLength={12}/></Section>:null}
   {isMisp?<Section title="Designated Person (DP)"><Field label="DP First Name" name="dp_first_name" required/><Field label="DP Middle Name" name="dp_middle_name"/><Field label="DP Last Name" name="dp_last_name" required/><Field label="DP Contact" name="dp_phone" required inputMode="tel" pattern="(?:\+91)?[6-9][0-9]{9}"/><Field label="DP Email" name="dp_email" required type="email"/><PanInput label="DP PAN No" name="dp_pan_number"/><IndianDateField label="DP Date of Birth" name="date_of_birth" required inputClassName={dateInputClass}/><Field label="DP Aadhaar Number" name="aadhaar_number" required inputMode="numeric" pattern="[0-9]{12}" maxLength={12} minLength={12}/></Section>:null}
   <Section title="Bank and GST details"><SelectField label="Bank Name" name="bank_id" required options={banks} placeholder="Select bank"/><Field label="Account Number" name="bank_account_number" required inputMode="numeric" pattern="[0-9]{6,20}"/><Field label="IFSC Code" name="bank_ifsc_code" required maxLength={11} minLength={11} pattern="[A-Za-z]{4}0[A-Za-z0-9]{6}"/><Field label="GST Number" name="gst_number" required={isMisp} maxLength={15}/></Section>
   <div className="sticky bottom-0 z-20 flex flex-col gap-2 border-t border-[#E2E8F0] bg-white/96 px-3 py-2 backdrop-blur sm:flex-row sm:items-center sm:justify-between sm:px-4"><p className="text-[9px] text-[#64748B]">Stage 1 saves the application and queues the PAN check.</p><button type="submit" className="w-full rounded-lg bg-gradient-to-r from-[#635BFF] to-[#4285F4] px-4 py-2 text-[10px] font-semibold text-white sm:w-auto">Save &amp; check PAN</button></div>
  </form>
 </div>;
}
function StageBar(){return <div className="grid grid-cols-1 gap-1 rounded-xl border border-[#DCE5EF] bg-white p-1.5 shadow-sm sm:grid-cols-3 sm:gap-1.5"><Stage active number="1" label="Primary & IIB"/><Stage number="2" label="Documents"/><Stage number="3" label="Review"/></div>}
function Stage({number,label,active=false}:{number:string;label:string;active?:boolean}){return <div className={`flex items-center justify-center gap-1.5 rounded-lg border px-3 py-2 text-[9.5px] font-semibold ${active?"border-[#C7D2FE] bg-[#EEF2FF] text-[#4338CA]":"border-[#E2E8F0] bg-[#F8FAFC] text-[#94A3B8]"}`}><span>{number}</span><span>{label}</span></div>}
function PanInput({label,name,compact=false}:{label:string;name:string;compact?:boolean}){return <div className={`min-w-0 ${compact?"":"xl:col-span-2"}`}><label className={labelClass} htmlFor={name}>{label} *</label><input id={name} name={name} required maxLength={10} minLength={10} pattern="[A-Za-z]{5}[0-9]{4}[A-Za-z]" className={`${inputClass} font-mono tracking-[0.03em]`}/><p className="mt-0.5 text-[8px] text-[#64748B]">PAN check starts when the form is saved.</p></div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="border-b border-[#E2E8F0] px-3 py-3 sm:px-4"><h3 className="mb-2.5 text-[11px] font-semibold text-[#0F172A]">{title}</h3><div className="grid min-w-0 grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-4">{children}</div></section>}
function Field({label,name,required=false,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string;name:string}){return <div className="min-w-0"><label className={labelClass} htmlFor={name}>{label}{required?" *":""}</label><input id={name} name={name} required={required} className={inputClass} {...props}/></div>}
function SelectField({label,name,required=false,options,placeholder,...props}:React.SelectHTMLAttributes<HTMLSelectElement>&{label:string;name:string;options:Array<{value:string;label:string}>;placeholder:string}){return <div className="min-w-0"><label className={labelClass} htmlFor={name}>{label}{required?" *":""}</label><select id={name} name={name} required={required} className={inputClass} {...props}><option value="">{placeholder}</option>{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></div>}