"use client";

import Link from "next/link";
import { Eye, Plus, Search } from "lucide-react";
import { useMemo, useState } from "react";

type Row = { id: string; policy_no: string; policy_type: string; start_date: string; end_date: string; insured_declared_value: number | null; premium_amount: number | null; customers: { contact_name: string } | null; vehicles: { vehicle_no: string } | null; insurance_companies: { name: string } | null };

export function BackofficePolicyRegister({ rows }: { rows: Row[] }) {
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => { const q=query.trim().toLowerCase(); return q ? rows.filter((row)=>[row.policy_no,row.policy_type,row.customers?.contact_name,row.vehicles?.vehicle_no,row.insurance_companies?.name].filter(Boolean).join(" ").toLowerCase().includes(q)) : rows; }, [query, rows]);
  return <section className="mx-auto max-w-[1480px] overflow-hidden rounded-2xl border border-[#DCE5EF] bg-white shadow-sm">
    <div className="flex flex-col gap-3 border-b border-[#E5ECF5] bg-[#F8FAFC] px-4 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.1em] text-[#64748B]">Operational register · protected finance</p><h1 className="mt-1 text-[16px] font-semibold text-[#17365D]">Policy Register</h1><p className="mt-1 text-[9.5px] text-[#667085]">View policy identity, coverage and premium details. Pay-in, payout, billing, retention and margin are not exposed.</p></div><Link href="/policies/new" className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-[#17365D] px-4 text-[10.5px] font-bold text-white"><Plus className="h-4 w-4"/>Add Policy</Link></div>
    <div className="border-b border-[#E5ECF5] px-4 py-3"><label className="relative block max-w-[430px]"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#94A3B8]"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search policy, customer, vehicle or insurer" className="h-10 w-full rounded-xl border border-[#CBD5E1] bg-white pl-9 pr-3 text-[10.5px] outline-none"/></label></div>
    <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[1000px] text-left text-[10.5px]"><thead className="border-b border-[#E5ECF5] bg-[#FBFCFE] text-[8.5px] font-bold uppercase text-[#64748B]"><tr><th className="px-4 py-3">Policy</th><th className="px-3 py-3">Customer</th><th className="px-3 py-3">Vehicle</th><th className="px-3 py-3">Insurer</th><th className="px-3 py-3">Validity</th><th className="px-3 py-3 text-right">IDV</th><th className="px-3 py-3 text-right">Premium</th><th className="px-4 py-3 text-right">Access</th></tr></thead><tbody className="divide-y divide-[#EEF2F6]">{filtered.map((row)=><tr key={row.id} className="hover:bg-[#FAFCFF]"><td className="px-4 py-3"><p className="font-bold text-[#17203A]">{row.policy_no}</p><p className="mt-0.5 text-[9px] text-[#64748B]">{pretty(row.policy_type)}</p></td><td className="px-3 py-3 font-semibold">{row.customers?.contact_name ?? "—"}</td><td className="px-3 py-3 font-mono">{row.vehicles?.vehicle_no ?? "—"}</td><td className="px-3 py-3">{row.insurance_companies?.name ?? "—"}</td><td className="px-3 py-3">{date(row.start_date)} – {date(row.end_date)}</td><td className="px-3 py-3 text-right">{money(row.insured_declared_value)}</td><td className="px-3 py-3 text-right">{money(row.premium_amount)}</td><td className="px-4 py-3 text-right"><Link href={`/policies/${row.id}`} className="inline-flex h-8 items-center gap-1.5 rounded-lg border border-[#CFE0F2] bg-[#EFF6FF] px-3 font-bold text-[#315B9A]"><Eye className="h-3.5 w-3.5"/>View</Link></td></tr>)}</tbody></table></div>
    <div className="space-y-2 p-3 md:hidden">{filtered.map((row)=><article key={row.id} className="rounded-xl border border-[#E2E8F0] p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-[13px] font-bold text-[#17203A]">{row.policy_no}</p><p className="mt-1 text-[10px] text-[#64748B]">{row.insurance_companies?.name ?? "Insurer not recorded"}</p></div><Link href={`/policies/${row.id}`} className="inline-flex h-8 items-center gap-1 rounded-lg bg-[#EFF6FF] px-3 text-[9px] font-bold text-[#315B9A]"><Eye className="h-3.5 w-3.5"/>View</Link></div><p className="mt-2 text-[10px] text-[#475569]">{row.customers?.contact_name ?? "—"} · {row.vehicles?.vehicle_no ?? "—"}</p></article>)}</div>
    {!filtered.length ? <div className="px-5 py-10 text-center text-[10px] text-[#7A8798]">No matching policies found.</div> : null}
  </section>;
}
function pretty(value:string){return value.replaceAll("_"," ").replace(/\b\w/g,(m)=>m.toUpperCase());}
function date(value:string){const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleDateString("en-IN");}
function money(value:number|null){return value==null?"—":new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(value);}
