"use client";

import Link from "next/link";
import { useMemo, useState, useTransition, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { ChevronDown, FileText, Upload } from "lucide-react";
import { convertLifeHealthCaseToPolicy, uploadLifeHealthCaseDocument } from "@/app/policies/life-health-policy-actions";
import { updateLifeHealthCaseDetails } from "@/app/policies/life-health-case-edit-actions";

type CaseData={id:string;caseNumber:string;businessLine:"Life"|"Health";status:string;sourcingDate:string;customerId:string;customerName:string;customerPhone:string;customerEmail:string;insurerId:string;insurerName:string;productName:string;proposalNumber:string;ppt:string;pd:string;paymentFrequency:string;paymentMode:string;premiumAmount:number;intermediaryType:string;intermediaryCode:string;leadSource:string;intermediaryMobile:string;rmName:string;rmCode:string;remarks:string;finalPolicyId:string|null;finalPolicyNo:string|null;finalPolicyCode:string|null;convertedAt:string|null};
type DocumentRow={id:string;document_type:string;file_name:string;created_at:string};
type Props={caseData:CaseData;insurers:Array<{id:string;name:string}>;documents:DocumentRow[]};
type IssueState={policyNumber:string;issuanceDate:string;startDate:string;endDate:string;finalPremium:string;sumInsured:string};

const field="h-10 w-full rounded-lg border border-[#D7DFEA] bg-white px-3 text-[11px] text-[#172B4D] outline-none focus:border-[#315B9A] focus:ring-2 focus:ring-[#DCE8FA]";
const readOnlyField=`${field} bg-[#F7F9FC] text-[#526174]`;
const label="mb-1.5 block text-[8.5px] font-bold uppercase tracking-[.055em] text-[#667085]";
const frequencies=["Monthly","Quarterly","Half Yearly","Annually","One Time"];
const modes=["Cash","Cheque","NEFT/RTGS","UPI","Credit/Debit Card","Net Banking"];
const today=()=>new Date().toISOString().slice(0,10);
const plusYearMinusDay=(s:string)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return"";const d=new Date(`${s}T00:00:00Z`);d.setUTCFullYear(d.getUTCFullYear()+1);d.setUTCDate(d.getUTCDate()-1);return d.toISOString().slice(0,10)};
const docs=[{type:"proposal_form",label:"Proposal Form"},{type:"benefit_illustration",label:"Benefit Illustration"},{type:"premium_receipt",label:"Premium Receipt"},{type:"policy_copy",label:"Policy Copy"}];

export function LifeHealthCaseDetail({caseData,insurers,documents}:Props){
  const router=useRouter(),isIssued=Boolean(caseData.finalPolicyId),docMap=useMemo(()=>new Map(documents.map(d=>[d.document_type,d])),[documents]);
  const[uploading,startUpload]=useTransition(),[converting,startConvert]=useTransition();
  const[error,setError]=useState<string|null>(null),[copy,setCopy]=useState<File|null>(null),[activityOpen,setActivityOpen]=useState(false);
  const[form,setForm]=useState({customerName:caseData.customerName,customerPhone:caseData.customerPhone,customerEmail:caseData.customerEmail,insurerId:caseData.insurerId,productName:caseData.productName,proposalNumber:caseData.proposalNumber,ppt:caseData.ppt,pd:caseData.pd,paymentFrequency:caseData.paymentFrequency,paymentMode:caseData.paymentMode,premiumAmount:String(caseData.premiumAmount||""),sourcingDate:caseData.sourcingDate,remarks:caseData.remarks});
  const[issue,setIssue]=useState<IssueState>({policyNumber:"",issuanceDate:today(),startDate:today(),endDate:plusYearMinusDay(today()),finalPremium:String(caseData.premiumAmount||""),sumInsured:""});
  const set=(k:string,v:string)=>setForm(x=>({...x,[k]:v})); const setI=(k:keyof IssueState,v:string)=>setIssue(x=>({...x,[k]:v}));
  const editData=()=>{const d=new FormData();d.set("caseId",caseData.id);Object.entries(form).forEach(([k,v])=>d.set(k,v));return d};
  const upload=(type:string,file:File|null)=>{if(!file)return;const d=new FormData();d.set("caseId",caseData.id);d.set("documentType",type);d.set("file",file);startUpload(async()=>{const r=await uploadLifeHealthCaseDocument(d);if(!r.ok){setError(r.error);return}router.refresh()})};
  const convert=()=>{setError(null);startConvert(async()=>{const savedResult=await updateLifeHealthCaseDetails(editData());if(!savedResult.ok){setError(savedResult.error);return}const d=new FormData();d.set("caseId",caseData.id);Object.entries(issue).forEach(([k,v])=>d.set(k,v));if(copy)d.set("policyCopy",copy);const r=await convertLifeHealthCaseToPolicy(d);if(!r.ok){setError(r.error);return}router.push("/policies/life-health-cases");router.refresh()})};
  if(isIssued)return <div className="mx-auto max-w-[1540px] rounded-xl border bg-white p-5 text-[11px] text-[#17365D]">This case is issued and closed. <Link className="font-bold underline" href={`/policies/${caseData.finalPolicyId}`}>View Policy {caseData.finalPolicyNo}</Link></div>;
  return <div className="mx-auto max-w-[1540px] space-y-3 pb-8">
    <section className="flex min-h-[72px] items-center justify-between rounded-xl bg-[#214A78] px-7 py-4 text-white"><div><h1 className="text-[20px] font-bold leading-none">{caseData.businessLine} Case</h1><p className="mt-2 text-[9px] text-white/70">{caseData.caseNumber}</p></div><div className="flex items-center gap-3"><span className="rounded-lg border border-white/25 bg-white/10 px-4 py-2 text-[10px] font-semibold">Awaiting policy</span><Link href="/policies/life-health-cases" className="flex h-9 items-center justify-center rounded-lg border border-white/25 px-5 text-[10px] font-semibold text-white hover:bg-white/10">Back</Link></div></section>
    <Section title="Case summary"><Grid>
      <F t="Customer name"><input className={field} value={form.customerName} onChange={e=>set("customerName",e.target.value)}/></F><F t="Mobile"><input className={field} value={form.customerPhone} onChange={e=>set("customerPhone",e.target.value)}/></F><F t="Email"><input className={field} value={form.customerEmail} onChange={e=>set("customerEmail",e.target.value)}/></F>
      <F t="Insurer"><select className={field} value={form.insurerId} onChange={e=>set("insurerId",e.target.value)}>{insurers.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></F><F t="Product"><input className={field} value={form.productName} onChange={e=>set("productName",e.target.value)}/></F><F t="Proposal no."><input className={field} value={form.proposalNumber} onChange={e=>set("proposalNumber",e.target.value)}/></F>
      <F t="PPT"><input className={field} value={form.ppt} onChange={e=>set("ppt",e.target.value)}/></F><F t="Policy duration / term"><input className={field} value={form.pd} onChange={e=>set("pd",e.target.value)}/></F><F t="Premium"><input className={field} value={form.premiumAmount} onChange={e=>set("premiumAmount",e.target.value.replace(/[^0-9.]/g,""))}/></F>
      <F t="Payment frequency"><select className={field} value={form.paymentFrequency} onChange={e=>set("paymentFrequency",e.target.value)}>{frequencies.map(v=><option key={v}>{v}</option>)}</select></F><F t="Payment mode"><select className={field} value={form.paymentMode} onChange={e=>set("paymentMode",e.target.value)}>{modes.map(v=><option key={v}>{v}</option>)}</select></F>
    </Grid></Section>
    <Section title="Source & ownership"><Grid>
      <F t="Sourcing date"><input type="date" className={field} value={form.sourcingDate} onChange={e=>set("sourcingDate",e.target.value)}/></F><F t="RM"><input className={readOnlyField} value={caseData.rmName} readOnly/></F><F t="Employee ID"><input className={readOnlyField} value={caseData.rmCode} readOnly/></F><F t="Lead source"><input className={readOnlyField} value={caseData.leadSource} readOnly/></F><F t="Source ID"><input className={readOnlyField} value={caseData.intermediaryCode} readOnly/></F><F t="Source mobile"><input className={readOnlyField} value={caseData.intermediaryMobile} readOnly/></F>
    </Grid><p className="mt-2 text-[8px] text-[#7A8798]">Ownership fields are linked to the authoritative source record and cannot be edited independently.</p></Section>
    <Section title="Mark Policy Issued"><Grid><F t="Policy number"><input className={field} value={issue.policyNumber} onChange={e=>setI("policyNumber",e.target.value.toUpperCase())}/></F><F t="Issuance date"><input type="date" className={field} value={issue.issuanceDate} onChange={e=>setI("issuanceDate",e.target.value)}/></F><F t="Policy start date"><input type="date" className={field} value={issue.startDate} onChange={e=>{setI("startDate",e.target.value);setI("endDate",plusYearMinusDay(e.target.value))}}/></F><F t="Policy end / maturity date"><input type="date" className={field} value={issue.endDate} onChange={e=>setI("endDate",e.target.value)}/></F><F t="Final premium"><input className={field} value={issue.finalPremium} onChange={e=>setI("finalPremium",e.target.value.replace(/[^0-9.]/g,""))}/></F><F t="Sum assured / insured"><input className={field} value={issue.sumInsured} onChange={e=>setI("sumInsured",e.target.value.replace(/[^0-9.]/g,""))}/></F></Grid></Section>
    <section className="overflow-hidden rounded-xl border border-[#D9E2F0] bg-white"><button type="button" onClick={()=>setActivityOpen(v=>!v)} className="flex w-full items-center justify-between px-4 py-3 text-left text-[11px] font-semibold text-[#17365D]"><span>Activity Status</span><ChevronDown className={`h-4 w-4 ${activityOpen?"rotate-180":""}`}/></button>{activityOpen?<div className="border-t p-4"><F t="Remarks / activity note"><textarea className={`${field} h-20 py-2`} value={form.remarks} onChange={e=>set("remarks",e.target.value)}/></F><p className="mt-2 text-[9px] text-[#667085]">Current status: <b>{caseData.status.replaceAll("_"," ")}</b></p></div>:null}</section>
    {error?<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-[10px] font-semibold text-red-700">{error}</div>:null}
    <section className="rounded-xl border border-[#D9E2F0] bg-white p-3"><div className="grid grid-cols-2 gap-2 md:grid-cols-3 xl:grid-cols-6">{docs.map(d=><Doc key={d.type} type={d.type} title={d.label} existing={docMap.get(d.type)} disabled={uploading} onUpload={upload}/>)}<Link href="/policies/life-health-cases" className="flex min-h-[92px] items-center justify-center rounded-xl border border-[#CAD7E7] bg-white px-4 text-[9px] font-bold text-[#17365D]">Cancel</Link><button type="button" onClick={convert} disabled={converting} className="min-h-[92px] rounded-xl bg-[#17365D] px-4 text-[9px] font-bold text-white disabled:opacity-60">{converting?"Creating policy…":"Create Policy & Close Case"}</button></div>{!docMap.has("policy_copy")?<label className="mt-2 block text-right text-[8px] text-[#667085]">Issued policy copy can be uploaded in the Policy Copy tile before closing.<input type="file" className="hidden" onChange={e=>setCopy(e.target.files?.[0]??null)}/></label>:null}</section>
  </div>
}
function Section({title,children}:{title:string;children:ReactNode}){return <section className="overflow-hidden rounded-xl border border-[#D9E2F0] bg-white"><div className="border-b px-4 py-3 text-[11px] font-semibold text-[#17365D]">{title}</div><div className="p-4">{children}</div></section>}
function Grid({children}:{children:ReactNode}){return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{children}</div>}
function F({t,children}:{t:string;children:ReactNode}){return <label><span className={label}>{t}</span>{children}</label>}
function Doc({type,title,existing,disabled,onUpload}:{type:string;title:string;existing?:DocumentRow;disabled:boolean;onUpload:(type:string,file:File|null)=>void}){return <label className={`flex min-h-[92px] cursor-pointer flex-col items-center justify-center rounded-xl border p-3 text-center ${existing?"border-emerald-200 bg-emerald-50/30":"border-[#DCE3EC] bg-[#FBFCFE]"}`}><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#EEF4FB] text-[#315B9A]"><FileText className="h-4 w-4"/></span><b className="mt-2 text-[9px] text-[#17365D]">{title}</b><span className="max-w-full truncate text-[8px] text-[#7A8798]">{existing?.file_name||"Not uploaded"}</span><span className="mt-1 flex items-center gap-1 text-[8px] font-semibold text-[#315B9A]"><Upload className="h-3 w-3"/>{existing?"Replace":"Upload"}</span><input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" disabled={disabled} className="hidden" onChange={e=>onUpload(type,e.target.files?.[0]??null)}/></label>}
