"use client";

import Link from "next/link";
import { useMemo, useState, useTransition, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { ChevronDown, Eye, LoaderCircle, Upload, UserRound } from "lucide-react";
import { convertLifeHealthCaseToPolicy, uploadLifeHealthCaseDocument } from "@/app/policies/life-health-policy-actions";
import { updateLifeHealthCaseDetails } from "@/app/policies/life-health-case-edit-actions";

type CaseData={id:string;caseNumber:string;businessLine:"Life"|"Health";status:string;sourcingDate:string;customerId:string;customerName:string;customerPhone:string;customerEmail:string;insurerId:string;insurerName:string;productName:string;proposalNumber:string;ppt:string;pd:string;paymentFrequency:string;paymentMode:string;premiumAmount:number;intermediaryType:string;intermediaryCode:string;leadSource:string;intermediaryMobile:string;rmName:string;rmCode:string;remarks:string;finalPolicyId:string|null;finalPolicyNo:string|null;finalPolicyCode:string|null;convertedAt:string|null};
type DocumentRow={id:string;document_type:string;file_name:string;created_at:string;view_url:string};
type ActivityRow={id:string;action:string;createdAt:string;createdBy:string};
type Props={caseData:CaseData;insurers:Array<{id:string;name:string}>;documents:DocumentRow[];activities:ActivityRow[]};
type IssueState={policyNumber:string;issuanceDate:string;startDate:string;endDate:string;finalPremium:string;sumInsured:string};

const field="h-9 w-full rounded-lg border border-[#D7DFEA] bg-white px-2.5 text-[10px] text-[#172B4D] outline-none focus:border-[#315B9A] focus:ring-2 focus:ring-[#DCE8FA]";
const readOnlyField=`${field} bg-[#F7F9FC] text-[#526174]`;
const label="mb-1.5 block text-[8px] font-bold uppercase tracking-[.055em] text-[#667085]";
const frequencies=["Monthly","Quarterly","Half Yearly","Annually","One Time"];
const modes=["Cash","Cheque","NEFT/RTGS","UPI","Credit/Debit Card","Net Banking"];
const today=()=>new Date().toISOString().slice(0,10);
const plusYearMinusDay=(s:string)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return"";const d=new Date(`${s}T00:00:00Z`);d.setUTCFullYear(d.getUTCFullYear()+1);d.setUTCDate(d.getUTCDate()-1);return d.toISOString().slice(0,10)};
const activityDate=(value:string)=>{const date=new Date(value);return Number.isNaN(date.getTime())?"—":date.toLocaleString("en-IN",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"})};

export function LifeHealthCaseDetail({caseData,insurers,documents,activities}:Props){
  const router=useRouter(),isIssued=Boolean(caseData.finalPolicyId),docMap=useMemo(()=>new Map(documents.map(d=>[d.document_type,d])),[documents]);
  const[uploading,startUpload]=useTransition(),[converting,startConvert]=useTransition();
  const[error,setError]=useState<string|null>(null),[copy,setCopy]=useState<File|null>(null),[activityOpen,setActivityOpen]=useState(false),[remarksOpen,setRemarksOpen]=useState(false),[uploadingType,setUploadingType]=useState<string|null>(null);
  const[form,setForm]=useState({customerName:caseData.customerName,customerPhone:caseData.customerPhone,customerEmail:caseData.customerEmail,insurerId:caseData.insurerId,productName:caseData.productName,proposalNumber:caseData.proposalNumber,ppt:caseData.ppt,pd:caseData.pd,paymentFrequency:caseData.paymentFrequency,paymentMode:caseData.paymentMode,premiumAmount:String(caseData.premiumAmount||""),sourcingDate:caseData.sourcingDate,remarks:caseData.remarks});
  const[issue,setIssue]=useState<IssueState>({policyNumber:"",issuanceDate:today(),startDate:today(),endDate:plusYearMinusDay(today()),finalPremium:String(caseData.premiumAmount||""),sumInsured:""});
  const set=(k:string,v:string)=>setForm(x=>({...x,[k]:v})); const setI=(k:keyof IssueState,v:string)=>setIssue(x=>({...x,[k]:v}));
  const editData=()=>{const d=new FormData();d.set("caseId",caseData.id);Object.entries(form).forEach(([k,v])=>d.set(k,v));return d};
  const upload=(type:string,file:File|null)=>{if(!file)return;const d=new FormData();d.set("caseId",caseData.id);d.set("documentType",type);d.set("file",file);setUploadingType(type);startUpload(async()=>{try{const r=await uploadLifeHealthCaseDocument(d);if(!r.ok){setError(r.error);return}router.refresh()}finally{setUploadingType(null)}})};
  const convert=()=>{setError(null);startConvert(async()=>{const savedResult=await updateLifeHealthCaseDetails(editData());if(!savedResult.ok){setError(savedResult.error);return}const d=new FormData();d.set("caseId",caseData.id);Object.entries(issue).forEach(([k,v])=>d.set(k,v));if(copy)d.set("policyCopy",copy);const r=await convertLifeHealthCaseToPolicy(d);if(!r.ok){setError(r.error);return}router.replace("/policies")})};
  if(isIssued)return <div className="mx-auto max-w-[1540px] rounded-xl border bg-white p-5 text-[11px] text-[#17365D]">This case is issued and closed. <Link className="font-bold underline" href={`/policies/${caseData.finalPolicyId}`}>View Policy {caseData.finalPolicyNo}</Link></div>;
  return <div className="mx-auto max-w-[1540px] space-y-3 pb-8">
    <section className="flex min-h-[72px] items-center justify-between rounded-xl bg-[#214A78] px-7 py-4 text-white"><div className="flex min-w-0 items-center gap-2.5"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full border border-white/25 bg-white/10"><UserRound className="h-5 w-5" aria-hidden="true"/></span><h1 className="truncate text-[20px] font-bold leading-none">{caseData.customerName}</h1>{caseData.proposalNumber?<span className="shrink-0 text-[12px] font-semibold text-white/80">{caseData.proposalNumber}</span>:null}</div><Link href="/policies/life-health-cases" className="flex h-9 shrink-0 items-center justify-center rounded-lg border border-white/25 px-5 text-[10px] font-semibold text-white hover:bg-white/10">Back</Link></section>
    <Section title="Case summary"><Grid><F t="Customer name"><input className={field} value={form.customerName} onChange={e=>set("customerName",e.target.value)}/></F><F t="Mobile"><input className={field} value={form.customerPhone} onChange={e=>set("customerPhone",e.target.value)}/></F><F t="Email"><input className={field} value={form.customerEmail} onChange={e=>set("customerEmail",e.target.value)}/></F><F t="Insurer"><select className={field} value={form.insurerId} onChange={e=>set("insurerId",e.target.value)}>{insurers.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></F><F t="Product"><input className={field} value={form.productName} onChange={e=>set("productName",e.target.value)}/></F><F t="Proposal no."><input className={field} value={form.proposalNumber} onChange={e=>set("proposalNumber",e.target.value)}/></F><F t="PPT"><input className={field} value={form.ppt} onChange={e=>set("ppt",e.target.value)}/></F><F t="Policy duration / term"><input className={field} value={form.pd} onChange={e=>set("pd",e.target.value)}/></F><F t="Premium"><input className={field} value={form.premiumAmount} onChange={e=>set("premiumAmount",e.target.value.replace(/[^0-9.]/g,""))}/></F><F t="Payment frequency"><select className={field} value={form.paymentFrequency} onChange={e=>set("paymentFrequency",e.target.value)}>{frequencies.map(v=><option key={v}>{v}</option>)}</select></F><F t="Payment mode"><select className={field} value={form.paymentMode} onChange={e=>set("paymentMode",e.target.value)}>{modes.map(v=><option key={v}>{v}</option>)}</select></F></Grid></Section>
    <Section title="Source & ownership"><Grid><F t="Sourcing date"><input type="date" className={field} value={form.sourcingDate} onChange={e=>set("sourcingDate",e.target.value)}/></F><F t="RM"><input className={readOnlyField} value={caseData.rmName} readOnly/></F><F t="Employee ID"><input className={readOnlyField} value={caseData.rmCode} readOnly/></F><F t="Lead source"><input className={readOnlyField} value={caseData.leadSource} readOnly/></F><F t="Source ID"><input className={readOnlyField} value={caseData.intermediaryCode} readOnly/></F><F t="Source mobile"><input className={readOnlyField} value={caseData.intermediaryMobile} readOnly/></F></Grid></Section>
    <Section title="Mark Policy Issued"><Grid><F t="Policy number" required><input className={field} value={issue.policyNumber} onChange={e=>setI("policyNumber",e.target.value.toUpperCase())}/></F><F t="Issuance date"><input type="date" className={field} value={issue.issuanceDate} onChange={e=>setI("issuanceDate",e.target.value)}/></F><F t="Policy start date"><input type="date" className={field} value={issue.startDate} onChange={e=>{setI("startDate",e.target.value);setI("endDate",plusYearMinusDay(e.target.value))}}/></F><F t="Policy end / maturity date"><input type="date" className={field} value={issue.endDate} onChange={e=>setI("endDate",e.target.value)}/></F><F t="Final premium"><input className={field} value={issue.finalPremium} onChange={e=>setI("finalPremium",e.target.value.replace(/[^0-9.]/g,""))}/></F><F t="Sum assured / insured"><input className={field} value={issue.sumInsured} onChange={e=>setI("sumInsured",e.target.value.replace(/[^0-9.]/g,""))}/></F></Grid></Section>
    <section className="overflow-hidden rounded-xl border border-[#D9E2F0] bg-white"><button type="button" onClick={()=>setActivityOpen(v=>!v)} className="flex w-full items-center justify-between px-4 py-3 text-left text-[11px] font-semibold text-[#17365D]"><span>Activity Status</span><ChevronDown className={`h-4 w-4 transition-transform ${activityOpen?"rotate-180":""}`}/></button>{activityOpen?<div className="border-t p-4"><div className="overflow-hidden rounded-xl border border-[#D9E2F0] bg-[#FBFCFE]">{activities.map((activity,index)=><div key={activity.id} className={`grid gap-2 px-4 py-3 md:grid-cols-[minmax(0,1fr)_260px_190px] md:items-center ${index?"border-t border-[#D9E2F0]":""}`}><div><p className="text-[8px] font-bold uppercase tracking-[.06em] text-[#8090A5]">{index===0?"Latest Action":"Previous Action"}</p><p className="mt-1 text-[12px] font-semibold text-[#17365D]">{activity.action}</p></div><p className="text-[9px] text-[#7A8AA0] md:text-right">Details: Created By: <span className="font-medium text-[#53657D]">{activity.createdBy}</span></p><p className="text-[9px] text-[#7A8AA0] md:text-right">At: {activityDate(activity.createdAt)}</p></div>)}</div></div>:null}</section>
    <section className="overflow-hidden rounded-xl border border-[#D9E2F0] bg-white"><button type="button" onClick={()=>setRemarksOpen(v=>!v)} className="flex w-full items-center justify-between px-4 py-3 text-left text-[11px] font-semibold text-[#17365D]"><span>Remarks / Activity Note</span><ChevronDown className={`h-4 w-4 transition-transform ${remarksOpen?"rotate-180":""}`}/></button>{remarksOpen?<div className="border-t p-4"><textarea className={`${field} h-20 py-2`} aria-label="Remarks / activity note" value={form.remarks} onChange={e=>set("remarks",e.target.value)}/></div>:null}</section>
    {error?<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-[10px] font-semibold text-red-700">{error}</div>:null}
    <section className="rounded-xl border border-[#D9E2F0] bg-white px-3 py-3"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex flex-wrap items-start gap-2"><UploadAction label="Policy Copy" type="policy_copy" existing={docMap.get("policy_copy")} disabled={uploading} loading={uploadingType==="policy_copy"} onUpload={(type,file)=>{setCopy(file);upload(type,file)}}/><UploadAction label="Proposal Form" type="proposal_form" existing={docMap.get("proposal_form")} disabled={uploading} loading={uploadingType==="proposal_form"} onUpload={upload}/><UploadAction label="Benefit Illustration" type="benefit_illustration" existing={docMap.get("benefit_illustration")} disabled={uploading} loading={uploadingType==="benefit_illustration"} onUpload={upload}/><UploadAction label="Premium Receipt" type="premium_receipt" existing={docMap.get("premium_receipt")} disabled={uploading} loading={uploadingType==="premium_receipt"} onUpload={upload}/><UploadAction label="Other Document" type="other_document" existing={docMap.get("other_document")} disabled={uploading} loading={uploadingType==="other_document"} onUpload={upload}/></div><div className="flex items-center gap-2"><Link href="/policies/life-health-cases" className="flex h-10 items-center justify-center rounded-xl border border-[#CAD7E7] bg-white px-5 text-[9px] font-semibold text-[#17365D]">Cancel</Link><button type="button" onClick={convert} disabled={converting} className="h-10 rounded-xl bg-[#17365D] px-5 text-[9px] font-bold text-white disabled:opacity-60">{converting?"Creating…":"Create Policy & Close Case"}</button></div></div></section>
  </div>
}
function Section({title,children}:{title:string;children:ReactNode}){return <section className="overflow-hidden rounded-xl border border-[#D9E2F0] bg-white"><div className="border-b px-4 py-3 text-[11px] font-semibold text-[#17365D]">{title}</div><div className="p-4">{children}</div></section>}
function Grid({children}:{children:ReactNode}){return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-6">{children}</div>}
function F({t,children,required=false}:{t:string;children:ReactNode;required?:boolean}){return <label><span className={label}>{t}{required?<span className="ml-0.5 text-red-600">*</span>:null}</span>{children}</label>}
function UploadAction({label:buttonLabel,type,existing,disabled,loading,onUpload}:{label:string;type:string;existing?:DocumentRow;disabled:boolean;loading:boolean;onUpload:(type:string,file:File|null)=>void}){return <div className="min-w-[142px] max-w-[190px]">{existing?<><div className="flex items-center gap-1"><label title={`Replace ${buttonLabel}`} className={`flex h-10 cursor-pointer items-center gap-2 rounded-xl border border-emerald-300 bg-emerald-50 px-3 text-[9px] font-semibold text-emerald-800 ${disabled?"cursor-wait opacity-70":""}`}>{loading?<LoaderCircle className="h-3.5 w-3.5 animate-spin"/>:<Upload className="h-3.5 w-3.5"/>}<span>{loading?"Uploading…":buttonLabel}</span><input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" disabled={disabled} className="hidden" onChange={e=>onUpload(type,e.target.files?.[0]??null)}/></label><a href={existing.view_url||undefined} target="_blank" rel="noreferrer" aria-label={`View ${buttonLabel}`} title={`View ${existing.file_name}`} className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-[#BFD3F5] text-[#1859B7] ${existing.view_url?"hover:bg-[#F5F9FF]":"pointer-events-none opacity-50"}`}><Eye className="h-4 w-4"/></a></div><p className="mt-1 truncate px-1 text-[8px] text-[#667085]" title={existing.file_name}>{existing.file_name}</p></>:<label className={`flex h-10 cursor-pointer items-center gap-2 rounded-xl border border-[#CAD7E7] bg-white px-4 text-[9px] font-semibold text-[#24569A] ${disabled?"cursor-wait opacity-70":""}`}>{loading?<LoaderCircle className="h-3.5 w-3.5 animate-spin"/>:<Upload className="h-3.5 w-3.5"/>}<span>{loading?"Uploading…":`Add ${buttonLabel}`}</span><input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" disabled={disabled} className="hidden" onChange={e=>onUpload(type,e.target.files?.[0]??null)}/></label>}</div>}
