"use client";

import { UploadCloud } from "lucide-react";
import { useRef,useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { completePolicyIntakeResponseUpload,preparePolicyIntakeResponseUpload } from "@/app/policy-intakes/actions";
const MAX=15*1024*1024,TYPES=new Set(["application/pdf","image/jpeg","image/png","image/webp"]);
async function uploadSigned(url:string,file:File){const body=new FormData();body.append("cacheControl","3600");body.append("",file);const response=await fetch(url,{method:"PUT",headers:{"x-upsert":"false"},body});if(!response.ok)throw new Error("upload_failed");}
export function PolicyIntakeResponseUpload({id}:{id:string}){const inputRef=useRef<HTMLInputElement>(null),router=useRouter();const[fileName,setFileName]=useState(""),[error,setError]=useState<string|null>(null),[pending,startTransition]=useTransition();function submit(){const file=inputRef.current?.files?.[0];setError(null);if(!file){setError("Choose the replacement policy copy.");return;}if(!TYPES.has(file.type)){setError("Upload a PDF, JPG, PNG or WebP policy copy.");return;}if(file.size>MAX){setError("Policy copy must be 15 MB or smaller.");return;}startTransition(async()=>{try{const meta={name:file.name,type:file.type,size:file.size},prepared=await preparePolicyIntakeResponseUpload(id,meta);if(!prepared.ok){setError(prepared.error);return;}await uploadSigned(prepared.signedUrl,file);const result=await completePolicyIntakeResponseUpload({id,storagePath:prepared.storagePath,file:meta});if(!result.ok){setError(result.error);return;}router.refresh();}catch{setError("Replacement upload couldn't be completed. Please try again.");}});}return <div className="rounded-2xl border border-amber-200 bg-amber-50 p-3"><p className="text-[9px] font-bold text-amber-950">Operations needs another policy copy</p><p className="mt-1 text-[8px] leading-4 text-amber-800">Upload a clearer or complete document. The previous copy remains in document history.</p><label className="mt-3 flex h-10 cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-amber-300 bg-white px-3 text-[9px] font-semibold text-[#17365D]"><UploadCloud className="h-4 w-4"/>{fileName||"Choose replacement file"}<input ref={inputRef} type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className="sr-only" onChange={e=>setFileName(e.target.files?.[0]?.name??"")}/></label>{error?<p className="mt-2 text-[8px] font-semibold text-red-700">{error}</p>:null}<button type="button" onClick={submit} disabled={pending} className="mt-2 h-10 w-full rounded-xl bg-[#17365D] text-[9px] font-bold text-white disabled:opacity-50">{pending?"Saving replacement…":"Send replacement to Operations"}</button></div>;}
