"use client";

import { ExternalLink, FileText, ShieldCheck, UserRound } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { loadPolicyIntakeOnboardingContext, openPolicyIntakeDocument, type PolicyIntakeOnboardingContext } from "@/app/policy-intakes/actions";

const KEY="insureit:policy-intake:pending:v1";

export function PolicyIntakeOnboardingContextCard(){
  const[context,setContext]=useState<PolicyIntakeOnboardingContext|null>(null);const[error,setError]=useState<string|null>(null);const[opening,setOpening]=useState(false);const[position,setPosition]=useState<{left:number;top:number;width:number}|null>(null);const mobileRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{let pending:{id?:string;savedAt?:number}|null=null;try{pending=JSON.parse(sessionStorage.getItem(KEY)||"null");}catch{}if(!pending?.id||!pending.savedAt||Date.now()-pending.savedAt>8*60*60*1000)return;void loadPolicyIntakeOnboardingContext(pending.id).then(result=>{if(result.ok)setContext(result.context);});},[]);
  useEffect(()=>{if(!context)return;let frame=0;const update=()=>{const summary=document.getElementById("policy-summary-fixed-card");if(window.innerWidth<1280||!summary){setPosition(null);return;}const rect=summary.getBoundingClientRect();setPosition({left:rect.left,top:rect.bottom+8,width:rect.width});};const schedule=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(update);};update();window.addEventListener("resize",schedule);window.addEventListener("scroll",schedule,true);const observer=new ResizeObserver(schedule);const summary=document.getElementById("policy-summary-fixed-card");if(summary)observer.observe(summary);return()=>{cancelAnimationFrame(frame);window.removeEventListener("resize",schedule);window.removeEventListener("scroll",schedule,true);observer.disconnect();};},[context]);
  async function openCopy(){if(!context)return;setOpening(true);setError(null);const result=await openPolicyIntakeDocument(context.id);setOpening(false);if(!result.ok){setError(result.error);return;}window.open(result.url,"_blank","noopener,noreferrer");}
  if(!context)return null;
  const card=<div className="rounded-2xl border border-[#D9E2F0] bg-white p-3 shadow-[0_10px_26px_rgba(15,23,42,.09)]"><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[#EEF4FB] text-[#315B9A]"><ShieldCheck className="h-3.5 w-3.5"/></span><div className="min-w-0 flex-1"><p className="text-[7.5px] font-bold uppercase tracking-[.1em] text-[#7A8798]">Policy Intake</p><p className="truncate text-[10.5px] font-bold text-[#17365D]">{context.number}</p></div></div><button type="button" onClick={openCopy} disabled={opening} className="mt-2.5 flex h-9 w-full items-center justify-center gap-2 rounded-xl border border-[#CFE0F2] bg-[#F4F8FC] text-[9px] font-bold text-[#244C73] hover:bg-[#EDF5FC] disabled:opacity-60"><FileText className="h-3.5 w-3.5"/>{opening?"Opening…":"View Policy Copy"}<ExternalLink className="h-3 w-3"/></button><div className="mt-2.5 space-y-1.5 border-t border-[#E8EDF3] pt-2.5 text-[8.5px] text-[#667085]"><p className="flex items-center gap-1.5"><UserRound className="h-3 w-3 text-[#7A8798]"/><span className="font-semibold text-[#344054]">{context.submittedBy}</span></p><p><span className="font-semibold text-[#344054]">{context.leadSourceType}</span> · {context.leadSource}</p><p>Customer · {context.customerMobile}</p></div>{error?<p className="mt-2 rounded-lg bg-red-50 px-2 py-1.5 text-[8px] font-semibold text-red-700">{error}</p>:null}</div>;
  return <><div ref={mobileRef} className="mt-3 xl:hidden">{card}</div>{position&&typeof document!=="undefined"?createPortal(<div className="fixed z-30" style={{left:position.left,top:position.top,width:position.width}}>{card}</div>,document.body):null}</>;
}
