import Link from "next/link";
import { ExternalLink } from "lucide-react";
import { AppShell } from "@/components/shell";
import { ReportQueryShortcuts } from "@/components/reports/report-query-shortcuts";
import { ReportApplyButton, ReportEmptyState, ReportExportLink, ReportFilterField, ReportPageShell, ReportResetLink, reportInputClass } from "@/components/reports/report-page-shell";
import { requireCapability } from "@/lib/master-data-server";
import { loadPolicyBusinessReport, type PolicyBusinessFilters, type PolicyBusinessQuery, type PolicyBusinessReport } from "@/lib/reports/policy-business";

export const dynamic = "force-dynamic";
export const revalidate = 0;
const PERIODS = [{ value: "90d", label: "Last 90 days" }, { value: "mtd", label: "Month to date" }, { value: "ytd", label: "Year to date" }, { value: "all", label: "All time" }] as const;
type Props = { searchParams: Promise<PolicyBusinessQuery> };

export default async function ReportsPage({ searchParams }: Props) {
  const profile = await requireCapability("view_reports");
  if (!profile) return null;
  const query = await searchParams;
  let payload: Awaited<ReturnType<typeof loadPolicyBusinessReport>> | null = null;
  let loadError = false;
  try { payload = await loadPolicyBusinessReport(profile, query); } catch (error) { console.error("[reports] policy business report failed", error instanceof Error ? error.message : "unknown error"); loadError = true; }
  const report = payload?.report ?? emptyReport();
  const filters = payload?.filters ?? fallbackFilters();
  const pages = Math.max(1, Math.ceil(report.register.total_count / Math.max(report.register.page_size, 1)));
  const exportHref = href("/reports/export/policy-business", filters);
  return <AppShell title="Reports"><ReportPageShell title="Policy production & portfolio" loadError={loadError} actions={<ReportExportLink href={exportHref} />} controls={<>
    <ReportQueryShortcuts label="Period" param="period" activeValue={filters.period} options={PERIODS} />
    <form action="/reports/business" method="get" className="grid gap-2 md:grid-cols-2 xl:grid-cols-[145px_145px_minmax(180px,1fr)_minmax(170px,1fr)_minmax(190px,1fr)_auto_auto]">
      <input type="hidden" name="period" value="custom" />
      <ReportFilterField label="From"><input name="from" type="date" defaultValue={filters.fromDate ?? ""} className={reportInputClass} /></ReportFilterField>
      <ReportFilterField label="To"><input name="to" type="date" defaultValue={filters.toDate ?? ""} className={reportInputClass} /></ReportFilterField>
      <ReportFilterField label="Insurance company"><select name="insurer" defaultValue={filters.insurerId ?? ""} className={reportInputClass}><option value="">All insurers</option>{report.filters.insurers.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></ReportFilterField>
      <ReportFilterField label="Relationship manager"><select name="rm" defaultValue={filters.rmEmployeeId ?? ""} className={reportInputClass}><option value="">All RMs</option>{report.filters.rms.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></ReportFilterField>
      <ReportFilterField label="Partner / intermediary"><select name="intermediary" defaultValue={filters.intermediaryCode ?? ""} className={reportInputClass}><option value="">All intermediaries</option>{report.filters.intermediaries.map(x => <option key={x.code} value={x.code}>{x.name}{x.name !== x.code ? ` · ${x.code}` : ""}</option>)}</select></ReportFilterField>
      <ReportApplyButton /><ReportResetLink href="/reports/business" />
    </form>
  </>}>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Policies" value={integer(report.summary.policy_count)} /><Metric label="Gross premium" value={currency(report.summary.gross_premium)} /><Metric label="Net premium" value={currency(report.summary.net_premium)} /><Metric label="Average premium" value={currency(report.summary.average_premium)} /><Metric label="Intermediaries" value={integer(report.summary.intermediary_count)} /></section>
    <section className="grid gap-4 xl:grid-cols-[minmax(0,1.15fr)_minmax(340px,.85fr)]"><article className="portal-card p-5 sm:p-6"><HeaderTitle title="Premium production trend" /><Trend rows={report.trend} /></article><article className="portal-card p-5 sm:p-6"><HeaderTitle title="Premium composition" /><Composition report={report} /></article></section>
    <section className="grid gap-4 xl:grid-cols-2"><article className="portal-card overflow-hidden"><Header title="Insurance company contribution" /><InsurerTable rows={report.insurers} /></article><article className="portal-card overflow-hidden"><Header title="RM production" /><RmTable rows={report.rms} /></article></section>
    <section className="portal-card overflow-hidden"><div className="border-b border-[#e9edf3] px-5 py-4"><h2 className="text-[14px] font-bold text-[#1b2943]">Policy business register</h2></div><Register rows={report.register.rows} /><Pagination page={report.register.page} pages={pages} total={report.register.total_count} prev={href("/reports/business", filters, Math.max(1, report.register.page - 1))} next={href("/reports/business", filters, report.register.page + 1)} /></section>
  </ReportPageShell></AppShell>;
}
function Metric({label,value}:{label:string;value:string}){return <article className="portal-card px-4 py-4 sm:px-5"><p className="text-[9px] font-black uppercase tracking-[.1em] text-[#7c899b]">{label}</p><p className="mt-2 text-[23px] font-semibold tracking-[-.03em] text-[#14213c]">{value}</p></article>}
function HeaderTitle({title}:{title:string}){return <h2 className="text-[14px] font-bold text-[#1b2943]">{title}</h2>}
function Header({title}:{title:string}){return <div className="border-b border-[#e9edf3] px-5 py-4"><HeaderTitle title={title}/></div>}
function Trend({rows}:{rows:PolicyBusinessReport["trend"]}){if(!rows.length)return <Empty/>;const max=Math.max(...rows.map(x=>x.gross_premium),1);return <div className="mt-5 space-y-3">{rows.map(x=><div key={x.month} className="grid grid-cols-[78px_minmax(0,1fr)_100px] items-center gap-3"><div><p className="text-[10px] font-bold text-[#35445d]">{month(x.month)}</p><p className="text-[8.5px] text-[#8a96a7]">{integer(x.policy_count)}</p></div><div className="h-2.5 overflow-hidden rounded-full bg-[#edf1f6]"><div className="h-full rounded-full bg-[#3559a8]" style={{width:`${Math.max((x.gross_premium/max)*100,2)}%`}}/></div><p className="text-right text-[10px] font-bold tabular-nums text-[#23334f]">{currency(x.gross_premium)}</p></div>)}</div>}
function Composition({report}:{report:PolicyBusinessReport}){const total=report.summary.net_premium||1;const rows=[{label:"Own damage",value:report.summary.od_premium},{label:"Third party",value:report.summary.tp_premium},{label:"CPA",value:report.summary.cpa_amount}];return <div className="mt-5 space-y-4">{rows.map(x=><div key={x.label}><div className="flex items-end justify-between gap-3"><p className="text-[10.5px] font-semibold text-[#536174]">{x.label}</p><p className="text-[13px] font-bold tabular-nums text-[#21324f]">{currency(x.value)}</p></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#edf1f6]"><div className="h-full rounded-full bg-[#516dab]" style={{width:`${Math.min((x.value/total)*100,100)}%`}}/></div></div>)}</div>}
function InsurerTable({rows}:{rows:PolicyBusinessReport["insurers"]}){if(!rows.length)return <Empty/>;return <div className="overflow-x-auto"><table className="w-full min-w-[560px]"><thead><tr className="bg-[#f8fafc] text-[8.5px] font-black uppercase tracking-[.08em] text-[#7c899b]"><th className="px-5 py-3 text-left">Insurance company</th><th className="px-3 py-3 text-right">Policies</th><th className="px-3 py-3 text-right">Gross premium</th><th className="px-5 py-3 text-right">Share</th></tr></thead><tbody className="divide-y divide-[#edf0f4]">{rows.map(x=><tr key={x.id} className="text-[10.5px]"><td className="px-5 py-3.5 font-semibold">{x.name}</td><td className="px-3 py-3.5 text-right">{integer(x.policy_count)}</td><td className="px-3 py-3.5 text-right font-bold">{currency(x.gross_premium)}</td><td className="px-5 py-3.5 text-right">{percent(x.share_percent)}</td></tr>)}</tbody></table></div>}
function RmTable({rows}:{rows:PolicyBusinessReport["rms"]}){if(!rows.length)return <Empty/>;return <div className="overflow-x-auto"><table className="w-full min-w-[560px]"><thead><tr className="bg-[#f8fafc] text-[8.5px] font-black uppercase tracking-[.08em] text-[#7c899b]"><th className="px-5 py-3 text-left">Relationship manager</th><th className="px-3 py-3 text-right">Policies</th><th className="px-3 py-3 text-right">Partners</th><th className="px-5 py-3 text-right">Gross premium</th></tr></thead><tbody className="divide-y divide-[#edf0f4]">{rows.map(x=><tr key={x.employee_id??`unassigned-${x.name}`} className="text-[10.5px]"><td className="px-5 py-3.5 font-semibold">{x.name}</td><td className="px-3 py-3.5 text-right">{integer(x.policy_count)}</td><td className="px-3 py-3.5 text-right">{integer(x.intermediary_count)}</td><td className="px-5 py-3.5 text-right font-bold">{currency(x.gross_premium)}</td></tr>)}</tbody></table></div>}
function Register({rows}:{rows:PolicyBusinessReport["register"]["rows"]}){if(!rows.length)return <Empty/>;return <div className="overflow-x-auto"><table className="w-full min-w-[1180px]"><thead><tr className="bg-[#f8fafc] text-[8.2px] font-black uppercase tracking-[.07em] text-[#7c899b]"><th className="px-5 py-3 text-left">Business date</th><th className="px-3 py-3 text-left">Policy</th><th className="px-3 py-3 text-left">Customer / vehicle</th><th className="px-3 py-3 text-left">Insurer</th><th className="px-3 py-3 text-left">RM / intermediary</th><th className="px-3 py-3 text-right">OD</th><th className="px-3 py-3 text-right">TP</th><th className="px-3 py-3 text-right">Gross</th><th className="px-5 py-3 text-center">Open</th></tr></thead><tbody className="divide-y divide-[#edf0f4]">{rows.map(x=><tr key={x.id} className="text-[10px] hover:bg-[#fbfcfe]"><td className="px-5 py-3.5 font-semibold">{date(x.business_date)}</td><td className="px-3 py-3.5"><p className="font-bold">{x.policy_no}</p><p className="text-[8.5px] text-[#8490a1]">{x.policy_type} · {x.status}</p></td><td className="px-3 py-3.5"><p className="font-semibold">{x.customer_name}</p><p className="text-[8.5px] text-[#8490a1]">{x.vehicle_no}</p></td><td className="px-3 py-3.5">{x.insurer_name}</td><td className="px-3 py-3.5"><p className="font-semibold">{x.rm_name??"Unassigned"}</p><p className="text-[8.5px] text-[#8490a1]">{x.intermediary_code??"—"}</p></td><td className="px-3 py-3.5 text-right">{currency(x.od_premium)}</td><td className="px-3 py-3.5 text-right">{currency(x.tp_premium)}</td><td className="px-3 py-3.5 text-right font-bold">{currency(x.gross_premium)}</td><td className="px-5 py-3.5 text-center"><Link href={`/policies/${x.id}`} className="inline-grid h-8 w-8 place-items-center rounded-lg border border-[#d9e1ec] text-[#425b8f]"><ExternalLink className="h-3.5 w-3.5"/></Link></td></tr>)}</tbody></table></div>}
function Pagination({page,pages,total,prev,next}:{page:number;pages:number;total:number;prev:string;next:string}){return <div className="flex items-center justify-between border-t border-[#edf0f4] px-5 py-3 text-[9.5px] text-[#738095]"><span>{integer(total)} records</span><div className="flex items-center gap-2"><Link href={page<=1?"#":prev} className={`rounded-md border px-3 py-1.5 font-bold ${page<=1?"pointer-events-none opacity-40":""}`}>Previous</Link><span>{page} / {pages}</span><Link href={page>=pages?"#":next} className={`rounded-md border px-3 py-1.5 font-bold ${page>=pages?"pointer-events-none opacity-40":""}`}>Next</Link></div></div>}
function Empty(){return <ReportEmptyState/>}
function href(path:string,f:PolicyBusinessFilters,page?:number){const s=new URLSearchParams();s.set("period","custom");if(f.fromDate)s.set("from",f.fromDate);if(f.toDate)s.set("to",f.toDate);if(f.insurerId)s.set("insurer",f.insurerId);if(f.rmEmployeeId)s.set("rm",f.rmEmployeeId);if(f.intermediaryCode)s.set("intermediary",f.intermediaryCode);if(page)s.set("page",String(page));return `${path}?${s}`}
function currency(v:number){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v||0)}function integer(v:number){return new Intl.NumberFormat("en-IN",{maximumFractionDigits:0}).format(v||0)}function percent(v:number){return`${new Intl.NumberFormat("en-IN",{maximumFractionDigits:1}).format(v||0)}%`}function date(v:string){return v?new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric",timeZone:"Asia/Kolkata"}).format(new Date(`${v}T00:00:00+05:30`)):"—"}function month(v:string){return v?new Intl.DateTimeFormat("en-IN",{month:"short",year:"2-digit",timeZone:"Asia/Kolkata"}).format(new Date(`${v}T00:00:00+05:30`)):"—"}
function fallbackFilters():PolicyBusinessFilters{return{period:"90d",fromDate:null,toDate:null,insurerId:null,rmEmployeeId:null,intermediaryCode:null,page:1}}
function emptyReport():PolicyBusinessReport{return{summary:{policy_count:0,active_policy_count:0,gross_premium:0,net_premium:0,od_premium:0,tp_premium:0,cpa_amount:0,average_premium:0,insurer_count:0,intermediary_count:0},trend:[],insurers:[],rms:[],filters:{insurers:[],rms:[],intermediaries:[]},register:{rows:[],total_count:0,page:1,page_size:25}}}
