import Link from "next/link";
import { redirect } from "next/navigation";
import { Download, Landmark } from "lucide-react";
import { AppShell } from "@/components/shell";
import { canAccessPolicyCommercials } from "@/lib/policy-commercial-access";
import { requireCapability } from "@/lib/master-data-server";
import { loadAccountsReport, type AccountsReportQuery } from "@/lib/reports/accounts";

export const dynamic="force-dynamic";export const revalidate=0;
type Props={searchParams:Promise<AccountsReportQuery>};
const periods=[['mtd','Month to date'],['90d','Last 90 days'],['ytd','Year to date'],['all','All time']] as const;

export default async function AccountsReportsPage({searchParams}:Props){const profile=await requireCapability("view_reports");if(!canAccessPolicyCommercials(profile))redirect("/access-denied");const query=await searchParams;const {report,filters}=await loadAccountsReport(query);const exportHref=href('/reports/export/accounts',filters);
return <AppShell title="Accounts Reports"><div className="reports-v2-page report-page-shell mx-auto max-w-[1600px] space-y-4 pb-10">
 <section className="r2-panel r2-header"><div className="r2-header__top"><div><div className="flex items-center gap-2 text-[#0f766e]"><Landmark className="h-4 w-4"/><span className="text-[9px] font-black uppercase tracking-[.14em]">Phase H · Read-only accounting</span></div><h1 className="r2-title mt-2">Accounts Reports</h1><div className="r2-meta mt-2"><span>Recognized → Invoiced → Received → Outstanding</span><span>•</span><span>Actual agreed partner payout and contribution</span></div></div><Link href={exportHref} className="r2-action"><Download className="h-3.5 w-3.5"/> Export CSV</Link></div></section>
 <section className="r2-panel p-4"><div className="flex flex-wrap items-end gap-2">{periods.map(([value,label])=><Link key={value} href={`/reports/accounts?period=${value}${filters.insurerId?`&insurer=${filters.insurerId}`:''}`} className={`rounded-lg border px-3 py-2 text-[9px] font-bold ${filters.period===value?'bg-[#17365D] text-white':'bg-white text-[#42526b]'}`}>{label}</Link>)}<form action="/reports/accounts" className="ml-auto grid gap-2 sm:grid-cols-[140px_140px_minmax(180px,1fr)_auto]"><input type="hidden" name="period" value="custom"/><input name="from" type="date" defaultValue={filters.fromDate??''} className="rounded-lg border px-3 py-2 text-[9px]"/><input name="to" type="date" defaultValue={filters.toDate??''} className="rounded-lg border px-3 py-2 text-[9px]"/><select name="insurer" defaultValue={filters.insurerId??''} className="rounded-lg border px-3 py-2 text-[9px]"><option value="">All insurers</option>{report.filters.insurers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="rounded-lg bg-[#0f766e] px-3 py-2 text-[9px] font-bold text-white">Apply</button></form></div></section>
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi label="Recognized Brokerage" value={money(report.summary.recognized)} note="Finalized reconciled income"/><Kpi label="Invoiced" value={money(report.summary.invoiced)} note={`${report.counts.open_invoices} open invoices`}/><Kpi label="Bank Receipts" value={money(report.summary.bank_receipts)} note={`TDS ${money(report.summary.tds)}`}/><Kpi label="Outstanding Receivable" value={money(report.summary.outstanding)} note="Current filtered invoice balance"/><Kpi label="Gross Contribution" value={money(report.summary.gross_contribution)} note={`Partner agreed ${money(report.summary.partner_agreed)}`}/></section>
 <section className="grid gap-4 xl:grid-cols-[1.4fr_.6fr]"><article className="r2-panel overflow-hidden"><Head title="Insurer accounting position"/><Table headers={['Insurer','Recognized','Invoiced','Bank Received','TDS','Outstanding','Variance']}>{report.insurers.map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td className="r2-num">{money(x.recognized)}</td><td className="r2-num">{money(x.invoiced)}</td><td className="r2-num">{money(x.bank_receipts)}</td><td className="r2-num">{money(x.tds)}</td><td className="r2-num">{money(x.outstanding)}</td><td className="r2-num">{money(x.variance)}</td></tr>)}</Table></article><article className="r2-panel overflow-hidden"><Head title="Receivable aging"/><div className="divide-y divide-[#edf0f4]"><Row label="Current / not overdue" value={money(report.aging.current)}/><Row label="1–30 days" value={money(report.aging.d1_30)}/><Row label="31–60 days" value={money(report.aging.d31_60)}/><Row label="61–90 days" value={money(report.aging.d61_90)}/><Row label="90+ days" value={money(report.aging.d90_plus)}/></div></article></section>
 <section className="grid gap-4 xl:grid-cols-2"><article className="r2-panel overflow-hidden"><Head title="Reconciliation position"/><div className="grid grid-cols-2 gap-px bg-[#edf0f4] sm:grid-cols-4"><Mini label="Finalized" value={report.counts.finalized_reconciliation}/><Mini label="Unmatched" value={report.counts.unmatched_reconciliation}/><Mini label="Pending review" value={report.counts.pending_reconciliation}/><Mini label="Variance" value={money(report.summary.variance)}/></div><Table headers={['Policy','Insurer','Period','Recognized','Adjustment','Variance']}>{report.reconciliation.slice(0,20).map(x=><tr key={x.id}><td><strong>{x.policy_no||'—'}</strong></td><td>{x.insurer_name||'—'}</td><td>{date(x.period_end)}</td><td className="r2-num">{money(x.recognized)}</td><td className="r2-num">{money(x.adjustment)}</td><td className="r2-num">{money(x.variance)}</td></tr>)}</Table></article><article className="r2-panel overflow-hidden"><Head title="Partner payable position"/><div className="grid grid-cols-2 gap-px bg-[#edf0f4] sm:grid-cols-4"><Mini label="Agreed payout" value={money(report.summary.partner_agreed)}/><Mini label="Paid" value={money(report.summary.partner_paid)}/><Mini label="Outstanding" value={money(report.summary.partner_outstanding)}/><Mini label="Open payables" value={report.counts.open_partner_payables}/></div><Table headers={['Partner','Policy','Status','Agreed','Outstanding']}>{report.partner.slice(0,20).map(x=><tr key={x.id}><td><strong>{x.intermediary_code||'—'}</strong></td><td>{x.policy_no||'—'}</td><td>{x.status}</td><td className="r2-num">{money(x.agreed)}</td><td className="r2-num">{money(x.outstanding)}</td></tr>)}</Table></article></section>
 <section className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><article className="r2-panel overflow-hidden"><Head title="Invoice register"/><Table headers={['Invoice','Insurer','Invoice date','Due date','Status','Gross','Outstanding']}>{report.invoices.slice(0,25).map(x=><tr key={x.id}><td><strong>{x.invoice_no||'Draft'}</strong></td><td>{x.insurer_name||'—'}</td><td>{date(x.invoice_date)}</td><td>{date(x.due_date)}</td><td>{x.status}</td><td className="r2-num">{money(x.gross)}</td><td className="r2-num">{money(x.outstanding)}</td></tr>)}</Table></article><article className="r2-panel overflow-hidden"><Head title="Period close history"/><div className="divide-y divide-[#edf0f4]">{report.periods.length?report.periods.slice(0,12).map(x=><div key={x.id} className="flex items-center justify-between gap-4 px-5 py-3 text-[9.5px]"><div><strong>{date(x.period_start)} → {date(x.period_end)}</strong><p className="mt-1 text-[#7c899b]">{x.closed_at?`Closed ${dateTime(x.closed_at)}`:x.reopened_at?`Reopened ${dateTime(x.reopened_at)}`:'Not closed'}</p></div><span className="rounded-full border px-2 py-1 text-[8px] font-bold">{x.status}</span></div>):<Empty/>}</div></article></section>
 <section className="rounded-xl border border-[#dce6f2] bg-[#f8fafd] px-4 py-3 text-[9.5px] leading-5 text-[#667085]">Recognized Brokerage includes finalized matched reconciliation transactions only: cycle status Reconciled/Closed and review status Accepted/Resolved. Gross Contribution = Recognized Brokerage − actual agreed partner payout for those recognized policies. Bank receipts and TDS remain separate settlement instruments.</section>
 </div></AppShell>}

function Kpi({label,value,note}:{label:string;value:string;note:string}){return <article className="r2-panel px-4 py-4"><p className="text-[8.5px] font-black uppercase tracking-[.08em] text-[#7c899b]">{label}</p><p className="mt-2 text-[19px] font-semibold tabular-nums text-[#14213c]">{value}</p><p className="mt-1 text-[8.5px] text-[#8490a1]">{note}</p></article>};function Head({title}:{title:string}){return <div className="r2-section-head"><h2>{title}</h2></div>};function Mini({label,value}:{label:string;value:string|number}){return <div className="bg-white px-4 py-3"><p className="text-[8px] font-bold uppercase text-[#8490a1]">{label}</p><p className="mt-1 text-[13px] font-bold tabular-nums text-[#26364f]">{value}</p></div>};function Row({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between px-5 py-3 text-[10px]"><span>{label}</span><strong>{value}</strong></div>};
function Table({headers,children}:{headers:string[];children:React.ReactNode}){return <div className="r2-table-wrap"><table className="r2-table"><thead><tr>{headers.map((h,i)=><th key={h} className={i>=headers.length-3?'r2-num':''}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table>{!children?<Empty/>:null}</div>};function Empty(){return <div className="r2-empty">No records available for this selection</div>};
function money(v:number){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v||0)}function date(v:string|null){if(!v)return'—';const d=new Date(`${v.slice(0,10)}T00:00:00Z`);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).format(d)}function dateTime(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kolkata'}).format(d)}
function href(path:string,f:{period:string;fromDate:string|null;toDate:string|null;insurerId:string|null}){const q=new URLSearchParams();q.set('period',f.period);if(f.fromDate)q.set('from',f.fromDate);if(f.toDate)q.set('to',f.toDate);if(f.insurerId)q.set('insurer',f.insurerId);return `${path}?${q}`}
