from pathlib import Path

path = Path('apps/web-portal/components/intermediary-document-grid.tsx')
text = path.read_text()

old_action = '''              action={existingDocument?.href ? (\n                <a href={existingDocument.href} target="_blank" rel="noreferrer" className="inline-flex h-7 items-center rounded-lg border border-[#D7DDF0] bg-white px-2.5 text-[8.5px] font-semibold text-[#24345A] shadow-sm">Open</a>\n              ) : null}\n'''
new_action = '''              action={(existingDocument?.href || (editable && (slot.system ? Boolean(existingDocument) : true))) ? (\n                <div className="flex items-center gap-1.5">\n                  {existingDocument?.href ? (\n                    <a\n                      href={existingDocument.href}\n                      target="_blank"\n                      rel="noreferrer"\n                      aria-label={`View ${title}`}\n                      title="View"\n                      className={compactActionClass}\n                    >\n                      <EyeIcon />\n                    </a>\n                  ) : null}\n                  {editable && slot.system && existingDocument ? (\n                    <a\n                      href={`${pathname}?stage=registration`}\n                      aria-label={`Replace ${title}`}\n                      title="Replace"\n                      className={compactActionClass}\n                    >\n                      <RefreshIcon />\n                    </a>\n                  ) : editable && !slot.system && slot.custom ? (\n                    <button\n                      type="button"\n                      disabled={maintenanceBusy}\n                      onClick={() => setCustomDialog({\n                        slotKey: slot.key,\n                        title,\n                        existingLabel: customLabels[slot.key] ?? existingDocument?.document_label ?? "",\n                        hasExistingDocument: Boolean(existingDocument),\n                      })}\n                      aria-label={existingDocument || selectedName ? `Replace ${title}` : `Add ${title}`}\n                      title={existingDocument || selectedName ? "Replace" : "Add document"}\n                      className={`${compactActionClass} disabled:cursor-not-allowed disabled:opacity-50`}\n                    >\n                      {existingDocument || selectedName ? <RefreshIcon /> : <PlusIcon />}\n                    </button>\n                  ) : editable && !slot.system ? (\n                    <label\n                      htmlFor={inputId}\n                      aria-label={existingDocument || selectedName ? `Replace ${title}` : `Upload ${title}`}\n                      title={existingDocument || selectedName ? "Replace" : "Add document"}\n                      className={`${compactActionClass} cursor-pointer`}\n                    >\n                      {existingDocument || selectedName ? <RefreshIcon /> : <PlusIcon />}\n                    </label>\n                  ) : null}\n                </div>\n              ) : null}\n'''
if old_action not in text:
    raise SystemExit('action block not found')
text = text.replace(old_action, new_action, 1)

old_custom = '''                  {slot.custom ? (\n                    <>\n                      <input type="hidden" name={`${slot.key}_label`} value={customLabels[slot.key] ?? existingDocument?.document_label ?? ""} />\n                      <div className="grid gap-1.5">\n                        <button\n                          type="button"\n                          disabled={maintenanceBusy}\n                          onClick={() => setCustomDialog({\n                            slotKey: slot.key,\n                            title,\n                            existingLabel: customLabels[slot.key] ?? existingDocument?.document_label ?? "",\n                            hasExistingDocument: Boolean(existingDocument),\n                          })}\n                          className="inline-flex h-8 w-full items-center justify-center rounded-lg bg-gradient-to-r from-[#635BFF] to-[#4B8DF8] px-3 text-[8.5px] font-semibold text-white disabled:opacity-50"\n                        >\n                          {existingDocument || selectedName ? "Replace / rename" : "Add document"}\n                        </button>\n                        {existingDocument ? (\n                          <button type="button" disabled={maintenanceBusy} onClick={() => void deleteCustomDocument(slot.key)} className="h-7 rounded-lg border border-red-200 bg-red-50 px-2 text-[8px] font-semibold text-red-700 disabled:opacity-50">Delete</button>\n                        ) : null}\n                      </div>\n                    </>\n                  ) : (\n                    <>\n                      <input\n                        id={inputId}\n                        name={inputName}\n                        type="file"\n                        required={slot.required && !existingDocument}\n                        accept=".pdf,.jpg,.jpeg,.png"\n                        onChange={(event) => {\n                          const file = event.currentTarget.files?.[0];\n                          setSelectedNames((current) => ({ ...current, [slot.key]: file?.name ?? "" }));\n                          onFileSelection?.(slot.key, Boolean(file));\n                        }}\n                        className="sr-only"\n                      />\n                      <label htmlFor={inputId} className="inline-flex h-8 w-full cursor-pointer items-center justify-center rounded-lg bg-gradient-to-r from-[#635BFF] to-[#4B8DF8] px-3 text-[8.5px] font-semibold text-white">\n                        {existingDocument ? "Replace" : "Upload"}\n                      </label>\n                    </>\n                  )}\n'''
new_custom = '''                  {slot.custom ? (\n                    <input type="hidden" name={`${slot.key}_label`} value={customLabels[slot.key] ?? existingDocument?.document_label ?? ""} />\n                  ) : (\n                    <input\n                      id={inputId}\n                      name={inputName}\n                      type="file"\n                      required={slot.required && !existingDocument}\n                      accept=".pdf,.jpg,.jpeg,.png"\n                      onChange={(event) => {\n                        const file = event.currentTarget.files?.[0];\n                        setSelectedNames((current) => ({ ...current, [slot.key]: file?.name ?? "" }));\n                        onFileSelection?.(slot.key, Boolean(file));\n                      }}\n                      className="sr-only"\n                    />\n                  )}\n'''
if old_custom not in text:
    raise SystemExit('editable action block not found')
text = text.replace(old_custom, new_custom, 1)

# The visible delete action is intentionally removed by the new compact UI; remove the now-unused handler.
start = text.find('  async function deleteCustomDocument(slotKey: string) {')
if start != -1:
    end = text.find('\n\n  return (', start)
    if end == -1:
        raise SystemExit('delete handler end not found')
    text = text[:start] + text[end:]

insert_before = '\nfunction CustomDocumentDialog({'
helpers = '''\nconst compactActionClass = "inline-flex h-8 w-8 items-center justify-center rounded-lg border border-[#D7DDF0] bg-white text-[#0F2A55] shadow-[0_4px_12px_rgba(15,23,42,0.08)] transition hover:border-[#B8C7DE] hover:bg-[#F8FAFC] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C7D2FE]";\n\nfunction EyeIcon() {\n  return (\n    <svg viewBox="0 0 24 24" aria-hidden="true" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8">\n      <path d="M2.5 12s3.4-5.5 9.5-5.5 9.5 5.5 9.5 5.5-3.4 5.5-9.5 5.5S2.5 12 2.5 12Z" />\n      <circle cx="12" cy="12" r="2.6" />\n    </svg>\n  );\n}\n\nfunction RefreshIcon() {\n  return (\n    <svg viewBox="0 0 24 24" aria-hidden="true" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">\n      <path d="M20 7v5h-5" />\n      <path d="M4 17v-5h5" />\n      <path d="M6.1 8.1A7 7 0 0 1 18.7 9L20 12" />\n      <path d="M17.9 15.9A7 7 0 0 1 5.3 15L4 12" />\n    </svg>\n  );\n}\n\nfunction PlusIcon() {\n  return (\n    <svg viewBox="0 0 24 24" aria-hidden="true" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round">\n      <path d="M12 5v14M5 12h14" />\n    </svg>\n  );\n}\n'''
if insert_before not in text:
    raise SystemExit('helper insertion point not found')
text = text.replace(insert_before, helpers + insert_before, 1)

path.write_text(text)
