from pathlib import Path

path = Path('apps/web-portal/components/policy-unified-form.tsx')
text = path.read_text(encoding='utf-8')

text = text.replace('const sections = ["Source", "Customer & Vehicle", "Policy & Premium", "Insurer Pay-in", "Partner Payout", "Review"];', 'const sections = ["Source", "Customer & Vehicle", "Policy & Premium", "Insurer Pay-in", "Partner Payout"];', 1)

# Add scroll tracking + section completion model after isEdit.
anchor = '  const isEdit=mode==="edit";\n'
insert = '''  const isEdit=mode==="edit";\n\n  const sectionProgress=useMemo(()=>{\n    const groups=[\n      [form.issuanceDate,form.businessLine,form.intermediaryType,form.leadSource,form.rmName,form.intermediaryCode],\n      [form.registrationNo,form.insuredName,form.phoneNo,form.vehicleClass,form.make,form.model,form.fuelType,form.manufacturingYear,form.capacity,form.chassisNo,form.engineNo,form.rtoState,form.rtoName],\n      [form.policyProduct,form.policyNo,form.insurerId,form.idv,form.od,form.tp,form.validFrom,form.validUpto],\n      [form.projectedOdPercent,form.projectedTpPercent],\n      [form.payoutOdPercent,form.payoutTpPercent,form.payoutStatus],\n    ];\n    return groups.map(values=>{const filled=values.filter(value=>String(value??"").trim()!=="").length;return{filled,total:values.length,complete:filled===values.length,empty:filled===0,remaining:values.length-filled};});\n  },[form]);\n\n  function goToSection(index:number){setActiveSection(index);document.getElementById(`policy-section-${index+1}`)?.scrollIntoView({behavior:"smooth",block:"start"});}\n\n  useEffect(()=>{\n    const elements=sections.map((_,index)=>document.getElementById(`policy-section-${index+1}`)).filter((item):item is HTMLElement=>Boolean(item));\n    if(!elements.length)return;\n    const observer=new IntersectionObserver(entries=>{\n      const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>a.boundingClientRect.top-b.boundingClientRect.top);\n      if(visible[0]){const index=Number((visible[0].target as HTMLElement).dataset.sectionIndex??0);setActiveSection(index);}\n    },{rootMargin:"-145px 0px -58% 0px",threshold:[0,.05,.2]});\n    elements.forEach(element=>observer.observe(element));\n    return()=>observer.disconnect();\n  },[]);\n'''
if anchor not in text:
    raise SystemExit('isEdit anchor not found')
text = text.replace(anchor, insert, 1)

# Remove top Book Active Policy button and make title header slightly tighter.
old_header = '''      <div className="flex flex-col gap-3 border-b border-[#E7ECF3] bg-[linear-gradient(135deg,#071D49_0%,#123B75_60%,#315B9A_100%)] px-5 py-4 text-white lg:flex-row lg:items-center lg:justify-between">\n        <div>{isEdit&&headerBadge?<div className="flex items-center gap-2"><span className="rounded-full bg-white/15 px-2.5 py-1 text-[8px] font-bold uppercase tracking-[.14em]">{headerBadge}</span>{headerMeta?<span className="text-[9px] text-white/70">{headerMeta}</span>:null}</div>:null}<h1 className={isEdit?"mt-2 text-[18px] font-semibold":"text-[18px] font-semibold"}>{headerTitle}</h1>{headerText?<p className="mt-0.5 text-[10px] text-white/70">{headerText}</p>:null}</div>\n        <div className="flex flex-wrap items-center gap-2"><button type="button" onClick={submitPolicy} disabled={isSubmitting} className="rounded-xl bg-white px-5 py-2.5 text-[10px] font-bold text-[#071D49] shadow-sm disabled:opacity-60">{isSubmitting?pendingText:submitText}</button></div>\n      </div>\n      <div className="flex gap-1 overflow-x-auto px-3 py-2">{sections.map((section,index)=><button key={section} type="button" onClick={()=>setActiveSection(index)} className={`flex min-w-fit items-center gap-2 rounded-lg px-3 py-2 text-[9.5px] font-semibold ${activeSection===index?"bg-[#EEF2FF] text-[#4338CA]":"text-[#667085] hover:bg-[#F8FAFC]"}`}><span className={`grid h-5 w-5 place-items-center rounded-full text-[8px] ${activeSection===index?"bg-[#4F46E5] text-white":"bg-[#EEF2F6]"}`}>{index+1}</span>{section}</button>)}</div>'''
new_header = '''      <div className="border-b border-[#E7ECF3] bg-[linear-gradient(135deg,#071D49_0%,#123B75_60%,#315B9A_100%)] px-5 py-3.5 text-white">\n        <div>{isEdit&&headerBadge?<div className="flex items-center gap-2"><span className="rounded-full bg-white/15 px-2.5 py-1 text-[8px] font-bold uppercase tracking-[.14em]">{headerBadge}</span>{headerMeta?<span className="text-[9px] text-white/70">{headerMeta}</span>:null}</div>:null}<h1 className={isEdit?"mt-2 text-[18px] font-semibold":"text-[18px] font-semibold"}>{headerTitle}</h1>{headerText?<p className="mt-0.5 text-[10px] text-white/70">{headerText}</p>:null}</div>\n      </div>\n      <div className="sticky top-[72px] z-40 flex gap-1 overflow-x-auto border-b border-[#E3E9F2] bg-white/95 px-3 py-2 shadow-[0_7px_18px_rgba(15,23,42,.07)] backdrop-blur">{sections.map((section,index)=>{const progress=sectionProgress[index];return <button key={section} type="button" onClick={()=>goToSection(index)} title={progress.complete?`${section} complete`:`${progress.remaining} required item${progress.remaining===1?"":"s"} remaining`} className={`group flex min-w-fit items-center gap-2 rounded-lg px-3 py-2 text-[9.5px] font-semibold transition ${activeSection===index?"bg-[#EEF2FF] text-[#4338CA]":"text-[#667085] hover:bg-[#F8FAFC]"}`}><span className={`grid h-5 w-5 place-items-center rounded-full text-[8px] font-bold ${progress.complete?"bg-[#E8F7EF] text-[#14845B]":progress.empty?(activeSection===index?"bg-[#4F46E5] text-white":"bg-[#EEF2F6] text-[#7A8798]"):"bg-[#FFF4D8] text-[#B76E00]"}`}>{progress.complete?<svg aria-hidden="true" viewBox="0 0 20 20" className="h-3 w-3" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"><path d="m5 10 3 3 7-7"/></svg>:index+1}</span><span>{section}</span>{!progress.complete&&!progress.empty?<span className="text-[7.5px] font-semibold text-[#B76E00]">{progress.remaining} left</span>:null}</button>})}</div>'''
if old_header not in text:
    raise SystemExit('header/navigation block not found')
text = text.replace(old_header, new_header, 1)

# Section 01: remove descriptive text and Auto source marker for month.
text = text.replace('<Section number="01" title="Policy source & ownership" subtitle="Who brought the business and how the policy should be classified.">', '<Section number="01" title="Policy source & ownership">', 1)
text = text.replace('<CompactSourceMeta label="Month" value={form.issuanceDate?new Date(`${form.issuanceDate}T00:00:00`).toLocaleDateString("en-US",{month:"short",year:"2-digit"}):"Auto"} source="Auto"/>', '<CompactSourceMeta label="Month" value={form.issuanceDate?new Date(`${form.issuanceDate}T00:00:00`).toLocaleDateString("en-US",{month:"short",year:"2-digit"}):"—"}/>', 1)

# Compact section header and anchor each section automatically by number.
old_section = 'function Section({number,title,subtitle,badge,action,children}:{number:string;title:string;subtitle?:string;badge?:string;action?:ReactNode;children:ReactNode}){return <section className="overflow-hidden rounded-2xl border border-[#D9E2F0] bg-white shadow-sm"><div className="flex items-start justify-between border-b bg-[#FBFCFE] px-4 py-3"><div className="flex gap-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#17365D] text-[9px] font-bold text-white">{number}</span><div><h2 className="text-[13px] font-semibold">{title}</h2>{subtitle?<p className="mt-0.5 text-[9px] text-[#667085]">{subtitle}</p>:null}</div></div><div className="flex items-center gap-2">{badge?<span className="rounded-full border bg-white px-2.5 py-1 text-[8px] text-[#667085]">{badge}</span>:null}{action}</div></div><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-4">{children}</div></section>;}'
new_section = 'function Section({number,title,subtitle,badge,action,children}:{number:string;title:string;subtitle?:string;badge?:string;action?:ReactNode;children:ReactNode}){const index=Math.max(0,Number(number)-1);return <section id={`policy-section-${index+1}`} data-section-index={index} className="scroll-mt-[148px] overflow-hidden rounded-2xl border border-[#D9E2F0] bg-white shadow-sm"><div className="flex min-h-12 items-center justify-between border-b bg-[#FBFCFE] px-4 py-2.5"><div className="flex items-center gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-[#17365D] text-[9px] font-bold text-white">{number}</span><div className="flex min-h-8 flex-col justify-center"><h2 className="text-[13px] font-semibold leading-tight">{title}</h2>{subtitle?<p className="mt-0.5 text-[9px] leading-tight text-[#667085]">{subtitle}</p>:null}</div></div><div className="flex items-center gap-2">{badge?<span className="rounded-full border bg-white px-2.5 py-1 text-[8px] text-[#667085]">{badge}</span>:null}{action}</div></div><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-4">{children}</div></section>;}'
if old_section not in text:
    raise SystemExit('Section helper not found')
text = text.replace(old_section, new_section, 1)

path.write_text(text, encoding='utf-8')
