from pathlib import Path

path = Path('apps/web-portal/app/customers/posp-misp/posp-misp-onboarding-form.tsx')
text = path.read_text(encoding='utf-8')

old_header = '''              <div className="flex items-center gap-2">\n                <Link href="/customers/posp-misp/import" className="rounded-lg border border-white/20 bg-white/10 px-3 py-2 text-[9.5px] font-semibold text-white transition hover:bg-white/15">Import Excel</Link>\n                <Link href={backHref} className="rounded-lg border border-white/20 px-3 py-2 text-[9.5px] font-semibold text-white/90 transition hover:bg-white/10">Back</Link>\n              </div>'''
new_header = '''              <div className="flex items-center gap-2">\n                <Link href={backHref} className="rounded-lg border border-white/20 px-3 py-2 text-[9.5px] font-semibold text-white/90 transition hover:bg-white/10">Back</Link>\n              </div>'''
if old_header not in text:
    raise SystemExit('POSP header action block not found')
text = text.replace(old_header, new_header, 1)

old_identity = '''            <PospSection id="posp-section-1" number="01" title="Identity & contact">\n              <SelectField label="RM" name="associate_employee_id" required options={salesManagers} placeholder="Select RM" defaultValue={initialValues.associate_employee_id} {...selectValidationHandlers} />\n              <PanInput label="PAN" name="pan_number" compact defaultValue={initialValues.pan_number} {...inputValidationHandlers} />\n              <IndianDateField label="Documents received" name="document_received_at" defaultValue={initialValues.document_received_at} inputClassName={dateInputClass} {...dateValidationHandlers} />\n              <Field label="Aadhaar" name="aadhaar_number" required inputMode="numeric" pattern="[0-9]{12}" maxLength={12} minLength={12} defaultValue={initialValues.aadhaar_number} {...inputValidationHandlers} />\n\n              <Field label="First Name" name="pos_first_name" required defaultValue={initialValues.pos_first_name} {...inputValidationHandlers} />\n              <Field label="Middle Name" name="pos_middle_name" defaultValue={initialValues.pos_middle_name} {...inputValidationHandlers} />\n              <Field label="Last Name" name="pos_last_name" required defaultValue={initialValues.pos_last_name} {...inputValidationHandlers} />\n              <IndianDateField label="Date of Birth" name="date_of_birth" required defaultValue={initialValues.date_of_birth} inputClassName={dateInputClass} {...dateValidationHandlers} />\n\n              <Field label="Mobile" name="applicant_phone" required inputMode="tel" pattern="(?:\\+91)?[6-9][0-9]{9}" defaultValue={initialValues.applicant_phone} {...inputValidationHandlers} />\n              <div className="md:col-span-1 xl:col-span-3"><Field label="Email" name="applicant_email" type="email" required defaultValue={initialValues.applicant_email} {...inputValidationHandlers} /></div>\n            </PospSection>'''
new_identity = '''            <PospSection id="posp-section-1" number="01" title="Identity & contact">\n              <div className="grid min-w-0 gap-3 md:col-span-2 md:grid-cols-2 xl:col-span-4 xl:grid-cols-5">\n                <SelectField label="RM" name="associate_employee_id" required options={salesManagers} placeholder="Select RM" defaultValue={initialValues.associate_employee_id} {...selectValidationHandlers} />\n                <Field label="First Name" name="pos_first_name" required defaultValue={initialValues.pos_first_name} {...inputValidationHandlers} />\n                <Field label="Middle Name" name="pos_middle_name" defaultValue={initialValues.pos_middle_name} {...inputValidationHandlers} />\n                <Field label="Last Name" name="pos_last_name" required defaultValue={initialValues.pos_last_name} {...inputValidationHandlers} />\n                <IndianDateField label="Date of Birth" name="date_of_birth" required defaultValue={initialValues.date_of_birth} inputClassName={dateInputClass} {...dateValidationHandlers} />\n              </div>\n              <div className="grid min-w-0 gap-3 md:col-span-2 md:grid-cols-2 xl:col-span-4 xl:grid-cols-5">\n                <IndianDateField label="Documents received" name="document_received_at" defaultValue={initialValues.document_received_at} inputClassName={dateInputClass} {...dateValidationHandlers} />\n                <PanInput label="PAN" name="pan_number" compact defaultValue={initialValues.pan_number} {...inputValidationHandlers} />\n                <Field label="Aadhaar" name="aadhaar_number" required inputMode="numeric" pattern="[0-9]{12}" maxLength={12} minLength={12} defaultValue={initialValues.aadhaar_number} {...inputValidationHandlers} />\n                <Field label="Mobile" name="applicant_phone" required inputMode="tel" pattern="(?:\\+91)?[6-9][0-9]{9}" defaultValue={initialValues.applicant_phone} {...inputValidationHandlers} />\n                <Field label="Email" name="applicant_email" type="email" required defaultValue={initialValues.applicant_email} {...inputValidationHandlers} />\n              </div>\n            </PospSection>'''
if old_identity not in text:
    raise SystemExit('POSP identity block not found')
text = text.replace(old_identity, new_identity, 1)

old_address = '''            <PospSection id="posp-section-2" number="02" title="Address">\n              <div className="md:col-span-2 xl:col-span-4"><Field label="Address" name="address" required defaultValue={initialValues.address} {...inputValidationHandlers} /></div>\n              <Field label="City" name="city" required defaultValue={initialValues.city} {...inputValidationHandlers} />\n              <Field label="State" name="state" required defaultValue={initialValues.state} {...inputValidationHandlers} />\n              <Field label="PIN Code" name="postal_code" required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} minLength={6} defaultValue={initialValues.postal_code} {...inputValidationHandlers} />\n            </PospSection>'''
new_address = '''            <PospSection id="posp-section-2" number="02" title="Address">\n              <div className="grid min-w-0 gap-3 md:col-span-2 md:grid-cols-2 xl:col-span-4 xl:grid-cols-5">\n                <div className="md:col-span-2 xl:col-span-2"><Field label="Address" name="address" required defaultValue={initialValues.address} {...inputValidationHandlers} /></div>\n                <Field label="City" name="city" required defaultValue={initialValues.city} {...inputValidationHandlers} />\n                <Field label="State" name="state" required defaultValue={initialValues.state} {...inputValidationHandlers} />\n                <Field label="PIN Code" name="postal_code" required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} minLength={6} defaultValue={initialValues.postal_code} {...inputValidationHandlers} />\n              </div>\n            </PospSection>'''
if old_address not in text:
    raise SystemExit('POSP address block not found')
text = text.replace(old_address, new_address, 1)

text = text.replace('label="Save & Continue" pendingLabel="Saving & opening documents…"', 'label="Upload Documents" pendingLabel="Saving & opening documents…"', 1)
text = text.replace('label="Save & Continue" pendingLabel="Saving & opening documents…"', 'label="Upload Documents" pendingLabel="Saving & opening documents…"', 1)

path.write_text(text, encoding='utf-8')
