"use server";

import * as XLSX from "xlsx";
import { getAccessibleCustomerIds } from "@/lib/employee-access-scope";
import { requireCapability } from "@/lib/master-data-server";
import { canAccessPolicyCommercials } from "@/lib/policy-commercial-access";
import { createSupabaseAdminClient } from "@/lib/supabase-admin";

export type PreviewStatus = "Ready" | "Warning" | "Error";
export type PayinPreviewRow = { rowNumber: number; policyId: string; policyNumber: string; insurer: string; projectedPayin: number; projectedTds: number; projectedNetPayin: number; billNumber: string; billAmount: number | null; billDate: string; actualTds: number | null; amountReceived: number | null; receiptDate: string; reference: string; difference: number | null; status: PreviewStatus; message: string };
export type PayoutPreviewRow = { rowNumber: number; payoutId: string; policyId: string; policyNumber: string; intermediaryType: string; intermediaryCode: string; payoutOdPercent: number; payoutTpPercent: number; projectedGrossPayout: number; projectedRetention: number; paidAmount: number | null; paidDate: string; reference: string; status: PreviewStatus; message: string };
export type ReconciliationUploadPreview = { totalRows: number; readyRows: number; warningRows: number; errorRows: number; skippedRows: number; payinRows: PayinPreviewRow[]; payoutRows: PayoutPreviewRow[]; message?: string };

type PolicyRow = { id: string; policy_no: string | null; customer_id: string; insurance_company_id: string | null; intermediary_type: string | null; intermediary_code: string | null; insurance_companies: { name?: string | null } | Array<{ name?: string | null }> | null };
type PayinDetailRow = { policy_id: string; total_projected_payin: number | string | null; tds_amount: number | string | null; payin_after_tds: number | string | null };
type PayoutDetailRow = { id: string; policy_id: string; intermediary_type: string | null; intermediary_code: string | null; od_payout_percent: number | string | null; tp_payout_percent: number | string | null; gross_payout: number | string | null; retention_amount: number | string | null; commercial_status: string | null; status: string | null };
type ReceiptRefRow = { insurer_id: string; bank_reference: string | null };
type PartnerPaymentRefRow = { intermediary_code: string | null; payment_reference: string | null };

const PAYIN_HEADERS = ["System Policy ID", "Policy Number", "Insurance Company", "Projected Pay-In", "Projected TDS", "Projected Net Pay-In", "Bill Number", "Bill Amount", "Bill Date", "Actual TDS", "Amount Received", "Receipt Date", "UTR / Reference"] as const;
const PAYOUT_HEADERS = ["System Payout ID", "System Policy ID", "Policy Number", "Intermediary Type", "Intermediary Code", "Payout OD %", "Payout TP %", "Projected Gross Payout", "Projected Retention", "Paid Amount", "Paid Date", "UTR / Reference"] as const;

export async function previewAccountsReconciliationUpload(formData: FormData): Promise<ReconciliationUploadPreview> {
  const profile = await requireCapability("view_accounts");
  if (!canAccessPolicyCommercials(profile)) throw new Error("Commercial details restricted");
  const file = formData.get("file");
  if (!(file instanceof File) || file.size === 0) return emptyPreview("Choose an Excel file to preview.");
  if (file.size > 8 * 1024 * 1024) return emptyPreview("The upload must be 8 MB or smaller.");

  let workbook: XLSX.WorkBook;
  try { workbook = XLSX.read(await file.arrayBuffer(), { type: "array", cellDates: false }); } catch { return emptyPreview("The workbook could not be read. Upload an .xlsx file generated from the Accounts workbook."); }
  if (!workbook.SheetNames.includes("Pay-In") || !workbook.SheetNames.includes("Pay-Out")) return emptyPreview("The workbook must contain both Pay-In and Pay-Out sheets generated by INSUREIT.");

  const payinRaw = XLSX.utils.sheet_to_json<Record<string, unknown>>(workbook.Sheets["Pay-In"], { defval: "", raw: false });
  const payoutRaw = XLSX.utils.sheet_to_json<Record<string, unknown>>(workbook.Sheets["Pay-Out"], { defval: "", raw: false });
  const headerError = validateHeaders(payinRaw, PAYIN_HEADERS, "Pay-In") ?? validateHeaders(payoutRaw, PAYOUT_HEADERS, "Pay-Out");
  if (headerError) return emptyPreview(headerError);
  if (payinRaw.length + payoutRaw.length > 2000) return emptyPreview("Preview supports up to 2,000 workbook rows at a time.");

  const activePayin = payinRaw.map((row, index) => ({ row, rowNumber: index + 2 })).filter(({ row }) => hasPayinInput(row));
  const activePayout = payoutRaw.map((row, index) => ({ row, rowNumber: index + 2 })).filter(({ row }) => hasPayoutInput(row));
  const skippedRows = payinRaw.length + payoutRaw.length - activePayin.length - activePayout.length;
  if (!activePayin.length && !activePayout.length) return { ...emptyPreview("No Pay-In or Pay-Out transaction values were entered in the workbook."), skippedRows };

  const policyIds = [...new Set([...activePayin.map(({ row }) => text(row["System Policy ID"])), ...activePayout.map(({ row }) => text(row["System Policy ID"]))].filter(validUuid))];
  const payoutIds = [...new Set(activePayout.map(({ row }) => text(row["System Payout ID"])).filter(validUuid))];
  const db = createSupabaseAdminClient();
  const customerIds = await getAccessibleCustomerIds(profile.id, profile.role, "view_accounts");
  if (customerIds !== null && !customerIds.length) return emptyPreview("No uploaded rows are inside your Accounts access scope.");

  let policies: PolicyRow[] = [];
  let payins: PayinDetailRow[] = [];
  let payouts: PayoutDetailRow[] = [];
  if (policyIds.length) {
    let policyQuery = db.from("policies").select("id,policy_no,customer_id,insurance_company_id,intermediary_type,intermediary_code,insurance_companies(name)").in("id", policyIds);
    if (customerIds !== null) policyQuery = policyQuery.in("customer_id", customerIds);
    const [{ data: policyData, error: policyError }, { data: payinData, error: payinError }] = await Promise.all([policyQuery, db.from("policy_payin_details").select("policy_id,total_projected_payin,tds_amount,payin_after_tds").in("policy_id", policyIds)]);
    if (policyError || payinError) throw new Error(policyError?.message ?? payinError?.message ?? "Unable to validate reconciliation workbook.");
    policies = (policyData ?? []) as PolicyRow[];
    payins = (payinData ?? []) as PayinDetailRow[];
  }
  if (payoutIds.length) {
    const { data, error } = await db.from("policy_intermediary_payouts").select("id,policy_id,intermediary_type,intermediary_code,od_payout_percent,tp_payout_percent,gross_payout,retention_amount,commercial_status,status").in("id", payoutIds);
    if (error) throw new Error(error.message);
    payouts = (data ?? []) as PayoutDetailRow[];
  }

  const policyMap = new Map(policies.map((policy) => [policy.id, policy]));
  const payinMap = new Map(payins.map((row) => [row.policy_id, row]));
  const payoutMap = new Map(payouts.map((row) => [row.id, row]));

  const payinRefs = [...new Set(activePayin.map(({ row }) => text(row["UTR / Reference"])).filter(Boolean))];
  const payoutRefs = [...new Set(activePayout.map(({ row }) => text(row["UTR / Reference"])).filter(Boolean))];
  let existingReceipts: ReceiptRefRow[] = [];
  let existingPartnerPayments: PartnerPaymentRefRow[] = [];
  if (payinRefs.length) { const { data } = await db.from("accounts_receipts").select("insurer_id,bank_reference").in("bank_reference", payinRefs); existingReceipts = (data ?? []) as ReceiptRefRow[]; }
  if (payoutRefs.length) { const { data } = await db.from("partner_payments").select("intermediary_code,payment_reference").in("payment_reference", payoutRefs); existingPartnerPayments = (data ?? []) as PartnerPaymentRefRow[]; }
  const existingReceiptKeys = new Set(existingReceipts.map((row) => `${row.insurer_id}|${normalizeRef(row.bank_reference)}`));
  const existingPayoutKeys = new Set(existingPartnerPayments.map((row) => `${normalizeRef(row.intermediary_code)}|${normalizeRef(row.payment_reference)}`));
  const payinUploadGroups = new Map<string, string>();
  const payoutUploadGroups = new Map<string, string>();

  const payinRows: PayinPreviewRow[] = activePayin.map(({ row, rowNumber }) => {
    const policyId = text(row["System Policy ID"]); const policy = policyMap.get(policyId); const livePayin = payinMap.get(policyId);
    const relation = policy?.insurance_companies;
    const insurer = Array.isArray(relation) ? relation[0]?.name ?? "" : relation?.name ?? text(row["Insurance Company"]);
    const projectedPayin = money(livePayin?.total_projected_payin); const projectedTds = money(livePayin?.tds_amount); const projectedNetPayin = money(livePayin?.payin_after_tds);
    const billNumber = text(row["Bill Number"]); const billAmount = optionalMoney(row["Bill Amount"]); const billDate = normalizedDate(row["Bill Date"]); const actualTds = optionalMoney(row["Actual TDS"]); const amountReceived = optionalMoney(row["Amount Received"]); const receiptDate = normalizedDate(row["Receipt Date"]); const reference = text(row["UTR / Reference"]); const difference = billAmount === null ? null : money(projectedPayin - billAmount);
    const issues: Array<{ status: PreviewStatus; message: string }> = [];
    if (!validUuid(policyId) || !policy) issues.push(error("System Policy ID is invalid, inaccessible, or no longer matches a policy."));
    if (policy && !livePayin) issues.push(error("Projected Pay-In is missing for this policy. Complete Policy Onboarding / Commercial Review first."));
    if (!billNumber || billAmount === null || !billDate) issues.push(error("Bill Number, Bill Amount and Bill Date are required for every Pay-In transaction row."));
    if (billAmount !== null && billAmount <= 0) issues.push(error("Bill Amount must be greater than zero."));
    if (actualTds !== null && actualTds < 0) issues.push(error("Actual TDS cannot be negative."));
    if (amountReceived !== null && amountReceived <= 0) issues.push(error("Amount Received must be greater than zero when entered."));
    if (amountReceived !== null && (!receiptDate || !reference)) issues.push(error("Receipt Date and UTR / Reference are required when Amount Received is entered."));
    if (amountReceived === null && (receiptDate || reference)) issues.push(error("Amount Received is required when receipt details are entered."));
    if (amountReceived !== null && actualTds !== null && billAmount !== null && money(amountReceived + actualTds) > money(billAmount) + 0.01) issues.push(error("Amount Received + Actual TDS cannot exceed the policy Bill Amount."));
    if (amountReceived !== null && reference && policy?.insurance_company_id) {
      const key = `${policy.insurance_company_id}|${normalizeRef(reference)}`;
      if (existingReceiptKeys.has(key)) issues.push(error("This insurer UTR / Reference already exists in INSUREIT."));
      const priorDate = payinUploadGroups.get(key);
      if (priorDate && priorDate !== receiptDate) issues.push(error("The same insurer UTR / Reference is used with different Receipt Dates in this workbook."));
      else if (!priorDate) payinUploadGroups.set(key, receiptDate);
    }
    if (policy && Math.abs(number(row["Projected Pay-In"]) - projectedPayin) > 0.01) issues.push(warning("Projected Pay-In was edited in Excel; the live INSUREIT value will be used."));
    if (policy && Math.abs(number(row["Projected TDS"]) - projectedTds) > 0.01) issues.push(warning("Projected TDS was edited in Excel; the live INSUREIT value will be used."));
    if (policy && Math.abs(number(row["Projected Net Pay-In"]) - projectedNetPayin) > 0.01) issues.push(warning("Projected Net Pay-In was edited in Excel; the live INSUREIT value will be used."));
    return { rowNumber, policyId, policyNumber: policy?.policy_no ?? text(row["Policy Number"]), insurer, projectedPayin, projectedTds, projectedNetPayin, billNumber, billAmount, billDate, actualTds, amountReceived, receiptDate, reference, difference, ...summarize(issues) };
  });

  const payoutRows: PayoutPreviewRow[] = activePayout.map(({ row, rowNumber }) => {
    const payoutId = text(row["System Payout ID"]); const policyId = text(row["System Policy ID"]); const policy = policyMap.get(policyId); const livePayout = payoutMap.get(payoutId);
    const intermediaryType = text(livePayout?.intermediary_type ?? policy?.intermediary_type ?? row["Intermediary Type"]); const intermediaryCode = text(livePayout?.intermediary_code ?? policy?.intermediary_code ?? row["Intermediary Code"]);
    const payoutOdPercent = money(livePayout?.od_payout_percent); const payoutTpPercent = money(livePayout?.tp_payout_percent); const projectedGrossPayout = money(livePayout?.gross_payout); const projectedRetention = money(livePayout?.retention_amount); const paidAmount = optionalMoney(row["Paid Amount"]); const paidDate = normalizedDate(row["Paid Date"]); const reference = text(row["UTR / Reference"]);
    const issues: Array<{ status: PreviewStatus; message: string }> = [];
    if (!validUuid(policyId) || !policy) issues.push(error("System Policy ID is invalid or outside your Accounts access scope."));
    if (!validUuid(payoutId) || !livePayout || livePayout.policy_id !== policyId) issues.push(error("System Payout ID is invalid or no longer belongs to this policy."));
    if (livePayout && !["entered", "reviewed"].includes(text(livePayout.commercial_status).toLowerCase())) issues.push(error("Commercial payout terms are not finalized. Complete Commercial Review first."));
    if (projectedGrossPayout <= 0) issues.push(error("Projected Gross Payout must be greater than zero before Accounts can record a payment."));
    if (!intermediaryCode) issues.push(error("Intermediary Code is missing for this payout."));
    if (paidAmount === null || paidAmount <= 0) issues.push(error("Paid Amount must be greater than zero for a Pay-Out transaction row."));
    if (!paidDate || !reference) issues.push(error("Paid Date and UTR / Reference are required for every Pay-Out transaction row."));
    if (reference && intermediaryCode) {
      const key = `${normalizeRef(intermediaryCode)}|${normalizeRef(reference)}`;
      if (existingPayoutKeys.has(key)) issues.push(error("This intermediary UTR / Reference already exists in INSUREIT."));
      const priorDate = payoutUploadGroups.get(key);
      if (priorDate && priorDate !== paidDate) issues.push(error("The same intermediary UTR / Reference is used with different Paid Dates in this workbook."));
      else if (!priorDate) payoutUploadGroups.set(key, paidDate);
    }
    if (livePayout && Math.abs(number(row["Projected Gross Payout"]) - projectedGrossPayout) > 0.01) issues.push(warning("Projected Gross Payout was edited in Excel; the live INSUREIT value will be used."));
    if (livePayout && Math.abs(number(row["Projected Retention"]) - projectedRetention) > 0.01) issues.push(warning("Projected Retention was edited in Excel; the live INSUREIT value will be used."));
    if (livePayout && Math.abs(number(row["Payout OD %"]) - payoutOdPercent) > 0.001) issues.push(warning("Payout OD % was edited in Excel; the live INSUREIT value will be used."));
    if (livePayout && Math.abs(number(row["Payout TP %"]) - payoutTpPercent) > 0.001) issues.push(warning("Payout TP % was edited in Excel; the live INSUREIT value will be used."));
    return { rowNumber, payoutId, policyId, policyNumber: policy?.policy_no ?? text(row["Policy Number"]), intermediaryType, intermediaryCode, payoutOdPercent, payoutTpPercent, projectedGrossPayout, projectedRetention, paidAmount, paidDate, reference, ...summarize(issues) };
  });

  const all = [...payinRows, ...payoutRows];
  return { totalRows: all.length, readyRows: all.filter((row) => row.status === "Ready").length, warningRows: all.filter((row) => row.status === "Warning").length, errorRows: all.filter((row) => row.status === "Error").length, skippedRows, payinRows, payoutRows };
}

function hasPayinInput(row: Record<string, unknown>) { return ["Bill Number", "Bill Amount", "Bill Date", "Actual TDS", "Amount Received", "Receipt Date", "UTR / Reference"].some((key) => text(row[key]) !== ""); }
function hasPayoutInput(row: Record<string, unknown>) { return ["Paid Amount", "Paid Date", "UTR / Reference"].some((key) => text(row[key]) !== ""); }
function validateHeaders(rows: Array<Record<string, unknown>>, required: readonly string[], sheet: string) { if (!rows.length) return null; const present = new Set(Object.keys(rows[0] ?? {}).map((value) => value.trim())); const missing = required.filter((header) => !present.has(header)); return missing.length ? `${sheet} is missing required column${missing.length > 1 ? "s" : ""}: ${missing.join(", ")}.` : null; }
function summarize(issues: Array<{ status: PreviewStatus; message: string }>): { status: PreviewStatus; message: string } { if (!issues.length) return { status: "Ready", message: "Ready for Confirm Import once the posting stage is enabled." }; const status: PreviewStatus = issues.some((item) => item.status === "Error") ? "Error" : "Warning"; return { status, message: issues.map((item) => item.message).join(" ") }; }
function error(message: string) { return { status: "Error" as const, message }; }
function warning(message: string) { return { status: "Warning" as const, message }; }
function emptyPreview(message: string): ReconciliationUploadPreview { return { totalRows: 0, readyRows: 0, warningRows: 0, errorRows: 0, skippedRows: 0, payinRows: [], payoutRows: [], message }; }
function text(value: unknown) { return String(value ?? "").trim(); }
function normalizeRef(value: unknown) { return text(value).replace(/\s+/g, "").toUpperCase(); }
function number(value: unknown) { const parsed = Number(String(value ?? "").replace(/,/g, "").trim() || 0); return Number.isFinite(parsed) ? parsed : 0; }
function money(value: unknown) { return Math.round(number(value) * 100) / 100; }
function optionalMoney(value: unknown) { const raw = text(value); return raw === "" ? null : money(raw); }
function validUuid(value: string) { return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value); }
function normalizedDate(value: unknown) { const raw = text(value); if (!raw) return ""; if (/^\d{4}-\d{2}-\d{2}$/.test(raw)) return raw; const parsed = new Date(raw); if (Number.isNaN(parsed.getTime())) return ""; return new Intl.DateTimeFormat("en-CA", { year: "numeric", month: "2-digit", day: "2-digit", timeZone: "Asia/Kolkata" }).format(parsed); }
