import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useMemo, useState } from 'react';
import { Linking, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

import { Screen } from '@/components/ui';
import { palette, roleTheme } from '@/lib/theme';

const faqs = [
  ['How do I track my claim?', 'Open Claims, select your claim, and follow its journey card for real-time status, document, survey, and settlement updates.'],
  ['How do I upload documents?', 'Open your claim and choose Upload Documents. You can add photos from your camera or files from your phone.'],
  ['How long does approval take?', 'Timing varies by insurer and survey status. Your claim journey shows the current stage and the next action.'],
  ['How do I contact my claim manager?', 'Raise a claim support ticket and choose the related claim. It is routed to that claim’s current manager.'],
  ['What documents are required for a claim?', 'Required documents are shown in the Upload Documents checklist for your current claim stage.'],
  ['What is a cashless claim?', 'A cashless claim is handled through a network garage, where eligible repair costs are coordinated directly with the insurer.'],
];

export default function HelpFaqsScreen() {
  const router = useRouter(); const [query, setQuery] = useState(''); const [open, setOpen] = useState(0);
  const items = useMemo(() => faqs.filter(([question, answer]) => `${question} ${answer}`.toLowerCase().includes(query.trim().toLowerCase())), [query]);
  return <Screen title="Help & FAQs" showTitleHeader={false}><View style={styles.heading}><Text style={styles.title}>Help & FAQs</Text><Text style={styles.sub}>Answers for your claim journey.</Text></View><View style={styles.search}><MaterialCommunityIcons name="magnify" size={20} color={palette.slate} /><TextInput value={query} onChangeText={setQuery} placeholder="Search FAQs or topics" placeholderTextColor="#8090A6" style={styles.searchInput} /></View><View style={styles.list}>{items.map(([question, answer], index) => { const expanded = open === index; return <Pressable key={question} accessibilityRole="button" onPress={() => setOpen(expanded ? -1 : index)} style={styles.faq}><View style={styles.faqTop}><View style={styles.questionIcon}><MaterialCommunityIcons name="help" size={16} color="#FFFFFF" /></View><Text style={styles.question}>{question}</Text><MaterialCommunityIcons name={expanded ? 'chevron-up' : 'chevron-down'} size={20} color={palette.slate} /></View>{expanded ? <Text style={styles.answer}>{answer}</Text> : null}</Pressable>; })}</View>{!items.length ? <Text style={styles.empty}>No help topics match that search.</Text> : null}<View style={styles.helpCard}><View style={styles.helpIcon}><MaterialCommunityIcons name="headset" size={26} color={roleTheme.customer.accent} /></View><Text style={styles.helpTitle}>Still need help?</Text><Text style={styles.helpBody}>Our support team is here to help with every stage of your claim.</Text><View style={styles.helpActions}><Pressable accessibilityRole="button" onPress={() => void Linking.openURL('tel:+916264911014')} style={styles.chatButton}><MaterialCommunityIcons name="phone-outline" size={16} color={roleTheme.customer.accent} /><Text style={styles.chatText}>Call us</Text></Pressable><Pressable accessibilityRole="button" onPress={() => router.push('/customer/raise-support-ticket')} style={styles.ticketButton}><MaterialCommunityIcons name="plus" size={16} color="#FFFFFF" /><Text style={styles.ticketText}>Create ticket</Text></Pressable></View></View></Screen>;
}
const styles = StyleSheet.create({ heading: { marginTop: -22, marginBottom: 10 }, title: { color: palette.ink, fontSize: 23, fontWeight: '900' }, sub: { color: palette.slate, fontSize: 11.5, fontWeight: '700', marginTop: 2 }, search: { height: 48, borderRadius: 14, borderWidth: 1, borderColor: '#DCE8F4', backgroundColor: '#FFFFFF', flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 11, marginBottom: 12 }, searchInput: { flex: 1, color: palette.ink, fontSize: 12, fontWeight: '700' }, list: { gap: 8 }, faq: { borderRadius: 15, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DCE8F4', padding: 11 }, faqTop: { flexDirection: 'row', alignItems: 'center', gap: 9 }, questionIcon: { width: 26, height: 26, borderRadius: 13, backgroundColor: roleTheme.customer.accent, alignItems: 'center', justifyContent: 'center' }, question: { flex: 1, color: palette.ink, fontSize: 12, lineHeight: 16, fontWeight: '900' }, answer: { color: palette.slate, fontSize: 11, lineHeight: 16, fontWeight: '700', marginLeft: 35, marginTop: 8, paddingTop: 8, borderTopWidth: 1, borderTopColor: '#E5ECF5' }, empty: { color: palette.slate, textAlign: 'center', marginVertical: 20, fontSize: 12, fontWeight: '700' }, helpCard: { alignItems: 'center', borderRadius: 19, backgroundColor: '#F0F6FF', borderWidth: 1, borderColor: '#D1E1FA', padding: 16, marginTop: 14, marginBottom: 8 }, helpIcon: { width: 48, height: 48, borderRadius: 16, backgroundColor: '#E8F8F0', alignItems: 'center', justifyContent: 'center' }, helpTitle: { color: palette.navy, fontSize: 17, fontWeight: '900', marginTop: 8 }, helpBody: { color: palette.slate, fontSize: 11, lineHeight: 16, fontWeight: '700', textAlign: 'center', marginTop: 3 }, helpActions: { flexDirection: 'row', gap: 8, width: '100%', marginTop: 13 }, chatButton: { flex: 1, height: 39, borderRadius: 12, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#BFEBD0', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 }, chatText: { color: roleTheme.customer.accent, fontSize: 10.5, fontWeight: '900' }, ticketButton: { flex: 1, height: 39, borderRadius: 12, backgroundColor: roleTheme.customer.accent, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 }, ticketText: { color: '#FFFFFF', fontSize: 10.5, fontWeight: '900' } });
