"use client";

import Link from "next/link";
import { Plus, Search, Shield, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";

type PolicyRow = { id: string; policy_no: string; policy_type: string; start_date: string; end_date: string; customers: { company_name: string | null; contact_name: string } | null; vehicles: { vehicle_no: string } | null; insurance_companies: { name: string } | null };
const PAGE_SIZE = 15;
function policyStatus(endDate: string) { const end = new Date(`${endDate}T23:59:59`); const now = new Date(); const days = Math.ceil((end.getTime() - now.getTime()) / 86400000); return days < 0 ? "Expired" : days <= 30 ? "Expiring soon" : "Active"; }
function formatDate(value: string) { const date = new Date(`${value}T00:00:00`); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric" }).format(date); }

export function PolicyWorkspace({ rows }: { rows: PolicyRow[] }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [page, setPage] = useState(1);
  const filtered = useMemo(() => rows.filter((row) => { const current = policyStatus(row.end_date); const haystack = [row.policy_no, row.policy_type, row.insurance_companies?.name, row.vehicles?.vehicle_no, row.customers?.company_name, row.customers?.contact_name].filter(Boolean).join(" ").toLowerCase(); return (status === "all" || current === status) && (!query.trim() || haystack.includes(query.trim().toLowerCase())); }), [query, rows, status]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const safePage = Math.min(page, totalPages); const pageRows = filtered.slice((safePage - 1) * PAGE_SIZE, safePage * PAGE_SIZE);
  return <section className="ui-glass-panel mx-auto max-w-[1440px] overflow-hidden rounded-[24px] border border-white/80 bg-white/78 shadow-[0_22px_65px_rgba(39,44,91,0.09)] backdrop-blur-xl">
    <div className="flex flex-col gap-3 border-b border-[#E8EAF3] bg-gradient-to-r from-[#FFF9F1] via-white to-[#F5F2FF] px-4 py-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-[#F59E0B] to-[#FF6F61] text-white shadow-[0_12px_28px_rgba(245,158,11,.24)]"><Shield className="h-5 w-5" /></span><div><p className="font-display text-[15px] font-semibold text-[#1A1D3C]">Policy registry</p><p className="text-[9.5px] font-medium text-[#7A8298]">{filtered.length} policies in current view</p></div></div><div className="flex min-w-0 flex-1 flex-col gap-2 sm:flex-row lg:max-w-[820px] lg:justify-end"><label className="relative flex-1 lg:max-w-md"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#8D95A9]" /><input value={query} onChange={(e) => { setQuery(e.target.value); setPage(1); }} placeholder="Search policy, insurer, vehicle or customer" className="h-10 w-full rounded-xl pl-10 text-[11.5px]" /></label><label className="relative"><SlidersHorizontal className="pointer-events-none absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-[#8D95A9]" /><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }} className="h-10 min-w-[165px] rounded-xl pl-9 text-[11px]"><option value="all">All statuses</option><option value="Active">Active</option><option value="Expiring soon">Expiring soon</option><option value="Expired">Expired</option></select></label><Link href="/policies/new" className="ui-primary-action inline-flex h-10 items-center justify-center gap-2 rounded-xl px-4 text-[11px] font-bold text-white"><Plus className="h-4 w-4" />Add Policy</Link></div></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[1050px] table-fixed text-left text-[11px] text-[#252944]"><thead className="sticky top-0 z-10 border-b border-[#E7E9F1] bg-[#F8F8FD]/95 text-[9px] font-bold uppercase tracking-[0.07em] text-[#747D95] backdrop-blur-xl"><tr><th className="w-[180px] px-4 py-3">Policy</th><th className="w-[190px] px-3 py-3">Insurer</th><th className="w-[190px] px-3 py-3">Customer</th><th className="w-[130px] px-3 py-3">Vehicle</th><th className="w-[190px] px-3 py-3">Validity</th><th className="w-[110px] px-3 py-3">Status</th><th className="w-[70px] px-3 py-3 text-center">Action</th></tr></thead><tbody className="divide-y divide-[#EEF0F6]">{pageRows.map((policy) => { const current = policyStatus(policy.end_date); return <tr key={policy.id} className="h-14 transition hover:bg-[#FFF8F2]"><td className="px-4"><Link href={`/policies/${policy.id}/edit`} className="block truncate font-display text-[12px] font-semibold text-[#1A1D3C] hover:text-[#5B4BDA]">{policy.policy_no}</Link><span className="text-[9.5px] text-[#7A8298]">{policy.policy_type}</span></td><td className="px-3"><span className="block truncate">{policy.insurance_companies?.name ?? "—"}</span></td><td className="px-3"><span className="block truncate">{policy.customers?.contact_name ?? "—"}</span></td><td className="px-3 font-mono">{policy.vehicles?.vehicle_no ?? "—"}</td><td className="px-3">{formatDate(policy.start_date)} – {formatDate(policy.end_date)}</td><td className="px-3"><span className={`rounded-full border px-2.5 py-1 text-[9px] font-bold ${current === "Active" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : current === "Expired" ? "border-red-200 bg-red-50 text-red-700" : "border-amber-200 bg-amber-50 text-amber-700"}`}>{current}</span></td><td className="px-3 text-center"><Link href={`/policies/${policy.id}/edit`} className="rounded-lg border border-[#D8D5FF] bg-[#F2F0FF] px-2.5 py-1.5 text-[9.5px] font-bold text-[#5B4BDA]">Edit</Link></td></tr>; })}</tbody></table>{!pageRows.length ? <div className="px-4 py-16 text-center"><p className="font-display text-[13px] font-semibold text-[#303550]">No matching policies</p><p className="mt-1 text-[10.5px] text-[#9299AA]">Adjust the search or status filter.</p></div> : null}</div>
    <div className="flex items-center justify-between border-t border-[#E8EAF2] bg-white/70 px-4 py-3 text-[10px] text-[#6E768C]"><p>Showing {pageRows.length ? (safePage - 1) * PAGE_SIZE + 1 : 0}–{Math.min(safePage * PAGE_SIZE, filtered.length)} of {filtered.length}</p><div className="flex gap-1"><button type="button" disabled={safePage === 1} onClick={() => setPage((p) => Math.max(1, p - 1))} className="h-8 rounded-lg border border-[#D9DCE7] bg-white px-3 font-semibold disabled:opacity-40">Previous</button><button type="button" disabled={safePage === totalPages} onClick={() => setPage((p) => Math.min(totalPages, p + 1))} className="h-8 rounded-lg border border-[#D9DCE7] bg-white px-3 font-semibold disabled:opacity-40">Next</button></div></div>
  </section>;
}
