"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

type PolicyRow = { id: string; policy_no: string; policy_type: string; start_date: string; end_date: string; customers: { company_name: string | null; contact_name: string } | null; vehicles: { vehicle_no: string } | null; insurance_companies: { name: string } | null };
const PAGE_SIZE = 15;

function policyStatus(endDate: string) { const end = new Date(`${endDate}T23:59:59`); const now = new Date(); const days = Math.ceil((end.getTime() - now.getTime()) / 86400000); return days < 0 ? "Expired" : days <= 30 ? "Expiring soon" : "Active"; }
function formatDate(value: string) { const date = new Date(`${value}T00:00:00`); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric" }).format(date); }

export function PolicyWorkspace({ rows }: { rows: PolicyRow[] }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [page, setPage] = useState(1);
  const filtered = useMemo(() => rows.filter((row) => { const current = policyStatus(row.end_date); const haystack = [row.policy_no, row.policy_type, row.insurance_companies?.name, row.vehicles?.vehicle_no, row.customers?.company_name, row.customers?.contact_name].filter(Boolean).join(" ").toLowerCase(); return (status === "all" || current === status) && (!query.trim() || haystack.includes(query.trim().toLowerCase())); }), [query, rows, status]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const safePage = Math.min(page, totalPages); const pageRows = filtered.slice((safePage - 1) * PAGE_SIZE, safePage * PAGE_SIZE);
  return <section className="mx-auto max-w-[1440px] overflow-hidden rounded-xl border border-[#E2E8F0] bg-white shadow-[0_1px_2px_rgba(15,23,42,0.04)]">
    <div className="flex flex-col gap-2 border-b border-[#E2E8F0] px-3 py-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex min-w-0 flex-1 flex-col gap-2 sm:flex-row"><input value={query} onChange={(e) => { setQuery(e.target.value); setPage(1); }} placeholder="Search policy, insurer, vehicle or customer" className="h-9 min-w-0 flex-1 rounded-md border border-[#CBD5E1] px-3 text-[11.5px] lg:max-w-md" /><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }} className="h-9 min-w-[155px] rounded-md border border-[#CBD5E1] bg-white px-2.5 text-[11px]"><option value="all">All statuses</option><option value="Active">Active</option><option value="Expiring soon">Expiring soon</option><option value="Expired">Expired</option></select><Link href="/policies/new" className="inline-flex h-9 items-center justify-center rounded-md bg-[#4F46E5] px-4 text-[11px] font-semibold text-white shadow-sm hover:bg-[#4338CA]">+ Add Policy</Link></div></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[1050px] table-fixed text-left text-[11px] text-[#1E293B]"><thead className="border-b border-[#E2E8F0] bg-[#F8FAFC] text-[9.5px] font-semibold uppercase tracking-[0.04em] text-[#64748B]"><tr><th className="w-[180px] px-3 py-2.5">Policy</th><th className="w-[190px] px-3 py-2.5">Insurer</th><th className="w-[190px] px-3 py-2.5">Customer</th><th className="w-[130px] px-3 py-2.5">Vehicle</th><th className="w-[190px] px-3 py-2.5">Validity</th><th className="w-[110px] px-3 py-2.5">Status</th><th className="w-[70px] px-3 py-2.5 text-center">Action</th></tr></thead><tbody className="divide-y divide-[#EEF2F6]">{pageRows.map((policy) => { const current = policyStatus(policy.end_date); return <tr key={policy.id} className="h-12 hover:bg-[#FAFCFF]"><td className="px-3"><Link href={`/policies/${policy.id}/edit`} className="block truncate text-[12px] font-semibold text-[#0F172A] hover:text-[#4F46E5]">{policy.policy_no}</Link><span className="text-[9.5px] text-[#64748B]">{policy.policy_type}</span></td><td className="px-3"><span className="block truncate">{policy.insurance_companies?.name ?? "—"}</span></td><td className="px-3"><span className="block truncate">{policy.customers?.contact_name ?? "—"}</span></td><td className="px-3 font-mono">{policy.vehicles?.vehicle_no ?? "—"}</td><td className="px-3">{formatDate(policy.start_date)} – {formatDate(policy.end_date)}</td><td className="px-3"><span className={`rounded-full border px-2 py-0.5 text-[9px] font-semibold ${current === "Active" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : current === "Expired" ? "border-red-200 bg-red-50 text-red-700" : "border-amber-200 bg-amber-50 text-amber-700"}`}>{current}</span></td><td className="px-3 text-center"><Link href={`/policies/${policy.id}/edit`} className="font-semibold text-[#4F46E5]">Edit</Link></td></tr>; })}</tbody></table>{!pageRows.length ? <div className="px-4 py-16 text-center"><p className="text-[12px] font-semibold text-[#334155]">No matching policies</p><p className="mt-1 text-[10.5px] text-[#94A3B8]">Adjust the search or status filter.</p></div> : null}</div>
    <div className="flex items-center justify-between border-t border-[#E2E8F0] px-3 py-2.5 text-[10px] text-[#64748B]"><p>Showing {pageRows.length ? (safePage - 1) * PAGE_SIZE + 1 : 0}–{Math.min(safePage * PAGE_SIZE, filtered.length)} of {filtered.length}</p><div className="flex gap-1"><button type="button" disabled={safePage === 1} onClick={() => setPage((p) => Math.max(1, p - 1))} className="h-7 rounded-md border border-[#CBD5E1] px-2.5 disabled:opacity-40">Previous</button><button type="button" disabled={safePage === totalPages} onClick={() => setPage((p) => Math.min(totalPages, p + 1))} className="h-7 rounded-md border border-[#CBD5E1] px-2.5 disabled:opacity-40">Next</button></div></div>
  </section>;
}
