-- Life/Health classification is canonical in policies.business_line.
-- Do not rewrite policies.business_type here: that field carries lifecycle values such as
-- New/Renewal and must remain intact. Reporting must group Life/Health by business_line.
-- This migration intentionally contains no data mutation so existing lifecycle semantics
-- are preserved while the report-side mapping is corrected in application code.
