import Link from "next/link";
import { Download, ExternalLink, Filter } from "lucide-react";
import { AppShell } from "@/components/shell";
import { requireCapability } from "@/lib/master-data-server";
import { emptyClaimsReport, loadClaimsReport, type ClaimsFilters, type ClaimsQuery, type ClaimsReport } from "@/lib/reports/claims";

export const dynamic="force-dynamic"; export const revalidate=0;
const PERIODS=[{key:"90d",label:"Last 90 days"},{key:"mtd",label:"Month to date"},{key:"ytd",label:"Year to date"},{key:"all",label:"All time"}] as const;
type Props={searchParams:Promise<ClaimsQuery>};

export default async function ClaimsReportsPage({searchParams}:Props){
  const profile=await requireCapability("view_reports"); const query=await searchParams;
  let payload:Awaited<ReturnType<typeof loadClaimsReport>>|null=null; let loadError=false;
  try{payload=await loadClaimsReport(profile,query)}catch(error){console.error("[reports] claims report failed",error instanceof Error?error.message:"unknown error");loadError=true}
  const report=payload?.report??emptyClaimsReport(); const filters=payload?.filters??fallbackFilters();
  const pages=Math.max(1,Math.ceil(report.register.total_count/Math.max(report.register.page_size,1)));
  const exportHref=href("/reports/export/claims",filters);
  return <AppShell title="Reports"><div className="mx-auto max-w-[1560px] space-y-4 pb-8">
    <header className="portal-card overflow-hidden">
      <div className="border-b border-[#e8ecf2] px-5 py-5 sm:px-6"><h1 className="text-[26px] font-semibold tracking-[-0.025em] text-[#13203b] sm:text-[30px]">Claims portfolio & aging</h1><ReportTabs/></div>
      <div className="px-5 py-4 sm:px-6">
        <div className="flex flex-wrap gap-2">{PERIODS.map(x=><Link key={x.key} href={`/reports/claims?period=${x.key}`} className={`rounded-lg border px-3 py-2 text-[10px] font-bold ${filters.period===x.key?"border-[#223a78] bg-[#223a78] text-white":"border-[#dfe5ee] bg-white text-[#506077]"}`}>{x.label}</Link>)}</div>
        <form action="/reports/claims" method="get" className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-[140px_140px_minmax(190px,1fr)_minmax(180px,1fr)_170px_auto_auto]">
          <input type="hidden" name="period" value="custom"/>
          <Field label="From"><input name="from" type="date" defaultValue={filters.fromDate??""} className={inputClass}/></Field>
          <Field label="To"><input name="to" type="date" defaultValue={filters.toDate??""} className={inputClass}/></Field>
          <Field label="Insurance company"><select name="insurer" defaultValue={filters.insurerId??""} className={inputClass}><option value="">All insurers</option>{report.filters.insurers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>
          <Field label="Claim status"><select name="status" defaultValue={filters.status??""} className={inputClass}><option value="">All statuses</option>{report.filters.statuses.map(x=><option key={x} value={x}>{x}</option>)}</select></Field>
          <Field label="Service mode"><select name="mode" defaultValue={filters.serviceMode??""} className={inputClass}><option value="">All modes</option><option value="broker_managed">Broker managed</option><option value="self_managed">Self managed</option></select></Field>
          <button className="mt-auto inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-[#172a5c] px-4 text-[10.5px] font-bold text-white"><Filter className="h-3.5 w-3.5"/>Apply</button>
          <Link href="/reports/claims" className="mt-auto inline-flex h-10 items-center justify-center rounded-lg border border-[#dfe5ee] bg-white px-4 text-[10.5px] font-bold text-[#526174]">Reset</Link>
        </form>
      </div>
    </header>
    {loadError?<div className="rounded-xl border border-red-200 bg-red-50 px-5 py-4 text-[11px] font-bold text-red-700">Reporting service unavailable.</div>:null}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Claims" value={integer(report.summary.claim_count)}/><Metric label="Open" value={integer(report.summary.open_claim_count)}/><Metric label="Settled" value={integer(report.summary.settled_claim_count)}/><Metric label="Avg open age" value={`${integer(report.summary.average_open_age_days)} days`}/><Metric label="Estimated loss" value={currency(report.summary.estimated_loss)}/><Metric label="Settlement" value={currency(report.summary.settlement_amount)}/></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{normalizedAging(report).map(x=><article key={x.key} className="rounded-xl border border-[#e2e7ee] bg-white px-4 py-3"><p className="text-[8px] font-black uppercase tracking-[.08em] text-[#8994a5]">{x.label}</p><p className="mt-1.5 text-[18px] font-semibold text-[#1e2d49]">{integer(x.claim_count)}</p></article>)}</section>
    <section className="grid gap-4 xl:grid-cols-2"><article className="portal-card overflow-hidden"><Header title="Status distribution"/><StatusTable rows={report.statuses}/></article><article className="portal-card overflow-hidden"><Header title="Insurance company claims"/><InsurerTable rows={report.insurers}/></article></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Pending documents" value={integer(report.documents.pending_documents)}/><Metric label="Rejected documents" value={integer(report.documents.rejected_documents)}/><Metric label="Claims with pending docs" value={integer(report.documents.claims_with_pending_documents)}/><Metric label="Claims with rejected docs" value={integer(report.documents.claims_with_rejected_documents)}/></section>
    <section className="portal-card overflow-hidden"><div className="flex items-center justify-between border-b border-[#e9edf3] px-5 py-4"><h2 className="text-[14px] font-bold text-[#1b2943]">Claims register</h2><a href={exportHref} className="inline-flex h-9 items-center gap-2 rounded-lg border border-[#cad4e4] bg-white px-3 text-[10px] font-bold text-[#263b69]"><Download className="h-3.5 w-3.5"/>Export CSV</a></div><Register rows={report.register.rows}/><Pagination page={report.register.page} pages={pages} total={report.register.total_count} prev={href("/reports/claims",filters,Math.max(1,report.register.page-1))} next={href("/reports/claims",filters,report.register.page+1)}/></section>
  </div></AppShell>
}

const inputClass="h-10 w-full rounded-lg border border-[#dfe5ee] bg-white px-3 text-[10.5px] font-semibold text-[#26364f] outline-none focus:border-[#7788bd] focus:ring-2 focus:ring-[#dfe5ff]";
function ReportTabs(){return <nav className="mt-4 flex flex-wrap gap-2"><Tab href="/reports" label="Business"/><Tab href="/reports/distribution" label="Distribution"/><Tab href="/reports/renewals" label="Renewals"/><Tab href="/reports/claims" label="Claims" active/></nav>}
function Tab({href,label,active=false}:{href:string;label:string;active?:boolean}){return <Link href={href} className={`rounded-lg border px-3 py-2 text-[10px] font-bold ${active?"border-[#223a78] bg-[#223a78] text-white":"border-[#dfe5ee] bg-white text-[#506077]"}`}>{label}</Link>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-1 block text-[8.5px] font-black uppercase tracking-[.08em] text-[#7b8799]">{label}</span>{children}</label>}
function Metric({label,value}:{label:string;value:string}){return <article className="portal-card px-4 py-4 sm:px-5"><p className="text-[9px] font-black uppercase tracking-[.1em] text-[#7c899b]">{label}</p><p className="mt-2 text-[22px] font-semibold tracking-[-.03em] text-[#14213c]">{value}</p></article>}
function Header({title}:{title:string}){return <div className="border-b border-[#e9edf3] px-5 py-4"><h2 className="text-[14px] font-bold text-[#1b2943]">{title}</h2></div>}
function StatusTable({rows}:{rows:ClaimsReport["statuses"]}){if(!rows.length)return <Empty/>;return <div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-[#f8fafc] text-[8.3px] font-black uppercase tracking-[.07em] text-[#7c899b]"><th className="px-5 py-3 text-left">Status</th><th className="px-3 py-3 text-right">Claims</th><th className="px-5 py-3 text-right">Estimated loss</th></tr></thead><tbody className="divide-y divide-[#edf0f4]">{rows.map(x=><tr key={x.status} className="text-[10px]"><td className="px-5 py-3.5 font-semibold text-[#283851]">{x.status}</td><td className="px-3 py-3.5 text-right">{integer(x.claim_count)}</td><td className="px-5 py-3.5 text-right font-bold">{currency(x.estimated_loss)}</td></tr>)}</tbody></table></div>}
function InsurerTable({rows}:{rows:ClaimsReport["insurers"]}){if(!rows.length)return <Empty/>;return <div className="overflow-x-auto"><table className="w-full min-w-[650px]"><thead><tr className="bg-[#f8fafc] text-[8.3px] font-black uppercase tracking-[.07em] text-[#7c899b]"><th className="px-5 py-3 text-left">Insurance company</th><th className="px-3 py-3 text-right">Claims</th><th className="px-3 py-3 text-right">Open</th><th className="px-3 py-3 text-right">Estimated loss</th><th className="px-5 py-3 text-right">Settlement</th></tr></thead><tbody className="divide-y divide-[#edf0f4]">{rows.map((x,i)=><tr key={`${x.id??"none"}-${i}`} className="text-[10px]"><td className="px-5 py-3.5 font-semibold text-[#283851]">{x.insurer_name}</td><td className="px-3 py-3.5 text-right">{integer(x.claim_count)}</td><td className="px-3 py-3.5 text-right">{integer(x.open_claim_count)}</td><td className="px-3 py-3.5 text-right">{currency(x.estimated_loss)}</td><td className="px-5 py-3.5 text-right font-bold">{currency(x.settlement_amount)}</td></tr>)}</tbody></table></div>}
function Register({rows}:{rows:ClaimsReport["register"]["rows"]}){if(!rows.length)return <Empty/>;return <div className="overflow-x-auto"><table className="w-full min-w-[1300px]"><thead><tr className="bg-[#f8fafc] text-[8px] font-black uppercase tracking-[.07em] text-[#7c899b]"><th className="px-5 py-3 text-left">Claim</th><th className="px-3 py-3 text-left">Customer / vehicle</th><th className="px-3 py-3 text-left">Policy / insurer</th><th className="px-3 py-3 text-left">Status</th><th className="px-3 py-3 text-right">Age</th><th className="px-3 py-3 text-right">Estimated</th><th className="px-3 py-3 text-right">Approved</th><th className="px-3 py-3 text-right">Settlement</th><th className="px-3 py-3 text-right">Docs</th><th className="px-5 py-3 text-center">Open</th></tr></thead><tbody className="divide-y divide-[#edf0f4]">{rows.map(x=><tr key={x.id} className="text-[10px] hover:bg-[#fbfcfe]"><td className="px-5 py-3.5"><p className="font-bold text-[#24344f]">{x.claim_no}</p><p className="text-[8.5px] text-[#8490a1]">{dateTime(x.created_at)}</p></td><td className="px-3 py-3.5"><p className="font-semibold">{x.customer_name}</p><p className="text-[8.5px] text-[#8490a1]">{x.vehicle_no}</p></td><td className="px-3 py-3.5"><p className="font-semibold">{x.policy_no}</p><p className="text-[8.5px] text-[#8490a1]">{x.insurer_name}</p></td><td className="px-3 py-3.5"><p className="font-semibold">{x.status}</p><p className="text-[8.5px] text-[#8490a1]">{labelMode(x.service_mode)}</p></td><td className="px-3 py-3.5 text-right font-bold">{integer(x.age_days)}d</td><td className="px-3 py-3.5 text-right">{currency(x.estimated_loss)}</td><td className="px-3 py-3.5 text-right">{currency(x.approved_amount)}</td><td className="px-3 py-3.5 text-right font-bold">{currency(x.settlement_amount)}</td><td className="px-3 py-3.5 text-right"><span className={x.rejected_documents?"font-bold text-red-700":x.pending_documents?"font-bold text-amber-700":"text-[#536174]"}>{integer(x.document_count)}</span></td><td className="px-5 py-3.5 text-center"><Link href={`/claims/${x.id}`} className="inline-grid h-8 w-8 place-items-center rounded-lg border border-[#d9e1ec] text-[#425b8f]"><ExternalLink className="h-3.5 w-3.5"/></Link></td></tr>)}</tbody></table></div>}
function Pagination({page,pages,total,prev,next}:{page:number;pages:number;total:number;prev:string;next:string}){return <div className="flex items-center justify-between border-t border-[#edf0f4] px-5 py-3 text-[9.5px] text-[#738095]"><span>{integer(total)} records</span><div className="flex items-center gap-2"><Link href={page<=1?"#":prev} className={`rounded-md border px-3 py-1.5 font-bold ${page<=1?"pointer-events-none opacity-40":""}`}>Previous</Link><span>{page} / {pages}</span><Link href={page>=pages?"#":next} className={`rounded-md border px-3 py-1.5 font-bold ${page>=pages?"pointer-events-none opacity-40":""}`}>Next</Link></div></div>}
function Empty(){return <div className="px-5 py-10 text-center text-[10px] font-semibold text-[#7a8798]">No data</div>}
function normalizedAging(r:ClaimsReport){return r.aging.length?r.aging:[{key:"0_7",label:"0–7 days",sort_order:1,claim_count:0},{key:"8_15",label:"8–15 days",sort_order:2,claim_count:0},{key:"16_30",label:"16–30 days",sort_order:3,claim_count:0},{key:"31_60",label:"31–60 days",sort_order:4,claim_count:0},{key:"61_plus",label:"61+ days",sort_order:5,claim_count:0}]}
function href(path:string,f:ClaimsFilters,page?:number){const s=new URLSearchParams();s.set("period","custom");if(f.fromDate)s.set("from",f.fromDate);if(f.toDate)s.set("to",f.toDate);if(f.insurerId)s.set("insurer",f.insurerId);if(f.status)s.set("status",f.status);if(f.serviceMode)s.set("mode",f.serviceMode);if(page)s.set("page",String(page));return `${path}?${s}`}
function currency(v:number){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v||0)}
function integer(v:number){return new Intl.NumberFormat("en-IN",{maximumFractionDigits:0}).format(v||0)}
function dateTime(v:string){if(!v)return"—";return new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric",timeZone:"Asia/Kolkata"}).format(new Date(v))}
function labelMode(v:string|null){return v==="self_managed"?"Self managed":v==="broker_managed"?"Broker managed":"—"}
function fallbackFilters():ClaimsFilters{return{period:"90d",fromDate:null,toDate:null,insurerId:null,status:null,serviceMode:null,page:1}}
