"use client";

import { useMemo,useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { approvePartnerPayable,closePartnerPayable,markPartnerPayableEligible,recordPartnerPayment,setPartnerPayableHold } from "./actions";

type Data=Awaited<ReturnType<typeof import("./actions").listPartnerPayablesWorkbench>>;
const money=(v:unknown)=>`₹${Number(v??0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export function PartnerPayablesWorkbench({data}:{data:Data}){
 const router=useRouter();const[pending,startTransition]=useTransition();const[msg,setMsg]=useState("");const[reason,setReason]=useState<Record<string,string>>({});
 const payablePartners=useMemo(()=>[...new Map(data.payables.filter(p=>["Payable Approved","Payment Initiated"].includes(p.status)&&Number(p.outstanding_amount)>0&&p.intermediary_code).map(p=>[String(p.intermediary_code),String(p.intermediary_type??"")])).entries()],[data.payables]);
 const[partner,setPartner]=useState(payablePartners[0]?.[0]??"");const[paymentDate,setPaymentDate]=useState("");const[paymentRef,setPaymentRef]=useState("");const[alloc,setAlloc]=useState<Record<string,string>>({});
 const paymentPayables=data.payables.filter(p=>p.intermediary_code===partner&&["Payable Approved","Payment Initiated"].includes(p.status)&&Number(p.outstanding_amount)>0);const paymentTotal=Object.values(alloc).reduce((s,v)=>s+(Number(v)||0),0);
 const run=(fn:()=>Promise<unknown>,success:string)=>startTransition(async()=>{try{setMsg("");await fn();setMsg(success);router.refresh();}catch(e){setMsg(e instanceof Error?e.message:"Action failed.")}});
 return <div className="mx-auto max-w-[1600px] space-y-4 pb-10">
  <section className="rounded-2xl border border-[#dbe3ee] bg-white p-5 shadow-sm"><p className="text-[9px] font-black uppercase tracking-[.14em] text-[#0f766e]">Phase F · Partner liability</p><h1 className="mt-2 text-[21px] font-semibold text-[#17365D]">Partner Payables</h1><p className="mt-1 max-w-5xl text-[10px] leading-5 text-[#667085]">Convert reviewed actual agreed partner commercials into explicit liabilities, approve them, place holds where required, and allocate partner payments. Eligibility is manual until Sankalp formally defines an automatic business trigger.</p>{msg?<div className="mt-3 rounded-xl bg-[#f8fafc] px-3 py-2 text-[10px]">{msg}</div>:null}</section>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Eligible candidates" value={data.eligibleCommercials.length}/><Metric label="Eligible" value={data.payables.filter(p=>p.status==="Eligible").length}/><Metric label="Approved" value={data.payables.filter(p=>p.status==="Payable Approved").length}/><Metric label="Held" value={data.payables.filter(p=>p.status==="Held").length}/><Metric label="Outstanding payable" value={money(data.payables.reduce((s,p)=>s+Number(p.outstanding_amount||0),0))}/></section>
  <section className="rounded-2xl border border-[#dbe3ee] bg-white p-5 shadow-sm"><h2 className="text-[13px] font-semibold text-[#17365D]">Commercials awaiting explicit eligibility</h2><div className="mt-3 overflow-auto rounded-xl border"><table className="min-w-[1000px] w-full text-[9.5px]"><thead className="bg-[#f8fafc]"><tr><th className="p-2 text-left">Policy</th><th className="p-2 text-left">Customer / vehicle</th><th className="p-2 text-left">Partner</th><th className="p-2 text-right">Agreed payout</th><th className="p-2 text-left">Eligibility reason</th><th className="p-2">Action</th></tr></thead><tbody>{data.eligibleCommercials.map(s=><tr key={s.id} className="border-t"><td className="p-2 font-semibold">{s.policyNo}</td><td className="p-2">{s.customerName}<div className="text-[8px] text-[#98a2b3]">{s.vehicleNo}</div></td><td className="p-2">{s.intermediary_type??"—"} · {s.intermediary_code??"—"}</td><td className="p-2 text-right font-semibold">{money(s.agreedAmount)}</td><td className="p-2"><input value={reason[s.id]??""} onChange={e=>setReason(r=>({...r,[s.id]:e.target.value}))} placeholder="Why is this payable now?" className="w-full rounded border px-2 py-1"/></td><td className="p-2 text-center"><button disabled={pending||!(reason[s.id]??"").trim()} onClick={()=>run(()=>markPartnerPayableEligible({policyPayoutId:s.id,reason:reason[s.id]??""}),"Payable marked eligible.")} className="rounded-lg bg-[#17365D] px-3 py-1.5 font-bold text-white disabled:opacity-40">Mark eligible</button></td></tr>)}</tbody></table></div></section>
  <section className="rounded-2xl border border-[#dbe3ee] bg-white p-5 shadow-sm"><h2 className="text-[13px] font-semibold text-[#17365D]">Payable control ledger</h2><div className="mt-3 overflow-auto rounded-xl border"><table className="min-w-[1120px] w-full text-[9.5px]"><thead className="bg-[#f8fafc]"><tr><th className="p-2 text-left">Policy</th><th className="p-2 text-left">Partner</th><th className="p-2 text-right">Agreed</th><th className="p-2 text-right">Outstanding</th><th className="p-2 text-left">Status</th><th className="p-2 text-left">Eligibility</th><th className="p-2">Controls</th></tr></thead><tbody>{data.payables.map(p=><tr key={p.id} className="border-t"><td className="p-2 font-semibold">{p.policyNo}</td><td className="p-2">{p.intermediary_type??"—"} · {p.intermediary_code??"—"}</td><td className="p-2 text-right">{money(p.agreed_amount)}</td><td className="p-2 text-right font-semibold">{money(p.outstanding_amount)}</td><td className="p-2">{p.status}{p.hold_reason?<div className="text-[8px] text-[#b54708]">{p.hold_reason}</div>:null}</td><td className="p-2 max-w-[260px]">{p.eligibility_reason}</td><td className="p-2"><div className="flex flex-wrap justify-center gap-1">{p.status==="Eligible"?<><button onClick={()=>run(()=>approvePartnerPayable(p.id),"Payable approved.")} className="rounded border px-2 py-1 font-bold">Approve</button><button onClick={()=>{const x=window.prompt("Hold reason");if(x)run(()=>setPartnerPayableHold({payableId:p.id,hold:true,reason:x}),"Payable held.")}} className="rounded border px-2 py-1">Hold</button></>:null}{p.status==="Payable Approved"?<button onClick={()=>{const x=window.prompt("Hold reason");if(x)run(()=>setPartnerPayableHold({payableId:p.id,hold:true,reason:x}),"Payable held.")}} className="rounded border px-2 py-1">Hold</button>:null}{p.status==="Held"?<button onClick={()=>run(()=>setPartnerPayableHold({payableId:p.id,hold:false}),"Hold released.")} className="rounded border px-2 py-1">Release hold</button>:null}{p.status==="Paid"?<button onClick={()=>run(()=>closePartnerPayable(p.id),"Payable closed.")} className="rounded border px-2 py-1 font-bold">Close</button>:null}</div></td></tr>)}</tbody></table></div></section>
  <section className="grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl border border-[#dbe3ee] bg-white p-5 shadow-sm"><h2 className="text-[13px] font-semibold text-[#17365D]">Record partner payment</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><select value={partner} onChange={e=>{setPartner(e.target.value);setAlloc({})}} className="rounded border px-3 py-2 text-[10px]">{payablePartners.map(([code,type])=><option key={code} value={code}>{type} · {code}</option>)}</select><input type="date" value={paymentDate} onChange={e=>setPaymentDate(e.target.value)} className="rounded border px-3 py-2 text-[10px]"/><input value={paymentRef} onChange={e=>setPaymentRef(e.target.value)} placeholder="Bank / payment reference" className="rounded border px-3 py-2 text-[10px]"/><div className="rounded bg-[#f8fafc] px-3 py-2 text-[10px] font-semibold">Allocated {money(paymentTotal)}</div></div><div className="mt-3 overflow-auto rounded-xl border"><table className="w-full text-[9.5px]"><thead className="bg-[#f8fafc]"><tr><th className="p-2 text-left">Policy</th><th className="p-2 text-right">Outstanding</th><th className="p-2">Allocate</th></tr></thead><tbody>{paymentPayables.map(p=><tr key={p.id} className="border-t"><td className="p-2">{p.policyNo}</td><td className="p-2 text-right">{money(p.outstanding_amount)}</td><td className="p-2 text-center"><input type="number" min="0" max={Number(p.outstanding_amount)} step="0.01" value={alloc[p.id]??""} onChange={e=>setAlloc(a=>({...a,[p.id]:e.target.value}))} className="w-28 rounded border px-2 py-1"/></td></tr>)}</tbody></table></div><button disabled={pending||!paymentTotal} onClick={()=>run(()=>recordPartnerPayment({intermediaryCode:partner,intermediaryType:payablePartners.find(x=>x[0]===partner)?.[1],paymentDate,paymentReference:paymentRef,paymentAmount:paymentTotal,allocations:Object.entries(alloc).map(([payableId,amount])=>({payableId,amount:Number(amount)}))}),"Partner payment recorded.")} className="mt-4 rounded-xl bg-[#0f766e] px-4 py-2 text-[10px] font-bold text-white disabled:opacity-40">Record payment</button></div><div className="rounded-2xl border border-[#dbe3ee] bg-white p-5 shadow-sm"><h2 className="text-[13px] font-semibold text-[#17365D]">Recent payments</h2><div className="mt-3 space-y-2">{data.payments.slice(0,40).map(p=><div key={p.id} className="rounded-xl border p-3 text-[9.5px]"><div className="flex justify-between gap-3"><span className="font-semibold">{p.intermediary_code}</span><span>{money(p.payment_amount)}</span></div><div className="mt-1 text-[#667085]">{p.payment_date} · {p.payment_reference}</div></div>)}</div></div></section>
 </div>
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border border-[#dbe3ee] bg-white p-4 shadow-sm"><p className="text-[8px] font-black uppercase tracking-[.08em] text-[#8490a1]">{label}</p><p className="mt-2 text-[18px] font-semibold text-[#17365D]">{value}</p></div>}
